### ISSUE TITLE
[feature request] Linux build

### ISSUE THREAD

**Issue by mxmilkiib** [BespokeSynth/BespokeSynth#1]
Would a Linux version of BespokeSynth be possible?

**Comment by awwbees** [comment]
It should be possible in theory, and probably easy to do: Bespoke is built on the JUCE framework and renders with nanovg, and both of those work in Linux. Practically, though, I don't have a Linux machine set up and don't see one in my near future, so it might not happen soon unless someone else wants to take the task on.

**Comment by mxmilkiib** [comment]
Fair enough. I asked on the [LinuxAudio.com forum](https://linuxmusicians.com/viewtopic.php?f=48&t=17968), they advised about the same.

If you're ever in the interest to try a lightweight Linux in a VM, I'd recommend Arch with trizen package manager, a desktop meta package like lxqt/lxde, with openframeworks-nightly, nanovg-git and various versions of glew being in the AUR.

**Comment by davephillips** [comment]
@mxmilkb - Working on it. See https://github.com/awwbees/BespokeSynth/issues/3

**Comment by mxmilkiib** [comment]
Thanks to the folks involved!
