### ISSUE TITLE
Module deleted from existence when it touched edge of screen . also corrupted previous save 

### ISSUE THREAD

**Issue by ShamanicArts** [BespokeSynth/BespokeSynth#1006]
## Describe the bug

MidiController module disappeared from project, wiping all mappings, after touching the corner. Save of project made at that moment is corrupted.

## Build info

bespoke NIGHTLY 1.1.0 (Dec 19 2022 17:56:48) - Mac OSX 12.6.2 - HEAD 9aa940e

## Steps To Reproduce

Unable to reproduce. seems like a one off bug.

**Comment by NoxyNixie** [comment]
How do you mean "touched corner"? Bespoke does not really have corners since it is an infinite canvas?

Not sure this bug report is that useful without a way to reproduce. Can you try and figure out a way to reproduce?

**Comment by ShamanicArts** [comment]
sure. I should have specified I wrote corner but I meant edge, as in the edge of the screen, when the module touched the edge of the screen it was deleted as well as all mappings it contained. unfortunately various attempts to recreate bug have not worked, so I think it must have been a one off. will continue to try and find ways to repro but until then  I guess only function of this report is to document that this happened

**Comment by PowerUser64** [comment]
Seems like this might've been a one-time occurrence, closing for now
