### ISSUE TITLE
Looper Module randomly corrupting cables

### ISSUE THREAD

**Issue by ShamanicArts** [BespokeSynth/BespokeSynth#1020]
## Describe the bug

potentially related to @crshrprt bug report about DC offset. looper module randomly corrupts cable and breaks output audio for entire project

## Build info

bespoke NIGHTLY 1.1.0 (Dec 22 2022 04:25:00) - Mac OSX 12.6.2 - HEAD 50bcb1e

## Steps To Reproduce

its a sporadic bug, no known steps to repro 

## Expected vs. actual behavior

https://youtu.be/xxdDEL8cLX8

**Comment by awwbees** [comment]
duplicate of #1016
