### ISSUE TITLE
Presets Don't Save with Patch

### ISSUE THREAD

**Issue by nedrob** [BespokeSynth/BespokeSynth#1032]
## Describe the bug

Created 3 presets for NoteSequencer. Saved the patch. When I reloaded the patch, the presets were gone.

## Build info

Nightly 1.1.0 Dec 15 2022 04:47:15

## Steps To Reproduce

Add a preset module to NoteSequencer. Save a few presets. Save the patch in a bsk file. Clear the patch. Reload the bsk file. All the presets are gone. 

Detailed steps
1. Connect Presets to a NoteSequencer.
2. Adds notes to NS. 
3. Add a pattern or 2 by shift clicking on Presets.
4. Add a few more patterns by clicking on the Presets Add button (just to cover all bases).
5. Save as a new patch (ie a ,bsk file).
6. Clear the patch
7. Load the patch saved in step 5.
8. None of the presets come back. 

What's really strange is that if you re-connect the preset module to the notesequencer, you may get back the first 1 or 2 presets, but not all of them. The preset module really doesn't re-load well

## Expected vs. actual behavior

Presets should be saved in bsk file. 
Screenshots of saved state and then the load state with no presets. 

![Screen Shot 2023-01-01 at 7 55 07 AM](https://user-images.githubusercontent.com/20388271/210177158-aa069d91-90b5-4c00-a288-36442dd548bd.png)
![Screen Shot 2023-01-01 at 7 55 32 AM](https://user-images.githubusercontent.com/20388271/210177161-8d75f2c5-7f1a-4414-b2eb-7c63a860ed81.png)

**Comment by NoxyNixie** [comment]
This is likely already fixed in 6c89a8ada681253d56ef35cd7fb5f391e3a6e811 

Can you try the latest Nightly build?

**Comment by nedrob** [comment]
Yes, it is fixed in latest build. Thanks.
