### ISSUE TITLE
Bespoke Doesn't Draw Anything until the Window is Moved

### ISSUE THREAD

**Issue by nedrob** [BespokeSynth/BespokeSynth#1033]
## Describe the bug

When starting Bespoke, the window is black and none of the controls (the transport and key modules) are visible. I have to move the window slightly to get everything to show up. 

## Build info

Nightly, 1.1.0 - Dec 15 2022 04:47:15
## Steps To Reproduce

Start Bespoke
Nothing is drawn. The background is black with no controls visible.
Slightly nudge the window. The background is painted in my selected background color and the transport, key and gain and output modules are visible. 

## Expected vs. actual behavior

The UI should be fully painted when the application is started.

**Comment by KottV** [comment]
What is OS? Could it be caused by hybrid video?

**Comment by PowerUser64** [comment]
Closing until further comment
