### ISSUE TITLE
Steam Deck support : halfway there

### ISSUE THREAD

**Issue by TheBricktop** [BespokeSynth/BespokeSynth#1034]
## Summary

As steamdeck is somewhat powerfull dedicated linux console there is a slight possibility of using it as a beefy musical instrument.
The steamOS 3 is a pretty decent arch distro with small caveat of locked filesystem, you might unlock it of course and modify it however You like but the next update everything is reset to the defaults resulting in things like pacman installed bespoke synth deleted.
Bespoke currently works only when installed using the pacman method.
Downloading the appimage and using it as an executable doesnt work because it lacks some shared libs, libselinux.so.1 for example.
### Motivation
Using BespokeSynth in a handheld console seems like  a cool idea.

If you are able to provide a pull request yourself for the feature that you are
proposing, please say so!

**Comment by NoxyNixie** [comment]
> Bespoke currently works only when installed using the pacman method.

Okay so it works then?

This issue is very unclear to me and looks to already be resolved?
