### ISSUE TITLE
Bespoke crashes when I attach new module with lasso

### ISSUE THREAD

**Issue by Joolean14** [BespokeSynth/BespokeSynth#1035]
## Describe the bug

Unexpected crash when attaching new module between two previously connected modules using the lasso technique.
Wasn't able to reproduce it again for this issue. Will attach some previous logs, hopefully one of those crashed because of that reason. Program has never crashed while 'interpreting music', they all have happened while building a patch.

## Build info

bespoke 1.1.0 (Sep 15 2022 20:52:56) - Linux - makepkg 0acb8ebf

## Steps To Reproduce

- Add a new module
- With the lasso technique try to connect the module between two previously attached modules

## Expected vs. actual behavior

The new module is connected between two previous connected module with the lasso technique vs Program crashes.

[crash_2022-12-25_15-57.txt](https://github.com/BespokeSynth/BespokeSynth/files/10333181/crash_2022-12-25_15-57.txt)
[crash_2022-12-26_09-37.txt](https://github.com/BespokeSynth/BespokeSynth/files/10333182/crash_2022-12-26_09-37.txt)
[crash_2022-12-27_07-54.txt](https://github.com/BespokeSynth/BespokeSynth/files/10333183/crash_2022-12-27_07-54.txt)
[crash_2022-12-27_08-30.txt](https://github.com/BespokeSynth/BespokeSynth/files/10333184/crash_2022-12-27_08-30.txt)

**Comment by NoxyNixie** [comment]
I am unable to reproduce this.

When lasso'ing multiple modules you can't connect them in-between two previously connected modules.

If this happens again can you post here or create a new issue with additional information possibly even a screen recording so we can see exactly what happens?
