### ISSUE TITLE
Samplecanvas volume fader changes pitch or speed but not volume

### ISSUE THREAD

**Issue by Joolean14** [BespokeSynth/BespokeSynth#1036]
## Describe the bug

Samplecanvas volume fader changes pitch or speed but not volume

## Build info

bespoke 1.1.0 (Sep 15 2022 20:52:56) - Linux - makepkg 0acb8ebf

## Steps To Reproduce

- Create and connect Samplecanvas module
- Add a sample
- Move volume fader

https://streamable.com/unt9sf

## Expected vs. actual behavior

Change volume of the Samplecanvas module vs Pitch or speed is changed.

**Comment by KottV** [comment]
it was fixed https://github.com/BespokeSynth/BespokeSynth/issues/977
