### ISSUE TITLE
BasicEQ audioeffect does not save / restore settings properly

### ISSUE THREAD

**Issue by ZUrlocker1** [BespokeSynth/BespokeSynth#1040]
## Describe the bug

BasicEQ audioeffect does not save/restore settings properly

## Build info

Jan 5, 2023 running on Mac M1

## Steps To Reproduce

Add BasicEQ audioeffect. Change the levels. Save. Restore. BasicEQ effects will be set to Even, regardless of how it was saved.

## Expected vs. actual behavior

The BasicEQ effects do not appear to be saved or otherwise are not restoring.
This was not an issue in the year old "stable" version of Bespoke 1.1.0 from Nov 2021. I have not checked older versions, but it does not work properly in the latest nightly build from Jan 5, 2023. 
I have attached a repeatable test case. (I added it as a ZIP file since github doesn't know what to do with a BSK file.)
[eq setting.bsk.zip](https://github.com/BespokeSynth/BespokeSynth/files/10362750/eq.setting.bsk.zip)

**Comment by ZUrlocker1** [comment]
Also attached a screenshot
<img width="1270" alt="BasicEQ setting" src="https://user-images.githubusercontent.com/104800415/211090961-0d2d7c4e-f9d2-471e-9e21-782cf5a6712a.png">

**Comment by MyLoFy** [comment]
Can reproduce in an empty project on Arch, home_bespokesynth_Arch/bespokesynth-current 1.1.0+git.180.16ece44-0
