### ISSUE TITLE
Chordholder module not responding correctly to pulses

### ISSUE THREAD

**Issue by bolam360** [BespokeSynth/BespokeSynth#1043]
## Describe the bug

The [chordholder] module does not output the held notes when it receives a pulse whether the "pulse to play" option is hecked or not. If it is holding a chord, it stops when it receives a pulse, regardless of whether "pulse to play" is checked or not. Tried using [notetopulse] and [pulser] modules.

## Build info

bespoke NIGHTLY 1.1.0 (Jan  7 2023 19:05:09) - Mac OSX 11.7.2 - HEAD 0d256c6

## Steps To Reproduce

keyboard input to [midicontroller] to [chordholder] to [arpeggiator]

## Expected vs. actual behavior

The pulse stops the chordholder if it is active, but does not start it regardless of the state of "pulse to play".

**Comment by NoxyNixie** [comment]
I'm not sure it is broken since it seems to work for me: 
![BespokeSynth_20230123_195518](https://user-images.githubusercontent.com/211381/214125590-4e1a426e-0ff1-420a-81db-b2336bad15fe.gif)


In `pulse to play` the notes need to be on at the time of the pulse for them to become held.

**Comment by bolam360** [comment]
Ah yes, you are correct. I think I misunderstood how these interact. I would still like it to behave a little differently but that's a feature request.
