### ISSUE TITLE
Update to JUCE 6 and cmake

### ISSUE THREAD

**Issue by dromer** [BespokeSynth/BespokeSynth#105]
So we don't have to use that darned `projucer` any more :)

**Comment by KottV** [comment]
I think it has to be split in two parts.
1. Update the code for JUCE 6 which is quite possible and is waited for a long :)
2. Port to Cmake. This part is not so obvious.

**Comment by eliot-akira** [comment]
In case this might be useful: there's a tool called FRUT which helps migrate a project using Projucer to use CMake.

https://github.com/McMartin/FRUT

**Comment by KottV** [comment]
afaik FRUIT generates it's own CMakeLists which is very different from JUCE6

**Comment by dromer** [comment]
See https://github.com/awwbees/BespokeSynth/pull/187
