### ISSUE TITLE
Who is maintaining the .deb package?

### ISSUE THREAD

**Issue by Asalle** [BespokeSynth/BespokeSynth#1052]
Hello! 
I stumbled upon this [request for package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025206) in debian bugs and prepared [a draft package](https://github.com/Asalle/bespoke-deb-package). But then I realized in your [releases entry](https://github.com/BespokeSynth/BespokeSynth/releases/tag/v1.1.0) you already have a .deb package available. 

* Who is maintaining this package? 
* Should I let them submit it to debian archives or can we work together?

**Comment by NoxyNixie** [comment]
My guess is that @KottV is likely behind those.

**Comment by KottV** [comment]
Yes me. The package is not in the Debian repo, it's in OBS https://build.opensuse.org/package/show/home:bespokesynth/bespokesynth-current see `debian.*` files and `bespokesynth-current.dsc`

Feel free to adopt it for merging into the Debian main repo.

**Comment by Asalle** [comment]
@KottV how do you see it working out? Do you want to be the author of the package and me - a maintainer? Or do you want me to submit it entirely under my name?

In any case, I'm not yet sure I'm ready for another maintainer load, but I would appreciate it if you could answer in case I find time in the future or somebody else wants to do it.

**Comment by KottV** [comment]
@Asalle I'm not a Debian user, so it would be better if you or someone from multimedia team take care of the package in Debian repo. And as you may see my package is not perfect :)

Sure I'll answer any question if any.
