### ISSUE TITLE
Bug - waveformviewer breaks with certain fx chains that use disabled modules

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1058]
## Describe the bug

Putting certain fx chains in front of the waveform viewer will cause it to display a flat line even though there should be sound going to it.

## Build info

bespoke 1.1.0 (Jan  1 1980 00:00:00) - Linux - unknown-branch deadbeef

## Steps To Reproduce

1. Create this effects chain:
signalgenerator -> eq -> eq -> waveformviewer
2. Disable both of the eq's
3. The waveformviewer will go flat, as if no sound is going to it.

If you then put a module like a _gain_ after the waveformviewer, the viewer will start working again.

## Expected vs. actual behavior

The waveform viewer should display the waveform regardless of whether the modules above it are disabled or not.

**Comment by PowerUser64** [comment]
Here's another related thing (I think it's the same bug, so I'm also reporting it here).

The `waveformviewer` exhibits some odd behavior when you attach more than one module to it. For example, take the effects chain described above (`signalgenerator` -> `eq` (disabled) -> `eq` (disabled) -> `waveformviewer`) and attach another signalgenerator to the `waveformviewer` at the end. At first, the `waveformviewer` will appear as if it doesn't have any input, but when one of the eq's is enabled, it will start working as expected.

All of these problems seem to be rooted in the `waveformviewer`'s behaviour when there's nothing connected to its output.

**Comment by NoxyNixie** [comment]
I am no longer able to reproduce this. I think this was fixed in the Bypass rework patch.

**Comment by PowerUser64** [comment]
Yup, can confirm! Tested in an older version and I can't reproduce it in the newer version!
