### ISSUE TITLE
Windows Defender flags the .msi as having a trojan.

### ISSUE THREAD

**Issue by imonroe** [BespokeSynth/BespokeSynth#106]
Downloaded the Windows .msi installer directly from the main page on https://www.bespokesynth.com/

Immediately upon completion, Windows Defender flagged the file and removed it.  

![image](https://user-images.githubusercontent.com/1263892/133341470-b2440d38-1d67-429e-b844-2a3f9cd4eb34.png)

**Comment by CarloCattano** [comment]
Hm Interesting . Did not have that warning on windows 10 myself. Which browser did you use ?

**Comment by imonroe** [comment]
Chrome, with latest updates.

**Comment by awwbees** [comment]
I received a report today on twitter that this is _possibly_ resolved; maybe enough users started playing with bespoke and defender updated some definitions? here's the tweet:
https://twitter.com/NapierRacing/status/1438241191401754633

let me know if it is resolved for you as well! if it is, I'll close this out.

**Comment by imonroe** [comment]
Yeah, it looks like it passes Windows Defender just fine now.  Thanks for looking into it!
