### ISSUE TITLE
Bug - metronome does not respond to modulation when off screen

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1061]
## Describe the bug

Some modules doesn't respond to automation unless they are visible.

## Build info

3fc87549496bcda1650a37f166ba3b4e08260067

## Steps To Reproduce

1. Create a metronome and connect it to the main output
2. Attach a slow LFO to the metronome
3. Listen to the metronome's sound change in volume as it plays
4. Pan the view away from the metronome such that it isn't in sight anymore
5. Notice how the metronome's volume level does not change

🔊🔊🔊 sound on ⬇️⬇️⬇️

https://github.com/BespokeSynth/BespokeSynth/assets/24578572/f8be24de-9241-4ee0-9076-b29d07b8102e

This was also documented happening with the midicc module [by @NotSoAnon on discord](https://discord.com/channels/846834873254805554/854199359913328671/1223431078140968985).

[Discord_HQ.webm](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/0af06c84-bab6-434c-95e5-811d406affb2) 

## Expected vs. actual behavior

The metronome should respond to automation whether it is in view or not. Right now, this is not the case.

**Comment by NoxyNixie** [comment]
> bespoke 1.1.0 (Jan 1 1980 00:00:00) - Linux - unknown-branch deadbeef

Well, I guess whatever build system you are using is causing issues detecting what git revision you are on and apparently also what date it is.

Do you have some alien build system we are not familiar with or how did you compile it?

**Comment by KottV** [comment]
> > bespoke 1.1.0 (Jan 1 1980 00:00:00) - Linux - unknown-branch deadbeef
> 
> Well, I guess whatever build system you are using is causing issues detecting what git revision you are on and apparently also what date it is.
> 
> Do you have some alien build system we are not familiar with or how did you compile it?

I think it's `deb` from OBS. There is a problem with getting tag during the build.

**Comment by PowerUser64** [comment]
I'm compiling bespoke from my nixos configuration. Nix resets file creation dates to ensure reproducible results. The better way to do a number like this is to have a commit hook in the repo that updates the date whenever there's a commit, I've seen it done in [the dolphin emulator project](https://github.com/dolphin-emu/dolphin) to get the commit hash into the build, maybe we could do something similar? If you want to know the hash I'm on instead, it's 867ca2593e8b915c97b0501ce7370d0ba6aa01a6. (but I just tested the latest commit 0b8dc148b41ec3798c3e7569cda5b347f02830ea and it's still a problem.)
