### ISSUE TITLE
Feat - paste and apply value without pressing enter

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1064]
## Summary

Currently, to paste a value onto a slider, you have to hover on the slider, press ctrl+v, then enter. This could be sped up if the need to press enter was removed.

### Motivation

As mentioned in #1059, moving values between sliders can be very tedious. This would help alleviate that.

**Comment by awwbees** [comment]
this would remove your ability to paste in a value (from another slider, or from an external source) and edit it before applying it, so I think this would be a downgrade. even though I agree that symmetry between hover-copy and hover-paste would be nice, I don't think it's worth it.

**Comment by PowerUser64** [comment]
Hmm, okay. What if instead it was implemented as applying edits to sliders when you click out of them? That would be more consistent with the user experience of text editing in general. For example, when editing the minimum or maximum values of a slider, you can click outside the edit area to apply the change, and the same goes for most other text fields. Perhaps sliders could be made more consistent with this? I think it would lead to a less confusing user experience.

**Comment by NoxyNixie** [comment]
I'm not sure @awwbees checks closed issues so you may want to post that as a new feature request.

**Comment by awwbees** [comment]
editing text fields and entering values onto sliders isn't quite the same: you need to intentionally click into a text field before typing to enter a value, but on sliders, you only need to start typing while hovering (no click necessary). so, to avoid accidental value changes, the user must press enter to confirm the value, and clicking away will just cancel the change.
