### ISSUE TITLE
Bug - notestepper doesn't spit notes when notes are sent close to the same time

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1068]
## Describe the bug

The notestepper doesn't split notes up if the notes are sent at the same time (eg. a chord is played).

## Build info

bespoke 1.1.0 (Jan  1 1980 00:00:00) - Linux - unknown-branch deadbeef
commit 0b8dc148b41ec3798c3e7569cda5b347f02830ea

## Steps To Reproduce

1. Make this effect chain:
![image](https://user-images.githubusercontent.com/24578572/213847126-77f98d4f-3a1f-43fa-a5c9-583255a7fb15.png)
2. Set the voice limit of the two oscillators to 1
3. Play two notes at the same time through the notestepper

## Expected vs. actual behavior

Only one of the notes will play. If you play the notes slightly apart, they will have a better chance of both playing. Instead, the notestepper should always send notes to different destinations.

**Comment by NoxyNixie** [comment]
This is actually by design:
```C++
if (time > mLastNoteOnTime + 10) //slop, to make a chord count as a single step
```

Maybe chords in a single step should be an option (off by default) instead?

**Comment by PowerUser64** [comment]
That would be a good addition. I often use this module to create polyphonic instruments by creating duplicates of monophonic instruments, which isn't always compatible with this.
