### ISSUE TITLE
Bug - can't scroll to zoom with mouse over a prefab

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1078]
## Describe the bug

Currently, it is impossible to zoom while your mouse is over a prefab.

## Build info

commit b0e179b5a6d5c6433965d92a943bb1019187dc15

## Steps To Reproduce

1. Add a prefab
2. Put your mouse on it and scroll to zoom

## Expected vs. actual behavior

You should be able to zoom the canvas regardless of whether your mouse is over a prefab or not.

**Comment by NoxyNixie** [comment]
You can if you hold `space`.

**Comment by PowerUser64** [comment]
Ah yes, I meant to include that.
