### ISSUE TITLE
Improve Linux support

### ISSUE THREAD

**Issue by makew0rld** [BespokeSynth/BespokeSynth#108]
Hello! Bespoke seems super cool.

Unfortunately, it's not the easiest to install on Linux right now, as your Linux build scripts are aimed at Ubuntu. I don't blame you, but it would help to have a way to compile Bespoke yourself. Right now it seems like the Makefile is not included by git, which makes this difficult or impossible. For those not on Ubuntu, it's unclear how to install Bespoke.

If you have the time, I'd suggest packaging Bespoke in a way that will work on all distros. The main ways of doing that on Linux would be [Flatpak](https://www.flatpak.org/), [AppImage](https://appimage.org/), or Snap. Snaps have a proprietary backend and are controversial ([1](https://lwn.net/Articles/825005/), [2](https://blog.linuxmint.com/?p=3906)), and so that leaves AppImage and Flatpak. Personally I would recommend Flatpak as it is better integrated with many Linux distros (GUI, app store, etc), and follows the standard Linux model of updating packages from an upstream repo, rather than the AppImage model where you just download a new file and delete the old one. Flatpak also supports sandboxing. However either option will work and I expect will be happily accepted by Linux users.

Thanks, and best of luck with Bespoke!

**Comment by KottV** [comment]
Hi,

there was attempt to build flatpak https://github.com/awwbees/BespokeSynth/issues/12#issuecomment-691468664
looks it has issues and doesn't go further

from my POV flatpak is the worst choice for such apps, you won't get Jack (until PipeWire become a full replacement), you may have an issues with VST plugins with incompatible libs

AppImage could work, maybe I'll look for building that

Anyway what is your distro? I have succesfuly build BespokeSynth for Debian/Ubuntu and openSUSE

**Comment by makew0rld** [comment]
Ah yes, it probably won't work with JACK. PipeWire is the solution to all this, but yeah it's not used everywhere yet.

My distro is Arch Linux.

Being able to compile Bespoke yourself is the most important thing though. The Makefile and some instructions should be available.

Thnaks!

**Comment by KottV** [comment]
I can give instruction if you want build locally. Perhaps you may realize how to make pkgbuild after that.
Main issue that Projucer in JUCE 5.4.7 requires X server even for generating Makefile.

**Comment by KottV** [comment]
Download JUCE 5.4.7 sources https://github.com/juce-framework/JUCE/releases/tag/5.4.7
Extract it and build the Projucer:
`cd /path/to/JUCE-5.4.7/extras/Projucer/Builds/LinuxMakefile`
```
make -j`numproc`
```
now run `/path/to/JUCE-5.4.7/extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave BespokeSynth.jucer` inside the BespokeSynth source folder

you should have `BespokeSynth/Builds/LinuxMakefile/Makefile` now

**Comment by westurner** [comment]
Packaging tools that may be useful for linux platforms:

- https://github.com/bpicode/github-action-fpm
  - https://github.com/bpicode/github-action-fpm/blob/master/Dockerfile
  - https://fpm.readthedocs.io/en/latest/index.html#things-that-should-work
    - deb, rpm, arch apk
- https://github.com/marketplace/actions/rpm-build
- https://github.com/marketplace/actions/build-rpm-action
- https://github.com/marketplace/actions/build-deb-action
- https://help.launchpad.net/Packaging/PPA/Uploading
- https://wiki.debian.org/CreatePackageFromPPA
- https://wiki.debian.org/PackagingWithGit
- https://docs.fedoraproject.org/en-US/quick-docs/publish-rpm-on-copr/#_step_3_automate_package_re_builds

**Comment by westurner** [comment]
- FWIU, you can generate minimal and/or initial e.g. RPM .spec files with FPM:
  https://github.com/jordansissel/fpm/issues/689#issuecomment-403916593
- Conda-forge rebuilds on git push to the correct branch of the package git repo for you:
  https://conda-forge.org/docs/maintainer/adding_pkgs.html
  - Conda-forge builds amd64 and arm64 targets
  - IDK which bespoke dependencies are not yet available in conda-forge? Are VST plugins as simple as finding the correct path?
  - Conda works on most major linux distros. Mamba is fast and uses libsolv just like rpm, dnf, and zypper.
  - https://westurner.github.io/tools/#conda #mamba
- https://jfrog.com/open-source/
- pkgs.org indexes official package repos for many distros:
  https://pkgs.org/search/?q=sooperlooper
- Windows package updater: Chocolatey
  - https://westurner.github.io/tools/#chocolatey
  - https://community.chocolatey.org/packages/mixxx
- MacOS package updater: Brew
  - https://westurner.github.io/tools/#brew
  - https://formulae.brew.sh/cask/mixxx

**Comment by fogti** [comment]
It would be nice if the generated `Makefile` could be released together with other release artifacts.

**Comment by follower** [comment]
### Working out runtime dependencies

I noticed this comment: https://github.com/awwbees/BespokeSynth/blob/bfe433ace650fb3081605979d3a0cba3a0ede036/Builds/LinuxMakefile/bespoke_dependencies.sh#L2

So in hope of providing some useful information I did this:

```bash
$ ldd BespokeSynth
```

Which generated this message & list of library dependencies:

```
./BespokeSynth: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./BespokeSynth)
./BespokeSynth: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./BespokeSynth)
	linux-vdso.so.1 (0x00007ffed9dfc000)
	libpython3.8.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f48cf869000)
	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f48cf562000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f48cf22a000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f48cf018000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f48ced64000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f48ceb45000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f48ce941000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f48ce5a3000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f48ce317000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f48ce0ff000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f48cdd76000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f48cdb5e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f48cd76d000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f48cd53b000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f48cd31e000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f48cd11b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f48ccf13000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f48d142f000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f48ccceb000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f48ccab9000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f48cc888000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f48cc5d2000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f48cc3b4000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f48cc1b0000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f48cbfaa000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f48cbd95000)
```

This is on an Elementary OS 5.1 (derived from Ubuntu 18.04 LTS) machine.

### Working out runtime package dependencies

Matching libraries listed to packages would allow us to cull down the list of package dependencies required.

### Issues with `libc`/`libstdc++` versions

Based on recent experience the `libc` error means that the binary was built on something more recent than Ubuntu 18.04 LTS, and based on what I eventually got to run with, it's from Ubuntu 20.04 LTS.

Specifically, for libc, this package: https://ubuntu.pkgs.org/20.04/ubuntu-updates-main-amd64/libc6_2.31-0ubuntu9.2_amd64.deb.html

This is the third or fourth precompiled binary I've downloaded with this issue in the past 2-3 days, so I guess we're at *that* point in the ecosystem upgrade cycle...

#### Dealing with the issue...

Given that [Ubuntu 18.04 LTS is still under maintenance](https://ubuntu.com/about/release-cycle) it would be nice (IMO) to still support running the pre-compiled builds on it.

This would most likely/easily require building the binaries on a 18.04 system.

### How to run the current Bespoke pre-compiled binary on Ubuntu 18.04 LTS-derived systems

[via my previous write up [here](https://github.com/WerWolv/ImHex/issues/81#issuecomment-917622785).]

I did eventually get the pre-compiled version to run on an Ubuntu 18.04 LTS derived system via a convoluted method which I can't recommend but thought I'd at least mention...

1. Download `Bespoke-Linux.zip`.
2. Extract to `BespokeSynth` directory.
3. `cd BespokeSynth`.
4. `mkdir _downloads_`
5. `pushd _downloads_`
6. Download these:
   ```
   wget http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.31-0ubuntu9.2_amd64.deb
   wget http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-10-cross/libstdc++6-amd64-cross_10.3.0-1ubuntu1~20.04cross1_all.deb
   ```
7. *Extract* the `.deb` files (*DO NOT* install them):
   ```
   dpkg-deb --vextract libc6_2.31-0ubuntu9.2_amd64.deb try__libc6_2_31/
   dpkg-deb --vextract libstdc++6-amd64-cross_10.3.0-1ubuntu1~20.04cross1_all.deb try__libstdc++/
   ```
8. `popd`
9. _Finally_, run Bespoke with:
   ```bash
   $ LD_PRELOAD=./_downloads_/try__libstdc++/usr/x86_64-linux-gnu/lib/libstdc++.so.6.0.28 ./_downloads_/try__libc6_2_31/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 --library-path ./_downloads_/try__libc6_2_31/lib/x86_64-linux-gnu/:./_downloads_/try__libstdc++/usr/x86_64-linux-gnu/lib/ ./BespokeSynth
   ```

What this is doing is using the `ld-linux` dynamic linker/loader from the more recent `libc` package to run the binary rather than having the system automatically use the standard one. *hand waves here*

It's a hack (& some software seems to have issues) but gets the binary running which is good enough for me at the moment.

In terms of binary releases, my preference of the three mentioned would be AppImage because I've encountered fewer issues with it but my priorities might be different to someone else's.

Hope some of this is useful to someone.

Now back to playing with our new toy. :)

**Comment by makew0rld** [comment]
> you should have `BespokeSynth/Builds/LinuxMakefile/Makefile` now

@KottV Ah I understand now, thanks for explaining. And there actually is an [AUR package](https://aur.archlinux.org/packages/bespokesynth-git/) already, with a build script, so that's nice. It would be nice if the instructions you gave were in the repo somewhere though.

**Comment by westurner** [comment]
- Can you run Bespoke in a container (by patching the X socket and what from `/dev` through,)?
- Can you build Bespoke release packages in (a) Multi-Stage Docker container(s)?
  - docs: https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
  - Layer: install build deps and **build** BespokeSynth for platform
  - Layer: **copy** BespokeSynth package, install, and *run tests*
    - Make it self-testing; Is there a good self-test command in the bespoke binary that can be called from the commandline? Build containers would need to have e.g. GNU Make installed if it's not just a `-t/--test` arg off `main()`.
- Could you dev Bespoke in a container?
    - docs: https://www.docker.com/blog/advanced-dockerfiles-faster-builds-and-smaller-images-using-buildkit-and-multistage-builds/
    > Let’s finish up with an example of combining the previous patterns to show how to create a Dockerfile that creates a minimal production image and then can use the contents of it for running tests or for creating a development image. 
    - "development image"
      - https://github.com/containers/toolbox
        > [...] On Fedora this is the `fedora-toolbox` image. This image is used to create a toolbox container that seamlessly integrates with the rest of the operating system by providing access to the user's home directory, the Wayland and X11 sockets, networking (including Avahi), removable devices (like USB sticks), systemd journal, SSH agent, D-Bus, ulimits, /dev and the udev database, etc..
        - does this include support for /dev/snd and pipewire passthrough to a host workstation *without `--privileged`*?
          - "DOC,ENH: How to connect container pipewire, alsa, jack to host pipewire" 
            https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1612

**Comment by KottV** [comment]
> 
> 
> > you should have `BespokeSynth/Builds/LinuxMakefile/Makefile` now
> 
> @KottV Ah I understand now, thanks for explaining. And there actually is an [AUR package](https://aur.archlinux.org/packages/bespokesynth-git/) already, with a build script, so that's nice. It would be nice if the instructions you gave were in the repo somewhere though.

hehe, this PKGBUILD is just copy-paste of my rpm spec :)
not sure it works at all

i'm gonna prepare AppImage, then probably will try with Arch package

**Comment by makew0rld** [comment]
AppImage sounds great thanks! Not sure if their docs cover this, but as @follower has mentioned, please build the AppImage on the oldest supported LTS of Ubuntu so there aren't libc version issues. This is also what the AppImage team recommends, see [here](https://discourse.appimage.org/t/specify-required-glibc-version-in-appimage/2413/5).

**Comment by b08x** [comment]
I would suggest Ansible for building/distributing applications. Every major distro has pip (which I would use to ensure version compatibility across distros). One could do (roughly); `pip install ansible && git clone <bespoke with a playbook in the main directyory> && ansible -c bespoke.yml` 

The advantage to this is that it breaks up the build process in a modular fashion. It's easier to maintain and make changes. I'm not sure what the future holds for concepts such as flatpak and snapd. While fantastic ideas, at present they both seem to actually make this process more convoluted, especially to someone who isn't that into linux. AppImage suffers from the same problems the major package managers do. In that versions of packages still conflict and it's even more difficult to debug. 

Right now, I'm actually trying to work out loading the fonts. It doesn't know where to look for frabk.ttf. I stumbled upon this, which may help [load font from file at loadtime](https://stackoverflow.com/questions/37572961/c-directwrite-load-font-from-file-at-runtime)

**Comment by makew0rld** [comment]
Ansible is for configuration and setup of multiple servers, not compiling applications. Just use a makefile or something instead. In any case, makefiles or playbooks are not an alternative to a compiled binary like an AppImage.

**Comment by ruffson** [comment]
Did anyone get it to work on Fedora 34? I keep getting a:

```
./BespokeSynth: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```
I have the python dev packages installed, tried sym-linking to my `libpython3.so` and even tried installing `python3.8-3.8.12-1.fc34.i686` which is the only package in the repos which provides that so. But no luck.

**Comment by KottV** [comment]
@ruffson 
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/package/BespokeSynth/

there is Fedora builds

**Comment by th5** [comment]
On Debian 11:
sudo apt install juce-tools
git clone https://github.com/awwbees/BespokeSynth.git
cd BespokeSynth
Projucer --resave BespokeSynth.jucer
cd Builds/LinuxMakefile
make -j6
[wait a while]
[keep waiting]
cd build
./BespokeSynth

**Comment by unfa** [comment]
I've just tried to run the official release on Manajro Linux.
I'm using PipeWire as a replacement for JACK and PulseAudio and when I set BepokeSynth to use JACK, it now eits immediatelly after startign with  a message "Killed".
Is there a config file I can delete to try again? I can't find anything in my user's home directory....

**Comment by b08x** [comment]
> Ansible is for configuration and setup of multiple servers, not compiling applications. Just use a makefile or something instead. In any case, makefiles or playbooks are not an alternative to a compiled binary like an AppImage.

About 4 years ago I figured out how to use Ansible to compile applications as part of "dev ops" solution. I really don't know how to explain this to anyone, other than you can.

It's just a set of organized instructions that produces a result.

The trouble with my suggestion, is that figuring Ansible out takes a while. The contents of a box are not always accurately reflected by a label. 

By the way...I'm not sure why you're trying to tell me what Ansible _is_, as I am the one who was explaining it you. 

As for compiled binaries, as I said, they have suffer from same problems. You're looking for some sort of ubiquity or cross platforming? Unless you convince the leadership of all the separate Linux communities to agree upon standardization of package versioning, naming, AppImages are a waste of time. Which is unfortunate, as I too, thought this was a good idea at one point.

**Comment by westurner** [comment]
FWIW, Configuration Management tools are considered a different category than Build Automation tools on Wikipedia. The conceptual components are very similar: there's a config object, a CFG control flow graph that is parallel and blocks at barriers (BSP) across multiple nodes; a distributed system for concurrent and/or parallel execution of tasks for {building, testing, distributing, and deploying, and then monitoring and responding to feedback from one or more test and production systems}.

If Ansible works for your software build automation, that's great. Anything can call a CMMI task (`./configure --help; make; make install`) on a remote node and fetch the results. Of course, then that's using GNU Make as the build tool (to call e.g. ninja, of course).

Anyways, systems like: {Blaze (Google), Pants build (Twitter), Buck (Facebook), and Bazel (Google)} have abstractly, *tasks* for building various types of build targets; functionality specific to software build, test, (and deploy).

(And then  systems like PyTorch and TensorFlow also have an online CFG that may be 'conpiled'/'executed' for and then on a given architecture)

(And then systems for data provenance model inputs, container commands, and outputs: dvc and quilt data)

GitHub Actions is a CI service - a continuous integration service that runs commands upon the firing of git post-receive event hooks - for running tasks that gives you the build logs - the output for each task - through the web. You can call whatever build, test, train, or deploy commands needed in a CI build script.

- Manual local build request / Git post-receive hook
  - Bash
    - Docker build / podman / builds build; [cloud] container build system XYZ:
      - MultiStage Dockerfile
        - Bash
          - Ansible & Subprocess
            - Make
              - [C]Make
                  - Clang
                  - Test runner
                  - Create package archive
                    - add metadata manifest
                    - compress to e.g. ZIP, which does CRC32
              - Upload signed build artifact to package repo
            - Deploy latest artifact to one or more new servers
              - Test the installed version; Is the program self-testing
            - (Only after the integration tests succeed in a clone of the production architecture, Update the DNS and/or Load Balancer configuration and HUP to reload so that *new* requests are pointed to upgraded and tested servers while old requests continue to go to old versions. Ansible can do this, but Terraform and Helm are *prupose-built* to keep production systems consistent with their executable definitions)

Is this the simplest, least complex thing that will work (for this portable desktop application)?

https://github.com/nektos/act :

> Run your GitHub Actions locally [...]
> Local Task Runner - I love make. However, I also hate repeating myself. With act, you can use the GitHub Actions defined in your .github/workflows/ to replace your Makefile!

I'm so old that I read that and think "and then I'll call *that* with a Makefile", which I still add to everything even though GNU Make is not a build chain component that should be expected to be installed either.

IMHO, there should be Actions that result in a built, tested, published, [and deployed] software application.

**Comment by b08x** [comment]
Ansible works for software automation in general. It can compile a binary all by itself after you give it the instructions to do so. Sound familiar? It should, as it describes the build process, in general. Sorry if I seem annoyed, but my point is somehow getting lost here. Wikipedia is not a good source here unfortunately, as it does not acknowledge that these are merely frameworks from which the creative mind can do with as it pleases. 

"IMHO, there should be Actions that result in a built, tested, published, [and deployed] software application." 
This is exactly Ansible was made for and does. If you look it, which obviously no one here has, you would know this.

Don't misunderstand my annoyed mood...I'm not trying advertise specific software. It's just that I'm getting feedback without the person having actual experience, and that is really obnoxious.

**Comment by hammerandtongs** [comment]
> On Debian 11:
> sudo apt install juce-tools
> git clone https://github.com/awwbees/BespokeSynth.git
> cd BespokeSynth
> Projucer --resave BespokeSynth.jucer
> cd Builds/LinuxMakefile
> make -j6
> [wait a while]
> [keep waiting]
> cd build
> ./BespokeSynth

I also needed libusb-1.0-0-dev and libjack-dev on my debian testing.

**Comment by b08x** [comment]
> > On Debian 11:
> > sudo apt install juce-tools
> > git clone https://github.com/awwbees/BespokeSynth.git
> > cd BespokeSynth
> > Projucer --resave BespokeSynth.jucer
> > cd Builds/LinuxMakefile
> > make -j6
> > [wait a while]
> > [keep waiting]
> > cd build
> > ./BespokeSynth
> 
> I also needed libusb-1.0-0-dev and libjack-dev on my debian testing.

You didn't have a problem with the fonts? Hmm...on "myyy debain" things compile without fatal exception, however I am unable, that is to say the computer is unable, to load the application itself due to it not knowing where it's own fonts are. 

```
void LoadGlobalResources()
{
   gFont.LoadFont(ofToResourcePath("frabk.ttf"));
   gFontBold.LoadFont(ofToResourcePath("frabk_m.ttf"));
   gFontFixedWidth.LoadFont(ofToResourcePath("iosevka-type-light.ttf"));
   //gModuleShader.load(ofToResourcePath("shaders/module.vert"), ofToResourcePath("shaders/module.frag"));
}
```

**Comment by hammerandtongs** [comment]
> > > On Debian 11:
> > > sudo apt install juce-tools
> > > git clone https://github.com/awwbees/BespokeSynth.git
> > > cd BespokeSynth
> > > Projucer --resave BespokeSynth.jucer
> > > cd Builds/LinuxMakefile
> > > make -j6
> > > [wait a while]
> > > [keep waiting]
> > > cd build
> > > ./BespokeSynth
> > 
> > 
> > I also needed libusb-1.0-0-dev and libjack-dev on my debian testing.
> 
> You didn't have a problem with the fonts? Hmm...on "myyy debain" things compile without fatal exception, however I am unable, that is to say the computer is unable, to load the application itself due to it not knowing where it's own fonts are.
> 
> ```
> void LoadGlobalResources()
> {
>    gFont.LoadFont(ofToResourcePath("frabk.ttf"));
>    gFontBold.LoadFont(ofToResourcePath("frabk_m.ttf"));
>    gFontFixedWidth.LoadFont(ofToResourcePath("iosevka-type-light.ttf"));
>    //gModuleShader.load(ofToResourcePath("shaders/module.vert"), ofToResourcePath("shaders/module.frag"));
> }
> ```

lol yeah i do have that problem once I tried to move it from LinuxMakefile/build (but it does run well where it built)

**Comment by dromer** [comment]
Please try current master as it has been updated to latest JUCE and uses cmake which makes the builds much easier to do.

**Comment by KottV** [comment]
> Ansible is for configuration and setup of multiple servers, not compiling applications. Just use a makefile or something instead. In any case, makefiles or playbooks are not an alternative to a compiled binary like an AppImage.

https://download.opensuse.org/repositories/home:/bespokesynth/AppImage/

EDIT: ok, it's not working due resource missing
EDIT2: resource lookup fixed

feedback appretiated

**Comment by westurner** [comment]
- https://www.google.com/search?q=install+opensuse+appimage+on+fedora
  - https://en.opensuse.org/openSUSE:Build_Service_AppImage_builds
    - https://docs.appimage.org/packaging-guide/hosted-services/opensuse-build-service.html
      - OBS builds AppImages from source or existing RPMs now!

Thx. Will hopefully have a chance to test on FC34 later this week. (Edit) FWIW, the non-AppImage Linux release definitely works on FC34 but that's not auto-updating.

**Comment by hemangandhi** [comment]
If it's any help, here's a few nixpkgs I tried to build to install this on NixOS: https://github.com/hemangandhi/dot-files/tree/master/nix-envs/bespoke-synth

The zip installation failed since for whatever reason, I get that the executable file isn't found. This happens with `strace` too so the only hunch I have is that it's built with a different assembly/binary format than what my system expects -- `file $(which BespokeSynth)` names a linker I don't have.

The git installation built successfully and ostensibly runs. But on launching the app, I'm told that `frabk.ttf` couldn't be found and there's no other text on the screen. (I think some of you had this issue on Debian too?)

**Comment by KottV** [comment]
> the non-AppImage Linux release definitely works on FC34 but that's not auto-updating

what release are you refering to?

**Comment by follower** [comment]
@KottV Thanks so much for the AppImage build! I tried it out & it worked for me.

The only thing that didn't work was a Surge VST crashed when loading (well, just after, it turns out)...

...ironically, this seems to have turned out to be because the binary download release appears not to load *any* VST3 on Linux?

AFAICT Bespoke is *intended* to support VST3 but with the binary release it just outputs. e.g.:

```
Attempting to load VST: /usr/lib/vst3/SurgeEffectsBank.vst3/Contents/x86_64-linux/SurgeEffectsBank.so
Attempting to load VST: /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so
Attempting to load VST: /usr/lib/vst/carla.vst/CarlaPatchbayFX.so
Creating VST instance: CarlaPatchbayFX
[...]
```

While troubleshooting the crash I discovered (via `LD_DEBUG=bindings` the binary release only ever looks for the `VST2` symbol `VSTPluginMain` instead of the `VST3` equivalent `GetPluginFactory`:
```
/usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so: error: symbol lookup error: undefined symbol: VSTPluginMain (fatal)
```

Whereas with the AppImage release this can be seen:  
```
binding file /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so [0] to /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so [0]: normal symbol `GetPluginFactory'
```

I noticed the AppImage build uses JUCE6 rather than JUCE5 due to a recent patch so maybe this explains the difference?

Thanks again for the AppImage build, I really appreciate it!

**Comment by KottV** [comment]
yes, binary from site is 5.4.7 yet
and Surge 1.9 is known to crash in Bespoke, developers are aimed to the next Surge_XT

**Comment by follower** [comment]
@hammerandtongs @hemangandhi If Bespoke can't find its resources in the default location it looks for an environment variable named `BESPOKE_DATA_DIR` & uses the path from there: https://github.com/BespokeSynth/BespokeSynth/blob/7576d6b0d50925bf67b13b59e0536992823d241f/Source/OpenFrameworksPort.cpp#L134-L135

This is probably why the text isn't showing.

You may want to try setting `BESPOKE_DATA_DIR` to an appropriate value. (As I discovered KottV had done with the AppImage. :) )

**Comment by jistr** [comment]
@unfa 
> I've just tried to run the official release on Manajro Linux. I'm using PipeWire as a replacement for JACK and PulseAudio and when I set BepokeSynth to use JACK, it now eits immediatelly after startign with a message "Killed". Is there a config file I can delete to try again? I can't find anything in my user's home directory....

I ran into a similar problem trying to use PipeWire JACK interface (Bespoke seems to hang for me though, not crash). Looks like the config is in `$XDG_DOCUMENTS_DIR/BespokeSynth`, so typically `$HOME/Documents/BespokeSynth`. After deleting that directory, Bespoke starts again.

**Comment by jistr** [comment]
@ruffson 
> Did anyone get it to work on Fedora 34? I keep getting a:
> 
> ```
> ./BespokeSynth: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
> ```
> 
> I have the python dev packages installed, tried sym-linking to my `libpython3.so` and even tried installing `python3.8-3.8.12-1.fc34.i686` which is the only package in the repos which provides that so. But no luck.

Just `dnf install python3.8` so that you get the x86_64 package.

(I don't know why `dnf provides libpython3.8.so.1.0` will only list the i686 package... I guess we have to query the full path as `dnf provides /usr/lib64/libpython3.8.so.1.0`, which then prints the correct package.)

**Comment by ruffson** [comment]
@jistr Ah thanks, good to know. I reverted to using the copr which at some point caused conflicts with zam plugins which made me uninstall that and currently I am testing the appimage which seems to work well.

**Comment by pushqrdx** [comment]
Except #309 everything is running absolutely fine on debian sid with Pipewire here, just Download prebuilt `Linux` package and run, but make sure to have libpython3.8 (you can dpkg -i [libpython3.8-minimal from ubuntu](https://pkgs.org/download/libpython3.8-minimal))

**Comment by BrunoVernay** [comment]
> Except #309 everything is running absolutely fine on debian sid with Pipewire here, ...

But are you using Jack as a "devicetype" or Alsa? (On Fedora it keeps crashing if Jack is selected. It would be nice to be able to sync transport.)

It seems that "Improve Linux support" could be closed as there are packages for most major distributions.
What is missing is support for Jack/Pipewire. That would allow to sync the transport with other applications. (That would also open the way for Flatpak.)

**Comment by tobiasBora** [comment]
For references, I managed to configure multiple inputs/outputs in pipewire by using ALSA + fake sources. More here https://github.com/BespokeSynth/BespokeSynth/issues/500

**Comment by BrunoVernay** [comment]
> For references, I managed to configure multiple inputs/outputs in pipewire by using ALSA + fake sources. More here #500

Thanks, #500 is indeed way more focused on Jack/Pipewire issue.  But JUCE being the issue, it will take time to solve it in JUCE, then to integrate the new JUCE version in Bespoke. Linux use-case being prioritized as their relative user base, both in JUCE and Bespoke, expect years before Jack/Pipewire is supported properly.  (There are still dependencies on X11, and crashes du to Wayland not being supported properly.)  
I do not want to sound too sad, the glass is half full: Bespoke works with Alsa and Wayland crashes are not frequents.

**Comment by KottV** [comment]
Bespokes's AppImage is available.

**Comment by alvaro-cuesta** [comment]
For anyone landing here from Google, you can download the AppImage here: https://download.opensuse.org/repositories/home:/bespokesynth/AppImage/

Works out of the box in Steam Deck.
