### ISSUE TITLE
Website Download Links Are Occluded by Footer in Narrower Browsers

### ISSUE THREAD

**Issue by tmilker** [BespokeSynth/BespokeSynth#109]
I'm not sure exactly which site being blocked causes it but with UBlock Origin & tracker URLs blocked, the download links on the website aren't able to be clicked.  ~~There's a number of errors in the console from grayscale.js that might be the cause of it:~~

The cause is the div containing the message footer(the one about all payment levels being the same) overlapping the links when the browser is 1182px or less.

**Comment by KottV** [comment]
it's a direct link https://www.bespokesynth.com/builds/Bespoke-Windows.msi
and hasn't any scrips or even redirects

**Comment by tmilker** [comment]
Looked at it again: It's not the ad blocking, it's the browser width.  A browser width under 1183 pixels has the div containing the footer(with the extra clear part) cover everything and not let the clicks through.

**Comment by awwbees** [comment]
thanks for this report! narrowing it down to the browser width was very helpful. I got some help on twitter and it is now fixed. you might need to shift-refresh the page to reload the CSS
