### ISSUE TITLE
VST problem, need some help

### ISSUE THREAD

**Issue by davephillips** [BespokeSynth/BespokeSynth#11]
Greetings ! 

Okay, I have identical Ubuntu 18.04 installations on my desktop and laptop machines. I build Bespoke from source on both machines. On the laptop Bespoke will load and use VST plugins without trouble. On the desktop loading a VST will stop all audio processing, including the clock. I use the same VST SDK, and as far as I can tell there's no significant difference between systems. Can anyone give me a hint where I should be looking to debug the problem on the desktop ? TIA!

dp

**Comment by KottV** [comment]
Hi,

Usually, I run app in gdb (need to build with RELEASE=Debug) and strace -f. Sometimes it gives a clue.

**Comment by davephillips** [comment]
@KottV - Thanks, I'll do a debug build today and see what I can find.

**Comment by awwbees** [comment]
gonna call this one stale
