### ISSUE TITLE
win 8.1 - zoom does not work

### ISSUE THREAD

**Issue by RO-mix** [BespokeSynth/BespokeSynth#111]
Cannot zoom using mouse wheel. Actually it does not work at all on all controls.

**Comment by RO-mix** [comment]
I have same issue with VItal vst.. which is also written on Juce.... in all other apps - all works.

**Comment by awwbees** [comment]
hmm, I'm sorry to hear this... it does seem suspicious that two JUCE apps both exhibit the same problem. maybe a JUCE bug? but I would think more people would complain about this if it happened in all JUCE apps. have you tried with another mouse, in case there's something particularly bizarre going on with yours?

**Comment by RO-mix** [comment]
Yes i tried with all devices. It is not a mouse..Same with anything.
Actually same beahavior i can also see in third Juce app - Unify..
Mousewheel messages does not get passed. I found a similar bug in Juce with AAX, something with MOUSE_HOOK

**Comment by KottV** [comment]
> I have same issue with VItal vst.. which is also written on Juce.... in all other apps - all works.

what is zoom with mouse wheel in Vital?

**Comment by awwbees** [comment]
stale issue, reopen if it's still causing issues

**Comment by RO-mix** [comment]
Sorry, did not see it. I will check.. What i understood - every plugin that use Open GL - Has no mouse wheel control on my system...
