### ISSUE TITLE
Black screen on macOS 13

### ISSUE THREAD

**Issue by hannesbraun** [BespokeSynth/BespokeSynth#1116]
## Describe the bug

When trying to start Bespoke on macOS 13.1, I only get a window with a black background. I didn't find a workaround yet. The application also hangs when trying to close it.

With macOS 12.6.2, Bespoke draws the UI as expected.

## Build info

Bespoke Nightly (2023-02-01)

## Steps To Reproduce

- Open Bespoke on macOS 13.
- You should now be presented with a black window.

## Expected vs. actual behavior

I expected the usual Bespoke UI to appear.

**Comment by andynameistaken** [comment]
When you compile it from source it displays UI, but haven't tested it further.
~~It looks like on the page is old release.~~

Anyway compiled version returns warinng:
```
ld: warning: dylib (/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib) was built for newer macOS version (13.0) than being linked (10.11)
```

**Comment by hannesbraun** [comment]
What kind of UI do you mean? All the Bespoke UI elements? I just compiled the latest master branch from source and all I get is the standard macOS window title bar...
<img width="1812" alt="Bildschirm­foto 2023-03-30 um 18 21 24" src="https://user-images.githubusercontent.com/37622889/228901233-f7198bda-801e-4b28-8175-5b31685a4979.png">

**Comment by andynameistaken** [comment]
Ok, I tried to  run it again and I have the same issue. It **was** working however I wrote answer too early - I should open it at least twice to be sure. I'm sorry for misleading you.

**Comment by withywindle** [comment]
The Nightly build from 2023-04-07 works for me on macOS 13. Downloaded from https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly

**Comment by hannesbraun** [comment]
Hmm, still doesn't work for me. I'll see if I can find another macOS 13 machine and see if it works there. Maybe it's something about my setup...

**Comment by NoxyNixie** [comment]
I've had people report that moving the Bespoke window sometimes resolved the black screen issue on mac.

**Comment by hannesbraun** [comment]
> I've had people report that moving the Bespoke window sometimes resolved the black screen issue on mac.

Unfortunately, that's not working for me either. But I got my hands on another macOS 13 machine and it's running fine there. So maybe, there's something installed/configured/whatever on my own computer that Bespoke doesn't like. I'll see when I've got time to search for this...

**Comment by NoxyNixie** [comment]
Make sure to also try resetting/removing your `Documents/BespokeSynth/userprefs.json` file. This seems to be needed when your hardware or drivers changes.

**Comment by andynameistaken** [comment]
I got nightly build running and what blocks loading GUI for me is connecting mini-jack to the computer. 
If I leave it unplugged it loads GUI.

**Comment by hannesbraun** [comment]
> I got nightly build running and what blocks loading GUI for me is connecting mini-jack to the computer.
> If I leave it unplugged it loads GUI.

Thanks a lot! Yes, having something plugged in to the headphone jack is causing Bespoke to not load the GUI for me as well.

**Comment by jobor019** [comment]
I had the same issue on a 13" MacBook Pro (2018) running  MacOS 12.5.1, I would just get a black screen when starting Bespoke. Since it was the first time I launched it on my current machine, there was no userprefs.json to configure.

Stepping through the code, it seems that [this line](https://github.com/BespokeSynth/BespokeSynth/blob/647e4a415f69f46dc08bb34a68470ea94c20b03e/Source/MainComponent.cpp#L247-L252) was causing the freeze (or more specifically [here](https://github.com/juce-framework/JUCE/blob/cfa289d943fb235d1d1fa6a087c4cded5bab1b41/modules/juce_audio_devices/native/juce_mac_CoreAudio.cpp#L701)). After some experimenting, I managed to get to the point where a userprefs.json was created and then I got a warning that my audio device (built-in speakers) didn't support a buffer size of 256. Changing it to 512 in the userprefs.json seems to have solved the issue for me.

**Comment by dme26** [comment]
I encountered what seems to be a similar situation on various computers running macOS 12.6.6. I seem to have unblocked the problem by uninstalling NoMachine (i.e., NX remote desktop: yet another piece of awesome software). I'm guessing that NX's virtual audio driver is similarly throwing off BespokeSynth's probing at start up: hopefully I can make progress with similar `userprefs.json` tweaking... (and no, I wasn't trying to use BespokeSynth over NX; I just happened to have NX installed. I note that Zoom and Teams' virtual audio devices seem not to be causing problems...)

**Comment by awwbees** [comment]
I believe this may finally be fixed by #1398, let me know!

**Comment by hannesbraun** [comment]
Yes, the issue is now gone (at least for me). Thank you very much!

**Comment by dme26** [comment]
Yes, fixed for me too. Thanks!
