### ISSUE TITLE
Crash on vst scan.. no chance to skip failed plugins

### ISSUE THREAD

**Issue by RO-mix** [BespokeSynth/BespokeSynth#112]
I have issues with some plugins (which i have plenty of).. Scanning mech does not continue scan after crash. Starts from the begining. So there is no chance to scan vst`s at all.. only copy something to separate folder and scan.

**Comment by rsmus7** [comment]
here too (Win 10) it crashes when I try to scan the vst folder, ( my folder is not on drive C:, I edited the search path)

**Comment by awwbees** [comment]
I've had enough people having issues with VST scanning that I'll have to rethink how it works. the scanning process should be skipping failed plugins, but it sounds like there's a bug.

for now, the temporary and unfortunate workaround would be to only scan a subset of your VST directories, or create a special directory where you copy in all the VSTs you want to use in bespoke, and just scan that directory

**Comment by skeddles** [comment]
yeah I had to delete the vst that wasnt working in order to finish scanning

**Comment by kiwisauce** [comment]
This seems more of an OS issue than VST issue imho

**Comment by awwbees** [comment]
fixed with new scanning process in #421
