### ISSUE TITLE
Bug - bypassed pan module doesn't send any audio

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1122]
## Describe the bug

When the pan module is bypassed, it doesn't send any audio.

## Build info

b6e01b9e3d13654c6849f1389767b459e7c5d6a3

## Steps To Reproduce

1. Send audio through the pan module
2. Disable the pan module
3. Nothing will come out the other side

## Expected vs. actual behavior

When disabled, the pan module should let audio though it as if its parameters were at their initial values.

**Comment by NoxyNixie** [comment]
I believe this was fixed in the Bypass rework.
