### ISSUE TITLE
Reason Rack VST3 Crashes Bespoke 1.0.0 on Win 10

### ISSUE THREAD

**Issue by AriaSalvatrice** [BespokeSynth/BespokeSynth#114]
Loading the Reason Rack Plugin 11.3.9d22 VST3 by Reason Studios crashes Bespoke 1.0.0 on Windows 10:

- Two instances of the Reason plugin are detected after a scan
- Adding either instance of Reason Rack Plugin crashes bespoke
- No error message of any kind, including when launching via Powershell
- Running Bespoke as admin doesn't prevent the crash
- The same installation of the Reason plugin was verified to work in other DAWs

Two instances of the Reason plugin being detected might be a separate issue - note that they provide both a .dll and .vst3: 
![image](https://user-images.githubusercontent.com/25130242/133427798-379d628d-b10a-4e27-bd9b-d38013889580.png)

The Reason Rack Plugin is notoriously difficult to get to work in VST hosts, but incredibly powerful, I'd love to get a chance to use it with Bespoke :D

**Comment by KottV** [comment]
You can open `Documents/BespokeSynth/vst/found_vsts.xml` and find the lines with that vst3's and their path.
Also I recommend reduce vst search path for just one dir with one plugin for testing :)
Maybe it can narrow.

**Comment by AriaSalvatrice** [comment]
From looking at that XML, one has `category="Fx"` and the other `category="Instrument"`, without the distinction being made in the UI. After removing one of the two entries from the XML, saving, and relaunching, Bespoke still crashes, so it's not the root of the problem.

**Comment by KottV** [comment]
ah, yeah BespokeSynth uses plugin's filename, not it's real/reported name
according crash with the Reason, it may be useful to test it with reference JUCE AudioPluginHost, maybe it's a JUCE-Reason specific bug

**Comment by KottV** [comment]
And off topic)

I saw your modules for vcvrack. I really hope you find a love with BespokeSynth and port your apps to it.

**Comment by awwbees** [comment]
it seems like I should get reason rack so I can try this out. it looks like they have a 7 day trial, so I guess after I start the trial, I have 7 days to race and figure out cause of the crash!

**Comment by NoxyNixie** [comment]
I've seen people have Reason Rack working perfectly with the Nightly builds. If this issue re-emerges please don't hesitate to post here again (or create a new issue, either way is good).
