### ISSUE TITLE
Bug - midicontroller "blink" feature does not work with Arturia MiniLab MKII

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1140]
## Describe the bug

The "blink" feature for midicontroller binds does not work for the Arturia MiniLab MKII, despite it supporting the feature (and possibly others).

## Build info

b6e01b9e3d13654c6849f1389767b459e7c5d6a3

## Steps To Reproduce

![image](https://user-images.githubusercontent.com/24578572/216571301-510bc7b4-4b4f-4c1c-980c-397f1e79c68e.png)

1. Add a midicontroller
2. Bind a control that has an LED on the controller to a value in bespoke.
3. Enable blink
4. Press the control

## Expected vs. actual behavior

If you're using an Arturia MiniLab MKII, the control that _should_ be blinking (according to bespoke) probably isn't blinking. It's possible other controllers have this problem, but I only have this controller to test with.

**Comment by awwbees** [comment]
does the minilab allow midi messages to control its lights? if it doesn't, this feature won't work. I don't have a minilab to test on, but I have another piece of arturia gear, and it handles lighting control in a poor way.

**Comment by PowerUser64** [comment]
From what I've seen in [the product's marketing](https://www.arturia.com/minilab-mkii/details) (go to the "pads" section near the top) and [some youtube videos](https://www.youtube.com/watch?v=OoqierppAzM&t=4m7s) it looks like it does support the feature. It is possible it does it in a weird way. I'm not sure how I would learn how it works though. Any ideas?

**Comment by PowerUser64** [comment]
Closing as it seems this to be an issue with the hardware
