### ISSUE TITLE
Please do a release.

### ISSUE THREAD

**Issue by magnetophon** [BespokeSynth/BespokeSynth#1155]
For us packagers out there!  :)

**Comment by NoxyNixie** [comment]
A release (1.2) is in the works but there is no ETA nor is there a roadmap.

It will be done when it is done ;)

In the meantime you can head to https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly for the latest official Nightly builds or go to https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth-current for additional Nightly builds provided by @KottV .

**Comment by magnetophon** [comment]
Ok, thanks.
