### ISSUE TITLE
Microphone Permission Popup not triggered on Mac OS Big Sur and Microphone not usable

### ISSUE THREAD

**Issue by KaiKruschel** [BespokeSynth/BespokeSynth#116]
Expected Behaviour:

On loading an input module an OS Popup comes up requesting Permission to use the System Microphone. After granting the request the microphone is usable and the permission shows up in the System Preferences under Security&Privacy -> Privacy -> Microphone

Current Behaviour:
The permission request never comes and therefore the microphone input cannot be used in Bespoke.

**Comment by KaiKruschel** [comment]
If started through a terminal application the microphone permission gets requested for the terminal after which bespoke runs as expected while running through the terminal.

**Comment by awwbees** [comment]
what do you have your "audio_input_device" assigned to in the "settings" section?

**Comment by paradiddle16** [comment]
I'm on mojave and the microphone doesn't work even though it's listed as an input in Bespoke. I checked in the permissions under security & privacy and the app isn't listed there. As far as I remember it didn't ask for any permissions. I had older versions of Bespoke on this mac all now deleted. Could that have screwed with it?

**Comment by awwbees** [comment]
I've gotten a few other reports on this, it seems like big sur must have changed how microphone permissions work. classic apple! I guess I'll have to upgrade to big sur so I can take a hands-on look. unless any enterprising mac devs who already have big sur installed see this issue and want to take a crack at it?

**Comment by paradiddle16** [comment]
Hi Ryan, I'm not on Big Sur myself. Mojave here. I can tell you that the microphone works no prob in all other softwares no exceptions. It didn't ask me for permissions for this version of bespoke. tried everything and still doesn't work.

**Comment by KaiKruschel** [comment]
I have the Built-in Microphone set as "audio_input_device". It's working fine with ableton and others. I had a quick google and found a couple posts on the JUCE boards of devs reporting similar problems on Mojave. I think these permissions were introduced with Mojave?

**Comment by biomassa** [comment]
i am seeing the same behavior, can't use audio input because the security dialog that allows the use of microphone is never triggered.

**Comment by nelsonmilum** [comment]
I'll +1 this as well. MacOS 11.6, M1 Mac, Bespoke 1.0.0

**Comment by sampok** [comment]
No audio input permission request on macOS Catalina either.

**Comment by awwbees** [comment]
8f9f0c0a5e1880d6e16c7c8c56b2e88a58e2bed8 should fix this, will be in 1.0.1 release

**Comment by monkymind** [comment]
**Update: Just noticed [KaiKruschel](https://github.com/awwbees/BespokeSynth/issues/116#issuecomment-920051104) mention this method 7 days ago...**

----

I also had no audio in (macOS Catalina). 

My workaround was to run **/Applications/BespokeSynth/Bespoke.app/Contents/MacOS/Bespoke** in terminal and then gave it microphone permission when requested. 

![Mac-audio](https://user-images.githubusercontent.com/51474710/134372668-767ac532-33b8-4a03-8f27-06976031bd26.jpg)

![settings](https://user-images.githubusercontent.com/51474710/134373442-f2128478-6c5e-4bc1-9bd8-ca85b8d111f3.jpg)

Looking forward to the 1.0.1 release :-)
