### ISSUE TITLE
crash on startup on Ubuntu 20.04

### ISSUE THREAD

**Issue by pierre2mars** [BespokeSynth/BespokeSynth#118]
I tried to run Bespoke on my laptop running Ubuntu 20.04
When I run bespoke_dependencies.sh, almost every dependency is present or installed except for libjack0, I get the following message:
following packages have unmet dependences:
 libjack-dev : Dépend: libjack0 (= 1:0.125.0-3build2) but will not be installed
(I translated the messages from french). 

When I run BespokeSynth, I get the following error:
Cannot connect to server socket err = No file or folder of this type
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Process stopped
Do you know what is the issue?
best regards,

Pierre

**Comment by dadoprom** [comment]
I have the same issue on also Ubuntu 20.04

**Comment by pierre2mars** [comment]
I tried what is discribed in this message: https://discord.com/channels/846834873254805554/853305783453745192/885728023377215518 
But even with jack running on a "dummy", Bespoke crashes... i don't know what else I can try?

**Comment by pierre2mars** [comment]
one more thing: here is the log from jackd: 
Wed Sep 15 22:28:26 2021: New client 'JuceJackDummy' with PID 122034
Wed Sep 15 22:28:26 2021: Client 'JuceJackDummy' with PID 122034 is out

**Comment by dromer** [comment]
On jackd2 (debian bullseye) I have to restart bespoke several times before it "sticks" and will run.

First time I changed the setting it immediately crashed, not particularly reliable yet (I kind of hope the update to JUCE6 will make it more stable: https://github.com/awwbees/BespokeSynth/issues/105 )

**Comment by KottV** [comment]
you can try these builds against Ubuntu 20.04

https://software.opensuse.org/package/bespokesynth-bin
https://software.opensuse.org/package/bespokesynth-data

**Comment by dadoprom** [comment]
@KottV thanx, these builds work on my 20.04 kubuntu
