### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by id-be** [BespokeSynth/BespokeSynth#1183]
## Summary

Timestamps for more accurate recording/exporting of songs and samples, ideally with autosnap to areas of the timeline that are not silent.

### Motivation

Greatly increase precision of recording start/stop times.

If you are able to provide a pull request yourself for the feature that you are
proposing, please say so!

**Comment by NoxyNixie** [comment]
I'm not sure what you mean. Most of anything related to time in Bespoke is in [bars (or measures)](https://en.wikipedia.org/wiki/Bar_(music)) and should be sample accurate.

You can very easily use the `eventcanvas` module to automatically start and stop recording and in combination with the `timelinecontrol` module you can also reset the time to 0 (or any other arbitrary number (which is in bars (or measures)).

And then there is the `songbuilder` if you want to control a bunch of modules in a single location and it allows you to sequence things.

Recording modules like the `looper` (and related) will already snap their recordings to measures (or parts or multiples).

So I'm not clear on what you want from this feature request? Can you perhaps illustrate it or explain some more?

**Comment by PowerUser64** [comment]
Closing until further comment
