### ISSUE TITLE
BLD: MacOS: Package with brew formula or cask

### ISSUE THREAD

**Issue by westurner** [BespokeSynth/BespokeSynth#119]
STORY: Users can keep BespokeSynth up to date on MacOS systems with homebrew.

Docs:
- https://brew.sh/
  - src: https://github.com/Homebrew/brew
  - docs: https://docs.brew.sh/
  - docs: https://docs.brew.sh/Adding-Software-to-Homebrew
  - docs: https://westurner.github.io/tools/#homebrew
  - https://github.com/westurner/dotfiles/blob/34171e5e8b0afe3860015b0d7abef806a1c49b8b/scripts/upgrade_mac.sh#L17
    - ```bash
      # sudo -u "${SUDO_USER}" brew upgrade $(sudo -u "${SUDO_USER}" brew list)
      brew upgrade $(brew list)
      brew cask upgrade # visual-studio-code iterm2 google-chrome firefox
      ````
- https://formulae.brew.sh/formula/fluid-synth#default
  - https://github.com/Homebrew/homebrew-core/blob/master/Formula/fluid-synth.rb
- https://formulae.brew.sh/cask/mixxx
  - https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/mixxx.rb

**Comment by westurner** [comment]
- [ ] Are relative paths required for successful portable packaging with homebrew?
  - "Mac version is tied to a hard-coded, non-standard path" awwbees/BespokeSynth#117

**Comment by awwbees** [comment]
can someone elaborate on the request here? sorry, I don't fully have the context to understand what is being requested.

**Comment by KottV** [comment]
maybe it means add BespokeSynth in homebrew repo, so it can be downloaded and build by Mac users in "home brew" way
@westurner you can try to do that if you're familiar with homebrew :)

**Comment by westurner** [comment]
Releasing packages to repositories that are regularly fetched from with a software updater has a number of advantages; vaguely:

- prevention of old version fragmentation: issues for old versions where it wasn't fixed yet
- in the event of e.g. security release, without a software updater, users will continue to have only the version that they downloaded until they just decide to go check the software version on the website regularly

https://brew.sh/ is one way to package apps on MacOS. E.g. `brew install bash firefox python` updates those formulas to the latest versions available in the package repo. IIRC, brew doesn't care what build system the hashed artifact to pkg is from

In the desc, there's an example of a brew formula for fluid-synth and a cask of mixx.

IIRC, brew only does cryptographic hashes and like conda - which also works on MacOS and does updates - doesn't do cryptographic signatures (or TUF or sigstore, which are newer than brew)? 

Somebody that's going to commit to updating the hash in the formula/cask could easily just cp another formula or create one with `brew create`

**Comment by westurner** [comment]
"Building Against Non-Homebrew Dependencies" https://docs.brew.sh/Building-Against-Non-Homebrew-Dependencies

**Comment by baconpaul** [comment]
@awwbees i got surge working in brew. Happy to chat about it. Basically first time is but tricky and there’s some packaging requirements but once you’ve done it once it is easy to maintain and their document and processes are good.  Op is right to tag issue 117 as one to resolve first also

**Comment by Tadaboody** [comment]
I think that once 117 is closed, we can use a `cask` like
```rb
﻿﻿cask "bespoke-synth" do
  version "1.0.0"
  sha256 :no_check

  url "https://www.bespokesynth.com/builds/Bespoke-Mac.dmg"
  name "bespoke-synth"
  desc "Modular DAW"
  homepage "https://www.bespokesynth.com/"

  app "Bespoke.app"
end
```
(Assuming 117 will rid of the `BespokeSynth` folder completely, otherwise `app "BespokeSynth/Bespoke.app"`)
Note the `sha256 :no_check`, this is because brew doesn't allow checking for sha if the resource url is not versioned

**Comment by baconpaul** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/surge-synthesizer.rb

there's the one we used for surge. We will need to rewrite this for surge-xt (our new release) since it changes package names and stuff. 

Also maybe get a version in the dmg in the bistro too?

Agree 117 is a pre-req

**Comment by djsavvy** [comment]
Looks like this issue can be closed now! I was able to install `bespoke` as a cask using homebrew.

**Comment by baconpaul** [comment]
Huh yeah!

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/bespoke.rb

**Comment by baconpaul** [comment]
Thanks https://github.com/llimllib who updated it! Neat

**Comment by westurner** [comment]
Thanks!
