### ISSUE TITLE
system-wide install and data path

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#12]
Hi,

I'd like to package BespokeSynth (I hope, you're not against more popularity) in Linux repositories.
One thing stops that - relative path for 'data' dir to binary. BS won't start without minimal configuration, so it has to be somewhere in system, if we gonna to install it via package manager.
What do you think, is it possible to distinguish factory and user datadir?
JUCE has File::commonApplicationDataDirectory File::userApplicationDataDirectory File::globalApplicationsDirectory File::userHomeDirectory functions which helps to find userdir and system path for data storing.

From my side I'll try to realize using examples from other JUCE synth (with my zero-level skills in c++)

**Comment by awwbees** [comment]
sorry, I missed this message! I don't know much about packaging in linux repos, but I'm definitely not against it. I'll have a look to figure out a way to have a system-wide install path... maybe I'll just have a priority system where bespoke scans through a list of directories when it starts up, and stops at the first valid one it finds

**Comment by KottV** [comment]
Ok, it's not so important feature for now)

**Comment by KottV** [comment]
As linux users are here now and I'm on way do make .deb packages in OBS, I'd like to rise up this question again. For now I package Bespoke with these modifications:
```
#elif JUCE_LINUX
   static string sDataDir = "";
   if (sDataDir == "")
   {
//      string localDataDir = File::getCurrentWorkingDirectory().getChildFile("data").getFullPathName().toStdString();
      string localDataDir = File::getSpecialLocation(File::userApplicationDataDirectory).getChildFile("BespokeSynth/data").getFullPathName().toStdString();
      if (juce::File(localDataDir).exists())
         sDataDir = localDataDir;
      else
//         sDataDir = File::getCurrentWorkingDirectory().getChildFile("../../MacOSX/build/Release/data").getFullPathName().toStdString();   //fall back to looking at OSX dir in dev environment
         sDataDir = File::getSpecialLocation(File::globalApplicationsDirectory).getChildFile("share/BespokeSynth/data").getFullPathName().toStdString();
   }

   return sDataDir + "/" + path;
#else
```

It makes to look data in ~/.config/BespokeSynth and fallback to /usr/share/BespokeSynth
@djdeath @awwbees what do you think about that concept?

**Comment by awwbees** [comment]
that seems like a great concept! I probably would want to modify it to:
```
#elif JUCE_LINUX
   static string sDataDir = "";
   if (sDataDir == "")
   {
      //look for a "data" folder in the current working directory
      //failing that, look for ~/.config/BespokeSynth/data
      //failing that, look for /usr/share/BespokeSynth/data
      //failing that, look in the OSX folder, which is my shared data folder for development
      string localDataDir = File::getCurrentWorkingDirectory().getChildFile("data").getFullPathName().toStdString();
      if (juce::File(localDataDir).exists())
      {
         sDataDir = localDataDir;
      }
      else
      {
         string configDataDir = File::getSpecialLocation(File::userApplicationDataDirectory).getChildFile("BespokeSynth/data").getFullPathName().toStdString();
         if (juce::File(configDataDir).exists())
         {
            sDataDir = configDataDir;
         }
         else
         {
            string shareDataDir = File::getSpecialLocation(File::globalApplicationsDirectory).getChildFile("share/BespokeSynth/data").getFullPathName().toStdString();
            if (juce::File(shareDataDir).exists())
            {
               sDataDir = shareDataDir;
            }
            else
            {
               sDataDir = File::getCurrentWorkingDirectory().getChildFile("../../MacOSX/build/Release/data").getFullPathName().toStdString();   //fall back to looking at OSX dir in dev environment
            }
         }
      }
   }

   return sDataDir + "/" + path;
#else
```

to keep much of the existing behavior
(I haven't tested/compiled this code, but I imagine it will work, barring typos)

**Comment by djdeath** [comment]
Have you looked into flatpak? https://flatpak.org/

A number LV2/VST plugins are available there already : 

```
$ flatpak search LV2
Name                 Description                                                       Application ID                                Version    Branch Remotes
So Synth LV2         So Synth LV2 plugin                                               …freedesktop.LinuxAudio.Lv2Plugins.SoSynthLV2 1.5        19.08  flathub
VL1Emulator          VL1 Emulator, An emulator of Casio VL-Tone VL1, based on source … …reedesktop.LinuxAudio.Lv2Plugins.VL1Emulator 1.1.0      19.08  flathub
Linux Audio BaseExt… Shared platform for Linux Audio plugins                           org.freedesktop.LinuxAudio.BaseExtension      19.08.1    19.08  flathub
x42Plugins           x42 LV2 Plugins collection                                        org.freedesktop.LinuxAudio.Plugins.x42Plugins 2020.07.14 19.08  flathub
ZamPlugins           ZamAudio Plugins LADSPA/LV2/VST                                   org.freedesktop.LinuxAudio.Plugins.ZamPlugins 3.13       19.08  flathub
LSP                  Linux Studio Plugins LADSPA/LV2/VST                               org.freedesktop.LinuxAudio.Plugins.LSP        1.1.24     19.08  flathub
KapitonovPluginsPack KapitonovPluginsPack Guitar amp LADSPA/LV2 plugins                …ktop.LinuxAudio.Plugins.KapitonovPluginsPack 1.2.1      19.08  flathub
DPF-Plugins          DPF-Plugins LV2/VST                                               …g.freedesktop.LinuxAudio.Plugins.DPF-Plugins 1.3        19.08  flathub
DISTRHO-Ports        DISTRHO Plugin Ports LV2/VST                                      …freedesktop.LinuxAudio.Plugins.DISTRHO-Ports 2020.07.14 19.08  flathub
sfizz                sfizz is a sample-based musical synthesizer LV2/VST3 plugin       org.freedesktop.LinuxAudio.Plugins.sfizz      0.4.0      19.08  flathub
reMID                reMID LV2 Plugin                                                  org.freedesktop.LinuxAudio.Plugins.reMID-lv2  0.3        19.08  flathub
GM Synth             General MIDI Synth LV2 plugin                                     org.freedesktop.LinuxAudio.Plugins.gmsynth    0.5.0      19.08  flathub
ZynAddSubFx Synthes… ZynAddSubFx (with Zyn-Fusion UI) LV2/VST plugins                  org.freedesktop.LinuxAudio.Plugins.ZynFusion  3.0.5      19.08  flathub
Surge Synthesizer    Surge Synthesizer LV2/VST3                                        org.freedesktop.LinuxAudio.Plugins.Surge      1.7.1      19.08  flathub
Ninjas2              Ninjas2 LV2/VST Plugin                                            org.freedesktop.LinuxAudio.Plugins.Ninjas2    0.2.0      19.08  flathub
Helm Synthesizer     Helm Synthesizer LV2/VST plugin                                   org.freedesktop.LinuxAudio.Plugins.Helm       0.9.0      19.08  flathub
Geonkick             Geonkick drums LV2 plugin                                         org.freedesktop.LinuxAudio.Plugins.Geonkick   2.3.6      19.08  flathub
ADLplug OPL/OPN      ADLplug OPL3/OPN2 soundchip FM Synthesizer LV2/VST plugin         org.freedesktop.LinuxAudio.Plugins.ADLplug    1.0.2      19.08  flathub
SWH                  SWH LV2 plugins                                                   org.freedesktop.LinuxAudio.Lv2Plugins.swh     1.0.16     19.08  flathub
setBfree             setBfree DSP Tonewheel Organ emulator LV2                         …g.freedesktop.LinuxAudio.Lv2Plugins.setBfree 0.8.11     19.08  flathub
TAP-plugins          Tom's Audio Processing LV2 plugin                                 org.freedesktop.LinuxAudio.Lv2Plugins.TAP     1.0.0      19.08  flathub
Sorcer               Sorcer polyphonic wavetable synth LV2 plugin.                     org.freedesktop.LinuxAudio.Lv2Plugins.Sorcer  1.1.3      19.08  flathub
MDA                  MDA Piano LV2 plugin                                              org.freedesktop.LinuxAudio.Lv2Plugins.MDA     1.2.4      19.08  flathub
GxPlugins            GxPlugins LV2                                                     ….freedesktop.LinuxAudio.Lv2Plugins.GxPlugins 0.8.0      19.08  flathub
Fabla                Fabla LV2 drum sampler plugin instrument.                         org.freedesktop.LinuxAudio.Lv2Plugins.Fabla   1.3.2      19.08  flathub
DrumGizmo            DrumGizmo drums LV2 plugin                                        ….freedesktop.LinuxAudio.Lv2Plugins.DrumGizmo 0.9.18.1   19.08  flathub
ArtyFX               ArtyFX LV2 plugin suite                                           org.freedesktop.LinuxAudio.Lv2Plugins.ArtyFX  1.3        19.08  flathub
AVL Drumkits         AVL Drumkits LV2 plugin                                           …g.freedesktop.LinuxAudio.Lv2Plugins.AVLDrums 0.4.1      19.08  flathub
LSP (Linux Studio P… LSP collection of LV2 plugins                                     ….github.wwmm.pulseeffects.plugin.lsp-plugins            4      flathub
```

That would solve packaging for all distros and we would get plugins for free.

**Comment by KottV** [comment]
I'm not familiar with flatpack because I prefer plugins be compiled natively in distro's environment and JUCE hasn't any additional dependencies, just X11 and ALSA (if this is the standalone application).
But I'll take a look for how they made that packages, thnx.

**Comment by KottV** [comment]
@djdeath 
If I understand correctly, plugins should be "flatpacked" too https://www.figuiere.net/hub/blog/?2020/06/22/881-flatpak-extensions
This is not convenient way if user just wants to add any VST (closed source for example) plugins to the project.

**Comment by djdeath** [comment]
So Flathub is a place dedicated to open/free apps mostly. But there is no restriction on having an additional flatpak source (much like another deb repo) that provides proprietary VSTs.

Quoting the flatpak documentation : `Applications can be open source or proprietary (although some distribution services, like
Flathub, can have restrictions in this respect).`

**Comment by KottV** [comment]
I understand.
But who will upload own payed plugin into flathub? :)

**Comment by djdeath** [comment]
I guess one solution for this would be to have BespokeSynth lookup a particular directory for additional plugins and make it accessible through the sandbox : https://docs.flatpak.org/en/latest/sandbox-permissions.html

That way you could drop-in a binary VST you got from a vendor.

**Comment by KottV** [comment]
It possible actually. But it's restricted for /usr thus system-wide plugins won't be accessed I'm afraid.
It's worth for bringing more popularity to Bespoke :). But I never have exp with Flatpack, so I can take a look in free time only because packaging in OBS has priority (and it supports many distros too).

**Comment by djdeath** [comment]
I started looking into it actually, hopefully will have something to share soon.

**Comment by djdeath** [comment]
My initial attempt : https://github.com/djdeath/org.freedesktop.LinuxAudio.BespokeSynth.yml

Pretty much doesn't work at this point, need to solve GL/audio issues.

**Comment by KottV** [comment]
And no VST as expected. If you want to add it there some tricks to do that:

1 Patch form jpcima https://github.com/jpcima/juce-linux-patches (that I use)
2 Use vestige instead of Steinberg SDK https://github.com/peterrudenko/JUCE/tree/6527266acc4074e8b501ffe21be4fbc8a8a28f3f as in https://github.com/helio-fm/helio-workstation
3 Use FST headers: https://git.iem.at/zmoelnig/FST/

**Comment by KottV** [comment]
Meanwhile there first .deb packages:

https://software.opensuse.org/package/bespokesynth-data
https://software.opensuse.org/package/bespokesynth-bin

It's very experimental and requires python27. Anyway, any testers are welcome @awwbees 

(if didn't mention before openSUSE bleedin-edge builds are here https://build.opensuse.org/package/show/home%3Akill_it%3AJUCE/BespokeSynth )

**Comment by djdeath** [comment]
> And no VST as expected. If you want to add it there some tricks to do that:
> 
> 1 Patch form jpcima https://github.com/jpcima/juce-linux-patches (that I use)
> 2 Use vestige instead of Steinberg SDK https://github.com/peterrudenko/JUCE/tree/6527266acc4074e8b501ffe21be4fbc8a8a28f3f as in https://github.com/helio-fm/helio-workstation
> 3 Use FST headers: https://git.iem.at/zmoelnig/FST/

Yeah, could do either. Just fighting a gnome-shell bug that crashes my session every time I launch the flatpak...

**Comment by KottV** [comment]
Oh. What is your distro and is it on Wayland (you have it iirc)?

**Comment by KottV** [comment]
I'm still think about proper perfect implementation for system/default/template and user(s) config.
It should keep user's configs up to date, or even maybe validate user's values.

```
Assume we have default/template config in /usr/share/BespokeSynth/data/userprefs.json (or wherever it in other OS).

At first we check if there is a userprefs.json in user's directory.

If No - copy the template in here. Open the preferences window as it is the first run.

If Yes - read lines in system template and then check if there is such parameter in user's config.
   If parameter is present - ok (maby validate for correct value such a path, or device name), keep it.
   If parameter is absent - insert it in the user's config with default value.
```
   
Maybe there is good practice already available over internet, if we don't want to re-invent bicycle?

**Comment by KottV** [comment]
I'd like to rise this question with  some thoughts:

Idea is to add to BespokeSynth the ability to handle user's data right. It should help BespokeSynth be more mature as distributable application.

I think it makes sense for all platforms, not just Linux.
At present Bespoke looks for data in directories then just uses it, no matter is that data actual or not.
So if some data files is updated in upstream, then user has to update manually. These files can be python stubs, text files, config template or smth else.

I see the next mechanism:

BespokeSynth is distributed with data files that will be installed in some system directory, readonly.
After the start, BespokeSynth compares user's and system data set. If system's is newer then user's files need to update.
Some files can be updated without warnings: help.txt, tooltips.txt, python stumbs.
Some other files: config.json, blank.json might be modified by user, and then we have to think what to do. I haven' t perfect idea for now *

As first step I propose to add the VERSION tag in valuable files, it can be git tag with short commit name, as for this moment: v0.0005-pre-261-g001bd0c for example.**
Thus, it will be easy to know that we need to update, even if nothing changed - it should not bring a problems.

I can start my own branch with that feature and try to implement this.
What do you think about this?

* it can be done as Linux package managers do:

if user's file is modified, then we put new file as userprefs.jsonnew and show the warning window which tells that you have to update your strings in config, including VERSION tag.
if file is not modified (same as default system) then we rename it in userprefs.jsonsave for safety then copy the new one.

** I must admit that I don't know how to compare such strings.

**Comment by awwbees** [comment]
9fee0ac837445a500f3b22ea40ce76b6ed85f6c1 includes the changes to have the behavior you're describing cross-platform. please let me know if these changes appropriately align to linux conventions! (in particular, the directories it uses to copy data from and to)

**Comment by KottV** [comment]
it changes user's data path from `userApplicationDataDirectory` to `userDocumentsDirectory` eg from `~/.config` to `~/Documents`
there is no any linux convention where is the right place to keep it, `~/.config` , `Documents` , `~/.local/share` - everyone dances as he can

if you intend to keep it in the same on every platform - fine, while i package it with `userApplicationDataDirectory` in mind
i think it's not late to change in your way)

**Comment by KottV** [comment]
oh, it won't work without `resource` dir in the current path, I mean in linux packaging we have:
```
/usr/bin/BespokeSynth (readonly) - binary itself
/usr/share/BespokeSynth/* (readonly) - data provided by package

~/.config/BespokeSynth/* (readwrite) - user's stuff
or/and
~/Documents/BespokeSynth/* (readwrite) - user's stuff
```
and what is difference between resource and data dirs?

**Comment by awwbees** [comment]
> if you intend to keep it in the same on every platform - fine, while i package it with `userApplicationDataDirectory` in mind
> i think it's not late to change in your way)

`~/.config` is a hidden directory, right? so I think it probably makes sense to use `~/Documents`, since users are intended to browse that directory

> oh, it won't work without resource dir in the current path, I mean in linux packaging we have:

ah yes, this was an oversight. fixed in 7c7c58f448bc6f863acdb577da907bef5cb358b4 to add `/usr/share` support for the `resource` directory

> and what is difference between resource and data dirs?

the intent here is that `resource` is for files that the user is not expected to modify (fonts, python documentation stubs, etc) and `data` is the directory users are expected to modify (`userprefs.json`, savestates, adding samples for the drumplayer to use, etc). the `resource` directory stays in the installed location (adjacent to the executable, or in `/usr/share`) and the `data` folder is copied to `~/Documents` to keep it separate from the install, with the behavior you describe above

additionally, in my most recent changes, I made it so that `userprefs.json` no longer needs to be distributed: bespoke can run with default settings when it doesn't find one. using the "settings" button within bespoke will allow users to create and edit a `userprefs.json` file

**Comment by KottV** [comment]
> `~/.config` is a hidden directory, right? so I think it probably makes sense to use `~/Documents`, since users are intended to browse that directory

Yeah, that make sense!

> the intent here is that `resource` is for files that the user is not expected to modify (fonts, python documentation stubs, etc) and `data` is the directory users are expected to modify (`userprefs.json`, savestates, adding samples for the drumplayer to use, etc). the `resource` directory stays in the installed location (adjacent to the executable, or in `/usr/share`) and the `data` folder is copied to `~/Documents` to keep it separate from the install, with the behavior you describe above

The vst scanner's files `deadmanspedal.txt found_vsts.xml used_vsts.json` must be writable  to user? So i guess they should be moved to the `data` then.

> additionally, in my most recent changes, I made it so that `userprefs.json` no longer needs to be distributed: bespoke can run with default settings when it doesn't find one. using the "settings" button within bespoke will allow users to create and edit a `userprefs.json` file

I saw that, cool!

**Comment by awwbees** [comment]
> The vst scanner's files deadmanspedal.txt found_vsts.xml used_vsts.json must be writable to user? So i guess they should be moved to the data then.

yeah, that was an issue, so I moved the vst scanner files from `internal` to a new `vst` folder for this purpose

**Comment by KottV** [comment]
Didn't it pushed yet? )

**Comment by awwbees** [comment]
hmm, I believe that the pushed code exhibits the behavior I'm describing.

from VSTPlugin.cpp:
`juce::File deadMansPedalFile(ofToDataPath("vst/deadmanspedal.txt"));`

**Comment by KottV** [comment]
sorry, a was looking into `Builds/MacOSX/build/Release/resource/internal` only

**Comment by KottV** [comment]
I've made testing with empty run and copied necessary old user's files. Works fine.
This is significant improvement. Really appreciate it.
