### ISSUE TITLE
UBY: Linux: Backspace / [Shift+]Delete to detach patch

### ISSUE THREAD

**Issue by westurner** [BespokeSynth/BespokeSynth#120]
With linux on a macbook, I only have a delete key. Because it's not backspace on a mac. So, you have to do `Shift+Delete`, which for usability pruposes is suboptimal for deleting a currently-selected-with-the-touchpad patch connection because its:

What I understand the intended keyboard shortcut to be:

- [x] Tap and hold && Backspace

What I think the keyboard shortcuts could be in order to support e.g. linux on a mac laptop:

- [x] Tap and hold && Backspace
- [x] Tap and hold && Shift+Delete
- [ ] Tap and hold && Delete
- [ ] Tap to select && Delete (for a11y)

**Comment by awwbees** [comment]
cool, yeah, I don't think it will cause any issues if I support both backspace and delete. can you elaborate on the last a11y request, there? is there some issue with holding a mouse button and pressing a key at the same time?

**Comment by westurner** [comment]
Ah, it's a trackpad so there's like a claw motion that's necessary when
holding a drink of water.

So, no joke I just looked this one up and in the web accessibility
guidelines I think this one is most similar:

https://www.w3.org/WAI/WCAG21/quickref/#keyboard-no-exception :

> 2.1.3 Keyboard (No Exception) Level AAA
> All functionality of the content is operable through a keyboard interface without requiring specific timings for individual keystrokes

And then the mouse guidelines describe additional guidelines.

Maybe also something like [Shift] Ctrl-P to select where to patch to/from?
Ctrl-P is from vim and now also vscode

Just Delete support would be cool.  Hopefully there's a Ctrl-z

**Comment by dromer** [comment]
Nearly every time I want to delete a module I first press the delete key .. and then realize it's doing nothing and press backspace.

I kind of feel that just Delete should be the better UX here (and indeed an undo for those unfortunate accidents).

**Comment by tobiasBora** [comment]
I also always type Delete before using backspace since most programs use it anyway. I also often try to delete a module that way before realizing I need to click on the arrow to delete it. For ctrl-z I created a separate issue here https://github.com/BespokeSynth/BespokeSynth/issues/526

**Comment by awwbees** [comment]
this was fixed in #388

**Comment by westurner** [comment]
Thanks!
