### ISSUE TITLE
Circle sequencer offsets are inverted

### ISSUE THREAD

**Issue by AriaStein** [BespokeSynth/BespokeSynth#121]
Increasing the offset value for a ring in the circle sequencer moves the offset backwards in time, and decreasing it moves it forward. This only affects the note itself; the UI correctly moves the rings forwards or backwards, causing the UI to not reflect the notes as actually played.

Issue encountered using the Windows build of version 1.0.0 on Windows 10.

**Comment by awwbees** [comment]
whoops! sheesh, I don't know how that one slipped through. easy fix for the next release, thanks!
