### ISSUE TITLE
Plugin host mode

### ISSUE THREAD

**Issue by sjomae** [BespokeSynth/BespokeSynth#1212]
## Summary
BespokeSynth only generates sound when the transport is running? I was wondering, why doesn't it function as a plugin host if the transport is not running? 

### Motivation

Use BespokeSynth (temporarily) in plugin host mode. Being able to generate sound from external input without running the transport.

**Comment by NoxyNixie** [comment]
Bespoke isn't designed like your usual DAW where the transport is something separate from audio processing. Bespoke wasn't designed to be "paused" in a similar way the more traditional linear DAWs do. The pausing of Bespoke is stopping audio processing completely and for the most part should only be used when you want to actually stop audio processing (for instance when you temporarily want to use the system resources elsewhere).

If you want to control things in a more traditional way you can use modules like the `songbuilder` or `groupcontrol`.
