### ISSUE TITLE
Compilation issues on UbuntuStudio 21.04

### ISSUE THREAD

**Issue by anagram3k** [BespokeSynth/BespokeSynth#122]
The bespoke build doesn't work on ubuntu 21.04 because the python installed version is 3.9

I am trying to compile it, but for some reason the build button on Projuicer is disabled. The paths are correct and JUCE is installed in home. This happens on the latest JUCE 5 and the latest JUCE 6

**Comment by KottV** [comment]
Projucer 5.4.7 hasn't build ability in Linux and 6'th version removed that option at all.
You have to generate the Makefile then do make.

BTW I've build Ubuntu 21.x packages:
https://software.opensuse.org/package/bespokesynth-bin
https://software.opensuse.org/package/bespokesynth-data

**Comment by anagram3k** [comment]
Thanks for the packages.

Anyway, found how to do it. Projuce creates the Makefile when you save the project.  This is completely not intuitive.
The compiling is working using JUCE 5, but I will use your packages. It is better to have standardized packages.

**Comment by anagram3k** [comment]
Another thing: Ubuntu 21.04 uses jack2 and this line in install_requirements.sh
```
sudo apt-get -y install libjack-dev
```
Will completely bork the system. 
BespokeSynth compiles and runs with libjack-jackd2-dev

**Comment by KottV** [comment]
yes, I think this still in the docs from the past
and surely you don't need to run any scripts, dependencies will be brought by PM

**Comment by ghost** [comment]
> The Bespoke (official) build doesn't work on ubuntu 21.04

Does not work on Debian 11 (where Python3.9.x)

BTW, What about provide distro independed package for Linux in form of ***AppImage*** with all needed dependencies bundled?

- https://appimage.org
  - https://github.com/AppImage/AppImageKit
  - https://github.com/AppImage/awesome-appimage

**Comment by ghost** [comment]
> BTW I've build Ubuntu 21.x packages:
> - https://software.opensuse.org/package/bespokesynth-bin
> - https://software.opensuse.org/package/bespokesynth-data

@KottV, may you provide direct link to your packages, because clicking on <kbd>Show community packages</kbd> on linked pages shows nothing.

**Comment by anagram3k** [comment]
It worked for me, @Symbian9. Click on "Expert Download" after clicking on "Show community packages"

**Comment by ghost** [comment]
> It worked for me, ~~`@Symbian6`~~ `@Symbian9`. Click on "Expert Download" after clicking on "Show community packages"

It does not work in Firefox `78.14.0esr` (maybe there are some issue with CSS/JS/etc. in browser).

Anyway I already found direct links to its DEB's:

- https://download.opensuse.org/repositories/home:/kill_it:/debian/
