### ISSUE TITLE
Linux: Touchpad stops working when opening a module via letter shortcut.

### ISSUE THREAD

**Issue by lvets** [BespokeSynth/BespokeSynth#1230]
## Describe the bug

When I open a module via it's letter (for instance "n"), my touchpad stops working and I can't scroll to the correct module in the menu that opened.
This happens in Ubuntu 23.04 and Ubuntu 22.10 running GNOME on Wayland.

## Build info

"bespoke 1.1.0 (Dec 25 2007 09:50:38) - Linux - unknown-branch deadbeef" & "bespoke NIGHTLY 1.1.0 (May  3 2023 01:44:26) - Linux - HEAD ab42359"

## Steps To Reproduce

Press "n" and try to move your mouse pointer.

## Expected vs. actual behavior

I would expect I would be able to move my mouse around. This works on Windows 11 for instance.

**Comment by KottV** [comment]
Does work with X11?

**Comment by lvets** [comment]
> Does work with X11?

Yeah, that works.

**Comment by lvets** [comment]
Some further testing reveals this also works fine on Arch Linux with Plasma on Wayland.

**Comment by NoxyNixie** [comment]
[I recall](https://discord.com/channels/846834873254805554/890239133677670410/1089511311332880503) this happening to someone else in the past and it looks to be not the fault of Bespoke but rather the input system used. 

Check your drivers/input support software for this "feature".

If you can demonstrate this actually is a Bespoke issue please report back here and I'll reopen the issue.

**Comment by lvets** [comment]
Found the issue, it's called "Disable While Typing" under Touchpad in Gnome-tweaks. You can probably disable this option via CLI as well.
