### ISSUE TITLE
Ramper target value not reached under certain conditions

### ISSUE THREAD

**Issue by dowdm** [BespokeSynth/BespokeSynth#1232]
## Describe the bug

A ramper using a length of a quarter note or smaller doesn't always achieve target value (Smallest length values seem most error prone)

## Build info

bespoke NIGHTLY 1.1.0 (Apr  7 2023 04:18:58) - Windows 11 - HEAD 8564ba1

## Steps To Reproduce

- open new project
- add ramper, add send
- connect ramper to send amount
- set ramper length to 64n, target 1
- press start on ramper
- set ramper target to 0, press start
- repeat with different target values

## Expected vs. actual behavior

Expected: target value is reached
Actual: target value is often times not reached (and neither rounded nor truncated)

**Comment by NoxyNixie** [comment]
This was fixed in fe543c8ae3ff7c5aa335b02750852c25a00a5e2d. You should download a newer Nightly build to have this fix.
