### ISSUE TITLE
spectrum module inconsistent 

### ISSUE THREAD

**Issue by ShantySuffisance** [BespokeSynth/BespokeSynth#1233]
## Describe the bug

The spectrum module sometimes shows nothing, even when audio cables show that signal flows into it. Sometimes adding a new spectrum module disables the old ones. Sometimes the spectrum module correctly shows a spectrum although no audio cable is connected to it.  

## Build info

bespoke 1.1.0 (May  8 2023 14:49:48) - Linux - main ab423597
(Kernel: 6.2.0-2-rt3-MANJARO)

## Steps To Reproduce

![grafik](https://user-images.githubusercontent.com/63818756/236837217-5a262ab6-4c8a-429f-a8a5-55a7c44801bd.png)

## Expected vs. actual behavior

I'd prefer that every instance of the spectrum module would exactly visualize the audio signal which is connected to it. Thank you very much for this great open source program. I really enjoy using it for fun or for teaching.

**Comment by PowerUser64** [comment]
Pretty sure this is related to #1058 and possibly #1246

**Comment by NoxyNixie** [comment]
I can not reproduce this one anymore. I think this was fixed with the Bypass rework patch.
