### ISSUE TITLE
Audio ports limited to 16?

### ISSUE THREAD

**Issue by Eurikon** [BespokeSynth/BespokeSynth#124]
Hi there, thanks for sharing this application.

I wanted to try it out, but unfortunately i can't reach the higher channels of my ADAT card.

The audio module shows only up to 16 channels,
is there a way around this?

Cheers :)

**Comment by awwbees** [comment]
ah, it looks like I have them hardcoded to a max of 16 at line 236 in https://github.com/awwbees/BespokeSynth/blob/master/Source/MainComponent.cpp

I naïvely thought that 16 was a reasonable limit. I am now very jealous of your soundcard! I should be able to raise that limit for a future release, or make it configurable.

**Comment by Eurikon** [comment]
Thanks, i will have to wait for that release then. 
Take your time, i will look around here from time to time.
(the sound card is RME Digiface USB (32 ADAT channels in total). 

Configurable sounds better to me, as there are people with even more channels, 128 hardware channels is not something strange in bigger studios.

All the best,
Latif

**Comment by dromer** [comment]
For the JACK driver it would be great if you could create i/o at will instead of limiting it to whatever the physical sound-device provides. I could have 1024 (or more) virtual i/o ports if I wanted to, even though my sound-card maybe has only 2.

However I believe this is a limitation to JUCE since it assumes it should always connect to a sound-card, even with the JACK driver.

**Comment by Eurikon** [comment]
> ah, it looks like I have them hardcoded to a max of 16 at line 236 in https://github.com/awwbees/BespokeSynth/blob/master/Source/MainComponent.cpp
> 
> I naïvely thought that 16 was a reasonable limit. I am now very jealous of your soundcard! I should be able to raise that limit for a future release, or make it configurable.

Hi, is there any update on this yet?
I would really like to try this software :)

**Comment by awwbees** [comment]
sorry, I haven't gotten to this particular issue yet. although in the time since you posted this issue, it has now become wildly easy to build from source, if you want to make that small change and try it out!
