### ISSUE TITLE
Bug - CRASH - shift-click to add send often crashes bespoke

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1245]
## Describe the bug

Often, shift-clicking on an audio source to add a send often crashes bespoke if bespoke has been open for long enough.

## Build info

- bespoke NIGHTLY 1.1.0 (May 18 2023 04:25:34) - Linux - HEAD 5f14a39

## Steps To Reproduce

1. Use bespoke for some time (30 minutes?)
2. Shift-click on a module's blue audio dot

profit

## Expected vs. actual behavior

This often crashes bespoke if it has been open for a while. It should never crash when adding a send with shift-click.

**Comment by awwbees** [comment]
hmm, I can't reproduce this one, unfortunately (on mac, at least). I was jamming with bespoke for many hours last weekend and never encountered it, and just now left a session running for 4 hours and then shift-clicked to create a bunch of sends with no crashes. maybe there's more steps involved to cause this one to reproduce? (or maybe it's linux-only? but that'd be odd)

**Comment by PowerUser64** [comment]
Just reproduced it by putting an instrument through a line of 94 sends (mixed with a few other things), it crashed on adding the 95th send. I also had a number of other things running at the time, which could've contributed to the crash. A few complex prefabs that mix data types. Here is the backtrace from gdb:

```
#0  ModularSynth::MouseMoved (this=this@entry=0x1adb550, intX=<optimized out>, intY=<optimized out>) at /home/user/git/BespokeSynth/Source/ModularSynth.cpp:1252
#1  0x0000000000675d0f in MainContentComponent::render (this=0x1adb040) at /home/user/git/BespokeSynth/Source/MainComponent.cpp:349
#2  0x000000000101864f in juce::OpenGLAppComponent::renderOpenGL (this=<optimized out>) at /home/user/git/BespokeSynth/libs/JUCE/modules/juce_opengl/utils/juce_OpenGLAppComponent.cpp:61
#3  juce::OpenGLContext::CachedImage::renderFrame (this=this@entry=0x1af8c10) at /home/user/git/BespokeSynth/libs/JUCE/modules/juce_opengl/opengl/juce_OpenGLContext.cpp:326
#4  0x00000000010189bb in juce::OpenGLContext::CachedImage::runJob (this=0x1af8c10) at /home/user/git/BespokeSynth/libs/JUCE/modules/juce_opengl/opengl/juce_OpenGLContext.cpp:583
#5  0x0000000000b93b47 in juce::ThreadPool::runNextJob (this=0x172d320, thread=...) at /home/user/git/BespokeSynth/libs/JUCE/modules/juce_core/threads/juce_ThreadPool.cpp:384
#6  0x0000000000bc8367 in juce::ThreadPool::ThreadPoolThread::run (this=0x1ecc650) at /home/user/git/BespokeSynth/libs/JUCE/modules/juce_core/threads/juce_ThreadPool.cpp:36
#7  0x0000000000b7b65e in juce::Thread::threadEntryPoint (this=0x1ecc650) at /home/user/git/BespokeSynth/libs/JUCE/modules/juce_core/threads/juce_Thread.cpp:96
#8  0x0000000000b7b8a9 in juce::juce_threadEntryPoint (userData=<optimized out>) at /home/user/git/BespokeSynth/libs/JUCE/modules/juce_core/threads/juce_Thread.cpp:118
#9  juce::threadEntryProc (userData=<optimized out>) at /home/user/git/BespokeSynth/libs/JUCE/modules/juce_core/native/juce_posix_SharedCode.h:865
#10 0x00007ffff73bfdd4 in start_thread () from /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libc.so.6
#11 0x00007ffff74419b0 in clone3 () from /nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libc.so.6
```

the send that broke the camel's back

![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/82be0baa-a6fc-4f1e-a0cd-2a805952b164)
![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/ed5a21fb-052e-4ddd-8e1d-472879e58080)

I think the general strategy to reproducing this is having some signal go between two points and then shift click to add send a ton. I also had connected the second output of the first 50 sends to the next send just to see if it made a difference, and I'm not convinced it did. Also, this bug is not a fan of alt-dragging as a way of getting more sends - it counts it as cheating and won't trigger by doing this. (I got up to 400 sends by duplicating the line and nothing happened except it took longer to duplicate all of them each time.)

**Comment by PowerUser64** [comment]
Steps to reproduce:
1. Make two gains and connect them
![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/d9f8d7b3-737b-4e4a-8f1f-74b724de84e8)
2. Shift click the point connecting them to add a send about 141 times
![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/16e9dac8-fc91-4683-bfc3-9da61c20ada1)

Eventually it will explode in a fiery flame :boom:
