### ISSUE TITLE
Crash on startup windows 11 

### ISSUE THREAD

**Issue by vriken** [BespokeSynth/BespokeSynth#125]
Hey, I just found bespoke and I think it looks really cool, although when I try to start it it freezes for a second then crashes.
My windows version is 20H2 and the OS build is 19042.1165.
I get no errors, it just crashes.

**Comment by awwbees** [comment]
is there a crash log in your <Documents>/BespokeSynth/ folder?

**Comment by vriken** [comment]
No, there are no logs or error messages.

**Comment by awwbees** [comment]
hmm, that's a shame. I wonder if it's a windows 11 specific issue? are there any windows 11 users reading this who can successfully run bespoke?

**Comment by xandora** [comment]
~~While I can run successfully on Windows 11 (Build 22000.194), the UI seems to stop responding to any input after a while forcing me to either end the task or right-click on the taskbar icon and choose quit.~~ This was due to: https://github.com/BespokeSynth/BespokeSynth/issues/123

**Comment by awwbees** [comment]
please reopen if you have any additional info. from @xandora's comment it sounds at least like it's not a windows 11 specific issue.
