### ISSUE TITLE
Bug - Preset module no longer found in menu or list

### ISSUE THREAD

**Issue by rothen-silvia** [BespokeSynth/BespokeSynth#1253]
## Describe the bug

Where has the preset module gone? It still works when loading old patches, but I dont find it anymore in the version I just installed.

## Build info

bespoke NIGHTLY 1.1.0 (May 24 2023 03:55:29) - Windows 10 - HEAD 2bf5c70

## Steps To Reproduce

Open menu other or click on empty space and type "p"

## Expected vs. actual behavior

Module "preset" does not show.

**Comment by NoxyNixie** [comment]
It is renamed to `snapshots`.
