### ISSUE TITLE
Oversampling bug - Writing to audio causes rendered WAV file to play at double speed

### ISSUE THREAD

**Issue by MATT-OG89** [BespokeSynth/BespokeSynth#1255]
## Describe the bug
When I write to audio the .wav file in the recordings directory plays back at double speed. 

## My Bespoke Settings 
SampleRate: 44100, Buffersize: 1024, Oversampling: 2. 

## Rendered WAV file stats when using above settings
SampleRate: 88.2, BitsPerSample: 16

## Build info
bespoke NIGHTLY 1.1.0 (Apr  7 2023 04:10:04) - Mac OSX 12.1 - HEAD 8564ba1

## Steps To Reproduce
Selecting the write to audio button with oversampling set to 2

## Expected vs. actual behavior
Rendered WAV file plays at normal speed vs rendered WAV file playing at double speed

**Comment by PowerUser64** [comment]
I can reproduce this on the latest commit.
