### ISSUE TITLE
my scale is blocked

### ISSUE THREAD

**Issue by Lehomar2vinci** [BespokeSynth/BespokeSynth#126]
![image](https://user-images.githubusercontent.com/67152033/133505283-195c9cf8-621a-40db-bad1-c384e0845995.png)

i cant do anything between 2 menues

**Comment by awwbees** [comment]
can you provide some info or a video on how to recreate this one? I can't get it to happen, there must be something subtle that I'm missing.

**Comment by awwbees** [comment]
stale issue, I think this has probably been fixed when a bunch of other stuff got fixed
