### ISSUE TITLE
Bug - multitrackrecorder won't bounce audio unless project is already saved

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1260]
## Describe the bug

When the multitrackrecorder is used in a project that hasn't been saved yet, it won't bounce audio.

## Build info

5454edb76d270c564b954c38472810922d0245cb

## Steps To Reproduce

1. Make a new, blank, unsaved project
2. Add a multitrackrecorder and record something into it
3. Bounce the audio
4. Look for the recorded audio in the recordings directory

## Expected vs. actual behavior

The multitrackrecorder should be able to bounce audio regardless of whether the project has been named or saved yet.

**Comment by NoxyNixie** [comment]
If the project isn't saved the multitrack recorder does bounce but it does not save it with your usual filename it will just be `multitrack_#` where # is the track number.

I see that I can make this a little different so that it adds a date-time.
