### ISSUE TITLE
Bug - disabled inverter sends no audio

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1265]
## Describe the bug

When the inverter is disabled, no audio is sent.

## Build info

5454edb76d270c564b954c38472810922d0245cb

## Steps To Reproduce

1. Connect an audio source to an inverter
2. Disable the inverter

## Expected vs. actual behavior

The inverter should not invert the signal when it is disabled. Right now, it does not output anything.

**Comment by PowerUser64** [comment]
Related:  #1315

**Comment by NoxyNixie** [comment]
Resolved by b36538759363e67abd6a18f8cbd2f2cb9ebcb409.
