### ISSUE TITLE
Potential permissions problem on macOS Big Sur

### ISSUE THREAD

**Issue by jeffgca** [BespokeSynth/BespokeSynth#127]
I downloaded the mac binary and tried to run it. The window would appear briefly but then disappear. 

Sensing a startup bug, I decided then to run the binary in the .app bundle directly from iTerm. I then got a macOS file system permissions dialog, and I clicked "yes" to allow iterm access to the Documents ( I think? ) folder.

After this, Bespoke runs just fine from Finder.

I'd be happy to re-test this using a fresh user account, I assume this is rooted in Big Sur-specific permissions.

**Comment by awwbees** [comment]
seems like there are several big sur permissions problems! see #116 

has anyone else seen this one?

**Comment by nelsonmilum** [comment]
Running MacOS 11.6, MacBook Pro M1, latest release of Bespoke. I have issue #116, but did not have any issue launching the app initially.

**Comment by awwbees** [comment]
I believe all these big sur permissions issues are fixed and will be in the 1.0.1 release
