### ISSUE TITLE
Bug - Looper doesn't allow audio passthru when disabled

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1271]
## Describe the bug

When the looper is disabled, audio does not pass through it.

## Build info

5454edb76d270c564b954c38472810922d0245cb

## Steps To Reproduce

1. Send audio through a looper
2. Disable the looper

## Expected vs. actual behavior

The looper should let the audio through and not play the contents of the loop. Right now, it gets stopped.

**Comment by crshrprt** [comment]
You can "bypass" it if you click on "mute" in the looper. 
It seems looper has the same behavior of send or gain modules, when disabled they block the audio flow, that is different from other modules like effects or plugins modules where disabling them don't block the audio flow.
So, given there is already a way to "bypass" correctly, is probably a matter of deciding if this behavior is consistent or should be changed.

**Comment by PowerUser64** [comment]
Ah yes, I meant to make an issue about this too. Given that the gain can be muted by turning its slider all the way down, I think using the disable button on the gain to not apply the gain operation would make a lot more sense. Especially given that the gain module can be used for much more than just making things louder or quieter. It can also be used to do a variety of things like sidechain compression or ring modulation. For tasks like these, having the disable button act as a bypass is much more useful because it lets you see what things sound like without the gain applied.

**Comment by PowerUser64** [comment]
Closing in favor of #1315
