### ISSUE TITLE
Bug - macroslider's start and end parameters can become immovable

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1276]
## Describe the bug

After removing and adding parameters to the macroslider, the start and end parameters become immovable.

## Build info

5454edb76d270c564b954c38472810922d0245cb

## Steps To Reproduce

1. Add a macroslider
2. Set its number of parameters to 1
3. Set its number of parameters to 3
4. Try moving the offsets for parameter 2 and 3

(you will have to reload your project to make them movable)

[bespoke macroslider.webm](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/f27c808a-29e6-42a0-bb13-44f46bb072f3)

In the case of this recording, things behaved even weirder than they usually do, you're normally not able to move them at all. Maybe you need to connect the first cable to something while there's only one output? not sure.

## Expected vs. actual behavior

The macroslider shouldn't break in this way.

**Comment by NoxyNixie** [comment]
I am unable to reproduce this in the latest Nightly build. If this bug resurfaces, feel free to reply to this issue or create a new one.

**Comment by PowerUser64** [comment]
Ah! This must've been fixed in https://github.com/BespokeSynth/BespokeSynth/pull/1343
(which also means https://github.com/BespokeSynth/BespokeSynth/issues/1323 was related)
