### ISSUE TITLE
Sporadic issues with node & link association.

### ISSUE THREAD

**Issue by chrismahoney** [BespokeSynth/BespokeSynth#128]
I couldn’t really pin this down, but I think it has to do with z-indexing or something similar for situations where multiple inputs are connected to a sink (i.e. feeding a bunch of stuff into gain -> splitter -> output).

First oddity: Pulling the intended jack to delete it (assuming LIFO based on the UX) about 90% of the time pulls the earliest connector instead. I’ve made due by just recreating that connection but I could see that being an interruption for performers.

Second oddity, doesn’t seem fun: No repro, but sometimes detached links will actually start carrying the previously attached source, and sometimes even just adjacent ones around with it while trying to remove. Maybe something to do with zoom scale not updating, not sure. I’ll update this issue and feel free to close it if someone else has reported similar issues. Otherwise this thing rules.

**Comment by awwbees** [comment]
would it be possible to record a short video of these two issues, via OBS or some other screen recorder? that would be helpful to fully understand. if you need a place to host them, streamable.com is convenient

**Comment by awwbees** [comment]
stale issue without followup, let's close this!
