### ISSUE TITLE
Feat - mouse wrap at edges of screen while holding space or middle click

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1283]
## Summary

A feature of some other programs that provide to aide in navigating an infinite working canvas (notably blender) is to cause the mouse to wrap when reaching the canvas boarder. This makes it so the distance you can move on the canvas is only limited by the distance you can physically move your mouse, rather than screen size.

### Motivation

This would make the canvas a lot more fun and smooth to navigate.

Here's a demo of how this feature works in blender:

https://github.com/BespokeSynth/BespokeSynth/assets/24578572/f5cac0bc-1e9f-4095-8579-afa88e652973

**Comment by awwbees** [comment]
added in #1431
