### ISSUE TITLE
How can the MacOS build be used?

### ISSUE THREAD

**Issue by jorisvdstraten** [BespokeSynth/BespokeSynth#13]
Seems like I'm missing something?
`cd BespokeSynth-master/Builds/MacOSX/build/Release`
`./run_bespoke.command: line 3: ./Bespoke.app/Contents/MacOS/Bespoke: No such file or directory`

**Comment by awwbees** [comment]
ah yes, I shouldn't have put that Builds folder into the repo, that is confusing.

you can find releases on this page: https://github.com/awwbees/BespokeSynth/releases

here is the most recent mac build: https://github.com/awwbees/BespokeSynth/releases/download/v0.0003-pre/Bespoke-Mac.zip
