### ISSUE TITLE
Feat - allow multiline comments

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1311]
## Summary

Sometimes it is necessary to have long comments to explain what something does. This isn't easy with the current comment module, as it doesn't support newlines in comments.

### Motivation

Allowing multiline comments would make it easier to document things without resorting to using multiple comment modules.

At some point down the road, maybe basic markdown-style syntax could even be added, like \*\*bold\*\* and \*italics\*.

**Comment by NoxyNixie** [comment]
Mostly duplicate of #770 .
