### ISSUE TITLE
"Disable" button on all modules should act as a bypass button

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1315]
As stated by @crshrprt in #1271 [(in this comment)](https://github.com/BespokeSynth/BespokeSynth/issues/1271#issuecomment-1603862799), there is inconstant behavior between many modules in regards to how the disable button is used. Some modules (like `gain`) stop outputting any sound when they are disabled, and for other modules (like the `effectchain`), it acts as a bypass, allowing values to pass through without being affected by the module's operation. I think it would be wise to pick one of these behaviors and use it everywhere.

First of all, to be clear what we are talking about, here is a screenshot of the gain module with the button I am referring to highlighted:

![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/09d3fbac-5435-4a73-a14f-07dbe9fc871f)

- Option 1: the button should disable output. This is the current behavior of the gain module as well as a few others.
- Option 2: the button should be a bypass button, allowing audio to pass through unaffected by the module's operation.

Here's a table of all modules in the audio category and which option they currently use:

| module | option 1 | option 2 |
| --- | --- | --- |
| gain | ✅ | |
| audiometer | ✅
| buffershuffler | | ✅
| effectchain | | ✅ |
| eq | | ✅ |
| feedback | ✅ | |
| freqdelay |  |  |
| inverter | ✅ | |
| lissajous | ✅ | |
| looper | ✅ | |
| looperrecorder | ✅ | |
| looperrewriter |  |   |
| multitapdelay | ✅ | |
| ringmodulator | | ✅ |
| samplecapturer | ✅ | |
| samplegrid | ✅ | |
| send | ✅ | |
| signalclamp | ✅ | |
| spectrum | ✅ | |
| splitter | ✅ | |
| panner | ✅ | |
| stutter |  |  |
| waveformviewer | ✅ | |
| waveshaper | ✅ | |

> *vocoder modules are excluded from this list*

It seems that most modules that view themselves as "effects" use option 2 and all other modules use option 1. The problem with this thinking is that most modules are effects in one way or another. Aside from visualizers like `lisajous` and utility modules like `samplecapturer` or `looperrecorder`, all of these modules have parameters that can be modulated to create a wide variety of effects. For example, the `gain` module can be used to do anything from ring modulation to sidechain compression, both of which are operations that would benefit from being able to toggle the disable button to bypass the effect. With the way things are right now, the only way to reliably bypass the effect of any module is to add a send above it and route audio around it. This is both sub-optimal for module organization and time to execute.

The modules I think are in the most need of being changed to use option 2 are

- gain
- looper ([#1271](https://github.com/BespokeSynth/BespokeSynth/issues/1271))
- waveshaper
- feedback
- inverter
- multitapdelay

Perhaps an `audiogate` module should be added in place of this function?

**Comment by baconpaul** [comment]
A couple of random thoughts, since I saw this on discord

1. It sounds like you want a 'power' and a 'bypass' button both. So why not add both? Or if you don't want to burn the room have a three-mode switch there?
2. Minor but "deactivate" is better language than "disable"
3. VCVRack has built in APIs for what 'bypass' means where you can easily advertise "this module attaches this input to this output unchanged when bypassed". It also has a 'processBypassed' method (which defaults to `foreach (bypass pair) copy in to out` but which you can use for other things if you want). 
4. VST3 has a 'Bypass' parameter which is a pain in the neck for a variety of reasons, but i wonder if you want bypass to be chainable in the graph so you can bypass a group of modules at once?

**Comment by NoxyNixie** [comment]
Resolved by b36538759363e67abd6a18f8cbd2f2cb9ebcb409.

**Comment by PowerUser64** [comment]
🎉 Thanks for your hard work on this @NoxyNixie!

**Comment by NoxyNixie** [comment]
> 🎉 Thanks for your hard work on this @NoxyNixie!

You're welcome!
