### ISSUE TITLE
Feat - note to note number module

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1321]
## Summary

There are a number of text fields that support inputting a value from 0 to 127 to represent a note value. However, there is no easy way to automate giving them a value.

Thanks to [@nex on the bespoke discord server](https://discord.com/channels/846834873254805554/854199359913328671/1066648440458723409) who figured this out, there is an equation that can be used to convert values from note to note number, given the note's frequency: `log(x * (4/55) * pow(2, 3/4)) * 12 / log(2)`.

![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/5bf844e3-c871-4b7d-ac89-b58c855eebcd)

However, this may not be obvious to all users.

### Motivation

This would make it possible to easily change the note values on modules such as the drumsequencer and pitchremap without the need for the expression module.

**Comment by baconpaul** [comment]
that's an odd formula. The more traditional formula is `freq = 440 * 2^((note-69)/12))` so `log2(freq/440) * 12 + 69 = note`

but that only works for equal scales. The notetofreq object uses `TheScale->PitchToFreq` where the scale has many modes, many of which are non-invertible

https://github.com/BespokeSynth/BespokeSynth/blob/main/Source/Scale.cpp#L174

so I don't think getting this correct is entirely small. You need to write an inverse of all those scale modes, and some can only be inverted with a search.

**Comment by PowerUser64** [comment]
Implemented in #1489
