### ISSUE TITLE
Trying to use scripting crashes on Mac OS 10.15.7

### ISSUE THREAD

**Issue by rbnpi** [BespokeSynth/BespokeSynth#133]
Python3 installed with brew and set to default (so in terminal python --version =>Python 3.9.7) When scripting is selected, as soon as you try and tap anything in Bespoke quits.( EDIT I tried changing to python 3.8.12 Same problem)
Are there any specific setup procedures required for it to recognise python as installed?

**Comment by awwbees** [comment]
are you seeing this warning? and then after you click it, it crashes?
![image](https://user-images.githubusercontent.com/839239/133718022-76965530-1c61-4ad2-bcb7-f2b4eead9aee.png)

it is expected that 3.9 would crash, but 3.8 should have worked

hmm. it sounds like maybe it's not finding python correctly. do you know where your python 3.8 is installed?

**Comment by rbnpi** [comment]
Yes I do see that warning. I (now) have python@3.8 installed by Brew on my Mac. When I click to continue it quits.
I also have brew installed python@3.9 but this is unlinked.
I have the following links in place to access it
which python => /usr/local/bin/python
ls -l /usr/local/bin/python => /usr/local/bin/python3
ls -l /usr/local/bin/python3 => ../Cellar/python@3.8/3.8.12/bin/python3

i.e. its in /usr/local/Cellar/python@3.8/3.8.12/bin
This contains
2to3			pip3.8			python3.8
2to3-3.8		pydoc3			python3.8-config
idle3			pydoc3.8		wheel3
idle3.8			python3
pip3			python3-config


python --version => Python 3.8.12

**Comment by joshlacey** [comment]
I'm seeing the same issue on Big Sur 11.1

python --version => Python 3.8.2

**Comment by Tadaboody** [comment]
Am getting the same issue on big sur 11.6 and python3.9 installed globally when running bespoke through the terminal this was the crash dump
```
❯ ./Contents/MacOS/Bespoke
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Applications/Bespoke.app/./Contents/MacOS/Bespoke'
  sys.base_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.base_exec_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.executable = '/Applications/Bespoke.app/./Contents/MacOS/Bespoke'
  sys.prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.exec_prefix = '/Library/Frameworks/Python.framework/Versions/3.8'
  sys.path = [
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
    '/Library/Frameworks/Python.framework/Versions/3.8/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000011196ae00 (most recent call first):
<no Python frame>
objc[19946]: objc_disposeClassPair: class 'JUCEWindow_ef40c80d8ba1a32c' still has subclasses, including 'NSKVONotifying_JUCEWindow_ef40c80d8ba1a32c'!
objc[19946]: objc_disposeClassPair: class 'JUCEWindow_ef40c80d8ba1a32c' still has subclasses, including 'NSKVONotifying_JUCEWindow_ef40c80d8ba1a32c'!
```
(FWIW
```py
Python 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import encodings
>>> encodings
<module 'encodings' from '/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/__init__.py'>
```

**Comment by awwbees** [comment]
that "filesystem encoding" error looks familiar. does the workaround in #31 fix your issue?

**Comment by Tadaboody** [comment]
From what I got from 31 is that I should set `PYTHONPATH`/`PYTHONHOME`, setting it still doesn't fix it.
```py
0.171667: Loading layout: /Users/me/Documents/BespokeSynth/layouts/blank.json
Python path configuration:
  PYTHONHOME = '/Users/me/Forks/BespokeSynth/.venv/bin/python3'
  PYTHONPATH = '/Users/me/Forks/BespokeSynth/.venv/lib/python3.9/site-packages/'
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Users/me/Forks/BespokeSynth/build/BespokeSynth_artefacts/Debug/BespokeSynth.app/Contents/MacOS/BespokeSynth'
  sys.base_prefix = '/Users/me/Forks/BespokeSynth/.venv/bin/python3'
  sys.base_exec_prefix = '/Users/me/Forks/BespokeSynth/.venv/bin/python3'
  sys.platlibdir = 'lib'
  sys.executable = '/Users/me/Forks/BespokeSynth/build/BespokeSynth_artefacts/Debug/BespokeSynth.app/Contents/MacOS/BespokeSynth'
  sys.prefix = '/Users/me/Forks/BespokeSynth/.venv/bin/python3'
  sys.exec_prefix = '/Users/me/Forks/BespokeSynth/.venv/bin/python3'
  sys.path = [
    '/Users/me/Forks/BespokeSynth/.venv/lib/python3.9/site-packages/',
    '/Users/me/Forks/BespokeSynth/.venv/bin/python3/lib/python39.zip',
    '/Users/me/Forks/BespokeSynth/.venv/bin/python3/lib/python3.9',
    '/Users/me/Forks/BespokeSynth/.venv/bin/python3/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
```

**Comment by Tadaboody** [comment]
seems like defining `PYBIND11_FINDPYTHON` to be off lets pybind find the running pybind by itself and run python scripts no problem, will test a bit more and open a PR soon!

**Comment by rbnpi** [comment]
built from latest source (commit #213) and now working fine with my python.

**Comment by Tadaboody** [comment]
Same here, probably pulled without noticing and thought the wrong thing fixed it ^_^

**Comment by Enkerli** [comment]
> built from latest source (commit #213) and now working fine with my python.

Same here. Building as is, without the Python root flag, it works fine with Xcode's version of Python. Then, thanks to @baconpaul , I realized my mistake and I’m now using the brew version.

Here’s what I did:
```
git clone https://github.com/awwbees/BespokeSynth
cd BespokeSynth
git submodule update --init --recursive
cmake -Bignore/build -DBESPOKE_PYTHON_ROOT=/opt/homebrew/Cellar/python@3.9/3.9.7
cmake --build ignore/build --parallel 4
```

That’s on a MacBook Air with M1, macOS Big Sur 11.6.

Build from the latest source also solved #116 (and the Terminal workaround didn’t work for me in 1.0).

**Comment by diimdeep** [comment]
I did rebuild bespoke from sources, pointing to 3.8 version with 
cmake -Bignore/build -DBESPOKE_PYTHON_ROOT=/usr/local/Cellar/python@3.8/3.8.9
but bespoke still crashed on opening .bsp.

username nex@discord told me that you have to manually create script module in empty bespoke first to get rid of crash.

I noticed that after you create script module from empty path, there appears file at ~/Documents/BespokeSynth/internal/python_installed after that .bsp opens without crash. After deleting this empty file crash comes back.

Python initialization is not handled properly when user opens .bsp with script.

[crash_2021-10-01_17-03.txt](https://github.com/BespokeSynth/BespokeSynth/files/7267937/crash_2021-10-01_17-03.txt)

**Comment by baconpaul** [comment]
I can reproduce this condition.
let me see if I can find a fix

**Comment by baconpaul** [comment]
The problem is that CodeEntry::Poll is called whether python is initialized or not in ScriptModule
