### ISSUE TITLE
documentation should be open source

### ISSUE THREAD

**Issue by severak** [BespokeSynth/BespokeSynth#134]
to enable external contributions.

For example, I think it miss FAQ and terminology section and I am want to contribute those.

**Comment by awwbees** [comment]
that is a great idea. having others help me with the documentation would be very powerful.

the documentation is somewhat open-source right now actually... the script https://github.com/awwbees/BespokeSynth/blob/master/autodoc/autodoc.py combines both https://github.com/awwbees/BespokeSynth/blob/master/Builds/MacOSX/build/Release/resource/help.txt and a digested version of https://github.com/awwbees/BespokeSynth/blob/master/Builds/MacOSX/build/Release/resource/tooltips_eng.txt into the site you see on bespokesynth.com/docs

but, everything in help.txt also appears in the app when you press the "?" button, so there is limited flexibility for the content you can include in there. I should figure out a way to flexibly add additional documentation for the site, which can be incorporated into the autodoc.py process and allow for better collaboration on documentation.

**Comment by severak** [comment]
I have started [Terminology](https://github.com/severak/alt-bespoke-docs/blob/main/terminology.md) article in separate repository.

**Comment by awwbees** [comment]
I have now started https://github.com/BespokeSynth/BespokeSynthDocs ! I need to figure out the best process for allowing contributions there.p
