### ISSUE TITLE
Notelooper and Drumplayer modules not working as expected

### ISSUE THREAD

**Issue by ChekPuk** [BespokeSynth/BespokeSynth#1344]
## Describe the bug

On freshly opened project Drumplayer plays weird weak, squeezed sounds when Notelooper sends pattern to it.

## Build info
bespoke NIGHTLY 1.1.0 (Jul  5 2023 14:14:30) - Linux - HEAD 4de7652

## Steps To Reproduce

In my setup I plug Drumsequencer -> Notelooper -> Drumplayer modules. When I play pattern on Drumsequencer - Drumplayer sounds Ok. When record this pattern to some slot on Notelooper - Drumplayer sounds Ok. Turn off Drumsequencer, only Notelooper plays recorded pattern, Drumplayer sounds Ok. Save. Reopen project. Notelooper plays pattern, and Drumplayer plays weird. Squeezed, cut, weak sounds. Then I clean Notelooper, and redo everything from beginning, Sounds Ok again until I save and open next time. Every time when Notelooper plays prerecorded pattern on freshly opened project - Drumplayer sounds weak and squeezed.

## Expected vs. actual behavior

It should play normal sounds :)

**Comment by PowerUser64** [comment]
Ah, I think I see what you mean. What's going on here is you have two things creating the notes and they overlap a bit. If you stop the output from one of them (e.g. with a notegate) so only one is playing at once, I think you'll find that it sounds much more normal. Let me know if this fixes it for you.

Here's the patch I made from your description:
![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/5a21f573-f90c-446a-b273-4f2d886f4698)

Given that the sound changes after save/load, this is kind of interesting behavior, so I'll leave this open for now.

**Comment by KottV** [comment]
@PowerUser64
nope, the issue occurs after loading a savestate with disabled drumseuencer, I confirm that

**Comment by NoxyNixie** [comment]
Can confirm too ;) Haven't figured out why though.

**Comment by NoxyNixie** [comment]
Okay, looks like modulation isn't saved/loaded correctly.

![image](https://github.com/BespokeSynth/BespokeSynth/assets/211381/22538f6b-d2e1-4c74-aee7-0fdc0418e9ea)

In the image above you see that mod is at 0.5 as well as pressure. Both of these should be 0.

Still digging ...

**Comment by NoxyNixie** [comment]
Found a likely culprit: 503b8c255c92cc418f91fb822a21657312230a26. Testing "fix".

**Comment by ChekPuk** [comment]
> Found a likely culprit: [503b8c2](https://github.com/BespokeSynth/BespokeSynth/commit/503b8c255c92cc418f91fb822a21657312230a26). Testing "fix".

Thank you. But I'll have to wait for next nightly build to check it. Never get luck to build Bespoke by myself, get stuck at juice building errors. So I hope tomorrow I will check nightly build
