### ISSUE TITLE
[Win10] Crash when selecting MIDI device in midicontroller module

### ISSUE THREAD

**Issue by rbaffy** [BespokeSynth/BespokeSynth#135]
Only happens when selecting my "KOMPLETE KONTROL A61" from the dropdown list, hard crash with no error log generated in the Program Files/Bespoke Synth folder. Other MIDI controller selections work as expected.

(loving this so far though, great work and happy to support it!)

**Comment by awwbees** [comment]
hmmm... that's strange! I coincidentally have a Komplete Kontrol S61 right next to me, and Win10, and it works fine. so I'm extra surprised that the A61 has issues!

do you see any crash log in `<Documents>/BespokeSynth`?

is it possible for you to try to reproduce this on a different computer, to try to isolate the potential cause?

**Comment by rbaffy** [comment]
I did find the crash log, attached one that was generated today. I'll attempt to repro on another machine tonight as well.

[crash_2021-09-21_09-13.txt](https://github.com/awwbees/BespokeSynth/files/7205310/crash_2021-09-21_09-13.txt)

**Comment by ishanpm** [comment]
I had a crash with an identical crash log when I tried to select a device that another program was already using. Maybe that is causing it?

**Comment by rbaffy** [comment]
Thanks @ishanpm , that tip definitely got me further -- although I wasn't running other programs directly using the A61, I ended up killing several Native Instrument processes running in the background and was able to eliminate the crash and use the A61. Very odd.

I guess the question is now: why do my other DAWs have no issue using the A61 with these NI processes running, but Bespoke does? @awwbees, this is technically "solved", but if you'd like me to keep it open and see if I can't narrow down the exact process even more I can do that in the next couple of weeks. I can deal with this solution in the meantime.

**Comment by awwbees** [comment]
that is very strange. I wonder if any other juce apps have this issue? I wonder if it would happen with the standalone version of vital, for example? (https://vital.audio)

side note: I do actually have experience with this background NI process! you can use it to control the keybed lights and encoder displays. though I currently only have this working on mac. https://www.youtube.com/watch?v=DIiV9Ur3rj8

**Comment by rbaffy** [comment]
I just loaded Vital standalone and it's working as expected, indeed very strange. I haven't been able to confirm identical behavior on another machine yet, let me do that and then I'll update you.

**Comment by awwbees** [comment]
closing stale issue, please reopen if there are any updates
