### ISSUE TITLE
Halt on re-open if output audio device no longer exists

### ISSUE THREAD

**Issue by chrismahoney** [BespokeSynth/BespokeSynth#136]
This seems to be by design, but just raising it for users with sporadic BT headphone use, etc. - If my BlueTooth device is either disconnected, or has been re-paired, there's a hard stop to force you to change the audio output device. That should be required, but the friction does feel like a failure state that takes a few minutes to figure out.

Low priority, maybe it's just an alternate initialization mode if something's wrong.

**Comment by awwbees** [comment]
hmm... can you elaborate on what you mean by "alternate initialization mode"?

**Comment by awwbees** [comment]
I was having similar issues recently, and #776 resolved them for me. this is an old issue, but maybe it resolves this, too.
