### ISSUE TITLE
Crash on Load of Old Patches

### ISSUE THREAD

**Issue by AbelianTransitSystem** [BespokeSynth/BespokeSynth#1377]
## Describe the bug

When selecting an older BSK file/patch to load (all of which were built under the previous version of Bespoke), the program pauses for a brief moment and then crashes.

This happens regardless of the file selected.

Of note: nearly all older BSK files in question contain 3rd party VSTs (64 bit only)

## Build info

bespoke 1.2.0 (Jul 13 2023 20:02:13) - Windows 10 - HEAD b69c3fb

## Steps To Reproduce

Click on "load", select an arbitrary BSK file from the /savestate subdir.

## Expected vs. actual behavior

Program crashes almost immediately upon load attempt. No other aberrant behavior noted.
 
[crash_2023-07-15_21-28.txt](https://github.com/BespokeSynth/BespokeSynth/files/12063104/crash_2023-07-15_21-28.txt)
[crash_2023-07-15_21-23.txt](https://github.com/BespokeSynth/BespokeSynth/files/12063105/crash_2023-07-15_21-23.txt)
[crash_2023-07-15_21-20.txt](https://github.com/BespokeSynth/BespokeSynth/files/12063106/crash_2023-07-15_21-20.txt)

**Comment by awwbees** [comment]
fixed in #1379
