### ISSUE TITLE
Windows 10. The window closes immediately.

### ISSUE THREAD

**Issue by dasmode** [BespokeSynth/BespokeSynth#138]
I can not run BeSpoke.
The window closes immediately.

Windows 10 (latest update), net. 3.5 and 4.8, all Visial C ++, Python 3.9.7
I do not understand what could be the problem.
No windows log or journal failures.

**Comment by vizicist** [comment]
My window closed immediately when I tried to use the script module.  I had Python 3.9 as well.  I installed Python 3.8 and that eliminated my problem, it might help yours.

**Comment by awwbees** [comment]
do you see any crash logs in `<Documents>/BespokeSynth`?

**Comment by dasmode** [comment]
Yes

[crash_2021-09-15_18-58.txt](https://github.com/awwbees/BespokeSynth/files/7182801/crash_2021-09-15_18-58.txt)
[crash_2021-09-15_19-59.txt](https://github.com/awwbees/BespokeSynth/files/7182802/crash_2021-09-15_19-59.txt)
[crash_2021-09-15_20-01.txt](https://github.com/awwbees/BespokeSynth/files/7182803/crash_2021-09-15_20-01.txt)
[crash_2021-09-16_11-18.txt](https://github.com/awwbees/BespokeSynth/files/7182804/crash_2021-09-16_11-18.txt)
[crash_2021-09-16_11-24.txt](https://github.com/awwbees/BespokeSynth/files/7182805/crash_2021-09-16_11-24.txt)

**Comment by NotZombieFood** [comment]
Having the same issue with py3.7
[crash_2021-09-17_22-08.txt](https://github.com/awwbees/BespokeSynth/files/7189105/crash_2021-09-17_22-08.txt)

**Comment by dasmode** [comment]
I uninstalled Python 3.9.7 completely, but the problem is the same.

[crash_2021-09-18_07-50.txt](https://github.com/awwbees/BespokeSynth/files/7189270/crash_2021-09-18_07-50.txt)
[crash_2021-09-18_07-44.txt](https://github.com/awwbees/BespokeSynth/files/7189271/crash_2021-09-18_07-44.txt)

**Comment by dasmode** [comment]
I installed Pyton 3.8 and 3.8.2 - I also cannot open Bespoke.
The program opens and immediately closes immediately.

[crash_2021-09-18_07-54.txt](https://github.com/awwbees/BespokeSynth/files/7189266/crash_2021-09-18_07-54.txt)

**Comment by dasmode** [comment]
I found the source of the problem. It's OpenGL (Nividia nvoglv64.dll). I was deleting nvoglv64.dll because some programs do not work correctly with OpenGL 4.6 on my old GTX550 video card. And so my computer used:

- GL_VENDOR: Microsoft Corporation
- GL_RENDERER: GDI Generic
- GL_VERSION: 1.1.0
- GL_SHADING_LANGUAGE_VERSION: n.a.

When I returned the drivers with OpenGL 4.6, Bespoke worked. This is the working configuration for BeSpoke:

- GL_VENDOR: NVIDIA Corporation
- GL_RENDERER: GeForce GTX 550 Ti / PCIe / SSE2
- GL_VERSION: 4.6.0 NVIDIA 388.13
- GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
- 
[gpu_caps_viewer_report (Bespoke run).txt](https://github.com/awwbees/BespokeSynth/files/7211212/gpu_caps_viewer_report.Bespoke.run.txt)
[gpu_caps_viewer_report (Bespoke close).txt](https://github.com/awwbees/BespokeSynth/files/7211213/gpu_caps_viewer_report.Bespoke.close.txt)
