### ISSUE TITLE
Appimage crashes on startup. Arch

### ISSUE THREAD

**Issue by OracleToes** [BespokeSynth/BespokeSynth#1381]
## Describe the bug

```
$ appimages/bespokesynth-latest-x86_64.AppImage
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/werman/noise-suppression-for-voice>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib/lv2/rnnoise_mono.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/rnnoise_stereo.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/werman/noise-suppression-for-voice>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib/lv2/rnnoise_mono.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/rnnoise_stereo.lv2/ (ignored)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Application directory not found. Please reinstall Bespoke.
terminate called recursively
[...]
terminate called recursively
Segmentation fault
```
Exits with error code 139
This is the same as issue #783 i think?

## Build info

Bespoke 1.2.0 appimage, it doesn't stay open long enough to click anything.

## Steps To Reproduce

Launch the appimage

## Expected vs. actual behavior

I would expect the appimage to launch bespokesynth without crashing.

If it's worth noting, the .tar.gz build works fine.

**Comment by KottV** [comment]
It was fixed yesterday, but seems that AppImage wasn't rebuild with proper version.
Now it should work.
Please make sure you have at least [1.2.0-lp154.5.1.Build5.2](https://download.opensuse.org/repositories/home:/bespokesynth/AppImage/bespokesynth-1.2.0-lp154.5.1.Build5.2.glibc2.29-x86_64.AppImage) or [nightly-1.2.0+git.3.7c8094e-lp154.9.1](https://download.opensuse.org/repositories/home:/bespokesynth/AppImage/bespokesynth-nightly-1.2.0+git.3.7c8094e-lp154.9.1.Build9.2.glibc2.29-x86_64.AppImage)

**Comment by KottV** [comment]
The dir https://download.opensuse.org/repositories/home:/bespokesynth/AppImage/

**Comment by OracleToes** [comment]
Yep, it works perfectly now!
