### ISSUE TITLE
Bespoke opens unreliably on new Mac

### ISSUE THREAD

**Issue by nvssynthesis** [BespokeSynth/BespokeSynth#1383]
Bespoke on my 2015 macbook was fine, but on this M2 mac with OSX 13.3, it will not start up properly. I have reinstalled the app for this computer yesterday.

In particular, it will open fine once, but then if I quit and reopen, Bespoke will appear to be open, but it just has a blank, black screen, with no objects or menus as Bespoke should have.

Then, if I try to quit Bespoke in this state, I will receive the infinite beachball, and have to force quit.

Sometimes, if I wait a while (say 15 minutes, no restart) and try to reopen, it will seem to reset to opening fine. Restarting the computer also solves it, but I don't want to do that every time I quit and reopen Bespoke.

Any idea why this may be?
<img width="1800" alt="Screenshot 2023-07-18 at 7 30 00 PM" src="https://github.com/BespokeSynth/BespokeSynth/assets/36166904/a52796ac-90c2-4efd-94d3-ac4819f0f51d">

**Comment by nvssynthesis** [comment]
Also note that this happened both when I open Bespoke the 'normal' way, or if I open it via Terminal.

**Comment by awwbees** [comment]
I've had a few reports of this that I'm trying to track down and reproduce. what are you using for audio? is it possibly USB headphones, bluetooth headphones, or headphones plugged into the audio jack? do you still get the issue if you set `audio_input_device` to "none" in the settings? could you post the contents of your `Documents/BespokeSynth/userprefs.json`?

**Comment by nvssynthesis** [comment]
I was using a combination of the built-in speaker and ordinary headphones at the time. I believe I switched from the speaker to the headphones (and tried to quit and reopen to do the switch). I will post that file momentarily

**Comment by nvssynthesis** [comment]
userprefs:
`{
   "devicetype" : "auto",
   "audio_output_device" : "auto",
   "audio_input_device" : "MacBook Pro Microphone",
   "samplerate" : 48000,
   "buffersize" : 256,
   "width" : 1700,
   "height" : 1100,
   "set_manual_window_position" : false,
   "position_x" : 200,
   "position_y" : 200,
   "zoom" : 1.0,
   "ui_scale" : 1.0,
   "scroll_multiplier_vertical" : 1.0,
   "scroll_multiplier_horizontal" : 1.0,
   "autosave" : false,
   "show_tooltips_on_load" : true,
   "show_minimap" : false,
   "record_buffer_length_minutes" : 30.0,
   "vst_always_on_top" : true,
   "max_output_channels" : 16,
   "max_input_channels" : 16,
   "draw_background_lissajous" : true,
   "lissajous_r" : 0.40799999237060547,
   "lissajous_g" : 0.24500000476837158,
   "lissajous_b" : 0.41800001263618469,
   "background_r" : 0.090000003576278687,
   "background_g" : 0.090000003576278687,
   "background_b" : 0.090000003576278687,
   "motion_trails" : 1.0,
   "mouse_offset_x" : 0.0,
   "mouse_offset_y" : -4.0,
   "recordings_path" : "recordings/",
   "tooltips" : "tooltips_eng.txt",
   "layout" : "layouts/blank.json",
   "youtube_dl_path" : "/opt/local/bin/youtube-dl",
   "ffmpeg_path" : "/opt/local/bin/ffmpeg"
}`

**Comment by nvssynthesis** [comment]
userprefs:
{
   "devicetype" : "auto",
   "audio_output_device" : "auto",
   "audio_input_device" : "MacBook Pro Microphone",
   "samplerate" : 48000,
   "buffersize" : 256,
   "width" : 1700,
   "height" : 1100,
   "set_manual_window_position" : false,
   "position_x" : 200,
   "position_y" : 200,
   "zoom" : 1.0,
   "ui_scale" : 1.0,
   "scroll_multiplier_vertical" : 1.0,
   "scroll_multiplier_horizontal" : 1.0,
   "autosave" : false,
   "show_tooltips_on_load" : true,
   "show_minimap" : false,
   "record_buffer_length_minutes" : 30.0,
   "vst_always_on_top" : true,
   "max_output_channels" : 16,
   "max_input_channels" : 16,
   "draw_background_lissajous" : true,
   "lissajous_r" : 0.40799999237060547,
   "lissajous_g" : 0.24500000476837158,
   "lissajous_b" : 0.41800001263618469,
   "background_r" : 0.090000003576278687,
   "background_g" : 0.090000003576278687,
   "background_b" : 0.090000003576278687,
   "motion_trails" : 1.0,
   "mouse_offset_x" : 0.0,
   "mouse_offset_y" : -4.0,
   "recordings_path" : "recordings/",
   "tooltips" : "tooltips_eng.txt",
   "layout" : "layouts/blank.json",
   "youtube_dl_path" : "/opt/local/bin/youtube-dl",
   "ffmpeg_path" : "/opt/local/bin/ffmpeg"
}

**Comment by awwbees** [comment]
if you change "audio_input_device" to "none", does that affect the likelihood of a black screen on launch?

**Comment by awwbees** [comment]
likely fixed by #1398
