### ISSUE TITLE
Songbuilder scene change restarts radiosequencer and controlsequencer

### ISSUE THREAD

**Issue by AlMagnifico** [BespokeSynth/BespokeSynth#1391]
## Describe the bug

When using the songbuilder sequencer, any radiosequencer and controlsequencer sequence is restarted when a new songbuilder scene is triggered, so I cannot have any longer sequences in those sequencers (and probably some more) than a scene in the song builder is. 

## Build info

1.2.0

## Steps To Reproduce

1. build a basic patch
2. Define a couple of scenes of a patch in Songbuilder
3. Add a controlsequencer (not controlled by songbuilder scenes) with 8 values, step size 1 bar
4. Activate the sequencer in songbuilder, play 2 scenes with 4 bars length each in loop

## Expected vs. actual behavior

The controlsequencer should run to all 8 steps, but it goes only from 0 to 3, then it resets because the next scene is triggered in the songbuilder.

**Comment by PowerUser64** [comment]
I think this would make most sense to be a feature request to provide a way to disable this feature. For what it's worth, I find it to be useful in most cases.

There are a few more modules that do this - here are some of them that I tested:

- lfo
- notecanvas
- radiosequencer
- pulser
- notelooper
- controlsequencer
- looper
- curvelooper
- m185sequencer
- fubble
- notecounter

![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/3b790d74-ba66-4d3d-825b-e91cdfaa7d41)

Other than the m185sequencer, all the modules here follow the "reset" behaviour where their "internal transport" gets reset to the beginning.

Here's the project file I made to test these: [bug-1391.zip](https://github.com/BespokeSynth/BespokeSynth/files/12159060/bug-1391.zip)

**Comment by AlMagnifico** [comment]
So, I see 3 possible solutions for this:
- adding a "reset with songbuilder scene" option in the ▸menu of all the sequencers/timed modulation sources or
- adding a column "reset sequencers" to each sequencer scene or
- adding a global "reset sequencers" option to the songbuilder  ▸menu 
(wording "sequencers" TBD because it also affect LFOs)
I'd prefer option 2 though it adds visual clutter to the song builder.

**Comment by PowerUser64** [comment]
I've discovered a way around this. The songbuilder doesn't reset modules' internal transport when the scene's play button is pressed. Instead of using the songbuilder's sequencer, another sequencer (or combination of sequencers) could be used, with the songbuilder just being used to load scenes on queue from the external sequencer. It's not perfect, but it should work for simple use cases.
