### ISSUE TITLE
Drumplayer doesn't react to MIDI velocity

### ISSUE THREAD

**Issue by AlMagnifico** [BespokeSynth/BespokeSynth#1393]
## Describe the bug

The drumplayer should take the velocity of the MIDI events feeding it into account

## Build info

bespoke NIGHTLY 1.2.0 (Jul 20 2023 04:17:38) - Windows 10 - HEAD 71134ce

## Steps To Reproduce

1. Add a drum player, connect output. Open Edit and make sure "full vel" checkbox is unchecked.
2. Connect a drumsequencer and add some notes, adjust the notes to different velocities by shift-dragging the cels in the sequencer.

## Expected vs. actual behavior
The drum beats sound all with max velocity, but should sound different depending on set step velocity. The "full vel" checkbox makes no difference to this behavior.

**Comment by NoxyNixie** [comment]
Resolved in c6b1410afefc8b0b9aeb4aa11ad5c32651879c9f.
