### ISSUE TITLE
many original project demo files are crashing Bespoke

### ISSUE THREAD

**Issue by drxian** [BespokeSynth/BespokeSynth#1394]
## Describe the bug

many original project demo files are crashing Bespoke

## Build info

bespoke 1.2.0 (Jul 13 2023 20:02:13) - Windows 11 - HEAD b69c3fb

## Steps To Reproduce

open>defaul bespoke project directory>example__arpeggiation.bsk

## Expected vs. actual behavior

BEspoke crashes instead of opening the project file..

**Comment by NoxyNixie** [comment]
Duplicate of #1376.

**Comment by unfa** [comment]
Yeah, I wanted to try the example projects yesterday using recent alpha and Bespoke crashed right away :P
