### ISSUE TITLE
Bug - Attempting to save audio of the "samplecapture" module freezes BespokeSynth

### ISSUE THREAD

**Issue by xoark** [BespokeSynth/BespokeSynth#1396]
## Describe the bug

Saving audio after having it written to a buffer when using the "samplecapture" module will freeze BespokeSynth.

## Build info

bespoke 1.2.0 (Jul 13 2023 20:02:13) - Windows 10 - HEAD b69c3fb

## Steps To Reproduce

1. Record audio into the samplecapture module 
2. Press "save" 
3. The application seems to be frozen.

## Expected vs. actual behavior

This should not occur. It makes saving audio that is in the samplecapture module impossible.

I'm not sure if this is an issue that can only be reproduced on my machine, though.

**Comment by PowerUser64** [comment]
Would you mind sharing a screenshot of what the modules look like before (or after) you click the button that freezes it?

I tried reproducing this on linux, but I wasn't able to do it with the steps you described. However, I _was_ able to reproduce it once (somehow) by fooling around with routing. It happened after I connected an effectchain to a samplecapturer that had an oscillator going into it. I can't reproduce it even by following my own steps though.

Here's what I built that's similar to the one that I got to freeze it:

![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/c0ecccff-77e6-4c10-98c5-0e774077ea07)

The highlighted modules are the important parts. The rest is just for keeping it making sounds for testing.

**Comment by xoark** [comment]
Thanks for the response. I'm currently having issues reproducing this again, as well. I'll continue to test things around and see if I can successfully reproduce the issue.

**Comment by NoxyNixie** [comment]
If this bug re-appears feel free to either post a new issue or comment on this one and I will re-open it.
