### ISSUE TITLE
Script module's window "negative" size.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#14]
Hi,

I've occasionally (or not) resized script editor window by dragging left low corner above it's header, now it impossible to expand it back:)

**Comment by awwbees** [comment]
aha yes, this has happened to me as well, and I keep forgetting to fix it.
thanks for the reminder!

**Comment by awwbees** [comment]
fixed in fb0106e9c68949b4d0755a95429195aabc07df39
