### ISSUE TITLE
allow LFO on settings sliders to function while settings are closed

### ISSUE THREAD

**Issue by bugbard-cryptid** [BespokeSynth/BespokeSynth#1404]
it's possible to add LFO to the sliders in settings, but they stop working once settings is closed, which seems expected. though, it would be fun to apply LFO to the background colors, to slowly change the colors over time :]

here's a gif of how it behaves right now:
![ezgif com-optimize](https://github.com/BespokeSynth/BespokeSynth/assets/61643906/76d48a35-be07-40c5-82ec-a14b05cbb5d4)

**Comment by NoxyNixie** [comment]
I'm going to go ahead and say that we won't implement this.

However you may want to have a look at the module `globalcontrols` as this module exposes some of the same settings specifically for modulation!

![BespokeSynth_20230828_233509](https://github.com/BespokeSynth/BespokeSynth/assets/211381/0c328b82-40bb-4b71-bccb-50c3f96cb517)

**Comment by bugbard-cryptid** [comment]
oooh i didnt know this was a module, thank you :o
