### ISSUE TITLE
Random Crash/Freeze (Linux)

### ISSUE THREAD

**Issue by unfa** [BespokeSynth/BespokeSynth#1411]
## Describe the bug

Seemingly randomly BespokeSynth crashes when I alter the connection graph (create or remove a connection)

Console output at crash was:
```
Fatal glibc error: malloc.c:2589 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)
```

Here's the session file that this issue happens in (I haven't seen this in other sessions yet):
[unfa - Live Session 02.bsk.zip](https://github.com/BespokeSynth/BespokeSynth/files/12386162/unfa.-.Live.Session.02.bsk.zip)

## Build info

```
bespoke NIGHTLY 1.2.0 (Jul 20 2023 04:15:33) - Linux - HEAD 71134ce
```

## System info:

```
System:
  Host: Kernel: 6.4.4-arch1-1 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.7 Distro: Arch Linux
CPU:
  Info: 12-core model: AMD Ryzen 9 3900X bits: 64 type: MT MCP cache:
    L2: 6 MiB
Graphics:
  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] driver: amdgpu
    v: kernel
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.1.2 driver: X:
    loaded: amdgpu dri: radeonsi gpu: amdgpu resolution: 1: 2560x1440
    2: 1080x1920~60Hz
  API: OpenGL v: 4.6 Mesa 23.1.5 renderer: AMD Radeon RX 6800 XT (navi21
    LLVM 15.0.7 DRM 3.52 6.4.4-arch1-1)
Audio:
  Device-1: AMD Navi 21/23 HDMI/DP Audio driver: snd_hda_intel
  Device-2: AKAI Professional M.I. MPK mini driver: snd-usb-audio type: USB
  Device-3: Focusrite-Novation Launchpad Mini MK3 driver: snd-usb-audio
    type: USB
  Device-4: PreSonus Audio Studio 24c driver: snd-usb-audio type: USB
  API: ALSA v: k6.4.4-arch1-1 status: kernel-api
  Server-1: JACK v: 1.9.22 status: active
  Server-2: PipeWire v: 0.3.77 status: active
  Server-3: PulseAudio v: 16.1 status: active
```

## Steps To Reproduce

Load the project I attached above and start playing around with it. At some point Bespoke will likely freeze and you'll need to terminate it forcecully.

## Expected vs. actual behavior

I would expect Bespoke Synth to not freeze randomly when I'm altering connections in a project.

**Comment by unfa** [comment]
Hmm. This seems to happen even if I don't touch anything:

```
Fatal glibc error: malloc.c:2589 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)
```

**Comment by unfa** [comment]
I've built from source just now and loading the attached session immediately crashes BespokeSynth:

```
Fatal glibc error: malloc.c:2589 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)
```

**Comment by unfa** [comment]
gdb  backtrace says this:

```gdb
Thread 21 "Pool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff20bc6c0 (LWP 597804)]
0x00007fff602cb38a in ?? () from /home/unfa/.lv2/geonkick.lv2/geonkick_single_lv2.so
(gdb) bt
#0  0x00007fff602cb38a in  () at /home/unfa/.lv2/geonkick.lv2/geonkick_single_lv2.so
#1  0x00007fff6023cdeb in  () at /home/unfa/.lv2/geonkick.lv2/geonkick_single_lv2.so
#2  0x00005555561f3e3f in juce::lv2_host::LV2AudioPluginInstance::processBlockImpl(juce::AudioBuffer<float>&, juce::MidiBuffer&)
    ()
#3  0x0000555555f9a115 in VSTPlugin::Process(double) ()
#4  0x0000555555b1ffd2 in ModularSynth::AudioOut(float**, int, int) ()
#5  0x00005555560c64c6 in juce::AudioDeviceManager::audioDeviceIOCallbackInt(float const**, int, float**, int, int, juce::AudioIODeviceCallbackContext const&) ()
#6  0x00005555560d7388 in juce::JackAudioIODevice::processCallback(unsigned int, void*) ()
#7  0x00007ffff5fad44d in Jack::JackClient::CallProcessCallback() (this=0x7fffcca84050) at ../common/JackClient.cpp:635
#8  Jack::JackClient::ExecuteThread() (this=0x7fffcca84050) at ../common/JackClient.cpp:599
#9  0x00007ffff5facbe8 in  () at ../common/JackClient.h:220
#10 0x00007ffff5fcabb1 in Jack::JackPosixThread::ThreadHandler(void*) (arg=0x7fffcca84298) at ../posix/JackPosixThread.cpp:63
#11 0x00007ffff708c9eb in  () at /usr/lib/libc.so.6
#12 0x00007ffff711123c in  () at /usr/lib/libc.so.6
```

**Comment by unfa** [comment]
I suspect the problem might be that the session contains multiple output modules because it has multiple "songs" loaded as prefabs with all stuff in them, which might be the culprit. The session however sometimes works for a bit, before crashing. I'll try to clean these up.

After the crash (seems like only audio thread freezes) the GUI becomes responsive again and if I want to save, the file dialog never opens and the GUI freezes too at that point.

**Comment by KottV** [comment]
So it's geonkick dies and brings host with.

BTW your patch seems extremely oversised, it doesn't fit with smallest zoom scale.

**Comment by KottV** [comment]
You can try to de-install it (geonkick) then load that patch.

**Comment by unfa** [comment]
Oh! Geonkick... That's too bad.
The session is large because I'm trying to combine multiple projects into one for a longer performance. Hotloading prefabs won't work unfortunately.

**Comment by iurienistor** [comment]
@unfa When it crashes dose it have the same frames related to Geonkick? Can you use a debug version?.. i.e. to build the geonkick from the source and use cmake -DCMAKE_BUILD_TYPE=Debug... thus, I'll be able to see more debug info?

[Switching to Thread 0x7ffff20bc6c0 (LWP 597804)]
0x00007fff602cb38a in ?? () from /home/unfa/.lv2/geonkick.lv2/geonkick_single_lv2.so
(gdb) bt
#0  0x00007fff602cb38a in  () at /home/unfa/.lv2/geonkick.lv2/geonkick_single_lv2.so
#1  0x00007fff6023cdeb in  () at /home/unfa/.lv2/geonkick.lv2/geonkick_single_lv2.so

**Comment by unfa** [comment]
@iurienistor Hey! Glad to see you :) I'll try to do that later this week but today I'm not going to manage that. I have already exported all my geonkick-made drums into samples so I can use them with BespokeSynth's drumplayer module, but I'll continue using Geonkick to design these.

**Comment by NoxyNixie** [comment]
I'm closing this issue since it has come to light that this was not a Bespoke issue but a Geonkick issue.
