### ISSUE TITLE
midioutput should allow selecting a MIDI channel

### ISSUE THREAD

**Issue by denilsonsa** [BespokeSynth/BespokeSynth#1412]
## Summary

We already have a [midioutput](https://bespokesynth.github.io/BespokeSynthDocs/modules/noteeffects/midioutput.html) module. It would be nice to have an option inside it to select a MIDI channel.

Bonus points for allowing more options (such as selecting an instrument, changing the channel volume, etc.), but this bonus can quickly become feature-creep (e.g. sending arbitrary MIDI commands).

### Motivation

[There are (at least) 16 channels, and the channel 10 is reserved for percussion](https://en.wikipedia.org/wiki/General_MIDI). Additionally, on some keyboards with light-up keys, those lights are usually activated on a separate channel (3 or 4).

### Footnote

I'm not a musician, and I thought about this feature while playing around with Bespoke. It's a nice-to-have new feature, but I understand it has quite limited use.

**Comment by NoxyNixie** [comment]
I believe this already exists and should work (I don't have midi devices to receive this though so haven't tested that this works but it should):

![image](https://github.com/BespokeSynth/BespokeSynth/assets/211381/759004a6-db9c-4b01-a954-61426014d87b)

**Comment by denilsonsa** [comment]
Thank you! Sorry for the noise! :)
