### ISSUE TITLE
Allow to disable the play head in the buffershuffler module

### ISSUE THREAD

**Issue by ycollet** [BespokeSynth/BespokeSynth#1414]
## Summary

Up to now, when I use the buffershuffler, the sample is continuously played. Not possible to disable the play head.
So, the sound triggered by the midi note is mixed with the sound of the sample played by the play head.
### Motivation

Add a check box to allow to disable the play head.

**Comment by awwbees** [comment]
the text of this issue isn't quite correct: the `buffershuffler` out audio doesn't get mixed with the input audio, it replaces it when triggered. but, in #1426, I added an option in the triangle menu, `only_play_when_triggered`, to make the `buffershuffler` not output any audio unless triggered by notes or some other means.

**Comment by ycollet** [comment]
Thanks a lot !
