### ISSUE TITLE
patches crash with bespoke 1.1.0

### ISSUE THREAD

**Issue by clairewiwi** [BespokeSynth/BespokeSynth#1419]
## Describe the bug
Hi,
I am using the latest version of Bespoke on Ubuntu and patches that i was using with the previous version crash instantly when i open them in Bespoke. Other patches work
Terminal:
$  ./BespokeSynth 
terminate called after throwing an instance of 'UnknownModuleException'
  what():  std::exception
Killed

## Build info
Ubuntu studio 22.04
bespoke NIGHTLY 1.1.0 (Jul 11 2023 16:38:44) - Linux - HEAD e718a06

## Steps To Reproduce

I tried to open the original example patch such as "example_looper_recorder.bsk" crashes immediately 
My own patch here same behavior:  upload it [here](https://cloud.nubo.coop/s/EkYCrDASfakHE7K)
thx!

**Comment by NoxyNixie** [comment]
1.1.0 is not the latest version. 1.2.0 is, however there is a known crashbug with the current release of 1.2.0 which was fixed in the nightly build. 

Can you try the latest nightly build?

**Comment by clairewiwi** [comment]
Many thanks for checking i installed the last linux Nightly build 2023_08_23 and the patches worked ! hurray!!

**Comment by NoxyNixie** [comment]
Alright thanks for checking.
