### ISSUE TITLE
Circle sequencer uneven depending on time signature

### ISSUE THREAD

**Issue by iamevn** [BespokeSynth/BespokeSynth#142]
The circle sequencer behaves oddly on time signatures where the top and bottom number don't match. It seems like the subdivisions of a ring always act as if it were 4/4. I'd expect once around the ring to always represent a measure. I noticed this initially in 9/8 but got weirdness in every time signature I tried except 2/2, 4/4, 8/8, and 16/16.

Steps to reproduce a simple case:

* Set time signature to 3/4
* Add a circle sequencer and set length for a ring to 3
* Add notes on that ring
* Those notes don't trigger evenly

Example image:
![image](https://user-images.githubusercontent.com/5936748/133692969-f540fa82-1cbd-46a1-b829-54a23d8d6172.png)
The yellow ring has 4 divisions but is playing 3 evenly spaced notes on the stream. The blue ring never plays I assume because it's the 4th quarter note in a measure of 3/4. Similarly the top row/purple ring should be 3 evenly spaced quarter notes but instead looks like a 4/4 triplet stuffed into a bar of 3/4.

Here's how the note stream for that example looks in 4/4. I'd expect it to look mostly like this no matter what the time signature is.
![image](https://user-images.githubusercontent.com/5936748/133693497-54d9b493-3ef2-4cb5-a9e2-8ca9b72bdb2b.png)

Recording with that pattern on a few different time signatures: https://streamable.com/nwt3ww

**Comment by iamevn** [comment]
Messing around a bit, I suspect it's something to do with the handling of [`kInterval_CustomDivisor` in `Transport::GetQuantized`](https://github.com/awwbees/BespokeSynth/blob/3098738839db17131949cd9b99b47fda2e0eed16/Source/Transport.cpp#L387).

Pulser also uses `kInterval_CustomDivisor` for its [`div` interval](https://github.com/awwbees/BespokeSynth/blob/3098738839db17131949cd9b99b47fda2e0eed16/Source/Pulser.cpp#L88) and appears to suffer from a similar issue:
<details><summary>[image]</summary>
<p>

![image](https://user-images.githubusercontent.com/5936748/133705880-2380445a-66b7-410f-bc68-6647d138b2c1.png)

</p>
</details>

Same for [note counter](https://github.com/awwbees/BespokeSynth/blob/3098738839db17131949cd9b99b47fda2e0eed16/Source/NoteCounter.cpp#L76)
<details><summary>[image]</summary>
<p>

![image](https://user-images.githubusercontent.com/5936748/133706333-11281d85-c45c-4d91-939c-6d74d41d299d.png)

</p>
</details>

**Comment by awwbees** [comment]
aha! looks like I need to step out of 4/4 and redo some math. thank you for the report and investigation!

**Comment by iamevn** [comment]
I have a hunch for a quick fix based on time signatures that reduce to 1/1 working but haven't tested yet since I don't have a build environment set up.

https://github.com/awwbees/BespokeSynth/blob/51684ef7329a9dfef23efb5b2717e70327489ac4/Source/Transport.cpp#L342
This adjustment looks like it needs to be skipped for `kInterval_CustomDivisor`

Edit: tested this and it seems to work well, sending a PR over
