### ISSUE TITLE
Saved prefab losing routing on load

### ISSUE THREAD

**Issue by NikalMight** [BespokeSynth/BespokeSynth#143]
I made a custom prefab similar to the default mixer prefab, except mine had 8 channels instead of 4. 

I created a gain module, wired it to a send module, and then created the additional channels using Alt-drag(the behaviour is very odd here as the position jumps up when you're Alt-dragging, instead of to the side where I expect it to go when dragging to the side). 

I then mapped my Maschine Jam touchstrips to the gain of each channel. I added an output gain to route all the send modules to. I finally saved it and closed and reopened the software, so that the prefab would show up in the menu.

I opened the prefab and the wiring was messed up. None of the Sends were connected to the respective Gains apart from the first and last. The first Send's output was connected to the first channel Gain instead of the output Gain module, ditto with the last Send module.

The Maschine Jam mappings were messed up too. All the controls were mapped to the first gain control instead of the respective gain control of the gain modules, except for the last Gain module, which was mapped correctly.

![Bespoke_Prefab_bug](https://user-images.githubusercontent.com/33601212/133702262-78d9728a-1a48-439b-890a-08a47a578643.png)

[8 channel mixer.zip](https://github.com/awwbees/BespokeSynth/files/7181529/8.channel.mixer.zip)

**Comment by awwbees** [comment]
ahhh... sorry that you lost all of that patching. I will take a look at this and try to reproduce it.

**Comment by NikalMight** [comment]
Thanks!
