### ISSUE TITLE
All Modules disappearing 

### ISSUE THREAD

**Issue by vomitdoll** [BespokeSynth/BespokeSynth#1440]
More often than not, when I tab out of the window, all modules disappear. All the sounds still play as intended, but the modules are gone (or maybe invisible) and thus can't be edited. So far I haven't found a way to revert this except of course loading to a previous savestate

I attached a .bsk of what this looks like, it's just a slightly modified version of a pre made save that comes with the software.

On Windows 10
[bespoke disappearance bug.zip](https://github.com/BespokeSynth/BespokeSynth/files/12709082/bespoke.disappearance.bug.zip)

**Comment by awwbees** [comment]
it's possible that when you alt-tab, it is somehow accidentally scrolling the canvas away from where you intend. when this issue occurs, could you try pressing the ~/` key to bring up the console, then type "home" and press enter? that will recenter the canvas. if that fixes it for you, please let me know, and I will try to understand what is causing the issue that is causing things to scroll away.

**Comment by NoxyNixie** [comment]
There have been two separate mentions of a similar issue on discord. In both cases enabling the minimap resolved their issue. Therefore viewport must have been moved to some distant location.

**Comment by KottV** [comment]
> could you try pressing the ~/` key to bring up the console, then type "home" and press enter? that will recenter the canvas. if that fixes it for you, please let me know, and I will try to understand what is causing the issue that is causing things to scroll away.

it worked for me with the savestate from @vomitdoll
