### ISSUE TITLE
License of `Source/ofxJSONElement.*` files

### ISSUE THREAD

**Issue by merkys** [BespokeSynth/BespokeSynth#1442]
Text contents of `Source/ofxJSONElement.*` files bear the following copyright indication:
```
 *  Created by Jeffrey Crouse on 12/17/10.
 *  Copyright 2010 Eyebeam. All rights reserved.
```
In strict sense, "All rights reserved" means that this file is not free software. Would it be possible to contact the author of these files and ask to relicense under some free software license?

**Comment by KottV** [comment]
does it make sense? https://github.com/jeffcrouse/ofxJSON/blob/master/license.md

**Comment by merkys** [comment]
Thanks for pointing to the upstream source. Top-level license is MIT, which is good, but I cannot find anywhere a mention of "Eyebeam" which seemingly owns some rights of the mentioned files. Nevertheless I will open an issue on ofxJSON tracker.

**Edit**: opened https://github.com/jeffcrouse/ofxJSON/issues/29

**Comment by merkys** [comment]
The author of ofxJSON has confirmed in https://github.com/jeffcrouse/ofxJSON/issues/29 that these files are MIT-licensed.
