### ISSUE TITLE
BespokeSynth Crashing when loading dexed and other plugins

### ISSUE THREAD

**Issue by redox-dev** [BespokeSynth/BespokeSynth#1443]
## Describe the bug

BespokeSynth crashes when loading many plugins such as Dexed (vst3), Vitalium (vst3), LSP Sampler and other LV2 LSP Plugins and more.

Getting the following error when running through terminal on crash:

`/usr/include/c++/13.2.1/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = juce::AudioPlayHead::TimeSignature; _Dp = std::_Optional_base<juce::AudioPlayHead::TimeSignature, true, true>]: Assertion 'this->_M_is_engaged()' failed.`
`fish: Job 1, 'BespokeSynth' terminated by signal SIGKILL (Forced quit)`

Bug appears since 1.2.0, works fine with 1.1.0.

## Build info

bespoke 1.2.1 (Sep 16 2023 21:38:18) - Linux - makepkg 9a2072ed
Using Arch Linux with KDE under wayland (if that helps).

## Steps To Reproduce

1. Install bespokesynth and dexed through pacman.
2. Start bespokesynth.
3. Try to load dexed. BespokeSynth crashes.

## Expected vs. actual behavior

I  am expecting it to load and not crash.

**Comment by KottV** [comment]
What audio system?

**Comment by redox-dev** [comment]
Pipewire.

**Comment by redox-dev** [comment]
But i don't know what exactly bespoke does, because its all set to auto.

**Comment by redox-dev** [comment]
Probably uses alsa with pipewire server as default auto, but as i said its set to auto. If i manually set it to my headphones (alsa) i have the same problem.

**Comment by cannimal** [comment]
I'm having the same problem regardless of using alsa or jack. happened with most plugins i tried. 
Tried reinstalling from everywhere i could.
If the transport is paused, plugin loads fine but as soon as i hit play, it crashes.
For now i'm using the imageapp but unfortunately it cant save new patches.

**Comment by maxigaz** [comment]
Can you still reproduce the issue with the latest [nightly build](https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly)? I've just tried it on Arch Linux and Pipewire (`devicetype` is set to `auto` in Bespoke's settings) and it doesn't crash anymore when I load the following plugins:

- B.Choppr (LV2)
- Cardinal (LV2)
- Crisp from NIH-plug (VST3)
- Odin2 (LV2)
- Surge XT (LV2)

(In comparison, versions 1.2.0 and 1.2.1 always crash when I add any of the above to a newly created session.)

**Comment by guigui2727** [comment]
Thanks a lot for your post and your answers because I had the exact same problem with Manjaro with the version from pacman (Bespoke version 1.2.1). Thanks @maxigaz for the Nightly Build suggestion. Using the latest Nightly Build solves the problem and it works like a charm (I can load plugins without crashes).

Here are informations about my system:
OS: Manjaro
Pipewire: version 0.3.84 (pipewire-jack, pipewire-alsa, pipewire-pulse installed as well)
Bespoke: Nightly Build 2023-12-19
Device Type in Bespoke configuration: auto

**Comment by redox-dev** [comment]
Can confirm, works like a charm with latest nightly build. We just need a new release now, so it is also available with the pacman package.
