### ISSUE TITLE
I would like to donate to you, not (only) to the NAACP

### ISSUE THREAD

**Issue by runiq** [BespokeSynth/BespokeSynth#1444]
I found the donation recommendations on the website, and so I donated to the NAACP, who are fighting for a noble cause, of course.

Still, this thing is _so goddamn ingenious_ that I can't help but wanting to give some money directly to you, @awwbees. Could you maybe set up Github sponsoring, or something similar?

**Comment by awwbees** [comment]
I really appreciate that sentiment, thank you so much! for the additional money that you might have sent to me, here is another organization you might redirect it to, which I would appreciate even more than if the money were given to me directly: https://www.afrorack.org/

apologies if this answer feels like a further evasion!
