### ISSUE TITLE
moving plugin windows causes xruns

### ISSUE THREAD

**Issue by dromer** [BespokeSynth/BespokeSynth#145]
A bit of a "custom" build using @KottV 's juce6.0.8 branch on debian 11 with jackd2:

Running nekobi.so inside the init patch with an external midi controller -> the moment I start moving around the plugin window the audio engine causes xruns (dropped frames). Otherwise seems to run fine.

**Comment by awwbees** [comment]
cool, I will try to reproduce this the next time I boot up linux!

**Comment by dromer** [comment]
I take it that on windows/mac this is not an issue then?

**Comment by dromer** [comment]
And of course right now I can't even reproduce it here .. I will close this issue and reopen if I can reproduce it again :D 

Only thing I can say for certain is that the fps of the scopes and other visualizations goes down to near zero when I move the plugin window around.
