### ISSUE TITLE
EQ module points can be dragged offwindow

### ISSUE THREAD

**Issue by portalhugger** [BespokeSynth/BespokeSynth#146]
When messing with the EQ module, I accidentally dragged point 0 too far to the left and it went behind the edge of the window. With some precision, it was possible to hover over a tiny sliver of the yellow circle, but clicking it just brought up the selection rectangle, as if I had clicked+dragged on empty space. You can probably solve it by making the circles' hitboxes larger, or having them reappear in default position if you disable+reenable the point.

**Comment by awwbees** [comment]
yeah, I should provide some protection against this. another workaround solution to bring them back would be to move the sliders associated with that frequency, to bring the handle back into range.
