### ISSUE TITLE
VST3 Busses and why Surge doesn't work in Bespoke

### ISSUE THREAD

**Issue by baconpaul** [BespokeSynth/BespokeSynth#148]
Hi!

Surge XT (our latest version) doesn't work in Bespoke. It loads and scans but says the audio is never called for, because you actually don't ever call ::processBlock 

The reason for this, though, is because of our bus layout. Surge is a synth (midi in) but also supports one audio in and up to 3 audio outputs. It works fine with no audio in and one stereo out of course but the other configurations are valid

If I rebuild surge to not have this (namely, take the extra output busses out of the picture) then bespoke runs surge xt just fin, and is fun and cool. 

But somewhere you are convincing yourself i'm not valid because of my 6 output configuration. Can't quite see it in the source.

The juce api getBusLayout and so on is implemented properly in surge. Hit my up here or on discord if you need any questions. I can't quite get the thing to build on mac and your exe won't let me attach a debugger alas, so i'm a bit stuck to figure out more than this, but if you build surge at head and comment out the scene a "withOutput" in SurgeSynthProcessor, it all works fine. SO that's definitely the problem.

Thanks!

**Comment by awwbees** [comment]
cool. I will grab surge and try to reproduce this, then figure out what bespoke is doing wrong!

**Comment by baconpaul** [comment]
Great
Surge 19 I hear crashes probably for the same reason but with less graceful handling of busses. Surge at head shows the issue.  You can grab that here https://surge-synthesizer.github.io//nightly_XT (and also that’s the auto built nightly I was chatting with you about on discord). Or if you want to debug surge the readme shares how to get it built. Let me know if I can help.

**Comment by baconpaul** [comment]
Oh right and cool this isn't just a surge bug. ModArtt pianotec has multiple output busses and it also doesn't make sound in bespoke. Here you can see the arturi Jup8 makes sound and Pianotec doesn't


![NotJustSurge](https://user-images.githubusercontent.com/13387561/133771927-11e0fcf2-2761-47b3-80a7-3b791d056cfd.gif)
