### ISSUE TITLE
Bug - pitchtovalue has no input

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1499]
## Describe the bug

It seems that the new pitchtovalue module introduced in 3c519d1f9a305866aa1cabd5e72c8541a7c82d20 doesn't accept inputs.

## Build info

f82acc4f2fae30d5f2d85fdb3c90dd71e928f55b

## Steps To Reproduce

1. Build f82acc4f2fae30d5f2d85fdb3c90dd71e928f55b
2. Run it
3. Add the pitchtovalue module
4. add a notegate
5. attempt to attach the output of the notegate to the pitchtovalue
6. the cable should not be able to be attached to the module (profit)

![image](https://github.com/BespokeSynth/BespokeSynth/assets/24578572/c8950fac-6a7b-4263-8c04-b1a284725b38)

## Expected vs. actual behavior

The pitchtovalue module should probably take a note as input, unless I understand its function to be different from that which is described in #1321.

**Comment by KottV** [comment]
wrong commit link, it has to be https://github.com/BespokeSynth/BespokeSynth/commit/3c519d1f9a305866aa1cabd5e72c8541a7c82d20
also pinging the author @merkys

**Comment by merkys** [comment]
Sorry, I was away for a while. You are right, I missed the `AcceptsNotes()`. The problem is that I wrote this module for v1.1.0 and did not update for v1.2.0 properly. Thank you for spotting and fixing the issue.
