### ISSUE TITLE
Compiling bespoke with juce 6.0.5

### ISSUE THREAD

**Issue by muziker** [BespokeSynth/BespokeSynth#150]
I've managed to compile this using juce 6.0.5. There's just this one line that has to be changed to get it to finish compiling :

In Sample.cpp, do this 
replace 
FileOutputStream* outputTo = outputFile.createOutputStream();
with 
auto zos=std::unique_ptr<FileOutputStream>(outputFile.createOutputStream());
FileOutputStream* outputTo=zos.get();

**Comment by dromer** [comment]
See https://github.com/KottV/BespokeSynth/commit/b828dc2483247b9179b51cc1167475bc0b089903
This updates to `6.0.8` - which is the latest `6.0` release.

For current `6.1.x` we need more work done.

**Comment by baconpaul** [comment]
Should we close this considering #187 ?

**Comment by muziker** [comment]
Sure i'll close this
