### ISSUE TITLE
Clicking in the enable/disable button can also cause the module to move

### ISSUE THREAD

**Issue by ianh** [BespokeSynth/BespokeSynth#153]
If you click the top left enable/disable button on a module, sometimes the module also moves a little bit.  Eventually, it will move far enough that the click to enable/disable doesn't work any more (without moving the mouse to where the button ended up).  I'd expect clicks which toggle this button not to move the module at all.

**Comment by awwbees** [comment]
fixed in e044aa5b0b93f10a0ab62c76918086d350268e01, will be in release 1.0.1
