### ISSUE TITLE
Bug - Textbox stuck on-module 

### ISSUE THREAD

**Issue by Nonexdog** [BespokeSynth/BespokeSynth#1531]
## Describe the bug

The textbox for choosing scripts in the Script module is remains "overlapped" in some weird manner, below the module's script box that you can edit, but above everything else. 

## Build info

bespoke 1.2.1 (Sep 16 2023 20:11:06) - Windows 10 - HEAD 9a2072e

## Steps To Reproduce

Unclear on how to reproduce it. I may have moved the mouse a certain way or pressed a certain key?? But it just sorta snapped into a bad place and didn't really get out of there. 

## Expected vs. actual behavior

Of course the expected behavior is for the list to just get hidden once again, but instead it did the following: 
https://github.com/BespokeSynth/BespokeSynth/assets/63328613/92e34f45-e2f6-4eef-8e6a-948206cd8ec2

Do note how the list occupies a way smaller space than usual when stuck, not expanding on two columns, and is also longer in height as well when opened.

**Comment by awwbees** [comment]
this popup would happen as a result of doing a mouse scroll over the list, although I haven't yet been able to reproduce the case where it gets stuck like that

**Comment by NoxyNixie** [comment]
I'm also not able to reproduce, can you find a reliable way to reproduce this?
