### ISSUE TITLE
Enhancement: highlight a module when a cable will connect to it

### ISSUE THREAD

**Issue by ianh** [BespokeSynth/BespokeSynth#154]
While dragging a cable over a module, it's not always clear when it will connect or not.  I've noticed myself clicking a little bit outside of the module I want to connect to, which means I have to start all over again.  I think it would feel nice to show a highlight around a module when clicking there would connect the currently-held cable to it.  That way you can be sure whether clicking will connect the cable to the module or not.

**Comment by awwbees** [comment]
this is a great idea

**Comment by awwbees** [comment]
added in 558584ed99b575f84771a4f715838650aeb42d14
