### ISSUE TITLE
Maybe Could Create An Appimage for Linux?

### ISSUE THREAD

**Issue by TheLostLambda** [BespokeSynth/BespokeSynth#155]
Heya! Thanks for sharing this awesome project! I run Arch Linux on a day-to-day basis, but the packages there are sometimes newer than those available in Ubuntu! As a consequence, I can't launch Bespoke on my computer because it's looking for `libpython3.8.so.1.0` when I have Python 3.9 installed.

I think since there are a few dependencies here, it would be easiest to create an [Appimage](https://appimage.org/) that runs on any Linux computer :)

I'm happy to work on this and submit a PR if you like this approach! Just let me know!

**Comment by dromer** [comment]
Already discussed in https://github.com/awwbees/BespokeSynth/issues/108

And of course Pull Requests are appreciated!

**Comment by KottV** [comment]
https://download.opensuse.org/repositories/home:/bespokesynth/AppImage/

glibc 2.26

EDIT: ok, it's not working due resource missing

**Comment by dromer** [comment]
it says 2.25 in the filename :P

works over here (but maybe because I have some dependency installed already?)

**Comment by KottV** [comment]
> it says 2.25 in the filename :P
> 
> works over here (but maybe because I have some dependency installed already?)

because you have resources installed, remove them and AppImage won't find it
strange, but adding env to the build scripts doesn't help, maybe i do smth wrong ot maybe it's an error in OBS appimage builder
```

AppDir:
  path: ./AppDir

env:
  BESPOKE_DATA_DIR: $APPDIR/usr/share/BespokeSynth/resource/
```

**Comment by KottV** [comment]
another option is to place `resources` near the binary as for develop version
i'd like to use common install

**Comment by KottV** [comment]
alright, more or less it's working
