### ISSUE TITLE
Feature - Assign MIDI channel to notes

### ISSUE THREAD

**Issue by geoffeep** [BespokeSynth/BespokeSynth#1551]
## Summary

When passing notes into a VST it would be great to support setting a MIDI Channel (multi instrument VSTs like Kontakt can use MIDI channels to route specific notes to specific instruments).

For example, if I have a Kontakt VST set up with multiple Random Note nodes I'd like those to each play a different Kontakt instrument with just a single Kontakt node placed (this is handled through MIDI Channels in Kontakt and Reaper).

![image](https://github.com/BespokeSynth/BespokeSynth/assets/7421471/69534438-bc4d-4c72-a9aa-d2889a28f5e4)

### Motivation

When I use Kontakt in Reaper I have a single instance of the VST that can load many instruments into a multi-rack (for example "Textural Violin" and "Gentle Winds" free libraries, one set to MIDI Channel 1 for input, the other set to MIDI Channel 2):

![image](https://github.com/BespokeSynth/BespokeSynth/assets/7421471/79eca8a0-6b34-4d6f-8320-7b1a2a19d10c)

Even when working with 4 different instruments at once, fed by 4 different MIDI channels in Reaper, CPU usage doesn't get much higher than 10% using this approach.

In Bespoke to replicate the same setup I have to create a separate Kontakt VST node for Kontakt 4 times, and my CPU usage goes up about 20% for each instance of that node, so I really can't use more than 2-3 Kontakt instruments before I start getting audio issues:

![image](https://github.com/BespokeSynth/BespokeSynth/assets/7421471/f498cf85-07ac-4c78-8dfa-d20c06f401ec)

**Comment by ArkyonVeil** [comment]
Just a heads-up to help you out until there's a cleaner way to do this. It feels like a bit of a hack, but it works.

Funnel your red instruments through the orange effect "Portamento", and then configure its Voice_IDX (this will be your channel)
Then in the VST tick the usevoiceaschannel checkbox. Should be good to go.
![image](https://github.com/BespokeSynth/BespokeSynth/assets/42283444/86ba81bc-0ed2-42a1-87b9-c4b4b61f3610)

**Comment by dekrain** [comment]
There's a parameter called _voice index_ that's passed around modules that produce/consume notes, although it isn't used much (only use I found are in `midicontroller` as an option to map **channel IDs** to voice idx) and most often it's set to _-1_. It should be viable to create a module that sets a desired voice ID for incoming notes, and then to tell the VST module to map voice IDs back to MIDI channels.

**Comment by dekrain** [comment]
**Update:** VST module already has an option to remap voice IDs to channel IDs (reverse of what `midicontroller` does), but the option isn't currently accessible anywhere in the GUI, it's turnable only by modyfying the project file.

**Comment by geoffeep** [comment]
That sounds very promising @dekrain ! 

I am trying to get Bespoke building locally with VST support (having some issues that I am discussing in the Discord). So that project file modification is something I could play around with locally if it is easy enough to do, and if I can work out my issues :)

In the meantime I will also check out that suggestion @ArkyonVeil , thank you!

**Comment by dekrain** [comment]
I just joined there. so I may be able to help you with some problems.

**Comment by geoffeep** [comment]
Ok yup that workaround is exactly what I want, thanks @ArkyonVeil !!

Happy to leave this request open if we want something in addition to this, like maybe a "Set Voice Channel" NoteEffect so that folks don't have to use Portamento, but this is great, thanks very much :)

**Comment by geoffeep** [comment]
> I just joined there. so I may be able to help you with some problems.

Nice!! 
Any help you can offer is much appreciated :) 

I have things mostly working, outside of VSTs (although it is compiling with the VST sdk, I just hit asserts if I try to use them, discussing in the "nerdy-stuff" channel).

But if I can get it working I was thinking I could probably duplicate NoteDisplayer (just because it is a pretty simple class) as a new "SetVoiceChannel" NoteEffect and then copy how the Portamento sets the VoiceIdx, and see how far I get!

**Comment by geoffeep** [comment]
Erm because I suck at git I moved that PR, lives here now :)
Renamed it to Voice Setter after some good feedback from folks on Discord

https://github.com/BespokeSynth/BespokeSynth/pull/1555

**Comment by awwbees** [comment]
resolved by #1555, thanks!
