### ISSUE TITLE
Bespoke on Windows 7 Error 0xc000007b

### ISSUE THREAD

**Issue by asorc** [BespokeSynth/BespokeSynth#1571]
Hello,

When I run the program, It doesn't start, the error code is 0xc000007b 

I have followed a YouTube tutorial to solve It, but It has not worked. 

Any clue on how to solve It?

Thank you very much for your attention.

Regards, cheers.

**Comment by NoxyNixie** [comment]
Windows 7 is no longer supported however you may be able to get it to work if you follow the instructions here in this issue: https://github.com/BespokeSynth/BespokeSynth/issues/736#issuecomment-1031925976
