### ISSUE TITLE
[Feature request] StudioRack integration

### ISSUE THREAD

**Issue by RustoMCSpit** [BespokeSynth/BespokeSynth#1582]
It's an open-source plugin manager called StudioRack:
https://github.com/studiorack

The aim of the project is to provide a free open-source way to manage plugin dependencies and their versions. It would involve the following steps:

    Publish a Github release containing the plugin source along with metadata plugins.json
    Tag your Github repository with studiorack-plugin so it can be discovered
    Wait for the studiorack-registry to index your plugin (every 24 hours)
    Check the registry feed for your plugin to appear

**Comment by KottV** [comment]
I wouldn't play with StudioRack. He distributes proprietary binary (from TAL) saying it's opensource (from DISTRHO) https://studiorack.github.io/studiorack-site/instruments/studiorack/distrho-ports/tal-noisemaker

**Comment by RustoMCSpit** [comment]
> I wouldn't play with StudioRack. He distributes proprietary binary (from TAL) saying it's opensource (from DISTRHO) https://studiorack.github.io/studiorack-site/instruments/studiorack/distrho-ports/tal-noisemaker

this sounds like an honest mistake rather than maliciousness

**Comment by RustoMCSpit** [comment]
> I wouldn't play with StudioRack. He distributes proprietary binary (from TAL) saying it's opensource (from DISTRHO) https://studiorack.github.io/studiorack-site/instruments/studiorack/distrho-ports/tal-noisemaker

contact the dev

**Comment by KottV** [comment]
btw BespokeSynth is not a plugin (at least for now)

**Comment by RustoMCSpit** [comment]
> btw BespokeSynth is not a plugin (at least for now)

theres a website

**Comment by KottV** [comment]
> > btw BespokeSynth is not a plugin (at least for now)
> 
> theres a website

what are you trying to say?

**Comment by RustoMCSpit** [comment]
> > > btw BespokeSynth is not a plugin (at least for now)
> > 
> > 
> > theres a website
> 
> what are you trying to say?

upload it to the website, when the app comes out it will come to the plugin versio  of the app

**Comment by RustoMCSpit** [comment]
wait i misread

**Comment by RustoMCSpit** [comment]
i thought yoy said 'studiorack' was not a plugin

**Comment by RustoMCSpit** [comment]
apologies

**Comment by NoxyNixie** [comment]
Marked as wontfix due to Bespoke not being a plugin and it won't be a plugin any time soon. This issue or a new issue can be opened once Bespoke is capable of being a plugin.

**Comment by RustoMCSpit** [comment]
should that be an issue tag type? 'wontfixplugin' makes more sense than 'wontfix'

**Comment by NoxyNixie** [comment]
Nah, wontfix suffices.

**Comment by RustoMCSpit** [comment]
> Nah, wontfix suffices.

do you intend on goinf back and readinf all of the wontfixes?

**Comment by NoxyNixie** [comment]
No but this will likely come up or will already be thought of when Bespoke is made a plugin. This however will take very long, there are some prerequisites that are very big tasks and not easy to do.

**Comment by RustoMCSpit** [comment]
right but in the long run does it not make sense to just have a WONTFIXPLUGIN for when that time comes

**Comment by NoxyNixie** [comment]
No, the additional tag would make things more confusing.
