### ISSUE TITLE
Bug: macroslider stops affecting child patches after restarting the app

### ISSUE THREAD

**Issue by kulgachev** [BespokeSynth/BespokeSynth#159]
To reproduce: place macroslider and another patch, connect any output to the patch property, restart the app, macroslider stops working and requires reconnecting it again

https://user-images.githubusercontent.com/63184432/133767571-3635c70d-e6b6-47a1-8337-389aeb1c7742.mp4

**Comment by NoxyNixie** [comment]
I can't reproduce this issue in the latest Nightly.

If this is still an issue please don't hesitate to post here or in a new issue ;)
