### ISSUE TITLE
Bespoke opens but no audio or transport

### ISSUE THREAD

**Issue by davephillips** [BespokeSynth/BespokeSynth#16]
Greetings !

The subject says it all. When I start Bespoke it opens okay but there's no transport activity and the "audio cpu" value is at 100%. Any hints what's gone wrong ? I have an earlier version that works fine on this machine. Btw, I'm on Ubuntu 18.04, GCC 7.5.0.

Best regards,

dp

**Comment by KottV** [comment]
Greetings,

Just for guess, is your soundcard configured properly in BespokeSynth and not utilized by other app (jack, pulse)?

**Comment by awwbees** [comment]
no immediate ideas... does your userprefs.json look the same between the build that's working and the build that's failing? if that's not it, you could try syncing back through commits to try to figure out when it stopped working for you.

**Comment by davephillips** [comment]
I'll check things as soon as I'm done teaching this morning.

**Comment by davephillips** [comment]
@awwbees - userprefs.json is identical between the builds. I'll check the commits to determine when the problem appeared.

@KottV - Bespoke posts this when opened from the command prompt:

```
$ ./BespokeSynth
pixel ratio: 1 screen width: 3840 screen height: 1080
output: Playback/recording through the PulseAudio sound server   input: Playback/recording through the PulseAudio sound server
Loading layout: /home/dlphilp/BespokeSynth/data/layouts/blank.json
```

**Comment by davephillips** [comment]
Okay, I've narrowed thins down to these facts:

Bespoke runs fine on my laptop. That machine has exactly one audio device, managed by Pulseaudio with its Jack sink. No problems with Bespoke there. So I don't think my problem is about Bespoke per se.

Bespoke opens on the desktop box but the transport doesn't run. I have multiple devices attached to this machine, which seems to be a problem with the Bespoke audio configuration. Interesting observation: As long as my USB interface is attached Bespoke opens (but still doesn't work). If I detach the USB interface Bespoke will open with an error regarding the audio interface (see the screenshot). However, the USB device is not being used for audio, nor is it ever the preferred interface. Nevertheless, it seems that Bespoke or - probably more correctly - JUCE is looking for the USB device when it sees the "auto" specification in its json preferences file. 

An easy out would be a more specific entry in the preferences. Is there any other option besides "auto" ?

![bespoke-error](https://user-images.githubusercontent.com/7815938/81814447-cbc87880-94f6-11ea-8470-8a6435da80c6.png)

**Comment by awwbees** [comment]
wow, that's quite a lot of audio devices! to specify which audio device you want to use, instead of "auto", you should type verbatim the name of the device in that list, after the colon (so, exclude the "ALSA:" part)

so, the line in your userprefs.json might look like:
`"audio_output_device" : "M Audio Delta 66, ICE1712 multi; Front Speakers",`

this is how it works on mac and windows at least, hopefully this also works for linux. it's strange that "auto" is not picking the preferred device, but that sounds like a juce/linux issue.

**Comment by davephillips** [comment]
@awwbees Thank you, that got me headed in the right direction. For my system here's what finally worked in userprefs.json :

```
{
   "samplerate" : 48000,
   "buffersize" : 256,
   "audio_output_device" : "M Audio Delta 66, ICE1712 multi; Front speakers",
   "audio_input_device" : "auto",
   "height" : 1000,
   "width" : 1700,
   "layout" : "layouts/blank.json",
   "vstsearchdirs" : ["/home/dlphilp/vst4Bespoke"]
}
```

If I specified the same device for input and output I received the same error as before.  I'm not processing external audio so I can live without its input for now.
