### ISSUE TITLE
VST3, Cardinal.  More audio channel input required

### ISSUE THREAD

**Issue by liqibing-3** [BespokeSynth/BespokeSynth#1644]
![微信图片_20240913163846](https://github.com/user-attachments/assets/b3b508a5-e04e-440f-9589-a2c30d330ca9)

**Comment by liqibing-3** [comment]
Currently, the input VST is mixed channels。Seek Assist

**Comment by KottV** [comment]
duplicate of https://github.com/BespokeSynth/BespokeSynth/issues/1564
