### ISSUE TITLE
Can't open program after sample rate error

### ISSUE THREAD

**Issue by Soulis6** [BespokeSynth/BespokeSynth#165]
No matter what I do I can't seem to get out of this error.

I'm getting a sample rate error when starting up, and nothing I seem to change actually sticks around when I hit 'save and close'.
Even changing to another audio device or devicetype doesn't seem to save when closing and relaunching. 

To clarify, selecting the 'save and exit bespoke' doesn't seem to save the settings here, and I don't see another way to edit them so I'm stuck in this loop.

![image](https://user-images.githubusercontent.com/7422751/133848064-a6612697-f9af-4db3-9b89-0f8a98d42750.png)

![image](https://user-images.githubusercontent.com/7422751/133848360-085ffe30-4954-41d7-a97f-bba592fc8949.png)

**Comment by severak** [comment]
Try changing `userprefs.json` manually and there set:

```
  "audio_output_device" : "auto",
  "audio_input_device" : "auto",
  "samplerate" : 44000,
```

Then select start Bespoke and select right devices and sample rate. It looks like in your case valid sample rate is 44100.

**Comment by Soulis6** [comment]
Where can `userprefs.json` be found? I couldn't find that anywhere in the install directory or in the documents data. Thanks for the help.

**Comment by severak** [comment]
In Windows it's in `BespokeSynth` in `Documents` folder, in my case (Windows 7) in `C:\Users\Spravce\Documents\BespokeSynth`.

**Comment by Soulis6** [comment]
hmm ok, I looked there and couldn't find anything, weirdly just seems like that file doesn't exist on my machine. Searching for it specifically across my computer doesn't find it either. 
Maybe the root of the problem is that the userprefs didn't get created or was deleted somehow?

![image](https://user-images.githubusercontent.com/7422751/133863585-f7b0a58e-b808-4c0b-b240-f98e3882a3b3.png)

**Comment by Soulis6** [comment]
Figured it out! Windows security blocked the creation of the userprefs for some reason. Went into the protection history of the Virus and Threat protection and found that it was blocking Bespoke from creating or updating the userprefs. 

No idea why it would do this, but allowing an exception for Bespoke has fixed this issue. 
Thanks for the help!
