### ISSUE TITLE
Allow changing the userdata path

### ISSUE THREAD

**Issue by atngames** [BespokeSynth/BespokeSynth#1651]
## Summary

On linux, BeSpoke creates userdata foldersystem in ~/Documents which is not desired behaviour. It would be useful to be able to change this userdata folder somewhere

### Motivation

Avoid cluttering Documents folder for users

**Comment by NoxyNixie** [comment]
This possibility was already added using the environment variable `BESPOKE_DATA_DIR` in 7891a7a5852e7b21fc299311767980aefc6fe1e3.

**Comment by atngames** [comment]
okay thanks
