### ISSUE TITLE
 Allow changing the userdata path does not work

### ISSUE THREAD

**Issue by atngames** [BespokeSynth/BespokeSynth#1666]
## Describe the bug

Hi,
I asked about a way to change where data is stored on my linux system in #1651 
This is closed since it has been implemented with an environment variable BESPOKE_DATA_DIR

But I did set BESPOKE_DATA_DIR to another directory and Bespoke still creates a dir in my Documents.

## Build info
bespoke 1.2.1 (Apr  1 2024 05:34:21) - Linux - unknown-branch deadbeef

## Steps To Reproduce

- add ` export BESPOKE_DATA_DIR=/home/user/Documents/Etienne` in my .bashrc file
- `source .bashrc
- restart
- Launch BespokeSynth
- The folder is recreated in my /home/user/Documents

## Expected vs. actual behavior

I expect the folder to be created in /home/user/Documents/Etienne

**Comment by KottV** [comment]
I did run `BESPOKE_DATA_DIR=/tmp/bespoke ./BespokeSynth` and the user data was created in this dir.

**Comment by NoxyNixie** [comment]
> bespoke 1.2.1 (Apr 1 2024 05:34:21) - Linux - unknown-branch deadbeef

That version is too old. You need at least a version from Jun 20 or later.

**Comment by atngames** [comment]
Thank you for your answer and sorry about my poor technical understanding.
