### ISSUE TITLE
UI Bug: Large VST directory goes off-screen in 

### ISSUE THREAD

**Issue by 0x4D5352** [BespokeSynth/BespokeSynth#167]
macOS 10.14.6, scanned my VST3 directory and found that the plug-ins get cut off from the right side of the app window. i can extend the right border of the window to bring it all into view (see screenshots), but otherwise i can't scroll through the vst directory or otherwise control/navigate through the dropdown menu.

i can just type the first letter of the plugins and access from there so there is a workaround in the meanwhile
![Screen Shot 2021-09-17 at 13 06 04](https://user-images.githubusercontent.com/67082011/133848561-0f9325b7-dbc6-4838-b16f-09d80d29345c.png)
![Screen Shot 2021-09-17 at 13 08 19](https://user-images.githubusercontent.com/67082011/133848574-155ae1cd-ef71-401b-971d-e505f72edb27.png)
e

**Comment by dromer** [comment]
Yup, have to resize to 3x 1080p width to see everything hehe. Would be nice to have a better overview, preferable per plugin author (would save a lot of space in my case).

A "quick-n-dirty" solution is to create a whitelist of plugins. However I forgot what that file is called and where it goes :)

**Comment by NikalMight** [comment]
A possible solution to this issue would be to have a module like the sample browser, but for plugins.

**Comment by MBYlt** [comment]
Can confirm that this issue exists in the Windows build as well.

> Would be nice to have a better overview, preferable per plugin author (would save a lot of space in my case).

Would save some space, though the overflow issue would still be present with "Unknown Author" plugins.

Personally, I don't think of a VST in terms of AuthorName PluginName - in my head it's "Serum", not "Xferrecords Serum" (case in point: I was originally going to use Surge as the example, but couldn't actually remember what author name it shows under), so this wouldn't really be great for my personal workflow. 

What would be ideal (in addition to actually being able to scroll the popup, of course) would be the ability to type the plugin name and have the window auto-populate with applicable results. Similar to how @'s often work on social sites.

> 
> A "quick-n-dirty" solution is to create a whitelist of plugins. However I forgot what that file is called and where it goes :)

Some consider a VST "whitelisted" by virtue of it being installed in the first place :P

**Comment by justSatyr** [comment]
I am pretty sure the vst format includes a 'category' for each plugin. I know that is how Reaper organizes them at least. Having them sorted by category would make the vst dropdown a little more usable.

**Comment by fredericlb** [comment]
Maybe a solution would be to display only the N most recently used/installed VST, and make the last item a VST browser acting more or less like the one in Reaper ? 

This could be improved later with a "favorite" option that would make a VST always appear in the dropdown menu, but a first version showing most recents and a browser could be great

**Comment by awwbees** [comment]
I fixed this one a few months back, dropdown lists now have paging if they're too large to fit on-screen
