### ISSUE TITLE
Regression: crash on loading larger projects after a recent commit

### ISSUE THREAD

**Issue by maxigaz** [BespokeSynth/BespokeSynth#1682]
## Describe the bug

When I try to load a project with quite a lot of modules, BespokeSynth crashes.

This happens only with the commit 840893a9fadf567cb96718311ae9ba7fdc1c1f99 on the main branch. With all the recent commits before that, including 61cd74c1d98a6e5706e7f9ce38d411a518bf9561, the same projects load without any crashes.

I can reproduce the crash with the current state of the main branch (running `git pull`), too.

I haven't been able to figure out what triggers the crash. I tried removing modules with the last known unaffected commit and then loading the project with the faulty one, and after a long trial and error, it would eventually load, but I couldn't come to a conclusion on which module(s) caused the issue.

## Build info

bespoke 1.2.1 (Oct 29 2024 21:39:06) - Linux - main 61cd74c1

## Steps To Reproduce

Load a project with a lot of modules.

## Expected vs. actual behavior

Bespoke shouldn't crash.

**Comment by NoxyNixie** [comment]
Are you saving after 840893a9fadf567cb96718311ae9ba7fdc1c1f99 and loading before it?

i.e. are you loading a `savestate that was saved with a nightly build after the mentioned patch` with `a build from before that same patch`?

**Comment by NoxyNixie** [comment]
Also can you provide the crashing savestate?

**Comment by maxigaz** [comment]
> Are you saving after [840893a](https://github.com/BespokeSynth/BespokeSynth/commit/840893a9fadf567cb96718311ae9ba7fdc1c1f99) and loading before it?
> 
> i.e. are you loading a `savestate that was saved with a nightly build after the mentioned patch` with `a build from before that same patch`?

The savestate was saved in an earler build (a nightly based on b4674fc to be exact).

> Also can you provide the crashing savestate?

I've just uploaded it here: https://paste.i2pd.xyz/?f7c26a7145b3caff#GR5Yn2rvEqhVTvvYYEyzMXW4ed9nQS5k2oGTvdraUSr9

In addition, here's a second one: https://paste.i2pd.xyz/?d816e7a71d4ec6a6#2b3ksRAzaNgmwAmPeQm1Z97JFur5UyUonYd3xj7iMCMw

The only difference between the two projects is that the second _doesn't_ crash and a single module (Safety Limiter) is absent in it. (However, I see cables with hot (loud) signals and Bespoke mutes the audio. Just something to be aware of.)

**Comment by NoxyNixie** [comment]
Thanks for the details!
