### ISSUE TITLE
Expression module's x1,y1,x2,y2 don't actually exist?

### ISSUE THREAD

**Issue by NoxyNixie** [BespokeSynth/BespokeSynth#171]
The hover text of the expression module seems to suggest something about the variables x1,y1,x2,y2 but either this is not implemented fully or I don't understand how to use these.

Each time I reference these in either a writing a value to it (e.g.: `x1 := 4`) or reading it (e.g.: `x+x1`) the expression "fails".

The variable `t` works fine though so that one is fully implemented.

[The code](https://github.com/awwbees/BespokeSynth/blob/master/Source/ModulatorExpression.cpp#L89) mentions the variables but if I'm not mistaken they are not used correctly?

**Comment by cassaundra** [comment]
Those "biquad state storage" variables make sense and work as expected in the waveshaper module, which leads me to think that the expression module was copy-pasted from that code, but still has a few of those remnants left over. Should be a simple fix!
