### ISSUE TITLE
Rhythmsequencer doesn't send out notes

### ISSUE THREAD

**Issue by AlMagnifico** [BespokeSynth/BespokeSynth#1730]
## Describe the bug

The rhythmsequencer doesn't send out notes

## Build info

bespoke NIGHTLY 1.2.1 (Dec 16 2024 04:32:17) - Windows 10 - HEAD bab8fb9

## Steps To Reproduce

+ add rhythsequencer
+ connect oscillator

## Expected vs. actual behavior

Note should come out of the sequencer and play the synth, but though the sequencer is working, no notes come out of it

**Comment by awwbees** [comment]
if your repro steps are complete, this sounds like the `rhythmsequencer` is not being used correctly: it is a note effect, so you need to send notes into it for it to sequence, such as via a `keyboarddisplay` plugged into it
<img width="935" alt="image" src="https://github.com/user-attachments/assets/e6fb1d22-74fe-4c8d-bf1a-b2987e108a79" />
