### ISSUE TITLE
editing a script in a script node crashes the application when the Jedi package is installed, on macOS 10.12.6

### ISSUE THREAD

**Issue by disconex** [BespokeSynth/BespokeSynth#175]
Without the Jedi static analysis tool installed, script nodes are working normally, except displaying the familiar warning to install Jedi. When I do so by running `python3.8 -m pip install jedi`, scripts can still be loaded and run, but then typing something that should trigger auto-completion causes a crash.

[crash_2021-09-18_05-45.txt](https://github.com/awwbees/BespokeSynth/files/7189216/crash_2021-09-18_05-45.txt)

**Comment by awwbees** [comment]
I believe that this is no longer an issue, due to the way that python is now distributed within bespoke
