### ISSUE TITLE
MIDI Clock input

### ISSUE THREAD

**Issue by jackmau** [BespokeSynth/BespokeSynth#178]
hi @awwbees,

I just discovered Bespoke is available on windows and it looks amazing, much more visually intuitive than anything else I have used for this purpose. I am thinking to switching my live looping setup to bespoke, but there are some features I am missing which are currently stopping me from. Hence I will be posting a fairly long list of FR of stuff. I will be actively start donating if I see that my input is taken into account, as I have done in the past in similar projects.

First of all is the absence of midi clock input, or any other way to sync Bespoke to another DAW/external sequencer (I am currently dependent on Ableton Tempo Follow for performing with a drummer). I thought a possible alternative could have been using midi-controlled tap tempo (sending midi notes on the beats from the other DAW/device), but there is no tap tempo functionality and I didn't find a pulse to BPM device.

**Comment by awwbees** [comment]
yes! both midi clock sync and ableton link support are planned for the near future, for tempo sync.

I had planned on getting midi clock sync in before 1.0.0 release, but it turned out to be more work than expected

**Comment by jackmau** [comment]
glad to hear it's in the pipeline @awwbees, would be very happy to test when this will be implemented

**Comment by gordominossi** [comment]
It would be really nice to be able to sync Bespoke to other pieces of software
Traktor Pro 3 uses Ableton Link, for example

**Comment by awwbees** [comment]
the latest bespoke nightly build (https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly) now has midi clock in/out! check out the `clockin` and `clockout` modules.
