### ISSUE TITLE
14-bit MIDI CC

### ISSUE THREAD

**Issue by jackmau** [BespokeSynth/BespokeSynth#179]
Most of the controllers I use transmit 14-bit midi, but Bespoke seems to only recognise 7-bit CC for midi control. I think I will try to write my own 14-bit interpreter in a script, but I would be nice to have a native implementation.

**Comment by awwbees** [comment]
can you refer me to some controllers that have this? I could buy a cheap one and add this support, it sounds great. I have a massive controller collection and somehow I have never come across this!!

**Comment by jackmau** [comment]
> can you refer me to some controllers that have this?

There are mostly three categories of _controllers_ that tend to have 14-bit midi:
- motorised fader/led knobs controllers (Behringher, Steinberg CMC, iCon Platform)  mostly 10-bit devices which trasmit in 14 bit
- fancy expressive controllers (Haken Audio, Monome Arc, FaderFox series)
- fancy synth (some Moog, such as little phatty series and Dave Smith Instruments)

> I have a massive controller collection and somehow I have never come across this!!

Well, no midi controller collection is ever enough big ;D I find odd you don't have any, check though if any of your device support 14-bit midi, more than 50% of the stuff I have has it (and I didn't bought it beacuse of it, I swear!)

> I could buy a cheap one

For cheap behringher BCF/BCR are good alternatives. If you are _really_ into midi controller my personal suggestion (I know I sound like a marketer, but is the most expressive controller out there for the money and typically you can get it used for well less than $100) would be to get a [Leap motion controller](https://www.ultraleap.com/product/leap-motion-controller/) + [midipaw](http://www.midipaw.com/) on windows or [GECO ](http://uwyn.com/geco/)on mac. It's as extreme as _controllerism_ as it goes (9 dimensions of control with a hand) an IMHO a mind blowing experinece; often a DAW blowing experience as well, as it provides heavy streams of high-resolution midi data.


More on the topic, 14-bit midi is conceptually very simple, no need of an actual controller to buy to be honest. The 14-bit message is just composed of two 7bit midi CC: the first one MSB (Most Significant Bits) correspond to the normal 7-bit message, the other one, known as LSB (Least Significant Bits), just gives granular 128 step per each MSB; thus resolution passes from 7-bit 128 to 14-bit 128^2=16384 steps. In practice it will be likely there will be less steps because most devices internally process at a lower rate (such as 10-bit mentioned earlier) and then just upsample. By Midi 1.0 convention the Midi CC of the LSB is the MSB CC + 32. This means that there can only be 32 14 bit-midi commands on a single midi channel (as CC0 is generally not used), cerrosponding to CC 1-32 for MSB and 33-64 for LSB.

Note than when talking to HW synth (but it may beneficial, at least performance-wise in Bespoke as well) it's useful to decide the maximum rate allowed for incoming/outgoing messages, as 14-bit midi are very bandwith hungry (considering the limited bandwith offered by midi 1.0). A particular problem in the MIDI 1.0 standard for 14-bit midi is that MSB may (or may not) be followed by LSBs, which [as documented here](https://www.hakenaudio.com/mpe) causes issues with jumps if the MSB update is not syncronous with the LSB one. Note that typically that is not the case with the opposite: when the MSB is constant just LSB are transmitted.

I have written 14 bit message encoders and decoders (in midi HEX notation) in [EEL ](https://www.cockos.com/EEL2/)for Reaper, I could easily write an implementation for you in Python or C/C++ (I am a scripter, don't ask me for help with the GUI implementation though ^^)

**Comment by awwbees** [comment]
oh excellent! I have both a BCF and a BCR, I must just have never used their 14-bit modes. (it looks like my linnstrument supports it too... I should have guessed)

thanks!

**Comment by awwbees** [comment]
I finally got a version of 14-bit MIDI in with #1594! it is not perfect, but hopefully a decent start.
