### ISSUE TITLE
Can't scroll or zoom inside large prefab

### ISSUE THREAD

**Issue by UniQMG522** [BespokeSynth/BespokeSynth#180]
When assembling a massive, larger-than-the-screen prefab it's possible to trap yourself inside it due to being unable to zoom via scrolling or drag the view around.

https://user-images.githubusercontent.com/48872143/133883265-c5b73fc9-8ff4-4b96-89e4-f78848ea127c.mp4

edit: Just found that space bar + mouse still works, probably still a good idea to allow right-click dragging in prefabs since they arguably qualify as 'empty space'

**Comment by ThePython10110** [comment]
You can middle click + drag (if you have a middle mouse button)
Edit: Also, space+scroll still works.

**Comment by awwbees** [comment]
fixed by #1081
