### ISSUE TITLE
MIDI CC recording

### ISSUE THREAD

**Issue by jackmau** [BespokeSynth/BespokeSynth#181]
Bespoke has very advanced Note and Audio recording looping functionality, but Midi CC, as far as I have gathered, seems to be neglected. I'd like a sort of canvas for CCs. Even more than so I would absolutely _love_  a fubble-style module with a Midi CC input instead of drawing.

**Comment by NoxyNixie** [comment]
We now have the `controlrecorder` which should be sufficient to take on the described role.
