### ISSUE TITLE
Drumplayer sequential reading 

### ISSUE THREAD

**Issue by jackmau** [BespokeSynth/BespokeSynth#182]
I love the random button onto each pad for proper round-robin perfomance of sample folders. I'd like to have the same for sequential reading of samples in the folder assigned to each pad, similarly to the current _aud_ control, but with the file sequence restarting from the beginning once it has reached the end of the folder. This would allow to play sequences onto one pad.

**Comment by awwbees** [comment]
I forgot about this issue, but I implemented this a few months ago! there are now `<` and `>` buttons on each drum pad
