### ISSUE TITLE
Unable to open up save files [Windows]

### ISSUE THREAD

**Issue by minosh7** [BespokeSynth/BespokeSynth#184]
I'm getting the error of "Couldn't load font from C:/users/user/Documents/BeSpokeSynth/MacOSX/build/Release/resource/frabk.ttf"

![image](https://user-images.githubusercontent.com/54686642/133885275-1390040b-5dd9-48d3-a137-973172b3d2dd.png)

I tried saving a file, then tried reopening it by clicking on the save file itself (and I selected the bsk files to open with BeSpoke) and this error appeared. I have currently two save files, neither of which are working. I also tried opening the ones that were provided in the savestate folder, but no luck.

When digging through the files, I am able to find the font, but not sure why when I'm on a Windows machine I get an error that leads me to a MacOSX directory that doesn't exist.

I'm currently on Windows 10.

**Comment by awwbees** [comment]
that error message looks goofy, but to make sure I fully understand: you're getting this issue by double-clicking .bsk files, which you have associated to work with BespokeSynth.exe? that functionality is not supported (though maybe I should support it eventually). the correct way to open .bsk files is via the "load" button inside bespoke.

**Comment by minosh7** [comment]
Oh, I was under the assumption it would work if I had defaulted the bsk files to open with Bespoke. Tried by loading it inside bespoke and it works. Thank you Ryan!
