### ISSUE TITLE
Crashing on Windows 10.

### ISSUE THREAD

**Issue by angelhandgel** [BespokeSynth/BespokeSynth#188]
I can get about two minutes in to using Windows Bespoke before it freezes then crashes. No crash logs. Even happens if I don't do anything. So frustrating.

Windows 10, Surface Pro 7, 256GB, 8GB RAM.

It doesn't need me to touch the screen (crashes even just leaving the program) but could it be that?

**Comment by awwbees** [comment]
no crash logs in `<Documents>/BespokeSynth`? hmm. I wonder if it's viewing your audio device as disconnecting or something. are you using an audio interface or anything? bluetooth headphones? wired headphones? the built in speakers?

**Comment by angelhandgel** [comment]
Hi Ryan, sorry for the confusion.  I was looking in the wrong location (program files).

I have the crash dumps and I have been changing the device type from Windows Audio to Direct Sound (ASIO doesn't give me any output devices).  The change to Direct Sound seems to have an effect but this affects latency.   Also been changing the buffer.  What affect does this have?  

Anyway, here are the crash logs (I'm none the wiser)
[Crashes.zip](https://github.com/awwbees/BespokeSynth/files/7192964/Crashes.zip)
.

**Comment by angelhandgel** [comment]
Also I was using the inbuilt speakers of the tablet.

**Comment by NoxyNixie** [comment]
The crashlogs can no longer be downloaded (404 on github).

Does the latest version of Bespoke Nightly work for you?

If not please report back with a new crahslog here and I'll reopen the issue ;)
