### ISSUE TITLE
UI Ghosting

### ISSUE THREAD

**Issue by xitska** [BespokeSynth/BespokeSynth#195]
Noticed Bespoke was ghosting when I downloaded it today.
OS: Windows 10 (Version 10.0.19042.1165)
GPU: GeForce GTX 1060

![bespoke ghost](https://user-images.githubusercontent.com/23122389/133927853-2c1d26de-75f4-4359-a324-59de98d31502.gif)

**Comment by awwbees** [comment]
this is intentional, though I will include the option to disable it in a suite of incoming visual options
