### ISSUE TITLE
Antialiasing oscillators

### ISSUE THREAD

**Issue by maurizdeb** [BespokeSynth/BespokeSynth#196]
It seems that oscillators introduce a lot of aliasing.
Is there implemented some antialiasing method (e.g. polybleb)?
Thank you!

**Comment by awwbees** [comment]
the oscillators are quite simple and the there is no antialiasing algorithm, though I should add one eventually. for now, maybe you could reduce it with oversampling. click the triangle menu on the oscillator for that
