### ISSUE TITLE
Arch PKGBUILD

### ISSUE THREAD

**Issue by zoe1337** [BespokeSynth/BespokeSynth#199]
Attached is a quick PKGBUILD for Arch Linux, using @baconpaul 's cmake port.
I'm not putting this on AUR because I don't want to maintain it, but someone might find this useful.

Just rename the file from PKGBUILD.txt to PKGBUILD and run makepkg

It builds and runs on latest Arch just fine, using system Python (3.9.7).

[PKGBUILD.txt](https://github.com/awwbees/BespokeSynth/files/7192411/PKGBUILD.txt)

**Comment by baconpaul** [comment]
Hey neat! But obviously please don’t put this in the repo yes since I think that branch will go away after it merges onto main.

**Comment by zoe1337** [comment]
Yes I thought so! I'm looking forward to cmake on main branch! I wasn't able to get current upstream master to build on Arch, due to lack of Python 3.8

**Comment by AlexMitchellMus** [comment]
Two things:

1) Current `bespokesynth-git` in AUR doesn't build (can we get this new PKGBUILD on he AUR?)
2) Can the PKGBUILD use all cores for make?

**Comment by Jikstra** [comment]
I updated the PKGBUILD to use the master branch of this repo as Cmake support got merged. I changed some minor things (using install over mkdir/cp). Maybe helpful for someone. 

PKGBUILD
```
_pkgname=bespokesynth
pkgname="$_pkgname"-git
pkgdesc="Software modular synth, VST host input, transport/Ableton Push (CMake)"
pkgver=r1012.46bff9b
pkgrel=1
arch=(x86_64)
url="https://github.com/awwbees/BespokeSynth"
license=(GPL3)
depends=('jack' 'curl' 'mesa' 'xorg-xrandr' 'python' 'libxext' 'ladspa' 'juce' 'xorg-server-xvfb')
makedepends=('gcc' 'libx11' 'libxinerama' 'freetype2' 'cmake')
checkdepends=()
optdepends=()
provides=('bespokesynth' 'bespokesynth-bin')
conflicts=('bespokesynth' 'bespokesynth-bin')
replaces=()
noextract=()
source=(
  "bespokesynth-git::git+https://github.com/BespokeSynth/BespokeSynth"
  "BespokeSynth.desktop"
)
sha256sums=(
  'SKIP'
  'c432e9f0e12b63002a4af7fa78e48e2656be18d262ecbae7514c09ff852dec85'
)

pkgver() {
  cd "$srcdir/${pkgname}"

  ( set -o pipefail
    git describe --long 2>/dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
  )
}

prepare() {
  cd "$srcdir/${pkgname}"
  git submodule update --init --recursive
}

build() {
  cd "$srcdir/${pkgname}"

  cmake -Bignore/build
  cmake --build ignore/build -j $(nproc)
}

package() {
  cd "$srcdir/${pkgname}"

  echo $(pwd)
  install -d "${pkgdir}/usr/bin"
  install "ignore/build/BespokeSynth_artefacts/Release/BespokeSynth" "${pkgdir}/usr/bin/BespokeSynth"

  install -d "${pkgdir}/usr/share/icons/hicolor/512x512/apps"
  install -Dm644 "bespoke_icon.png" "${pkgdir}/usr/share/icons/hicolor/512x512/apps/BespokeSynth.png"

  install -d "${pkgdir}/usr/share/applications/"
  install -Dm644 "${srcdir}/BespokeSynth.desktop" "${pkgdir}/usr/share/applications/BespokeSynth.desktop"

  install -d "${pkgdir}/usr/share/BespokeSynth/"
  cp -r resource "${pkgdir}/usr/share/BespokeSynth/"
}
```

BespokeSynth.desktop
```
[Desktop Entry]
Name=BespokeSynth
GenericName=Software modular synth
Comment=Software modular synth with a lot of features
Exec=/usr/bin/BespokeSynth
Icon=BespokeSynth
Categories=AudioVideo;Audio;Music;Midi
Terminal=false
Type=Application
Keywords=MIDI;Synth;VST
```

**Comment by baconpaul** [comment]
Hi!
The cmake install rules at head should do those installs for you if that helps

**Comment by baconpaul** [comment]
And also will properly obey cmake install prefix which you probably want to set

**Comment by Jikstra** [comment]
> And also will properly obey cmake install prefix which you probably want to set

@baconpaul 
I tried to use the .desktop file that is getting created with cmake, but somehow cmake ignores `cmake -Bignore/build . -DCMAKE_INSTALL_PREFIX=/usr` and the .desktop file still points to `/usr/local/bin/BespokeSynth`. But probably i need to do a clean build (which takes long on my device). But in theory the `-DCMAKE_INSTALL_PREFIX` should be the correct way?

**Comment by baconpaul** [comment]
It did when i did a clean build yesterday but I know Kott has been updating it also. That said, you don't need a clean build. just blow away the ignore/build/*Desktop and they should regenerate

**Comment by dvzrv** [comment]
I have updated the PKGBUILD in the AUR and am about to add bespokesynth to the official repositories.

For devendoring purposes and for usability issues I will open a few tickets though and if time permits upstream my solutions to them.

I think this ticket may be closed now.

**Comment by baconpaul** [comment]
Should you perhaps wait until there’s a 1.1.0 tag later this week post the 1.1 beta?

**Comment by dvzrv** [comment]
@baconpaul Yes. I also realized there is at least one major blocker (#591) to package this in the official repositories.

**Comment by baconpaul** [comment]
Yeah bespoke had snapshots at 1.0 and we’ve been moving to proper submodules as we work but certainly aren’t done yet

**Comment by baconpaul** [comment]
(Submodules would of course include the license file of the original code)

**Comment by dvzrv** [comment]
I understand. The problematic code is the one that does not allow redistribution (3dxware) and should not be in this repository though (it is likely also not compatible with the GPL3).

**Comment by baconpaul** [comment]
Yeah we should treat that one more like asio or vst2.

**Comment by NoxyNixie** [comment]
I'll go and do this now:

> I think this ticket may be closed now.

If at any point this needs to be reopened don't hesitate to post on this issue and I will reopen it ;)
