### ISSUE TITLE
Vst and iLok

### ISSUE THREAD

**Issue by earlabs** [BespokeSynth/BespokeSynth#200]
hi, just started looking into this. Scanning for vst's I got a message to reconnect (authorize) my GRM stuff to iLok. In my usual DAW I have no issues with these vst's. After pressing cancel Bespoke freezes.
Also I think it would be good to be able to select the folders to be searched.

**Comment by awwbees** [comment]
if you click the "settings" button, you can specify which vst directories to search. you can also edit this file via `<documents>/BespokeSynth/userprefs.json`, which may be more convenient

**Comment by awwbees** [comment]
fixed with new scanning process in #421
