### ISSUE TITLE
crash while attempting to load .bsk files

### ISSUE THREAD

**Issue by cmovvv** [BespokeSynth/BespokeSynth#203]
when attempting to load two separate .bsk files (each approximately 40mb in size), bespoke goes unresponsive and then closes after about a minute. (.bsk files reference two samples and one vst, all located on local disk.) crash logs indicate something with the "stack frame" function, but only some of them are detailed.

[crash_2021-09-19_12-11.txt](https://github.com/awwbees/BespokeSynth/files/7192819/crash_2021-09-19_12-11.txt)
[crash_2021-09-19_14-06.txt](https://github.com/awwbees/BespokeSynth/files/7192820/crash_2021-09-19_14-06.txt)
[crash_2021-09-19_15-40.txt](https://github.com/awwbees/BespokeSynth/files/7192821/crash_2021-09-19_15-40.txt)

**Comment by awwbees** [comment]
could you post the bsk files that crash? I will try to reproduce it

**Comment by cmovvv** [comment]
github wouldn't allow me to attach the files individually or as a compressed archive, so here is a drive link with the requested files. please let me know if you have any trouble accessing them. https://drive.google.com/file/d/1EYs_FHCMYIgF-waTJjy4km_SnICfqnLK/view?usp=sharing

**Comment by cjthehammer** [comment]
I have the exact same issue with multiple of my .bsk files. Here is one such file, but all of them have the exact same 100% reproducible crash on load, and the crash files are near identical.

[example1.zip](https://github.com/awwbees/BespokeSynth/files/7199795/example1.zip)
[crash_2021-09-20_21-20.txt](https://github.com/awwbees/BespokeSynth/files/7199796/crash_2021-09-20_21-20.txt)

**Comment by fornullusa** [comment]
I recently made a video on my youtube channel about bespoke synth and in the comments section mentioned that I had stopped using the app after not being able to load my project. You invited me to send the file for debugging and so here it is. 
I was able to successfully load this file a few times while working on it, but the next day I tried to load it and it resulted in a crash of bespoke synth.
Thank you for your time.

**Comment by rbckman** [comment]
Recently hit the same issue! not able to load multiple save states, had a very groovy project with alot of midi mappings and loops. Really bummed out cuz I reeeally really love Bespoke and would like to continue jamming with it. I'm hopeful we find what makes em brake!

**Comment by fornullusa** [comment]
I've noticed something that happens before a patch can't be loaded. The connectors on some modules will be wrong. It also  happens if the same type of module does not have a unique name. It seems like the code should be assigning unique IDs to each device and not relying on string matching of name to determine what is connected to what.

**Comment by rbckman** [comment]
hm. so yes, there's no VSTs in my project. I was only messing around with midi mappings and loops + effects, got one saved state waaay back that works, then did couple of days more midi mappings and some nice grooves but sadly its all gone for now :( is there some way to unpack the bsk file and have a look around?

**Comment by rbckman** [comment]
my crash log

backtrace:
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x8dc1d0) [0x56329a5d71d0]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x48b086) [0x56329a186086]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x8c988d) [0x56329a5c488d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14140) [0x7f236652f140]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x141) [0x7f2366066ce1]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x123) [0x7f2366050537]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9a7ec) [0x7f23663e87ec]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5966) [0x7f23663f3966]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa59d1) [0x7f23663f39d1]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa5c65) [0x7f23663f3c65]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x283042) [0x563299f7e042]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x412459) [0x56329a10d459]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x668e65) [0x56329a363e65]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x492d09) [0x56329a18dd09]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x49364b) [0x56329a18e64b]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x49394f) [0x56329a18e94f]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x450f79) [0x56329a14bf79]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x97bd09) [0x56329a676d09]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x97b972) [0x56329a676972]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x97a46b) [0x56329a67546b]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x31825d) [0x56329a01325d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f2366051d0a]
/home/rbckman/Robs/BespokeSynth/ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth(+0x31c34a) [0x56329a01734a]



OS: Linux
CPU vendor: GenuineIntel
CPU model: Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
CPU speed: 3222 MHz
num cores: 4
num CPUs: 2
RAM: 7835 MB
computer: radiorymd-looperstation
language: American English
region: United States
display language: American English-United States
description: 
manufacturer: 
build: bespoke 1.0.999 (Nov  6 2021 12:25:22))

**Comment by rbckman** [comment]
I'll just leave the bsk files here if someone knows how to troubleshoot this.
this is groovy but not working https://radiorymd.com/static/groovy.bsk
this aint groovy but working https://radiorymd.com/static/working.bsk

**Comment by NoxyNixie** [comment]
The original cause of this crash was fixed however old savestates will still crash currently. The problem resolution isn't exactly clear.

The problem is that child modules of the effectchain module weren't saving their name. Making any savestate that has different child names break. Now you can't directly rename these child modules however when you create multiple of the same effect in a single effectchain and then remove the first of that effect the additional ones will have names with numbers in them.
