### ISSUE TITLE
`presets` messes up `notecanvas`

### ISSUE THREAD

**Issue by jabcross** [BespokeSynth/BespokeSynth#204]
![image](https://user-images.githubusercontent.com/6402237/133947684-123d423e-3e39-42ee-a52f-f49e0d634f68.png)

- Add note canvas
- Add `presets`
- Drag `presets`' gray circle into note canvas
- Save a preset
- Reload a preset
- wat

**Comment by ishanpm** [comment]
Thankfully this bug seems purely visual, and it's possible to work around it by holding Ctrl and dragging downwards on the canvas until you can see again.

**Comment by ghost** [comment]
It's not just visual, it incorrectly recalls the notes.
https://www.youtube.com/watch?v=XoRSmAmBBd4

**Comment by NoxyNixie** [comment]
I am unable to reproduce this issue in the latest Nightly build. The modules have had quite a few fixes and now it is also called `snapshots` instead.

If this issue resurfaces feel free to either respond on this issue or create a new one.
