### ISSUE TITLE
Unable to run BespokeSynth in Linux because dependency of libpython3.8.so.1.0

### ISSUE THREAD

**Issue by knight-ryu12** [BespokeSynth/BespokeSynth#208]
Hi. I am trying to run BespokeSynth under Archlinux.
But due to dependency of libpython3.8.so.1.0, this will never run (Downgrade is generally not recommended)

Current ldd output
```        
        linux-vdso.so.1 (0x00007fffb6f1b000)
        libpython3.8.so.1.0 => not found
        libasound.so.2 => /usr/lib/libasound.so.2 (0x00007fb1b90f6000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fb1b8fb5000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fb1b8fa0000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fb1b8ed6000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb1b8eb5000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb1b8eac000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fb1b8d68000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007fb1b8ce2000)
        libusb-1.0.so.0 => /usr/lib/libusb-1.0.so.0 (0x00007fb1b8cc4000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb1b8aae000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb1b8a93000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fb1b88c5000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007fb1b88ba000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb1ba685000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fb1b8890000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007fb1b8876000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fb1b8863000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fb1b882c000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fb1b8754000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007fb1b8746000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fb1b868e000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007fb1b865b000)
        libudev.so.1 => /usr/lib/libudev.so.1 (0x00007fb1b8633000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fb1b862c000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fb1b8624000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fb1b85ff000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fb1b84ca000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007fb1b84a7000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fb1b842e000)
```

uname -a output
`Linux digitalfairy 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64 GNU/Linux`

**Comment by baconpaul** [comment]
If you build at head on arch, it will detect your os python version and create an executable which links against that

**Comment by cooperdp1965** [comment]
> If you build at head on arch, it will detect your os python version and create an executable which links against that

I have the same issue but not sure what you mean by "If you build at head on arch". Please can you help?

**Comment by baconpaul** [comment]
Build bespoke from the current head of source in GitHub rather than download a binary

**Comment by tobtobxx** [comment]
Yes, either build it from source or install the AUR package `python38`.

Se the arch wiki: https://wiki.archlinux.org/title/Python#Old_versions

**Comment by spectromas** [comment]
Building from source and/or installing python38 doesn't fix things for me. According to ldd everything is accounted for but it dies when I try to run it, the only output in a terminal being 'killed'.

**Comment by chris-aeviator** [comment]
I'm able to build from SRC, but starting `./ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth` errors with

```
./BespokeSynth: /opt/miniconda3/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./BespokeSynth)
./BespokeSynth: /opt/miniconda3/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./BespokeSynth)
```

while only `extra/libstdc++5 3.3.6-7 (208.0 KiB 824.7 KiB) (Installed)` is available in the arch repos.
`

**Comment by KottV** [comment]
@chris-aeviator seems your python setup is broken, why the toolchain looking for it in the `/opt/miniconda3/` ?

**Comment by tobtobxx** [comment]
@chris-aeviator Can you run `ldd ./ignore/build/Source/BespokeSynth_artefacts/Release/BespokeSynth`?

Also `/usr/lib/libstdc++.so.6 is owned by gcc-libs 11.1.0-1`. Do you have this file and this package?

Should be a different issue btw.

**Comment by KottV** [comment]
Seems to be fixed for a long.
