### ISSUE TITLE
 Build Error: CMake 3.16 or higher is required.  You are running version 3.13.4

### ISSUE THREAD

**Issue by mark-orion** [BespokeSynth/BespokeSynth#211]
This is on a Ubuntu 18.04 system. Would it be possible to make the build system requirements as low as possible ? There are many people who still run Ubuntu 18.04, some even 16.04. The same probably applies to many users of Debian and other distros.
otherwise - great project !

Just to add: I found a workaround (at least for Ubuntu) by replacing the distributions CMake with the one on the snap store. The process is described here: https://graspingtech.com/upgrade-cmake/

**Comment by baconpaul** [comment]
there's a couple of features pybind uses to locate os python which the docs say require 3.16, hence the check.
if you lower the version in the cmake file does it work?

**Comment by mark-orion** [comment]
I tried that but it did not work because there are similar higher version requirements in other cmake files (juce). In the end I found a way to get around the problem by installing the latest CMake via Ubuntus snap store. However that would not solve the problem for other non-Ubuntu users with older systems. I do not know what build system you are using, but it would probably a good ideal to try an older linux so that everything has better backward compatibility. My guess is that even older pybind versions won't rely on CMake 3.16.
thanks, Mark

On 20 September 2021 14:22:20 BST, Paul ***@***.***> wrote:
>there's a couple of features pybind uses to locate os python which the docs say require 3.16, hence the check.
>if you lower the version in the cmake file does it work?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/awwbees/BespokeSynth/issues/211#issuecomment-922923392
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by baconpaul** [comment]
ahh right yes juce requires a relatively recent version.

These version constraints are for real reasons too. 

But can't you just install a version from cmake.org? That's how I upgraded when i was on ubuntu 18 and how the surge users on older debians have done it too.
