### ISSUE TITLE
couldn't load font from /frabk.ttf - and gui window without text

### ISSUE THREAD

**Issue by mark-orion** [BespokeSynth/BespokeSynth#212]
I managed to create a build, but when I try to start Bespoke from the  BespokeSynth/ignore/build/BespokeSynth_artefacts/Release folder, I am getting a window with gui elements, but no text and this error message.
I tried to copy all the *.ttf files from the resource folder into the releases folder, but that did not work.
System: Ubuntu 18.04

**Comment by layneson** [comment]
I had this same problem. However, when launching Bespoke from either of the `BespokeSynth_artefacts` or `Release` folders, it works (after copying the resources into `Release`).

**EDIT**: If I only copy the `*.ttf` files, I can launch from `BespokeSynth_artefacts` but not `Release`. If I copy all resources, I can launch successfully from either directory.

**Comment by baconpaul** [comment]
I have a PR #213 in to fix this problem (basically by copying the resource directory next to the exe in the dev time cycle on win/lin, but doing something a bit more on mac)

If you want to try the branch on that PR and make sure it works for you it would be appreciated.

**Comment by layneson** [comment]
@baconpaul I tried your PR and it works just as manually copying the resources does. Doesn't get rid of the issue where you have to launch from `BespokeSynth_artefacts` or `Release`, but that's probably a different issue.

**Comment by baconpaul** [comment]
Yes one we were just discussing on discord.

my pr addresses that for Mac but Linux needs a bit more work

**Comment by mark-orion** [comment]
Thanks for the responses. Problem solved (at least here). The solution was to cd into the build directory and then start Bespoke from there with "BespokeSynth_artefacts/Release/BespokeSynth". This did not even require me to copy any resources.

**Comment by baconpaul** [comment]
yeah we have mac and (almost) windows sorted in this regard; linux is next. but that prescription works indeed.

**Comment by baconpaul** [comment]
So I think we can close this issue. On Linux at head there is a waterfall of the cmake install dir, /usr, an env var which lets you override, and cwd.

**Comment by KottV** [comment]
There shouldn't be any resources path problem. At now.
