### ISSUE TITLE
GUI papercuts

### ISSUE THREAD

**Issue by AlexMitchellMus** [BespokeSynth/BespokeSynth#214]
- [x] Lasso Select highlights node GUI widgets, when in lasso mode, hover should be disabled.
![Screenshot from 2021-09-21 04-53-30](https://user-images.githubusercontent.com/12004932/134063146-22825b7f-ce6a-4a6a-8a6c-a27aec1b4abc.png)

- [x] Dragging node edge (cable) over a node highlights widgets, cable drag mode should disable hover. (for cable type that does't connect to widget type)
![Screenshot from 2021-09-21 04-54-56](https://user-images.githubusercontent.com/12004932/134063158-327163e9-1828-46d1-90c1-e9cb74aa7071.png)

- [x] Tool-tips render their text blurry if they are attached to a node widget (slider, value, etc)  The add node drop-downs render their tool-tips sharp, however when the tool-tip for the drop-down menu is on top of a node widget area, they will also be blurry

https://user-images.githubusercontent.com/12004932/134378677-64458895-5578-46d6-9e61-47ff764062b8.mp4

**Comment by awwbees** [comment]
note that the specifics of that blurry text is actually because you have the canvas at a slightly different zoom level than the title bar, which is expected
