### ISSUE TITLE
script modules lose connections from note ouputs > 0 upon saving/loading

### ISSUE THREAD

**Issue by disconex** [BespokeSynth/BespokeSynth#219]
To reproduce: Make a `script` module which runs `me.set_num_note_outputs(2)`. Connect each note output to somewhere, e.g. a `notegate`.

![Screen Shot 2021-09-21 at 05 58 40](https://user-images.githubusercontent.com/90849955/134110141-334620ef-1314-4962-a2a6-cb6b0c05ece4.png)

Save the patch and load the [saved state](https://github.com/awwbees/BespokeSynth/files/7200174/note-outputs-test.bsk.zip). Only note output `0` is connected to its target now.

![Screen Shot 2021-09-21 at 06 13 39](https://user-images.githubusercontent.com/90849955/134110635-73e40cfc-188c-434c-9741-e386ae2df45f.png)

**Comment by awwbees** [comment]
fixed this one a while back, should be good now!
