### ISSUE TITLE
Circle Sequencer Click Area Issue

### ISSUE THREAD

**Issue by Capital-EX** [BespokeSynth/BespokeSynth#22]
I don't know if this the intended behavior of the Circle Sequencer, but where you need to click doesn't line up with where the marks are:
![odd](https://user-images.githubusercontent.com/13488718/90338988-b6625f00-dfbb-11ea-8375-9f6afe97e987.gif)

I'm running this on Windows 10 in case that is useful.

**Comment by awwbees** [comment]
aha, yes, that certainly isn't intended. circlesequencer was a half-finished idea that I abandoned, and I guess it broke somewhere along the way. perhaps I should remove it to reduce confusion.

**Comment by sukhchainn** [comment]
I'll give it a try, cheer me up!

Edit:
Sorry, I can't. My machine can't run ProJucer because it has problems with VS IDE installation.
My bad.

**Comment by Capital-EX** [comment]
I liked the idea, but I think it's functionality overlaps with the polyrhythm tool. So, it may be best to remove it.

**Comment by awwbees** [comment]
I ended up fixing the issues in this one a while back. it works now!
