### ISSUE TITLE
input module does not pass audio (MacOS 11.5.2, MOTU828es, MOTU MidiExpress 128)

### ISSUE THREAD

**Issue by prismatic7** [BespokeSynth/BespokeSynth#220]
Hi

The module 'input' is not passing audio from any input channel with the setup described. MIDI is being passed out (notesequencer > midioutput) and audio can be monitored at the audio interface or via other software (Ableton live, Audacity) but cannot be received via 'input'.

**Comment by awwbees** [comment]
which os are you running, big sur? possible duplicate of #116

**Comment by Enkerli** [comment]
(macOS 11.5.2 is indeed Big Sur. Monterey, macOS 12, should come in a few weeks.)

**Comment by prismatic7** [comment]
Hi folks. That's correct, 11.5.2 is Big Sur. I upgraded at the weekend, once everything I use was certified. I'm not going anywhere near Monterey until this time next year at least!

**Comment by awwbees** [comment]
I believe all these big sur permissions issues are fixed and will be in the 1.0.1 release
