### ISSUE TITLE
Crash: On load savestate with prefab/spawn prefab, null pointer

### ISSUE THREAD

**Issue by UniQMG522** [BespokeSynth/BespokeSynth#221]
Bespoke crashes when spawning this specific prefab or loading a savestate containing it:
[oscilliscope-sprite.pfb.txt](https://github.com/awwbees/BespokeSynth/files/7200532/oscilliscope-sprite.pfb.txt)

<details>
<summary>Crash log</summary>
stack frame:
CallWindowProcW + 0x3bd
DispatchMessageW + 0x1f2
BaseThreadInitThunk + 0x14
RtlUserThreadStart + 0x21

backtrace:
3: UnhandledExceptionFilter + 0x1ea
4: memset + 0x1b32
5: _C_specific_handler + 0x96
6: _chkstk + 0x11f
7: RtlRaiseException + 0x399
8: KiUserExceptionDispatcher + 0x2e

OS: Windows 10
CPU vendor: GenuineIntel
CPU model: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
CPU speed: 3653 MHz
num cores: 12
num CPUs: 6
RAM: 16319 MB
computer: Spire
language: en
region: US
display language: en-US
description: Windows (Desktop)
manufacturer: 
build: bespoke 1.0.0 (Sep 13 2021 20:28:53)
</details>

**Comment by awwbees** [comment]
I'm not able to load this prefab (github says "not found"), but I think this is likely fixed by #532

**Comment by awwbees** [comment]
that is: your prefab still probably crashes, but the circumstances that led to the creation of the bad prefab are now fixed
