### ISSUE TITLE
Unable to get working on Windows 10 or Debian Linux

### ISSUE THREAD

**Issue by cooperdp1965** [BespokeSynth/BespokeSynth#224]
I have downloaded and attempted to install on Windows 10 and get a MSVCP140.dll and VCRUNTIME140.dll were not found error. So, I tried installing on my Linux machine and get a Python library issue that has previously been reported and seems to relate to a missing old Python library.

On Windows 10, I installed the C++ Redistributable runtime and that fixed the issue but the screen refresh rate is only running at around 20fps and so everything is blurry. Holding O down does pop up an option to select an oscillator but it disappears very quickly.

I would really like to give this a go and so any advice to help with getting it working, on either Windows 10 or Linux, would be really appreciated.

**Comment by awwbees** [comment]
I'm not really sure what this could be... wacky graphics driver issues?

**Comment by ebunders** [comment]
I have the same issue with the linux version. But I managed to get the windows version to run on Ubuntu using wine.

**Comment by KottV** [comment]
> I have the same issue with the linux version. But I managed to get the windows version to run on Ubuntu using wine.

with wine? good to know that it works:)

what is your Ubuntu version?

**Comment by ebunders** [comment]
Ubuntu 21.04. The latest.
I haven't tested it, but this way you should be able to use vst's as well...

**Comment by KottV** [comment]
I think we can close this.
