### ISSUE TITLE
error setting buffer size to 256 on device ''

### ISSUE THREAD

**Issue by jrmain** [BespokeSynth/BespokeSynth#225]
The complete error message is "error setting buffer size to 256 on device '', fix this in userprefs.json (a valid buffer size might be: 0)"

It looks like Bespoke is having trouble identifying the output device.

Any clues as to how to resolve this?

Windows 8.1 64-bit. No other audio issues on this PC that I've noticed.

**Comment by awwbees** [comment]
what is in the audio_output_device dropdown in the settings window? could you post a screenshot?

**Comment by jrmain** [comment]
![DeviceError01](https://user-images.githubusercontent.com/1110694/134265062-33209226-eadb-4e3d-bd5d-9a3cd6dc9346.png)

**Comment by awwbees** [comment]
interesting. and this also looks like a different error than the initial report. hmm... I'm not really sure. is it possible that some other app has an exclusive lock on your audio device?

**Comment by jrmain** [comment]
Hey you're right. I actually seem to get a few different messages. As for whether another app has an exclusive lock, I'll look into that and let you know what I find.

**Comment by jrmain** [comment]
![DeviceError02](https://user-images.githubusercontent.com/1110694/134280038-9554c826-4e44-4727-bcbf-ef93734faf3b.png)

**Comment by jrmain** [comment]
I tried disabling exclusive mode on all available audio output devices but that didn't help. It turns out that the only devicetype that works is DirectSound. Windows Sound doesn't work, and 'auto' chooses Windows Sound. I understand that DirectSound can introduce clicks and distortions, but at least it's working. Thanks.

**Comment by awwbees** [comment]
DirectSound can work fine if you find the right combo of buffer size and sample rate, so if it's not clicking, sounds like you found the right combo!
