### ISSUE TITLE
noterangefilter bug

### ISSUE THREAD

**Issue by Korblys** [BespokeSynth/BespokeSynth#228]
minor issue regarding noterangefilter, unsure if user error or problem with effect itself- when selecting between values 58 and 60 or similar number difference, numbers like 59 aren't selectable via the slider. Attempted to try zoomed in as close as Bespoke allows, yet the same problem persists.

included a recording of issue, showing problem with 58-60 and 62-64.

https://user-images.githubusercontent.com/90932975/134275839-5084ee2c-5d1d-4b65-80c5-2085d0a0daf3.mp4

**Comment by awwbees** [comment]
I will take a look at why it is not giving you full resolution. in the meantime, two options:
- while hovering over the slider, you could use the up and down arrows on the keyboard to increment the value
- while hovering over the slider, you could type the desired number and then press enter

**Comment by ThePython10110** [comment]
You can also hold shift while dragging to change by smaller amounts.

**Comment by awwbees** [comment]
resolved by #1091
