### ISSUE TITLE
How to use python within BespokeSynth?

### ISSUE THREAD

**Issue by muziker** [BespokeSynth/BespokeSynth#232]
Where is the python terminal from within bespoke? I've compiled a version and i cannot find any python related instruments?

**Comment by KottV** [comment]
other->script

PS. I think such questions are more suitable for Discord channel "how-do-i"

**Comment by muziker** [comment]
There's a discord channel? Why not an FAQ instead or a video tutorial?

**Comment by KottV** [comment]
> There's a discord channel? Why not an FAQ instead or a video tutorial?

https://www.bespokesynth.com/docs/index.html
