### ISSUE TITLE
prefab mixer connections resetting after file save and load

### ISSUE THREAD

**Issue by cmovvv** [BespokeSynth/BespokeSynth#237]
i have one patch that keeps resetting my mixer connections whenever i load it, even following a save and "save as" to a separate file.  here are screenshots that demonstrate this (the middle image shows the correct connections). the patch can be accessed at https://drive.google.com/file/d/13otS3l7Qo4kDWsuuUn_02rQOPEgG_lV3/view?usp=sharing

![bespoke_connections_reset_001](https://user-images.githubusercontent.com/47002861/134367300-e9698128-0b33-4a65-8f8b-419e4ce91898.jpg)

![bespoke_connections_reset_002](https://user-images.githubusercontent.com/47002861/134367377-3012336d-3117-4a61-8378-c28c3de52f4d.jpg)

![bespoke_connections_reset_003](https://user-images.githubusercontent.com/47002861/134367401-4cdb3308-3ca0-4e21-a798-3cd408e7add4.jpg)

**Comment by awwbees** [comment]
I think #532 fixes this, there was an issue where modules inside prefabs weren't getting assigned unique names (which breaks cable routing)
