### ISSUE TITLE
Backspace to unlink doesn't work on note canvas

### ISSUE THREAD

**Issue by tobtobxx** [BespokeSynth/BespokeSynth#238]
As ridiculous as it sounds, yes.

I unlink other modules by grabbing the handle and pressing backspace. They (the couple ones I tested at least) work. But when I try to unlink a note canvas from an oscillator, it just... doesn't work.

Version: 1.0.0
OS: Arch Linux

(IMO this shortcut is quite inconvenient. I'd suggest something like Blender's ctrl-drag for cutting through conenctions. In general, there's something to be learned from blender's controls for nodes, but this is just my 2c).

Thank you :v:

**Comment by crystalthoughts** [comment]
Same issue here on mac!

**Comment by asmw** [comment]
Huh, same on Ubuntu 21.10.
I'll take a look
