### ISSUE TITLE
How to zoom without a trackpad ?

### ISSUE THREAD

**Issue by rncar** [BespokeSynth/BespokeSynth#24]
In the help.txt file says
* Hold space bar and drag two fingers vertically to zoom in and out.

**Comment by awwbees** [comment]
I should reword that! your mouse wheel should provide equivalent behavior to the trackpad, so hold the space bar and scroll the mouse wheel.

**Comment by rncar** [comment]
I have not a mouse wheel, I use a wacom table.
Would be great to have a key combination to zoom.

**Comment by awwbees** [comment]
hmm. does your wacom tablet have any scrolling functionality? bespoke uses scrolling in several places, so it might be tough to use without any way to scroll. I don't know which model wacom you have, but many seem to offer scrolling capability: https://101.wacom.com/UserHelp/en/StandardGestures.htm

**Comment by rncar** [comment]
I need to investigate further, maybe its possible to activate it in some configuration file.
At this moment I am simulating the scroll buttons using ```xdotool click 4``` and ```xdotool click 5```
