### ISSUE TITLE
"CTRL+A" to select all inside text

### ISSUE THREAD

**Issue by ZachIsAGardner** [BespokeSynth/BespokeSynth#246]
When I'm editing the text inside a module and I input "CTRL+A" I'm expecting it to highlight all the text. Instead it inputs an "A" like I'm holding down shift.

Can we make it so when you do "CTRL+A" it highlights all the text? This would be pretty useful for when renaming things or typing out a comment since it starts with "insert comment here".

**Comment by fredericlb** [comment]
Hi ! I started working on my first PR to add selection in text inputs. If no one is working on this it would be pretty easy for me to add main keyboard shortcuts like this one.

**Comment by awwbees** [comment]
that would be awesome @fredericlb! I have code that does that in CodeEntry.cpp, and never got around to bringing it into TextEntry. if you haven't looked at the CodeEntry stuff yet, it could be a useful resource!

**Comment by fredericlb** [comment]
Thanks, I started writing my own stuff to handle selection but after your comment the PR is now mainly a copy/paste of what was in CodeEntry :)

**Comment by awwbees** [comment]
got added in the PR referenced above
