### ISSUE TITLE
looks like lotsafun, but I can't hear anything

### ISSUE THREAD

**Issue by 1xch** [BespokeSynth/BespokeSynth#25]
Starts muted, and stays muted no matter what I hookup.

**Comment by awwbees** [comment]
could you post a screenshot of something you've made that isn't making sound?

also, I've just put up a new release which you should go download, it could possibly help.

**Comment by 1xch** [comment]
It could be that I do not know what I am doing. I'll try the newer version(which I cannot because there is no linux version). 

What is the fastest way to test that sound is coming from the program?

**Comment by awwbees** [comment]
the new version has a readme.txt with a very brief "getting started", which also applies to the older version:
 * hold the 'o' key and choose "oscillator"
 * drag the circle at the bottom of the oscillator to patch a cable onto the "gain" module
 * hold the 'n' key and choose "notesequencer"
 * drag the circle at the bottom of the notesequencer to patch a cable onto the "oscillator" module
 * tada!

new linux build coming soon!

**Comment by awwbees** [comment]
that linux build is now up: https://github.com/awwbees/BespokeSynth/releases/tag/v0.0004-pre

**Comment by KottV** [comment]
Hi, Ryan

Binary is linked with webkit2gtk which is not necessary AFAIK. This can be disabled by JUCE_WEB_BROWSER="0" in .jucer (or in Projucers's gui - modules juce_gui_extra)
Also it contains debug info, that's why file is so big.

**Comment by bcaccia** [comment]
* **Bespoke version:** v0.0004-pre
* **OS:** Ubuntu Linux 18.04

**Repro:**

1. Open a terminal and `cd` into the Bespoke application directory. Run `./BespokeSynth`
2. Press and hold the `o` key on your keyboard and select `oscillator` from the menu
![image](https://user-images.githubusercontent.com/23156454/90898755-fe56fc80-e394-11ea-8fbc-27ac4d7f307e.png)

3. Connect the output of the `oscillator` to the input of the `gain` module

**Expected:**

* The user will hear the audio output of the oscillator module through their speakers

**Bug:**

* There is no audio output from Bespoke

**Additional Notes:**

* This is the output shown in my terminal after launching Bespoke. It indicates it is using PulseAudio.

```
./BespokeSynth                        
0.001: pixel ratio: 1 screen width: 3840 screen height: 1200
0.001: Could not load file /home/bcaccia/Applications/Bespoke-Linux/data/internal/used_vsts.json
0.001: output: Playback/recording through the PulseAudio sound server   input: Playback/recording through the PulseAudio sound server
0.120002: Loading layout: /home/bcaccia/Applications/Bespoke-Linux/data/layouts/blank.json
0.120002: Could not load file /home/bcaccia/Applications/Bespoke-Linux/data/internal/used_vsts.json
```

* This is what is displayed in the Sound panel of Gnome when Bespoke is active:
![image](https://user-images.githubusercontent.com/23156454/90899632-36127400-e396-11ea-8891-82c6f3bc277c.png)


I am available to provide further debug information.

**Comment by bcaccia** [comment]
Looks like user error on my part because if I load the default fubbles script demo save state I get audio which means I'm likely not hooking things up correctly.

**Comment by bcaccia** [comment]
Yup, following the exact instructions in @awwbees [previous comment](https://github.com/awwbees/BespokeSynth/issues/25#issuecomment-677872153) and it works fine. 

I thought hooking up the oscillator directly to the output would just output similar to VCV Rack. Looks like the OSC needs something triggering it to output.

**Comment by awwbees** [comment]
@bcaccia ah yes, if you use a `signalgenerator`, that will provide the basic oscillator you expected, while `oscillator` is a more complex polyphonic-enveloped-triggered package

**Comment by awwbees** [comment]
@KottV thanks! I was wondering why the executable was so large

**Comment by 1xch** [comment]
@awwbees 

thanks! I can hear something now.
