### ISSUE TITLE
libpython3.8 dependency unresolvable

### ISSUE THREAD

**Issue by SekoiaTree** [BespokeSynth/BespokeSynth#250]
I tried to run this, but I'm having some issues.. just clicking on the file, it seems to think it's a shared library. Trying to run through commandline, and I get the following error:

`./BespokeSynth: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory`
It seems there's some kind of dependency on python 3.8, which is currently uninstallable through apt... Unsure what to do.
Computer info:
Pop!_OS 21.04, 64-bit
GNOME version: 3.38.5
Windowing System: X11

**Comment by baconpaul** [comment]
if you build the source from head it will use your local python at compile time.

**Comment by SekoiaTree** [comment]
I'll do that for sure, should still be fixed tho

**Comment by WMRamadan** [comment]
I can confirm the same problem:
`./BespokeSynth: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory`

Platform Specs:
OS: Ubuntu 21.04 x86_64
Kernel: 5.11.0-34-generic
DE: GNOME 3.38.4
WM: Mutter

**Comment by baconpaul** [comment]
Right. Because the binary binds to 3.8 and Python isn’t abi compatible across major versions

If you want to run the binary you need 3.8. If you want to bind to 3.9 you need to do a build from source.

**Comment by mkesper** [comment]
Confirmed for Debian 11 too. Probably it would be a good idea to offer a build against libpython3.9 too. Alternatively offer a docker config to build against.

**Comment by awwbees** [comment]
I believe bespoke's new python setup (as of 1.1.0) resolves this issue
