### ISSUE TITLE
GUI Papercuts V2

### ISSUE THREAD

**Issue by AlexMitchellMus** [BespokeSynth/BespokeSynth#257]
- [ ] Clicking LMB on header bar of node moves node right by a few pixels

https://user-images.githubusercontent.com/12004932/134663658-dd98efdb-b7e6-4708-a4e0-82eae6069a23.mp4

- [ ] Modulation cables can't be LMB disconnected from their destination handle, but audio / data cables can

https://user-images.githubusercontent.com/12004932/134663686-115f1dc1-df18-4d72-9bf6-92e93e9f479a.mp4

**Comment by NoxyNixie** [comment]
I believe both of these have been resolved in the latest Nightly builds, not sure since which change.

If this reoccurs you can leave a comment here or create a new issue.
