### ISSUE TITLE
"Input and output devices don't share a common sample rate"?

### ISSUE THREAD

**Issue by omgitsraven** [BespokeSynth/BespokeSynth#26]
Launching the provided Windows binary, I just get a black screen that says `error initializing audio device: The input and output devices don't share a common sample rate!`

the next line says `initialization errors could potentially be fixed by changing buffer size, sample rate, or input/output devices in userprefs.json`, but I couldn't find anything there that helped:
- I tried changing `buffersize` from 256 to 128 and 512, no difference
- I tried changing `samplerate` from 48000 to 44100, no difference
- I couldn't find anything in userprefs.json about input or output devices; mine just looks like this:
```
{
   "buffersize" : 256,
   "height" : 1100,
   "layout" : "\\layouts\\blank.json",
   "samplerate" : 48000,
   "vstsearchdirs" : [
      "C:\\Program Files\\Common Files\\VST2",
      "C:\\Program Files\\Common Files\\VST3",
      "C:\\Program Files\\Steinberg\\VSTPlugins"
   ],
   "width" : 1700
}
```

**Comment by awwbees** [comment]
I just put up a new release, which should help with this issue.

in the latest release, if there are no matching sample rates between your output device and input device (which happens to be the case for me when I have my webcam as the default microphone), a workaround is to set your `audio_input_device` (which you will see in the `userprefs.json` in the latest build) to "none". it means that you won't be able to use the "input" modules to get microphone input, but perhaps this is acceptable.

**Comment by omgitsraven** [comment]
That works around it, thanks!

I would be curious to try the microphone input feature though... but the only values I've been able to enter for `audio_input_device` and `audio_output_device` that work are "none" and "auto"; everything else says "no such device". Is there a special format I'm supposed to use, or am I supposed to copy the entire string as printed in the 'valid devices' list (i.e. `Windows Audio: Microphone (High Definition Audio Device)`)?

**Comment by awwbees** [comment]
the format can be a little strange for the exact text you need to enter. I should figure out a way to make this easier. if you follow along in this thread, it may be helpful: https://github.com/awwbees/BespokeSynth/issues/16

**Comment by omgitsraven** [comment]
OK, that's gotten me back to the "don't share a common sample rate" error with two manually-specified devices, so the device specifying works!

I'm reasonably certain that these devices should have sample rates in common, though...

**Comment by asmw** [comment]
@omgitsraven is this still an issue?

**Comment by omgitsraven** [comment]
Haven't touched it in ages, sorry!

**Comment by asmw** [comment]
@omgitsraven I'll close this then, if you encounter this in the future, please open a new issue
