### ISSUE TITLE
Radio sequencer improvements

### ISSUE THREAD

**Issue by NikalMight** [BespokeSynth/BespokeSynth#261]
I've been using the radio sequencer to do long sequences with and there are a few improvements that could be made:

- 128 steps is too short at 1 bar per step, especially for higher tempos. For example, at 175 bpm, 128 steps of 1 bar amounts to nearly 3 minutes of music which isn't really enough. Ideally, the number of steps should be set by the user to an arbitrary number with a reasonable upper limit of say 512 or 1024.
- Larger step sizes of multiple bars would be helpful for macro-scale sequencing for introducing entire sections. The current maximum is 1 bar. Other options should be available such as 2, 4, 8 and 16 bars.
- At the moment, there are only two colours for the cells- a brighter colour for every 4 steps and a darker colour for the rest. When you have a large number of steps, it becomes quite confusing to know where you are, and you have to count how far away from the start you are. It would be a good idea to add different colours for the start of every 16th group of steps and possibly every 32nd step to help know where you are in the sequence.
- The default number of rows is set to 8 at the moment. This is usually overkill for me and wastes too much screen space. If I have several stacked on top of each other, it makes it harder to drag cables to where I want to go, as I have to scroll past a lot of unused rows. I typically use between 1 and 3 rows. A default option of two rows with additional buttons for adding more when needed and removing unused rows would be good. This also applies to other modules, such as the event canvas.
- Currently, the only way to get the software to save the size of radio sequencers is if you do it manually by using the top right menu. If you drag out the module with the dragging handle at the bottom right, this isn't reflected in the dimensions in the menu and on saving the project, the radio sequencer resets itself to the default size or whatever it is is in the menu.
- There are often times where I don't want mutually exclusive rows and I'd like a control that behaves more like a sequence of checkboxes rather than radio buttons and there don't seem to be any modules that do what I want. Either switch the existing radio sequencer functionality to checkbox functionality or create a "checkbox" sequencer module. A single checkbox sequencer could eliminate many radio sequencers for me.

**Comment by Keiler3K** [comment]
I thought of the same when working with radio sequencer. Did you try eventcanvas? It provides more freedom, e.g. triggering events simultaneously, and the ability define the number of rows. However, I had issues with events "touching" the very left or right side of the canvas (i.e. starting immediately with the first measure and/or ending at the end of the last measure).

**Comment by NoxyNixie** [comment]
Most if not all your points have been addressed already. Let me go through them:

* 1024 length sequences will be possible once #1070 is merged (any larger will be unwieldy at the least but also impacts render performance significantly).
* I can see the option to make each step take up to 8 bars at least right now in the `radiosequencer`.
* The `radiosequencer` currently saves it's size and is unaffected by changing options in the triangle menu.
* There now is a `one_row_per_column` mode which when turned off allows selecting multiple rows (i.e. your checkbox mode).
![image](https://user-images.githubusercontent.com/211381/214423002-df53fa65-7942-48ed-8120-04a4f0c4e79a.png)

The default will likely not be changed. 8 is a reasonably nice number for default rows and should cover most uses. If you want it smaller you can do so in the triangle menu.

The only thing I see not having been addressed is the colors changes in the 16th or larger steps. I now kind of may have resolved that too with #1092.

So I think that is all points addressed? If I'm wrong please feel free to reply on this issue or create a new one ;)
