### ISSUE TITLE
Massive difference in L and R channels in VST plugins

### ISSUE THREAD

**Issue by NikalMight** [BespokeSynth/BespokeSynth#263]
I ran a drum sequence through Guitar Rig and made sure it was using stereo inputs. The stereo image was really unbalanced. I disabled all the modules in GR to make sure it wasn't some effect I'd added. Both inputs and outputs were the same on GR's meters. I added an instance of bx_meter afterwards and the massive disparity between the L and R channels was obvious on the meter. There are other plugins this happens to and it's clearly a bug.

**Comment by KottV** [comment]
How many inputs it has? It's a known issue with more than two channels plugin, with AUX input for example.

**Comment by NikalMight** [comment]
That must be it. It has 4 inputs. I hope it gets fixed soon as a lot of my plugins have multiple channels.

**Comment by baconpaul** [comment]
oh @awwbees I fixed this in https://github.com/BespokeSynth/BespokeSynth/commit/c9998fa5e04ad6683f8791c069bf54a82a22c73e if you want to close it (and @NikalMight if you can build from source you can get the fix also).

**Comment by KottV** [comment]
Closed with https://github.com/BespokeSynth/BespokeSynth/commit/c9998fa5e04ad6683f8791c069bf54a82a22c73e
