### ISSUE TITLE
Logless crash when trying script node (Windows 10 + Python 3.8 installed)

### ISSUE THREAD

**Issue by cduquesne** [BespokeSynth/BespokeSynth#272]
Hi ! 
I'm running Windows 10 and wanted to try the scripting features of Bespoke.
I installed Python 3.9 from python website but still had a silent crash when adding a script node.
So I used pyenv-win to get the actual 3.8 version (it seems there is no simpler way to get it ?)
I tried with 3.8.10 and 3.8.0 but the result is still the same : after the warning I have a silent crash when adding a script node.
Any idea ? Thanks !

**Comment by severak** [comment]
Same here on Windows 7 with Python 3.8 installed:

```
C:\Users\Spravce>py --version
Python 3.8.5
```

**Comment by GitToDaChoppa** [comment]
Same issue on Mac here...

**Comment by NoxyNixie** [comment]
I believe this has been resolved by bundeling Python with Bespoke.

Let me know if the latest Nightly build does not work for you. You can reply on this issue and it will be reopened or create a new issue.
