### ISSUE TITLE
[REQUEST] "Panic" button/ability in VSTs (for stuck notes)

### ISSUE THREAD

**Issue by MBYlt** [BespokeSynth/BespokeSynth#276]
I get the occasional stuck note here and there (I think Dexed is particularly prone to them, but that may well just be superstition on my part). Anyway, it'd be handy to be able to send the DAW version of a "MIDI panic" to a VST instrument suffering from a stuck note or constantly-increasing/decreasing CC.

**Comment by awwbees** [comment]
does the noteflusher module work in this case?

**Comment by MBYlt** [comment]
That's a good idea, and I'll have to keep it in mind to try. Would it work on "stuck" CCs though?

I still think being able to send a "all notes/cc off" from a keyboard shortcut or context-menu command would be more zone-friendly (as in, "in the zone") than adding / patching a new module.

**Comment by MBYlt** [comment]
Update: Tried noteflusher. Oddly enough, it doesn't work.

Clicking "flush" seems to occasionally produce hiccups in active sequences, so I guess it's doing *something*, but when there's a stuck note as a result of a sequencer module being disconnected from the VST, that note is there to **stay**.

**Comment by baconpaul** [comment]
I think this would be as simple as adding a button to the VSTPlugin (or maybe the VSTPlugin triangle menu) which just sent the midi allNotesOff message down to the synth (and maybe have another button which sends allSoundOff). Most plugins deal with both of these correctly.

If I knew how to add something to the triangle screen I would do this myself!
