### ISSUE TITLE
[WIP] Information about Surge 1.9 crash

### ISSUE THREAD

**Issue by follower** [BespokeSynth/BespokeSynth#277]
_[WIP: I'm primarily using this issue to dump some details I discovered while debugging a [different issue](https://github.com/BespokeSynth/BespokeSynth/issues/108#issuecomment-927482450) in case its useful.]_

### VST3 Support?

(Aside: I was under the (mistaken?) impression that BespokeSynth 1.0 supported VST3 but at least on Linux that appears not to be the case with the release binary.)

With the binary release it just outputs. e.g.:

```
Attempting to load VST: /usr/lib/vst3/SurgeEffectsBank.vst3/Contents/x86_64-linux/SurgeEffectsBank.so
Attempting to load VST: /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so
Attempting to load VST: /usr/lib/vst/carla.vst/CarlaPatchbayFX.so
Creating VST instance: CarlaPatchbayFX
[...]
```
The "Attempting to load VST" message appears to originate within JUCE: https://github.com/juce-framework/JUCE/blame/4f01392000965f6c5e957329220d5ad06ca174c4/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp#L612

While troubleshooting the crash I discovered (via `LD_DEBUG=bindings` the binary release only ever looks for the `VST2` symbol `VSTPluginMain` instead of the `VST3` equivalent `GetPluginFactory`:
```
/usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so: error: symbol lookup error: undefined symbol: VSTPluginMain (fatal)
```

The `VSTPluginMain` lookup appears to be around here: https://github.com/juce-framework/JUCE/blame/4f01392000965f6c5e957329220d5ad06ca174c4/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp#L663

Whereas with the AppImage release this can be seen:  
```
binding file /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so [0] to /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so [0]: normal symbol `GetPluginFactory'
```

The `GetPluginFactory` is mentioned around here: https://github.com/juce-framework/JUCE/blob/46ea879739533ca0cdc689b967edfc5390c46ef7/modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp#L992

I noticed the AppImage build uses JUCE6 rather than JUCE5 due to a recent patch so maybe this explains the difference?

### Surge

While testing the AppImage file in the above link I noticed that Bespoke successfully identified VST3 plugins & (with one exception) also appeared to load the ones I tried successfully.

The one exception was Surge 1.9 which appeared to crash on load.

It turns out the plugin actually loads okay the crash only occurs when processing starts. This means that if you pause the transport control you can load the Surge VST3 successfully but as soon as play is resumed the plugin crashes.

When using the AppImage `bespokesynth-1.0.0+git57.a0511b9-lp152.7.1.Build9.1.glibc2.25-x86_64.AppImage` the backtrace I got for the crash via `gdb` was:

```
Thread 11 "JUCE ALSA" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffceaad700 (LWP 29382)]
0x00007fffcd61a368 in ?? () from /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so
(gdb) bt
#0  0x00007fffcd61a368 in ?? () from /usr/lib/vst3/Surge.vst3/Contents/x86_64-linux/Surge.so
#1  0x0000555555fd571f in void juce::VST3PluginInstance::processAudio<float>(juce::AudioBuffer<float>&, juce::MidiBuffer&, Steinberg::Vst::SymbolicSampleSizes, bool) ()
#2  0x0000555555fd5d9f in juce::VST3PluginInstance::processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) ()
#3  0x0000555555d166ba in VSTPlugin::Process(double) ()
#4  0x0000555555db6b42 in ModularSynth::AudioOut(float**, int, int) ()
#5  0x0000555555ed5799 in juce::AudioDeviceManager::audioDeviceIOCallbackInt(float const**, int, float**, int, int) ()
#6  0x0000555555ecfa9d in juce::(anonymous namespace)::ALSAThread::run() ()
#7  0x0000555555e92d1b in juce::Thread::threadEntryPoint() ()
#8  0x0000555555e92e19 in juce::threadEntryProc(void*) ()
#9  0x00007ffff67f26db in start_thread (arg=0x7fffceaad700) at pthread_create.c:463
#10 0x00007ffff5bdc71f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Disassembly of the code around the crash location:

```
   0x00007f8095d08353:	e9 b5 fc ff ff	jmpq   0x7f8095d0800d
   0x00007f8095d08358:	0f 1f 84 00 00 00 00 00	nopl   0x0(%rax,%rax,1)
   0x00007f8095d08360:	f3 0f 10 81 10 01 00 00	movss  0x110(%rcx),%xmm0
=> 0x00007f8095d08368:	f3 41 0f 11 02	movss  %xmm0,(%r10)
   0x00007f8095d0836d:	f3 0f 10 81 10 03 00 00	movss  0x310(%rcx),%xmm0
   0x00007f8095d08375:	f3 41 0f 11 01	movss  %xmm0,(%r9)
   0x00007f8095d0837a:	f3 0f 10 81 10 02 00 00	movss  0x210(%rcx),%xmm0
```

`processAudio` implementation appears to be here: https://github.com/juce-framework/JUCE/blame/4f01392000965f6c5e957329220d5ad06ca174c4/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp#L2341-L2342

(Oh, actually, I think the more relevant code might be this bit `invokeProcessFunction` which is inlined: https://github.com/juce-framework/JUCE/blame/4f01392000965f6c5e957329220d5ad06ca174c4/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp#L2474-L2492

via https://github.com/juce-framework/JUCE/blame/4f01392000965f6c5e957329220d5ad06ca174c4/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp#L2454  )

The ~~`processBlock`~~ `process` method of the Surge synth plugin (which crashes) is here: ~~https://github.com/surge-synthesizer/surge/blob/692d7774a390f41832c492878a0a920cca567629/src/surge-xt/SurgeSynthProcessor.cpp#L193~~ https://github.com/surge-synthesizer/surge/blame/release/1.9.0/src/vst3/SurgeVst3Processor.cpp#L462

The `processBlock` of the Surge *Effects* plugin doesn't crash and is here: ~~https://github.com/surge-synthesizer/surge/blob/558997e34821b84c3b17ea7f9fc0a4420c03ef4a/src/surge-fx/SurgeFXProcessor.cpp#L129~~ https://github.com/surge-synthesizer/surge/blob/release/1.9.0/src/surge_effects_bank/SurgeFXProcessor.cpp#L136

Other details:

```
(gdb) info frame
Stack level 0, frame at 0x7f809719a8f0:
 rip = 0x7f8095d08368; saved rip = 0x5572372a771f
 called by frame at 0x7f809719aa10
 Arglist at 0x7f809719a818, args: 
 Locals at 0x7f809719a818, Previous frame's sp is 0x7f809719a8f0
 Saved registers:
  rbx at 0x7f809719a8b8, rbp at 0x7f809719a8c0, r12 at 0x7f809719a8c8, r13 at 0x7f809719a8d0, r14 at 0x7f809719a8d8, r15 at 0x7f809719a8e0, rip at 0x7f809719a8e8
(gdb) info registers 
rax            0x0	0
rbx            0x0	0
rcx            0x7f806b0c6010	140189528514576
rdx            0x0	0
rsi            0x7f806b0c6010	140189528514576
rdi            0x7f80640051a0	140189410283936
rbp            0x55723850d630	0x55723850d630
rsp            0x7f809719a820	0x7f809719a820
r8             0x7f80640053d0	140189410284496
r9             0x0	0
r10            0x0	0
r11            0x0	0
r12            0x557238ec3960	93949069637984
r13            0x0	0
r14            0x7f8064005600	140189410285056
r15            0x0	0
rip            0x7f8095d08368	0x7f8095d08368
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

 * @baconpaul mentioned Surge 1.9 here: https://github.com/BespokeSynth/BespokeSynth/issues/148#issuecomment-921691770

 * And @baconpaul also supplied a patch to get Surge XT working: https://github.com/BespokeSynth/BespokeSynth/pull/186

 * As the AppImage was built recently enough to include that change it appear the latest nightlies of the Surge XT synth & FX plugins load okay: https://surge-synthesizer.github.io/nightly_XT (I did a little testing with `surge-xt-linux-x86_64-NIGHTLY-2021-09-26-f5c5ee8.tar.gz`.)

 * I think the related code for those plugins is:
    * https://github.com/surge-synthesizer/surge/blob/558997e34821b84c3b17ea7f9fc0a4420c03ef4a/src/surge-fx/SurgeFXProcessor.cpp#L129
    * https://github.com/surge-synthesizer/surge/blob/558997e34821b84c3b17ea7f9fc0a4420c03ef4a/src/surge-fx/SurgeFXProcessor.cpp#L129 

[WIP: TODO : Add other details. ]

**Comment by baconpaul** [comment]
So

1. If you build head of bespoke and head of surge it all works. The binary of bespoke is built with JUCE 5.4.7 which doesn't support VST3 on Linux; the head of code is Juce 6.1.1 which does. 
2. Surge 1.9 deals poorly with being given a bus layout other than what it asks for, but Surge at head is more reslient
3. Bespoke 1.0 mis-handled (and to an extent still mis-handles) all multi-bus VSTs but is better with the patch you mention above.
4. But Bespoke still has problems with multi-in multi-out FX and the Surge Effects Bank is that (since it has a vocoder side chain) so things like the SFX Vocoder won't be available.

**Comment by baconpaul** [comment]
Interestingly the SFX Bank multi-bus thing seems to make it so that bespoke passes through both the dry and wet signal. Hold on let me see if I can fix that too quickly.

**Comment by baconpaul** [comment]
OK PR #279 will fix up the fx bank dry signal problem (it was the symmetric fix to the output bus problem, just for multi-in).

**Comment by baconpaul** [comment]
So @follower with that merged at head of bespoke all the surge xt plugins work fine for me. Same for you?

the surge classic one is because bespoke sends is 3 outputs 2 of which are disabled - this is not a pattern any other daw sends. If we weee still patching 1.9 it would be a quick fix but really I’d like to do a more robust bus fix to bespoke one day. And we’ve almost started xt beta anyway

**Comment by baconpaul** [comment]
With PR #344 in place I can also load Surge 1.9 in Bespoke, so I think we can close this issue if that gets merged.
