### ISSUE TITLE
BespokeSynth.lv2? (was JUCE6?)

### ISSUE THREAD

**Issue by mxmilkiib** [BespokeSynth/BespokeSynth#28]
Might a move to JUCE 6 be on the cards? With JUCE 5 and the Projucer manual resave requirement, there's no way to automate the build atm.

**Comment by mxmilkiib** [comment]
N.b. there is also the DPF fork of JUCE which also can also target LV2, which would be amazing

https://github.com/DISTRHO/juce/tree/juce6

**Comment by KottV** [comment]
@mxmilkiib what you mean by LV2 target here?

**Comment by KottV** [comment]
>>With JUCE 5 and the Projucer manual resave requirement, there's no way to automate the build atm.

This is not true completely.
BTW BespokeSynth need just few updates to be compiled with JUCE6.

**Comment by mxmilkiib** [comment]
@KottV Unless I'm misunderstanding what is possible; as in build a BespokeSynth.lv2, like BespokeSynth can (AFAIU) run as a VST, also like Carla which can run as an VST/LV2 plugin.

> This is not true completely.

Ah, it has been a bit since I tried previously and I may have missed the steps in some other issue; is there a set of steps to programmatically build the app?

**Comment by KottV** [comment]
>>build a BespokeSynth.lv2

it could be great to have Bespoke as plugin: https://github.com/awwbees/BespokeSynth/issues/3#issuecomment-581544204

>>is there a set of steps to programmatically build the app?

sure https://build.opensuse.org/package/view_file/home:kill_it:JUCE/BespokeSynth/BespokeSynth.spec?expand=1
Projucer --resave command does resave, yes
and you need Xvfb for that
or you can take Projucer from JUCE6

**Comment by mxmilkiib** [comment]
Thank you! I'm getting [as far as](https://gist.github.com/mxmilkiib/c8f5bd859bb840b384b21a17e452325d) various undefined references; I double-checked the dependencies but maybe I'm missing something?

**Comment by xunil-cloud** [comment]
Hi, @mxmilkiib. Do you compile on linux? What distro are you using? I think you need to use python2-config (or python-config, depends on your system)rather than python3-config to get rid of that linking error.

**Comment by awwbees** [comment]
@mxmilkiib have you installed all of the dependencies listed here? https://github.com/awwbees/BespokeSynth/blob/master/Builds/LinuxMakefile/build/bespoke_dependencies.sh

these were sufficient to allow me to build (at least in JUCE 5.4.7) with a clean install of ubuntu 18.04

**Comment by awwbees** [comment]
(note that there are additional dependencies there compared to dependencies listed in an earlier thread, as python scripting support has been added since then)

**Comment by mxmilkiib** [comment]
Sorry, I think that was me managing to miss a couple of lines in the build steps, got it built now :)

**Comment by mxmilkiib** [comment]
JUCE 7 preview supports LV2 plugins and hosting.

**Comment by awwbees** [comment]
very exciting! when JUCE 7 hits full stable release, I will likely migrate over

**Comment by mxmilkiib** [comment]
A wee bump now 7 is out.
