### ISSUE TITLE
What version of OpenGL is required for Bespoke on Windows 10?

### ISSUE THREAD

**Issue by MSB-P** [BespokeSynth/BespokeSynth#280]
Getting the immediate crash when launching, and looking around here reveals a likely graphics issue as the cause.

I'm on an ancient laptop that's limited to OpenGL V2 (built in Intel 965 chipset driver).

Also curious to know what CPU extensions / features are required.

[crash_2021-09-27_12-06.txt](https://github.com/BespokeSynth/BespokeSynth/files/7238233/crash_2021-09-27_12-06.txt)

**Comment by awwbees** [comment]
this is the minimum required version set in code, maybe it's helpful: `openGLContext.setOpenGLVersionRequired(juce::OpenGLContext::openGL3_2);`

OpenGL 2 is not supported
