### ISSUE TITLE
Blank screen under debian 10

### ISSUE THREAD

**Issue by federicogalland** [BespokeSynth/BespokeSynth#283]
I built the package following the instructions on README.md

The first time I run it, I forgot to start jackd, and the GUI fired up OK.

I closed the program, started jackd and the run bespoke again, and now I only get a blank screen.

If I press the SHIFT key, I see the mouse cursor changing.

I already tried deleting the BespokeSynth folder under $HOME

Any ideas?

Thanks a lot for this great software anyway!

**Comment by federicogalland** [comment]
OK, I figured it out...

I deleted the BespokeSynth folder under $HOME, run:

`pulseaudio -k`

and then started the jackd server (without pasuspender) and the interface worked fine.

Thanks again!

**Comment by KottV** [comment]
so, it works?
