### ISSUE TITLE
Speed resolution for Drum Player is too coarse

### ISSUE THREAD

**Issue by NikalMight** [BespokeSynth/BespokeSynth#285]
I was trying to tune some samples in the drum player and the minimum resolution is 0.01. I know from DJing that increasing/decreasing the speed by +/- 6% changes the pitch by 1 semitone. Therefore, the minimum resolution is 16.67 cents (0.01/(0.06/100)). This is too coarse for precise musical tuning. Adding another decimal point of precision would make tuning drum samples easier. The other samplers have 0.001 precision, so I don't see why the drum sampler only has 0.01. Its lack of precision is particularly obvious when you're using tonal samples.

On a side note, it would be preferable if speed was expressed in semitones and cents, as it's more musically useful.

**Comment by awwbees** [comment]
if you hold shift while dragging, you can adjust more finely than normal mouse movement allows. you can also type in specific values if you type a number while hovered over the slider. additionally, you can tape math expressions into the slider, which may be useful for achieving specific musical values. note that the displayed number is rounded, and doesn't necessarily represent the precise value of the slider.
