### ISSUE TITLE
Can't interact after alt-tab

### ISSUE THREAD

**Issue by ThomLalcte** [BespokeSynth/BespokeSynth#286]
Hi,

At some point, mayby after I leave a menu or I alt-tab, I cant interact with anything with my mouse except for dragging the view. keyboard shortcuts dont work either. Clicking on the Icon to maximize the window does nothing.
However, when I hover over nodes, the tooltip shoe up.

I've had this issue on my laptop about every time I opened the app. My PC does not have the issue (tho I do not use it as much)

I dont know which system information you need so feel free to ask

**Comment by awwbees** [comment]
very likely the same issue as #123￼

**Comment by awwbees** [comment]
likely now fixed
