### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by symbioid** [BespokeSynth/BespokeSynth#287]
Using Windows 10 - 19043.1237

I downloaded and successfully ran bespoke, then the next day I attempted to run it and received a blank application.  No menu, nothing.  No interactivity, right or left click does nothing in the app.  The only thing I can do is windows control (minimize, close, etc).   I uninstalled a few weeks ago and decided to try again today.

I downloaded the latest version from the main bespoke page, and checked to make sure my graphics drivers are up to date.  Trying again now, I have the same issue.    I'm attaching a screen shot.  

No idea what might be causing this, any ideas?

EDIT: Also - please let me know if there are any logs or other info I can submit to assist in troubleshooting.  :)

![image](https://user-images.githubusercontent.com/52691141/135023435-63d9ebd9-ee3e-4aa6-8416-c1129f5c3415.png)

**Comment by awwbees** [comment]
I sent you this on Twitter, but it's easier to track it here:

￼that's a new one to me! what if you delete your "Documents/BespokeSynth/userprefs.json" file? and if that doesn't work, how about that whole directory?

**Comment by symbioid** [comment]
Thanks!  Deleting the userprefs.json did the trick! Cheers!
