### ISSUE TITLE
Wrong time position sent to VST3

### ISSUE THREAD

**Issue by jpcima** [BespokeSynth/BespokeSynth#289]
Hello, I received a problem report to sfizz VST3, about the plugin receiving wrong time position.
The plugin would non-stop reset its cc smoothing, because we do that as result of a jump in the time position.

The jump detection is triggered every cycle under Bespoke, because it seems to constantly send a time position which is 8 beats ahead of the expectation.

patch:
[2021-09-28_08-38.bsk.gz](https://github.com/BespokeSynth/BespokeSynth/files/7242867/2021-09-28_08-38.bsk.gz)

for reference:
https://github.com/sfztools/sfizz/blob/867cf2b459f8e2f5bf4a148538add2a95ad55ca8/src/sfizz/Synth.cpp#L1469-L1470

**Comment by baconpaul** [comment]
Heya @jpcima just FYI I think #336 will fix this. If you happened to have a moment to pull and test that’d be great. I tested with stochas and a test plugin I wrote but not quite sure how to test with sfizz

**Comment by jpcima** [comment]
I can't test immediately atm, this is a test SFZ that wouldn't smooth.
In a normal host, cc74 would sweep pitch 1 octave, with smoothing lasting for 1 second.
```
<region>
sample=*saw
pitch_oncc74=1200
pitch_smoothcc74=1000
```

**Comment by jpcima** [comment]
@baconpaul it's still failing, same issue. The beat position is still at a fixed offset after where it's expected to be.

**Comment by baconpaul** [comment]
OK which git version of bespoke did you build as of, and how do I confirm it?

**Comment by jpcima** [comment]
Currently I'm at fa8affd. Repro is as follows
- add sfizz, load bespoke.sfz file above
- play note and keep it down
- vary CC74 from 0 to 1 and vice-versa
Under an ordinary plugin host, the pitch would sweep,.

**Comment by baconpaul** [comment]
sigh. that bsk file on my mac ends up configured really weirdly and won't let me map my midi devices.

when i save that sfz file above and load it i get no sound. 

and i can't see where you even read ppqPosition in your codebase

so gonna need more help. What would really be useful is an sfz file which shows the problem and then i can load that into fizz and make a network. i feel like the sfz file above is missing something. like i said it makes no sound.

**Comment by jpcima** [comment]
>and i can't see where you even read ppqPosition in your codebase

The exact code is linked in the OP, it's a jump detection based on musical position.
That sfz misses nothing to make sound, plays here without trouble.

Attaching the exact file
[bespoke.sfz.gz](https://github.com/BespokeSynth/BespokeSynth/files/7304233/bespoke.sfz.gz)

I'll make a quick debug session inside bespoke to get an idea of what happens.

**Comment by baconpaul** [comment]
so @jpcima i'm trying to figure out what's wrong

first of all: at fa8affd the executable moved from build/Bespoke_artecfacts to build/Source/bespoke_artefacts so just want to be sure you are running the right code

I took `SfizzVstProcessor::updateTimeInfo` and augmented it as such

```
 if (context.state & context.kProjectTimeMusicValid) {
        double beats = context.projectTimeMusic * 0.25 * _timeSigDenominator;
        double bars = beats / _timeSigNumerator;
        beats -= int(bars) * _timeSigNumerator;

        std::cout << "ppqPos=" << context.projectTimeMusic << " ppqPosBarStart=" << context.barPositionMusic << " beats=" << beats << " bars=" << bars << " ppqPosBarStart * den / num =" << context.barPositionMusic * _timeSigDenominator / _timeSigNumerator << std::endl;
        synth.timePosition(0, int(bars), beats);
    }
```

basically adding that print statement. When I do and run bespoke at that git commit I see

```
ppqPos=35.6249 ppqPosBarStart=32 beats=3.62489 bars=8.90622 ppqPosBarStart * den / num =32
ppqPos=35.6764 ppqPosBarStart=32 beats=3.67644 bars=8.91911 ppqPosBarStart * den / num =32
ppqPos=35.728 ppqPosBarStart=32 beats=3.728 bars=8.932 ppqPosBarStart * den / num =32
ppqPos=35.7796 ppqPosBarStart=32 beats=3.77956 bars=8.94489 ppqPosBarStart * den / num =32
ppqPos=35.8311 ppqPosBarStart=32 beats=3.83111 bars=8.95778 ppqPosBarStart * den / num =32
ppqPos=35.8827 ppqPosBarStart=32 beats=3.88267 bars=8.97067 ppqPosBarStart * den / num =32
ppqPos=35.9342 ppqPosBarStart=32 beats=3.93422 bars=8.98356 ppqPosBarStart * den / num =32
ppqPos=35.9858 ppqPosBarStart=32 beats=3.98578 bars=8.99644 ppqPosBarStart * den / num =32
ppqPos=36.0373 ppqPosBarStart=36 beats=0.0373333 bars=9.00933 ppqPosBarStart * den / num =36
ppqPos=36.0889 ppqPosBarStart=36 beats=0.0888889 bars=9.02222 ppqPosBarStart * den / num =36
ppqPos=36.1404 ppqPosBarStart=36 beats=0.140444 bars=9.03511 ppqPosBarStart * den / num =36
ppqPos=36.192 ppqPosBarStart=36 beats=0.192 bars=9.048 ppqPosBarStart * den / num =36
ppqPos=36.2436 ppqPosBarStart=36 beats=0.243556 bars=9.06089 ppqPosBarStart * den / num =36
ppqPos=36.2951 ppqPosBarStart=36 beats=0.295111 bars=9.07378 ppqPosBarStart * den / num =36
ppqPos=36.3467 ppqPosBarStart=36 beats=0.346667 bars=9.08667 ppqPosBarStart * den / num =36
ppqPos=36.3982 ppqPosBarStart=36 beats=0.398222 bars=9.09956 ppqPosBarStart * den / num =36
```

etc... so there's no time jump, no 8 measure offset. 

That's the same thing I see when I use https://github.com/baconpaul/tempo-tester and that also matches reaper's behavior. 

So I sort of wonder. Are you sure sure you are running an executable built at head? What output do you expect at that code point?

**Comment by jpcima** [comment]
> so just want to be sure you are running the right code

I'm not running the right code.... let me test again

**Comment by baconpaul** [comment]
Yeah so i just tested at head and controller 74 acts like a pitch bend with that sfz here. So I think we are fixed!

**Comment by jpcima** [comment]
It's confirmed working. Very nice, thank you. hope it didn't waste too much of your time.

**Comment by baconpaul** [comment]
Hey I got to read the sfizz code! Wasn’t a waste at all. And super glad it worked :)
