### ISSUE TITLE
Linux weird click/drag issues

### ISSUE THREAD

**Issue by djdeath** [BespokeSynth/BespokeSynth#29]
I downloaded the last release build (https://github.com/awwbees/BespokeSynth/tree/v0.0004-pre) and gave it a try on Linux Ubuntu and I'm having weird click/drag issues.

Feels like some events get dropped and so sometimes a click-drag-release action will miss the release and keep dragging a component. Or click is missed and nothing happens.

What kind of environment have you tested with?

**Comment by awwbees** [comment]
I tested in ubuntu 18.04, but my macbook trackpad works terribly in linux (I think I need to install better drivers), so I wasn't able to get a real test of how things feel or notice any broken behavior like that. the test was more of a "ok, cool, it runs and makes sound!". I do wonder if it's related to the issue you link, are you able to compile on your own and test a debug build?

**Comment by djdeath** [comment]
Closing, it seems to be the same issue as #30.
