### ISSUE TITLE
textentry in pitchremap cannot be modulated

### ISSUE THREAD

**Issue by cmovvv** [BespokeSynth/BespokeSynth#292]
values within a pitchremap module currently can be connected to by a controlsequencer, but they are marked as "unimplemented" and are unaffected by changes to the controlsequencer values. request to add this functionality in a later update.

**Comment by NoxyNixie** [comment]
This seems to be working in the latest Nightly build:

![BespokeSynth_20230125_170411](https://user-images.githubusercontent.com/211381/214614036-1a849426-87fa-491a-8ecb-c379464af8d3.gif)
