### ISSUE TITLE
Missing vst\ directory not automatically created

### ISSUE THREAD

**Issue by Tarinaky** [BespokeSynth/BespokeSynth#294]
When running on Windows 10, the vst directory is not automatically created in ~/Documents/BespokeSynth.

If this directory is missing, it will prevent the creation of the files found_vsts.xml and deadmanspedal.txt as it will not be created automatically.

**Comment by Tarinaky** [comment]
In file https://github.com/BespokeSynth/BespokeSynth/blob/main/Source/VSTPlugin.cpp

Creation of the vst/ directory seems to occur as part of initialisation of class VSTPlugin, however writing of the xml and deadmanspedal files occur in function GetAvailableVSTs(). 

My guess is that   
`juce::File(ofToDataPath("vst")).createDirectory();` 
should be added to GetAvailableVSTs().

I think issues like https://github.com/BespokeSynth/BespokeSynth/issues/223 might be related to this one. If nothing else because the lack of deadmanspedal.txt to make end user debugging of problematic vsts easier.

**Comment by awwbees** [comment]
fixed in #298
