### ISSUE TITLE
v1.0.0 is missing CMakeLists.txt

### ISSUE THREAD

**Issue by magnetophon** [BespokeSynth/BespokeSynth#295]
When I checkout v1.0.0, there is no more CMakeLists.txt.
The head version does have it, but I'd like to package this for NixOS, and for that I'd prefer to use the release.

**Comment by KottV** [comment]
Then you have to use Projucer. Cmake was added after 1.0.0
But it's recommended to use HEAD.

**Comment by baconpaul** [comment]
Yeah @magnetophon i noticed the same with 1.0.0 which is why mvf and awwbees and kottv I did the cmake and juce 6 port 😀

**Comment by baconpaul** [comment]
(Also 1.0.0 builds against juce547 so has no linux vst3 support)

**Comment by KottV** [comment]
yep
and Projucer needs X server to regenerate Makefile. So...i think doesn't worth it :)

**Comment by baconpaul** [comment]
Yeah

**Comment by magnetophon** [comment]
Thanks!
Any chance of a new release to include the cmake port?

**Comment by magnetophon** [comment]
Ah, just got my answer in the chat:  yes!

**Comment by magnetophon** [comment]
Bespoke will soon be available in NixOS: https://github.com/NixOS/nixpkgs/pull/140158
