### ISSUE TITLE
Cant select ASIO audio (Motu M4), locks up Bespoke.

### ISSUE THREAD

**Issue by JohnnyTLuxury** [BespokeSynth/BespokeSynth#296]
Right off the bat after installing I selected my audio interface, I saved and closed. Reopened to the settings page and was stuck in limbo. Can't click on anything, just stuck. All I can do is open and close. I figured out what I did wrong, which was not changing the preset interface buffer size, default is 0, which is blatantly stupid. No interface has 0 as a buffer setting, most systems kick back ugly noise at 32. I would imagine a proper default would be 512, which like 99% of other audio software comes preset as. Still, my fault, I didn't check. But now, it's stuck, I've uninstalled it, reinstalled and it just opens to the same settings page with no way to navigate. Clicking any of the boxes does nothing.

EDIT: Ok, so this just led me thru a rabbit hole. A fewr issues: Apparently I cannot select ASIO audio (MOTU M4), it will only allow me to use windows audio @144ms buffer size. If I choose ASIO, I only get a 64 ms buffer size option (or 0 as the default) and then it's lock-up city no matter what. I restart and I can't do anything. Erasing the Userprefs files allows me to reset settings. Also, a red flag is uninstalling LEAVES the Bespoke files in User/documents (Windows) directory, maybe a few Mbs, but still useless clutter that should be deleted when u uninstall Bespoke.

**Comment by awwbees** [comment]
it's hard for me to pick out what the actual issue is from here
