### ISSUE TITLE
Linux build error [SOLVED]

### ISSUE THREAD

**Issue by davephillips** [BespokeSynth/BespokeSynth#3]
Greetings ! I've successfully built the VST2 plugin on Ubuntu 18.04 but haven't tested it yet. Now I'm attempting a Linux build of the standalone version on an old Fedora 23 system but I've run into an error. Btw, I created the Linux Makefile with JUCE Projucer, in which I left the format at the Default (GUI Application) selection, i.e. I didn't select any plugin build. 

Here's the build error, please advise if there's a fix: 

```
Compiling VSTPlugin.cpp
../../Source/VSTPlugin.cpp: In member function ‘void VSTPlugin::SetVST(std::__cxx11::string)’:
../../Source/VSTPlugin.cpp:205:18: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<juce::AudioProcessor>’ and ‘juce::AudioPluginInstance*’)
          mPlugin = mFormatManager.getFormat(i)->createInstanceFromDescription(desc, gSampleRate, gBufferSize);
                  ^
In file included from /usr/include/c++/5.3.1/memory:81:0,
                 from ../../../JUCE/modules/juce_core/system/juce_StandardHeader.h:46,
                 from ../../../JUCE/modules/juce_core/juce_core.h:201,
                 from ../../../JUCE/modules/juce_audio_basics/juce_audio_basics.h:52,
                 from ../../Source/../JuceLibraryCode/JuceHeader.h:17,
                 from ../../Source/SynthGlobals.h:12,
                 from ../../Source/ChannelBuffer.h:12,
                 from ../../Source/IAudioReceiver.h:12,
                 from ../../Source/IAudioProcessor.h:13,
                 from ../../Source/VSTPlugin.h:12,
                 from ../../Source/VSTPlugin.cpp:9:
/usr/include/c++/5.3.1/bits/unique_ptr.h:249:7: note: candidate: std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = juce::AudioProcessor; _Dp = std::default_delete<juce::AudioProcessor>]
       operator=(unique_ptr&& __u) noexcept
       ^
/usr/include/c++/5.3.1/bits/unique_ptr.h:249:7: note:   no known conversion for argument 1 from ‘juce::AudioPluginInstance*’ to ‘std::unique_ptr<juce::AudioProcessor>&&’
In file included from /usr/include/c++/5.3.1/memory:81:0,
                 from ../../../JUCE/modules/juce_core/system/juce_StandardHeader.h:46,
                 from ../../../JUCE/modules/juce_core/juce_core.h:201,
                 from ../../../JUCE/modules/juce_audio_basics/juce_audio_basics.h:52,
                 from ../../Source/../JuceLibraryCode/JuceHeader.h:17,
                 from ../../Source/SynthGlobals.h:12,
                 from ../../Source/ChannelBuffer.h:12,
                 from ../../Source/IAudioReceiver.h:12,
                 from ../../Source/IAudioProcessor.h:13,
                 from ../../Source/VSTPlugin.h:12,
                 from ../../Source/VSTPlugin.cpp:9:
/usr/include/c++/5.3.1/bits/unique_ptr.h:269:2: note: candidate: template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::is_convertible<typename std::unique_ptr<_Up, _Ep>::pointer, typename std::unique_ptr<_Tp, _Dp>::_Pointer::type>, std::__not_<std::is_array<_Up> > >::value, std::unique_ptr<_Tp, _Dp>&>::type std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Up = _Up; _Ep = _Ep; _Tp = juce::AudioProcessor; _Dp = std::default_delete<juce::AudioProcessor>]
  operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
  ^
/usr/include/c++/5.3.1/bits/unique_ptr.h:269:2: note:   template argument deduction/substitution failed:
../../Source/VSTPlugin.cpp:205:18: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘juce::AudioPluginInstance*’
          mPlugin = mFormatManager.getFormat(i)->createInstanceFromDescription(desc, gSampleRate, gBufferSize);
                  ^
In file included from /usr/include/c++/5.3.1/memory:81:0,
                 from ../../../JUCE/modules/juce_core/system/juce_StandardHeader.h:46,
                 from ../../../JUCE/modules/juce_core/juce_core.h:201,
                 from ../../../JUCE/modules/juce_audio_basics/juce_audio_basics.h:52,
                 from ../../Source/../JuceLibraryCode/JuceHeader.h:17,
                 from ../../Source/SynthGlobals.h:12,
                 from ../../Source/ChannelBuffer.h:12,
                 from ../../Source/IAudioReceiver.h:12,
                 from ../../Source/IAudioProcessor.h:13,
                 from ../../Source/VSTPlugin.h:12,
                 from ../../Source/VSTPlugin.cpp:9:
/usr/include/c++/5.3.1/bits/unique_ptr.h:278:7: note: candidate: std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = juce::AudioProcessor; _Dp = std::default_delete<juce::AudioProcessor>; std::nullptr_t = std::nullptr_t]
       operator=(nullptr_t) noexcept
       ^
/usr/include/c++/5.3.1/bits/unique_ptr.h:278:7: note:   no known conversion for argument 1 from ‘juce::AudioPluginInstance*’ to ‘std::nullptr_t’
../../Source/VSTPlugin.cpp: In member function ‘virtual void VSTPlugin::Poll()’:
../../Source/VSTPlugin.cpp:279:98: warning: ‘virtual float juce::AudioProcessor::getParameter(int)’ is deprecated [-Wdeprecated-declarations]
          mParameterSliders[i].mValue = mPlugin->getParameter(mParameterSliders[i].mParameterIndex);
                                                                                                  ^
In file included from ../../../JUCE/modules/juce_audio_processors/juce_audio_processors.h:113:0,
                 from ../../Source/../JuceLibraryCode/JuceHeader.h:20,
                 from ../../Source/SynthGlobals.h:12,
                 from ../../Source/ChannelBuffer.h:12,
                 from ../../Source/IAudioReceiver.h:12,
                 from ../../Source/IAudioProcessor.h:13,
                 from ../../Source/VSTPlugin.h:12,
                 from ../../Source/VSTPlugin.cpp:9:
../../../JUCE/modules/juce_audio_processors/processors/juce_AudioProcessor.h:1015:19: note: declared here
     JUCE_DEPRECATED (virtual float getParameter (int parameterIndex));
                   ^
../../Source/VSTPlugin.cpp: In member function ‘virtual void VSTPlugin::FloatSliderUpdated(FloatSlider*, float)’:
../../Source/VSTPlugin.cpp:512:97: warning: ‘virtual void juce::AudioProcessor::setParameter(int, float)’ is deprecated [-Wdeprecated-declarations]
          mPlugin->setParameter(mParameterSliders[i].mParameterIndex, mParameterSliders[i].mValue);
                                                                                                 ^
In file included from ../../../JUCE/modules/juce_audio_processors/juce_audio_processors.h:113:0,
                 from ../../Source/../JuceLibraryCode/JuceHeader.h:20,
                 from ../../Source/SynthGlobals.h:12,
                 from ../../Source/ChannelBuffer.h:12,
                 from ../../Source/IAudioReceiver.h:12,
                 from ../../Source/IAudioProcessor.h:13,
                 from ../../Source/VSTPlugin.h:12,
                 from ../../Source/VSTPlugin.cpp:9:
../../../JUCE/modules/juce_audio_processors/processors/juce_AudioProcessor.h:1132:18: note: declared here
     JUCE_DEPRECATED (virtual void setParameter (int parameterIndex, float newValue));
                  ^
Makefile:1384: recipe for target 'build/intermediate/Release/VSTPlugin_33bc53cb.o' failed
make: *** [build/intermediate/Release/VSTPlugin_33bc53cb.o] Error 1
```

**Comment by awwbees** [comment]
I've never built for Linux and don't currently have access to a Linux machine, so I'm not sure of the proper fix... but, as is Bespoke is not set up properly to scan for VSTs on Linux, so you could merely comment that line out to compile. That will prevent you from hosting VSTs, but you're not losing out since Bespoke doesn't currently support VSTs on Linux anyway.

(note: it's likely trivial work to add Linux VST support, given a Linux machine to test on)

**Comment by davephillips** [comment]
@awwbees - I started over with a fresh pull. I had to make some additions to the Jucer file and I had to make a few minor changes in the source code, mostly to accommodate my ancient compiler (GCC 5.3.1). I will detail those changes later but I thought I'd share this screenshot of your synth running (and sounding) on Fedora 23 Linux: 

![bespoke-firstlinuxview](https://user-images.githubusercontent.com/7815938/73601960-d018e900-4538-11ea-8000-26456cf8b9e8.png)

**Comment by davephillips** [comment]
A few notes re: building for Linux on Fedora 23 with GCC 5.3.1

Changes to BespokeSynth.jucer:
```
Added Linux Makefile to Exporters
Added GLEW_STATIC and GL_GLEXT_PROTOTYPES to Extra Preprocessor Definitions 
Added ../../Source/json/include and ../../Source/glew/include to Header Search Paths for Debug and Release configs
Added path to VST2 SDK to Global Paths
```

In ModularSynth.cpp:
```
Changed INT_MAX to INT8_MAX
```

In LinnstrumentControl.h:
```
Added <unistd.h> to includes
```

In Sample.cpp:
```
- 125
+ 125 bool b1 {nullptr}; 
- 126 ScopedPointer<AudioFormatWriter> writer = wavFormat->createWriterFor(outputTo, gSampleRate, channels, 16, nullptr, 0);
+ 126 ScopedPointer<AudioFormatWriter> writer = wavFormat->createWriterFor(outputTo, gSampleRate, channels, 16, b1, 0);
```

As per the README, I adjusted the buffer size and sample rate in userprefs.json to match my settings for Jack. Audio output is now clean and clear. I have not tested MIDI at all yet, nor have I tested the VST version.

After building I placed the binary and data files in $(HOME)/BespokeSynth/. The binary runs from the top level. Btw, I retrieved the ./data files from the zipfile for the Mac binary. Maybe they can be packaged somewhere for Windows and Linux as well ?

**Comment by awwbees** [comment]
amazing work! that's great news that no major changes were necessary to get things running in linux. I should integrate these changes in, this might be the push I need to set up a linux install so I can test it out.

**Comment by davephillips** [comment]
@awwbees - Thank you, it was an easy job with JUCE and Google. Btw, I rebuilt the VST2 on Fedora 23 and tried to test it with Bitwig 2.3.5. Alas, it won't scan and/or load. I'll test it with other DAWs today, will try to get a detailed report and debug the error. And Thank You for the cool synth and for making it an open-source project. :)

**Comment by awwbees** [comment]
I have never built Bespoke as a VST before (though it is on my list as a future thing I'd like to do!), so it is not too surprising that it is busted. I am sure that there is some extra code that will be necessary to make it function properly as a VST.

**Comment by davephillips** [comment]
I'll bang on it for a while. I need better logs from the hosts, I know that Bitwig has some good reporting, not sure about Reaper. That might point towards the problem. If a solution looks do-able I'll take a few swings at it. :)

**Comment by davephillips** [comment]
@awwbees - Thanks to your latest changes I can now load and run some VSTs within BespokeSynth. The OxeFM synth works perfectly, including the GUI open/close. The u-he Triple Cheese synth plays and switches its presets correctly, but without GUI. U-he's TyrellN6 works but doesn't show its GUI and can't switch presets. I'll continue to test more plugins and try to debug problems.

[Edit] Okay, I forgot to install the data & resource files for the u-he plugins. Their GUIs display correctly now but for some reason those plugins halt the transport. More to look into.

[Edit] Resolved the u-he problem, apparently multiple instances of the plugin caused a bad reaction. Deleted the extras, I now have u-he plugins for native Linux running in BespokeSynth. Very cool.

**Comment by awwbees** [comment]
fantastic! I should be re-adding some old VST support soon, where you can adjust/modulate the VST parameters directly on the Bespoke module (rather than needing to use the VST's GUI), which should open a lot of possibilities. I had that working a few years ago, but it was broken when a JUCE API changed. it shouldn't be too hard to hook it back up.

also, I believe VST3 is currently broken across all platforms, but I think I just need a few small changes to fix that

**Comment by davephillips** [comment]
This addition to ModularSynth.h

`#include <limits.h>`

will fix any errors with a missing INT_MAX.

Best,

dp

**Comment by sonata-chen** [comment]
@davephillips - Hey, I followed your instructions to build the standalone application on linux. Everything is OK, but I got another error when compiling `OpenFrameworksPort.cpp` and `MainComponent.cpp`. 

There are some undeclared OpenGL functions. When compiling on Microsoft Windows, `glew.h` will be included, how about linux? How did you fix that?

**Comment by davephillips** [comment]
@sonata-chen - Can you post the error messages ?

**Comment by sonata-chen** [comment]
@davephillips - Well, I'm so stupid. I forgot to define `GL_GLEXT_PROTOTYPES` macro. Now, I can build the binary, but there is a runtime error when I try to execute the program.

Error Messages:

```
JUCE v5.4.5
Shader shader/vert error:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Shader shader/vert error:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Could not init nanovg.
Could not init font bounds nanovg.
Segmentation fault (core dumped)
```

any ideas? thanks.

[Edit] Solved, see [below](#issuecomment-587248429).

**Comment by davephillips** [comment]
@sonata-chen - Perhaps your OpenGL is outdated ? What Linux distro are you running ?

**Comment by sonata-chen** [comment]
> What Linux distro are you running ?

@davephillips 

Manjaro which is based on Arch Linux

**Comment by sonata-chen** [comment]
> Error Messages:
> 
> ```
> JUCE v5.4.5
> Shader shader/vert error:
> 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
> 
> Shader shader/vert error:
> 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
> 
> Could not init nanovg.
> Could not init font bounds nanovg.
> Segmentation fault (core dumped)
> ```
> 

Finally, I found the solution at [here](https://github.com/google-research/football/issues/7). Simply set an environment variable before running the program. `MESA_GL_VERSION_OVERRIDE=3.2 ./BespokeSynth` works for me.

----
P.S.
* GCC version: 9.2.0
* Linux distribution: Manjaro (kernel: 5.4.18-1-MANJARO)
* Output of `glxinfo | grep OpenGL`:
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
OpenGL core profile version string: 4.6 (Core Profile) Mesa 19.3.3
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 19.3.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by davephillips** [comment]
@sonata-chen - I'm glad to hear you got it working. My apologies for not replying earlier, I've been busy setting up a new system, it took more time than I expected.

**Comment by sonata-chen** [comment]
@davephillips It's OK. Thanks for your replies. Good work!

**Comment by mxmilkiib** [comment]
I'm looking to build from scratch so as to possibly get BespokeSynth in the AUR. (I can't find the previous copy I had or quite remember how far in building I got :)

How far from "here is the set of steps/commands to run to get from clone to a completed build on Linux" might we be?

Currently, running `make` in the Linux Makefile dir gives:
```
Compiling JuceToPush2DisplayBridge.cpp
In file included from ../../Source/push2/push2/JuceToPush2DisplayBridge.h:24,
                 from ../../Source/push2/push2/JuceToPush2DisplayBridge.cpp:21:
../../JuceLibraryCode/../JuceLibraryCode/JuceHeader.h:17:10: fatal error: juce_audio_basics/juce_audio_basics.h: No such file or directory
   17 | #include <juce_audio_basics/juce_audio_basics.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:398: build/intermediate/Debug/JuceToPush2DisplayBridge_9a62e852.o] Error 1
```

**Comment by awwbees** [comment]
can't give you a full set of steps right now, but I can give a high level:

instead of using the Makefile (which I probably shouldn't have included in the depot), I'd recommend installing JUCE and then generating the Makefile yourself using the "Projucer". `BespokeSynth.jucer` is the project file you'll want to load up. installing JUCE will also fix the compilation issue you're encountering, which is complaining because it can't find JUCE headers.

additionally, there are some dependencies you'll want to install. I haven't fully streamlined this list, so it might be overkill, but I think it should cover you:
https://github.com/awwbees/BespokeSynth/blob/master/Builds/LinuxMakefile/build/bespoke_dependencies.sh

**Comment by mxmilkiib** [comment]
Aaah, yes, the opening and resaving in Projucer thing is the blocker.

JUCE 6 will be doing away with that which is good.

There was a [patch](https://github.com/jpcima/juce-linux-patches) for an older version of JUCE, jpcima thinks it's probably out-of-date.

I think though waiting for JUCE 6 to come out would be the best option.

Thanks for the further details, that'll make putting a package together easier later.
