### ISSUE TITLE
Framerate locked at 32 fps on Linux

### ISSUE THREAD

**Issue by pushqrdx** [BespokeSynth/BespokeSynth#309]
For some reason Bespoke runs extremely poor for me on X11/Openbox with or without compositor on intel igpu. Fps is locked at 32

**Comment by KottV** [comment]
"intended" https://github.com/BespokeSynth/BespokeSynth/issues/30
**sometimes** Bespoke lose clicks with full FPS
i think it should keep opened

**Comment by pushqrdx** [comment]
@KottV well, it's very jarring, there's even some weird motion blur happening while panning that makes it worse

**Comment by pushqrdx** [comment]
@KottV well, it's very jarring, there's even some weird motion blur happening while panning that makes it worse

**Comment by KottV** [comment]
blur is the feature

**Comment by KottV** [comment]
you can remove `|| BESPOKE_LINUX` in https://github.com/BespokeSynth/BespokeSynth/blob/f19dd06302385b4be31af7c0d515a9a1d56a6e40/Source/MainComponent.cpp#L131

recompile, and see how it works

**Comment by pushqrdx** [comment]
> blur is the feature

it would be yeah if it were running 60fps

**Comment by KottV** [comment]
Ok. What means "extremely poor"? Is it just the value ~30 fps confuses, or there are visual dropouts?

**Comment by pushqrdx** [comment]
@KottV running at 30fps with motion blur (without knowing that it's actually intended) gave the impression that the UI is performing badly, i thought it might even be something wrong with my drivers. I think at least a note should be added to the readme that on Linux it's expected to run at 30fps temporarily until the input issue is fixed

**Comment by pushqrdx** [comment]
@KottV ok i built from source and renabled 60fps, and yes i found the dropped input bug you referenced, however here's a nice workaround. Just run bespoke with this
```
LIBGL_DRI3_DISABLE=true LIBGL_DRI2_DISABLE=true ./BespokeSynth
```
This also works
```
LIBGL_ALWAYS_SOFTWARE=true ./BespokeSynth
```

idk why would software render or disabling dri get around the input dropping issue but at least it works at 60fps

**Comment by KottV** [comment]
thanks for the info, i'll try that too
i think we need someone with OpenGL knowledge here :)

**Comment by unfa** [comment]
Hey! I also would like to see Bespoke run at 60 FPS.

Plus I've had some strange audio lags and dropouts while using it on my recent livestream (not sure if it's related):

https://youtu.be/mh66PG_LeEM?t=4725

**Comment by pushqrdx** [comment]
> Hey! I also would like to see Bespoke run at 60 FPS.
> 
> Plus I've had some strange audio lags and dropouts while using it on my recent livestream (not sure if it's related):
> 
> https://youtu.be/mh66PG_LeEM?t=4725

@unfa Been fiddling around to see what might be the root cause of this issue and it seems like (though not sure) something is causing the CPU to be too busy to handle input events, based on that i wouldn't be surprised that audio is also affected. It looks like a mesa problem related to batch rendering but i am not sure where in the stack is it triggered

**Comment by unfa** [comment]
@pushqrdx My system was under load as I was streaming live - but my CPU usage was quite low (20% tops IIRC). I run on a Ryzen 9 3900X, so there's a lot of cores to spare, maybe something is starving because it's not multithreaded?
For a short while I opened `btop` on the stream to see what causes the dropouts, I can't find the exact moment though...

**Comment by pushqrdx** [comment]
@unfa i submitted [a fix](349). Been playing with bespoke for a bit now and haven't noticed any audio dropouts so far, Make sure that you have realtime priority given to pipewire, one problem that you might have is RTKIT setting low hard limit on the priority pipewire has, making pipewire xrun even at low cpu utilization.
