### ISSUE TITLE
multiple bugs on presets module

### ISSUE THREAD

**Issue by severak** [BespokeSynth/BespokeSynth#331]
- it's not possible to connect multiple things to one `presets` module (the circle shows a + on hover, but dragging from it does nothing)
- it's not possible do disconnect existing cable from `presets` module or reroute it (you need to delete whole `presets` module)
- maybe we should have *save preset* button in addition to shift+click saving (this will be more obvious)

**Comment by NoxyNixie** [comment]
All of these points have been fixed and are available in the latest Nightly build. The save button is named `add`.
