### ISSUE TITLE
[Feature Request] Add project name to the end of the recording filename

### ISSUE THREAD

**Issue by spectromas** [BespokeSynth/BespokeSynth#338]
It would be great if you could distinguish which project a recording came from. I like the current filename but perhaps the option to addend the project name at the end would be useful. I think an option for preappend or append would be great, both are handy but personally I prefer append if it has to be only one.

**Comment by asmw** [comment]
I will take a look at his, sounds like a good idea

**Comment by asmw** [comment]
Should be in the next version then :)

**Comment by spectromas** [comment]
Thanks @asmw, that's amazing!
