### ISSUE TITLE
Will Bespoke run on (old) OS X El Capitan? (10.11)

### ISSUE THREAD

**Issue by kosso** [BespokeSynth/BespokeSynth#340]

**Comment by awwbees** [comment]
I'm not sure, I don't have an El Cap machine to test on. you might want to attempt to build from source, from the instructions at the bottom of the readme.

**Comment by mvf** [comment]
It should *run* on 10.11 "El Capitan", but *building* requires at minimum 10.13 "High Sierra". We just had confirmation on Discord that it definitely won't build (out of the box) on 10.12 "Sierra".

**Comment by asmw** [comment]
@kosso is your question answered?

**Comment by NoxyNixie** [comment]
I'm going to assume this question has been answered. If not feel free to reply to this issue and it will be reopened or post a new one ;)
