### ISSUE TITLE
"Couldn't load font" error when opening bsk on Windows via double click

### ISSUE THREAD

**Issue by justSatyr** [BespokeSynth/BespokeSynth#354]
I haven't been able to fully figure out where this is coming from but if a patch is saved on a mac os copy of Bespoke and then you try and open in on a windows machine by double-clicking the file you get the error:

"Couldn't load font from C:/Users/USERNAME/MacOSX/build/Release/resource/frabk.tff"

Where USERNAME is the username you are logged into. Strangely, opening up Bespoke and loading the same file from the "Load" button seems to work fine.

I thought maybe it was just me but I have seen at least one other person on the discord run into the same inssue.
![Screenshot 2021-10-06 194714](https://user-images.githubusercontent.com/8130125/136298693-b4d2469d-d6e1-4ce2-a8bb-3d47c0d5436e.png)

**Comment by baconpaul** [comment]
right this means that bespoke doesn't launch from the directory with its resources. we don't do a very good job on windows of finding the resources search path to look up that directory.
