### ISSUE TITLE
Write Midi Sequencer to a MIDI fille and play a MIDI file ?

### ISSUE THREAD

**Issue by felipeinfantino** [BespokeSynth/BespokeSynth#371]
Is it possible to save some midi data produced by the Drum sequencer into a MIDI file?

Is it possible to import a MIDI file and play it?

Thanks a lot for this software!

**Comment by felipeinfantino** [comment]
Or maybe from a note stream. Something like a record Midi , stop midi, filepath

**Comment by nak21** [comment]
I'm wondering the same as felipeinfantino. 
Midi file import/export would be awesome!

**Comment by gusmccallum** [comment]
Hi I'd like to work on this, can you please assign it to me?

**Comment by NoxyNixie** [comment]
In the latest Nightly build you can record the notes from a `drumsequencer` into the `notecanvas`  module which has the option to save and load midi:

![image](https://user-images.githubusercontent.com/211381/214623914-4372c5f4-c55f-4200-8504-95864d2e5130.png)
