### ISSUE TITLE
Pulse Train fires first two pulses at the same time

### ISSUE THREAD

**Issue by ghost** [BespokeSynth/BespokeSynth#377]
When receiving a pulse, the pulse train seems to be triggering the first two pulses at the same time. I checked out the pulse train code, and from what i can tell, it might be processing both the pulse and the time event simultaneously

![bugpulsetrain](https://user-images.githubusercontent.com/2838883/136711716-420a866e-ce58-45f8-842e-fbd28c6c2057.gif)

**Comment by GekkieHenkie** [comment]
Additional observation:
When 'reset' is clicked in 'transport', the second pulse of the pulsetrain is triggered correctly as expected, but only on the first loop. While the train keeps looping, every subsequent loop 'skips' the second pulse again (and triggers it together with the first pulse as described in this bug's opening post). Every time 'reset' is clicked in 'transport', the second pulse gets correctly fired on its first loop.

## Build:
bespoke 1.1.0 (Sep 15 2022 20:52:56) - Linux - makepkg 0acb8ebf

**Comment by NoxyNixie** [comment]
> bespoke 1.1.0 (Sep 15 2022 20:52:56) - Linux - makepkg [0acb8eb](https://github.com/BespokeSynth/BespokeSynth/commit/0acb8ebff6e59f8b000da240e11f31ccee9cca72)

Can you try with the latest Nightly build?

There have been some significant timing changes since the build you are using.

**Comment by NoxyNixie** [comment]
I am unable to reproduce this in the latest Nightly build:

![BespokeSynth_20230125_174850](https://user-images.githubusercontent.com/211381/214625884-0d47aa10-a6d7-4dfe-bda4-17ec644ff883.gif)

If this problem returns feel free to post on this issue and it will be reopened or create a new one ;)
