### ISSUE TITLE
Vst's not loaded when saving and reopening prefab

### ISSUE THREAD

**Issue by dmt-hub** [BespokeSynth/BespokeSynth#395]
When creating a prefab with some vsts inside, it doesnt reload correctly.
Some vsts are not loaded inside the prefab.

**Comment by awwbees** [comment]
this is a very vague report, can you provide more specifics? it works fine for me when I do this:
1. create a VST
2. change some VST parameters
3. put the VST in a prefab
4. save the prefab
5. load in that saved prefab

if you provide more specifics, maybe it will help me to figure out what is going wrong for you.

**Comment by dmt-hub** [comment]
Sorry for the vague description.

1. Put 6 different VSTS (doesnt matter which ones) inside a prefab
3. Save the prefab
4. Close Bespokesynth
5. Open Bespokesynth
6. Load the said prefab
7. problem: some vsts are loaded correctly, some are just not loaded and i get empty modules.

https://imgur.com/a/rB5h6YE

**Comment by dmt-hub** [comment]
https://imgur.com/a/rB5h6YE

**Comment by awwbees** [comment]
thank you for the further details! I still can't reproduce the issue in a quick test, but I will try more variations later.

**Comment by dmt-hub** [comment]
this issue has been resolved.
