### ISSUE TITLE
The "sustainpedal" module doesn't send the same note if it's already sustained.

### ISSUE THREAD

**Issue by dertasiu** [BespokeSynth/BespokeSynth#403]
If I attach a "midicontroller" to a "sustainpedal" module and patch the 64 midi cc to the "sustain" checkbox on the "sustainpedal", I can't send the same sustained note twice unless I deactivate and reactivate the "sustain" checkbox.
For example, if the "sustain" checkbox is enabled and I press the C key twice, it will only sound the first time.

Tried on [07dd70b](https://github.com/BespokeSynth/BespokeSynth/commit/07dd70bb5925db271d59bd1805941fe86e13400e) commit, Linux with VST enabled and the Linux high FPS patch.

**Comment by awwbees** [comment]
oh interesting, it looks like I did this intentionally, but I can't remember why:
`if (!mIsNoteBeingSustained[pitch]) //don't replay already-sustained notes`

if you comment out this line (line 73 of SustainPedal.cpp), does that give the behavior you expect?

**Comment by dertasiu** [comment]
I didn't saw that line, my bad.
I've created a pull request (#411) with a checkbox to allow bypassing the current behavior.
Thank you!

**Comment by awwbees** [comment]
fixed by #438
