### ISSUE TITLE
Crash when loading "example__scripting.bsk"

### ISSUE THREAD

**Issue by andrew-aaron** [BespokeSynth/BespokeSynth#410]
As soon as I try to load "example__scripting.bsk" Bespoke crashes. 
When re-loading Bespoke, the samplerate and buffersize cannot be set, forcing me to switch my Roland Octacapture off and on again. Python 3.8 is installed.

[crash_2021-10-16_02-06.txt](https://github.com/BespokeSynth/BespokeSynth/files/7354258/crash_2021-10-16_02-06.txt)

**Comment by baconpaul** [comment]
In a fresh bespoke, can you load the script module? Does it say "click to use python"? If you click to use python can you then in a fresh bespoke load the example?

There was a bug in bespoke 1.0 where loading a bsk assumes python even if it isn't set up and it sounds like you may be hitting it.

**Comment by andrew-aaron** [comment]
I didn't see "click to use Python" but I loaded a script. The "example__scripting.bsk" now loads. I don't fully understand why as I used the "drumsynth_randomize.py" script last night.. shouldn't that have done the same thing?
Anyway, I consider this resolved. Thank you!
