### ISSUE TITLE
MIDI clock + start / stop out to external device

### ISSUE THREAD

**Issue by initialed85** [BespokeSynth/BespokeSynth#417]
Hi @awwbees,

Love the product, having a lot of fun tinkering with it.

I've got a Behringer RD8 that I'm able to interact with via MIDI using the drum sequencer in Bespoke.

This gives me a fair bit of flexibility in that I can control how all the sounds are delivered using the HMI on the RD8 but for any sequence changes I need to use Bespoke.

For jamming, it'd be pretty awesome if I could get the RD8 to take the clock and start/stop state from Bespoke so I can use the RD8 while jamming in its entirety alongside anything I've got coming out of Bespoke.

I'm not at all experienced with MIDI (or any of this really) but I _think_ it would mean being able to send some system real-time messages related to the Bespoke's state:

- Start / Restart = 250
- Stop / Pause = 252
- Continue = 251
- Clock = 248

If this request is covered under the functionality coming that'll solve https://github.com/BespokeSynth/BespokeSynth/issues/178 then happy for you to just close this issue.

**Comment by awwbees** [comment]
the latest bespoke nightly build (https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly) now has midi clock in/out! check out the `clockin` and `clockout` modules.
