### ISSUE TITLE
Unable to get audio input working

### ISSUE THREAD

**Issue by initialed85** [BespokeSynth/BespokeSynth#418]
Hi @awwbees,

Having heaps of fun with Bespoke- decided I want to feed my hardware instruments back into it so I can play with some cool filters.

Unfortunately I can't seem to get anything to come out of the audio input module. Here's how I'm testing:

![image](https://user-images.githubusercontent.com/5491690/137619224-273314c5-2ed7-498a-ab61-a34edef7fa77.png)

(Green and red just to clarify what does and doesn't work).

With that setup, I'm able to record using Quicktime and the levels seem fine I think (test recording at https://drive.google.com/file/d/1SctpV-tjwMTPtjd8jF3Q1DuYcRBafc61/view?usp=sharing if that helps at all).

My Bespoke settings look like this:

![image](https://user-images.githubusercontent.com/5491690/137619385-2ac34b65-c960-4c1d-955e-fe72d04c5f40.png)

And the workspace looks like this:

![image](https://user-images.githubusercontent.com/5491690/137619418-4d690579-359f-4ed2-8ac9-519f1864ed26.png)

MacBook details:

![image](https://user-images.githubusercontent.com/5491690/137619487-422b2434-7a79-431b-9893-26abb2810497.png)

MacOS details:

![image](https://user-images.githubusercontent.com/5491690/137619581-3287e7ab-8e00-4409-aff5-56487f790a4b.png)

And USB sound card details:

![image](https://user-images.githubusercontent.com/5491690/137619527-fef65a2e-155a-4fab-bf44-2ddfc5b957b6.png)

Any ideas? I couldn't see anything obvious that I've missed in the doco.

**Comment by awwbees** [comment]
it sounds like you're encountering issue #116, which is fixed for the next release, or if you build from source. there's also a workaround at the bottom of that issue discussion which might work for you.
