### ISSUE TITLE
How to use SF2?

### ISSUE THREAD

**Issue by mnn** [BespokeSynth/BespokeSynth#419]
I saw this issue - https://github.com/BespokeSynth/BespokeSynth/issues/255, so I installed sfizz which supposedly supports SF2 (I am beginner in music software). But it doesn't show up in "vst plugins:", even after several rescanning and dozen of times closing and reopening the application.

I see in a console that Bespoke found the files, but for some reason it didn't load them nor reported an error:

```
<> ./BespokeSynth
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Attempting to load VST: /usr/lib/vst3/sfizz.vst3/Contents/x86_64-linux/sfizz.so
Attempting to load VST: /usr/lib64/vst3/sfizz.vst3/Contents/x86_64-linux/sfizz.so
```

That's an output from a launch, one click on rescan vsts and exit.

Manjaro
Bespoke 1.0.0 (downloaded from releases)
sfizz 1.0.0-1 (Manjaro community repo)

**Comment by KottV** [comment]
>Bespoke 1.0.0 (downloaded from releases)

this version has not vst3 support
you need to compile Bespoke by yourself or use 3rd party builds (for example https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth Arch package)

**Comment by mnn** [comment]
Tried the linked package and it doesn't work at all. It instantly crashes.

```
$ BespokeSynth
terminate called after throwing an instance of 'std::runtime_error'
  what():  Application directory not found. Please reinstall Bespoke.
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
$
```

Package in AUR is broken as well. :disappointed: 

```
Hunk #3 FAILED at 556.
1 out of 3 hunks FAILED -- saving rejects to file Source/CMakeLists.txt.rej
patching file libs/CMakeLists.txt
Hunk #1 FAILED at 8.
1 out of 1 hunk FAILED -- saving rejects to file libs/CMakeLists.txt.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
error making: bespokesynth-git
```

**Comment by KottV** [comment]
linked package is fixed now, please reinstall
thnx for pointing :)
