### ISSUE TITLE
"fubble" macro conns still on old position visible after collapse modules + "send" conns unvisible when collapse

### ISSUE THREAD

**Issue by cxbignekoc** [BespokeSynth/BespokeSynth#420]
-Version 1.00 
-win 10

1. macrosilder connectors from fubble connected to karplus synth´s biquad:**Q** and **F** are still visible on the old possition after collapse module
2. all connectors from the "send" module, from oscillator, lost the visibility after collapse the send module (but is still connected)

or is it a feature ??
![bespoke](https://user-images.githubusercontent.com/31941245/137637171-03ee9412-e471-4d7a-b7a4-f0bbac860552.png)

**Comment by NoxyNixie** [comment]
I believe part of this issue has been resolved in: 794a498e9c44ee63cb09f7afed6d3ea12e05c1d3
