### ISSUE TITLE
Add some example files in share/bespokesynth/examples

### ISSUE THREAD

**Issue by ycollet** [BespokeSynth/BespokeSynth#425]
To help people learn about how to use extensively bespokesynth, add some example files in share/bespokesynth/examples.

**Comment by OleksiySitka** [comment]
I assume that you are talking about linux. There are some examples already in ~/Documents/BespokeSynth/savestate

**Comment by ycollet** [comment]
Argh ! Thanks for the link.
These files are also in the source repository.
I close the ticket !
Thanks a lot again.
