### ISSUE TITLE
Mouse pointer is mapping to ten or so pixels upper left

### ISSUE THREAD

**Issue by ChunkieSpooner** [BespokeSynth/BespokeSynth#436]
Hi, I've just tried Bespoke for the first time, but I can't even join one synth to the output because I literally can't click on the circle at the bottom of the synth. If I really zoom in a long way, I can eventually get the circle to highlight, but this is when my mouse pointer is pointing about 10 pixels or more above and to the left of the actual circle! When I move my pointer in lists of synths, it highlights the one 10 pixels below the end of the mouse pointer too. 
I am using an HP EliteDesk 800 G1 USDT computer, so it's completely standard. 
Bespoke looks amazing though, thank you for all your hard work on it, let's hope I can use it one day!

**Comment by awwbees** [comment]
which OS?

**Comment by thorwil** [comment]
I have the same issue. Linux / Ubuntu Unity 21.10, my own build of 88f1f1375da346e1a83fc8e794b3a30e01d2db85 since the release lacked CMakeLists.txt.

**Comment by KottV** [comment]
> I have the same issue. Linux / Ubuntu Unity 21.10, my own build of [88f1f13](https://github.com/BespokeSynth/BespokeSynth/commit/88f1f1375da346e1a83fc8e794b3a30e01d2db85) since the release lacked CMakeLists.txt.

It's on Wayland or X11? Which GPU?

**Comment by thorwil** [comment]
X11. Integrated GPU of an AMD Ryzen 3 PRO 4350G (Renoir), kernel driver: amdgpu.

On rereading the original report: the offset here is upwards, i.e. I have to aim below targets.
