### ISSUE TITLE
Connections from midicontroller's grid are not saved

### ISSUE THREAD

**Issue by OleksiySitka** [BespokeSynth/BespokeSynth#441]
Hi
I have a launchpad mini, and I noticed that when I connect grid from several midicontroller pages to several sequencers grid inputs, save patch and reopen it, only current midicontrolers page connection is saved correctly, grids from other pages are just disconnected. It seems to affect only grid connections, as I have several pads from different pages connected to some places, and seems like they work correctly.

I'm on Pop!_OS (21.04) Linux

Steps to reproduce:
1. Create midicontroller module
2. Switch to layout and select some grid layout (for example monome)
3. Create several instances of something with the grid input (for example drumsequencer)
4. Connect grid from separate pages of midicontroller to modules from step 3
5. Save file and close Bespoke
6. Open Bespoke and the file
7. See that current page connection is there, but if you switch to other pages grids are disconnected

Expected behaviour:
Grid connections from each page are saved and restored on opening the file

**Comment by awwbees** [comment]
ah! sorry for this oversight, that is definitely a bummer. it used to work, but I guess something broke somewhere along the way. I will fix this.

**Comment by asmw** [comment]
@AlexSleepy, I think this is fixed, I can re-load a bsk with multi-page grid connections and they get restored.

**Comment by OleksiySitka** [comment]
@asmw is there some new version that I'm not aware of, or are you using a custom build?

**Comment by asmw** [comment]
@AlexSleepy if you are not building the current main branch, it will be in the upcoming 1.1 release

**Comment by OleksiySitka** [comment]
@asmw thanks. I'll wait for 1.1 for now

**Comment by OleksiySitka** [comment]
I've checked in 1.1.0 beta installed from .deb, and I still observe the same behaviour...

**Comment by OleksiySitka** [comment]
I didn't follow the development for some time, but this seems to be fixed. At least it works in nightly build from 2023-05-24
