### ISSUE TITLE
Segmentation fault on Manjaro Linux

### ISSUE THREAD

**Issue by ghost** [BespokeSynth/BespokeSynth#46]
Hello.
Probably after upgrading my system, I've got an segmentation fault on the execution of Bespoke.
How can I fix the issue. 

`[aki@w530 Bespoke-Linux]$ ./BespokeSynth 
0.001: pixel ratio: 1 screen width: 1920 screen height: 1080
Shader shader/vert error:

Shader shader/vert error:

Could not init nanovg.
Could not init font bounds nanovg.
Shader shader/vert error:

Segmentation fault (core dumped)`

Thanks in advance.

**Comment by awwbees** [comment]
if you run via the file https://github.com/awwbees/BespokeSynth/blob/master/Builds/LinuxMakefile/build/Bespoke-GLSLfix.sh (should be included with the linux build), does that fix the issue for you? I was having this crash on an older laptop, and running via that shell script fixed it for me.

**Comment by ghost** [comment]
The same error occurs with the script.
With another clean installed Manjaro, after installing only python2, Bespoke works ok.
So thanks anyway.

**Comment by awwbees** [comment]
ah great! no answer to the mystery, but I'm glad you've got everything working again.
