### ISSUE TITLE
Drumsampler kit path

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#47]
Hi,

I've tried to save drumkit from the example 2020-09-02_21-56_feedback_distortion_drums.bsk and saw that it uses absolute paths:

```
         "name" : "test",
         "samples" : [
            {
               "linkid" : -1,
               "pan" : 0.0,
               "sample" : "C:\\Users\\Ryan Challinor\\Documents\\Code\\BespokeSynth\\Builds\\MacOSX\\build\\Release\\data\\drums\\hits\\808kit\\Kick\\Kick [finger].wav",
               "speed" : 1.0,
               "vol" : 0.6299999952316284
            },
            {
               "linkid" : -1,
               "pan" : 0.0,
               "sample" : "C:\\Users\\Ryan Challinor\\Documents\\Code\\BespokeSynth\\Builds\\MacOSX\\build\\Release\\data\\drums\\hits\\808kit\\Clap\\Clap [rico].wav",
               "speed" : 1.0,
               "vol" : 0.8673469424247742
            },
            {
               "linkid" : -1,
               "pan" : 0.0,
               "sample" : "C:\\Users\\Ryan Challinor\\Documents\\Code\\BespokeSynth\\Builds\\MacOSX\\build\\Release\\data\\drums\\hits\\808kit\\HatClosed\\HH [finesse].wav",
               "speed" : 1.0,
               "vol" : 0.6299999952316284
            },
            {
               "linkid" : -1,
               "pan" : 0.0,
               "sample" : "C:\\Users\\Ryan Challinor\\Documents\\Code\\BespokeSynth\\Builds\\MacOSX\\build\\Release\\data\\drums\\hits\\808kit\\Perc\\Perc [thot].wav",
               "speed" : 1.0,
               "vol" : 0.2959183752536774
```

But it seems that samples actually in the .bsk file.
So one question is it possible to export that samples from your example?

**Comment by awwbees** [comment]
yes, I should refactor the save/load kit stuff, that is all very old and not very useful anymore, it was from before I serialized sample data into the drumplayer. one way to use that drum kit in another patch would be to drop in a prefab object, add the drumplayer to the prefab, then save that prefab.

but, this is not ideal. I should update the kit save/load to use binary files that store the wave data in the saved kits, so kits can be reused more easily.

**Comment by awwbees** [comment]
in the latest release I have removed the kit selection dropdown to eliminate confusion, until I add a better way to save drum kits

**Comment by KottV** [comment]
yeah, I notice that, but the samples need to be moved so I open the issue https://github.com/awwbees/BespokeSynth/issues/54

**Comment by KottV** [comment]
I think we can close this.
