### ISSUE TITLE
Limit values greater than 1 do not effect rendered audio

### ISSUE THREAD

**Issue by AlexMitchellMus** [BespokeSynth/BespokeSynth#473]
When setting the limit setting for `output N` node, `write audio` renders an audio file without the applied `limit` setting (found in `output node` flippy triangle menu).
 
The setup of the nodes - there is no clipping in the signal path (obviously)
![Screenshot from 2021-10-23 15-06-21](https://user-images.githubusercontent.com/12004932/138580046-b57848ee-9582-43aa-9194-de1f841bfe2d.png)

The output of `write audio` viewed in Audacity, notice the life-right channels are identically clipped.
![Screenshot from 2021-10-23 14-58-03](https://user-images.githubusercontent.com/12004932/138580047-09082251-1a95-4ad4-a49b-0daa2f6d12ad.png)

Project file for reference
[output_limit_test.zip](https://github.com/BespokeSynth/BespokeSynth/files/7404041/output_limit_test.zip)

**Comment by awwbees** [comment]
the text of this bug is not technically true: the "limit" setting does affect the output. try setting it to .1 to observe this.

but, it looks like the true issue here is that bespoke won't render the wav file with output values greater than 1.

**Comment by AlexMitchellMus** [comment]
I don't know what the limit value is doing. From reading the source code, it minmaxs the value.

Outputing to system probably shouldn't have a hard clip on it anyway. Especially when in the future bespoke is a plugin itself.

The term limit in audio land can get confused with limiter. Which this isn't.

**Comment by AlexMitchellMus** [comment]
Closing as 16bit wav clips to +-1 regardless.
