### ISSUE TITLE
Scan VST folder has a horrible Crash to Desktop issue.

### ISSUE THREAD

**Issue by DarkAlchy** [BespokeSynth/BespokeSynth#485]
Tried this several times, even uninstalling and reinstalling to roam around bringing this issue up to find it is not just I who has it.  Scan the folder, wait a few minutes then POOF BeSpoke is gone with a crash.  No crash popup, nothing just POOF.

How do we even find out the issue (where is a log) if it just goes POOF like that?  I have many other DAWs I use and none of them go POOF when I scan the VST folders.

**Comment by DarkAlchy** [comment]
I am on Windows 10, as were the others I believe.

**Comment by IvanPedroMuricy** [comment]
Dealing with the same problem... My OS: Windows 10 ...

**Comment by awwbees** [comment]
this is fixed if you build from source, or wait for the 1.1.0 release

**Comment by DarkAlchy** [comment]
Then I will wait for the 1.1.0 release and try it again at that time.

**Comment by dadoprom** [comment]
@awwbees when is the 1.1.0 release happening? Thank you for your hard work, bespoke is amazing :)

**Comment by awwbees** [comment]
soon (tm)
