### ISSUE TITLE
adding Script or ScriptStatus exits BespokeSynth

### ISSUE THREAD

**Issue by zeffii** [BespokeSynth/BespokeSynth#49]
no errors, just straight closes to desktop when i add either Script or ScriptStatus module.
win10.64bit

is bespoke expecting a local installation of Python?

**Comment by KottV** [comment]
>>is bespoke expecting a local installation of Python?

yes https://github.com/awwbees/BespokeSynth/issues/31

**Comment by zeffii** [comment]
okidoki. thanks @KottV ! (looking forward to this!)

**Comment by zeffii** [comment]
but the python38.dll is included in the portable/folder , bespoke should just be picking that up right?

**Comment by KottV** [comment]
Hm, I haven't tested that in Windows. I can take a look tomorrow.

**Comment by awwbees** [comment]
it's possible that you need a local install of python in addition to the included DLL. I'll have to figure out how I can reproduce this scenario on my local machine (uninstall python, I guess?) and then handle the error better (explain to the user that you need to install python, instead of just crashing)

**Comment by zeffii** [comment]
i installed from https://www.python.org/downloads/release/python-385/

now the script module loads :)  
![image](https://user-images.githubusercontent.com/619340/92764538-cb50c900-f394-11ea-9f95-da33634feb33.png)

**Comment by zeffii** [comment]
you know what this means right?

**Comment by awwbees** [comment]
unlimited potential?

**Comment by zeffii** [comment]
being able to sequence from python is magical. and py3.8 has many nice language features :)
