### ISSUE TITLE
Pinned envelope editors can't be recreated

### ISSUE THREAD

**Issue by tegarriott** [BespokeSynth/BespokeSynth#491]
Using the build from 1a1593f0:

1. Create a patch that can utilize an `envelopeeditor`, like `oscillator`
2. Create an `envelopeeditor`, like on the corner of the `volume` box
3. Press the button to `pin` it
4. Select the `envelopeeditor` and then remove it by pressing backspace
5. After this, the `envelopeeditor` can't be recreated using the above steps unless you delete and recreate the patch

**Comment by asmw** [comment]
I can reproduce this on Ubuntu 21.10

**Comment by asmw** [comment]
Should be fixed in the next release
