### ISSUE TITLE
When using individual outs on drumplayer you cannot duplicate the output

### ISSUE THREAD

**Issue by spectromas** [BespokeSynth/BespokeSynth#498]
When I set the drums to have individual outputs I am unable to create more than one cable from the output. Using shift click, which seems to work with every other module, a new send is created but it routes the previous output to it. 

I assume this is a bug? I want to create a few different sends for fx but I can't see a way to do it with this implementation.

**Comment by NoxyNixie** [comment]
I am not able to reproduce this issue in the latest nightly build. This may have been fixed.

If this bug resurfaces feel free to comment here or open a new issue.
