### ISSUE TITLE
Drumpayer does not reset at the right place

### ISSUE THREAD

**Issue by spectromas** [BespokeSynth/BespokeSynth#499]
Pretty simple to reproduce, it resents to step two rather than one. 

- Create a drumplayer
- Assign step one to a kick and step two to a hat
- Press reset lots of times quickly and you only hear the hat

**Comment by NoxyNixie** [comment]
There have been a couple of timing fixes since the posting of this issue. In the latest Nightly build I am unable to reproduce this issue.

If this problem is still happening for you in the latest build please don't hesitate to reply to this issue and it will be reopened or post a new one ;)
