### ISSUE TITLE
Option for audio device settings.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#5]
Hi,
BespokeSynth uses default audio device, if i understand correctly.
It will be great to have simple option to select which device to use for input/output. Maybe at first it  can be done in userprefs.json :)

**Comment by nay-seven** [comment]
+1 !  ;-)

**Comment by awwbees** [comment]
ah this is a great idea, I'm not sure why I never thought to do this. feature added just now in 746720a
