### ISSUE TITLE
Note Expression Bug

### ISSUE THREAD

**Issue by everythingability** [BespokeSynth/BespokeSynth#512]
![image](https://user-images.githubusercontent.com/96276/139584336-099720e7-be3a-4144-ae47-26c7c6e47f57.png)

Mac (self-build) Big Sur. When I add a note expression, I get XML in the inputs.

**Comment by awwbees** [comment]
I can't reproduce this. did you accidentally paste some content into there, maybe?

**Comment by everythingability** [comment]
Now I can't replicate it. It happened two or three times prior. Won't happen now. Could it be when I was at a constant 100% cpu.

Sorry to waste your time.

**Comment by asmw** [comment]
@everythingability any news or can this issue be closed?

**Comment by everythingability** [comment]
See above @asmw .  Reckon it's closed, but not my call.

**Comment by asmw** [comment]
@everythingability allright. IF it happens again, please re-open.
