### ISSUE TITLE
Creating modules inside a prefab container does not give them unique names, breaks routing on load

### ISSUE THREAD

**Issue by Fin6art** [BespokeSynth/BespokeSynth#513]
To clarify, I understand that names are used for routing and multiple modules having the same name makes it impossible for the program to tell which one of them should be routed to.
The issue is that creating or copying modules inside a prefab does not give them unique names, unlike elsewhere.

To reproduce this issue:

- Create a module inside a prefab container
- Create another module of the same type inside the prefab container
- OR copy the module with alt-drag
![prefab modules](https://user-images.githubusercontent.com/93475568/139585091-b367e4f8-7f3d-4710-8b62-cdeee71e9db0.png)

Both modules now have the same name and need to be manually changed to ensure correct routing on load of the prefab.
This is assumed to be unintentional as modules are always created with a unique name outside of prefabs.

**Comment by awwbees** [comment]
fixed by #532
