### ISSUE TITLE
UI not responding after clicking load/save

### ISSUE THREAD

**Issue by JensBee** [BespokeSynth/BespokeSynth#514]
* latest revision from head
* running on linux (arch) on wayland/swaywm 

Hi,
if I click on load/save in the upper bar, the UI is left unresponsive. I can see that parts of the UI get hover effects if the mousepointer touches them, but it's completely unresponsive to clicks or keyboard input.
Clicks on load/save have no effect and I'm not sure what to expect here (a dialog, notice, ..).
There is no output on the hosts terminal console. I'm unable to open the bespoke console after clicking so I can't tell if there are any hints.

Tried also with a 1.0.0 release. The UI is not blocking there, but the clicks on load/save have also no effect.

Thank you :)

**Comment by KottV** [comment]
This is kind of bug, JUCE native file chooser is not invoked. So you need to install zenity or kdialog.

**Comment by JensBee** [comment]
Ah, didn't knew that. Installing zenity fixed it. _I'll try to update the archlinux PKGBUILD._
