### ISSUE TITLE
Hidden cables become visible on project loading, prefab loading or copying (via alt-drag)

### ISSUE THREAD

**Issue by Fin6art** [BespokeSynth/BespokeSynth#516]
To reproduce this issue:

- Minimize a router with an outbound cable to hide it
- Save project
- Load project

Screenshot: Hidden cables become visible after loading the prefab.
(The cables are all correctly connected, but should not all be visible)
![hiding cables](https://user-images.githubusercontent.com/93475568/139593229-22f7bb0d-1fdb-40e6-a85e-ebe51964a51e.png)

**Comment by NoxyNixie** [comment]
Minimizing `audiorouter`s no longer hides cables. This issue is thus resolved (The ability to hide cables has for the most part been seen as a bug).

See also: 794a498e9c44ee63cb09f7afed6d3ea12e05c1d3
