### ISSUE TITLE
Feature request: Undo (Ctrl-Z)

### ISSUE THREAD

**Issue by tobiasBora** [BespokeSynth/BespokeSynth#526]
It's easy to do an operation wrong, either by mistake or because you realize after a few changes that this won't work and you want to go back to the original setting. Would it be possible to provide undo/redo actions?

**Comment by awwbees** [comment]
getting true undo to function is an absurd amount of work, and I don't anticipate it will ever happen in bespoke. I plan to pursue a more limited version of undo in the future, like a history list on each module of recent changes.

**Comment by westurner** [comment]
You would need a log of:

```
[(Document, Control, Operation, InverseOperation), ]
```

**Comment by westurner** [comment]
To do collaboration features, a CRDT may also get you basically multi-user undo.

CRDT: https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type : 
- GDocs, GSheets
- CoCalc
- JupyterLab/rtc (Y.js)


https://en.m.wikipedia.org/wiki/Unidirectional_Data_Flow_(computer_science)
- Redux

https://en.wikipedia.org/wiki/Undo

**Comment by tobiasBora** [comment]
I may be a bit naive, but a first quick and dirty solution could be to save the whole project in a new file every-time a change is made? With maybe an option to enable/disable for users that find this solution too inefficient on big projects. Or am I missing something?

**Comment by KottV** [comment]
you have autosave for that

**Comment by awwbees** [comment]
> I may be a bit naive, but a first quick and dirty solution could be to save the whole project in a new file every-time a change is made? With maybe an option to enable/disable for users that find this solution too inefficient on big projects. Or am I missing something?

yeah, this would be a good solution, but the issue here is that it becomes untenable pretty immediately, rather than only on big projects. if you create even a modest patch and press ctrl-s frequently while working, you will see how much it hitches. it wouldn't be an acceptable solution.
