### ISSUE TITLE
Draw selection instead of wire

### ISSUE THREAD

**Issue by tobiasBora** [BespokeSynth/BespokeSynth#528]
In many cases when I click on a node to draw a wire, it starts a selection:

![image](https://user-images.githubusercontent.com/2164118/139709906-0b130339-0947-4666-9826-3d59b2446150.png)

I'm sure that I'm clicking on the node as it does that even if I wait for the dot to become white (and this is confirmed by the fact that the selection starts inside the node) What I'd expect instead is:

![image](https://user-images.githubusercontent.com/2164118/139710108-16f3b5be-33a8-4edf-9f4c-c4e81cfe9edb.png)

I noticed that if I wait 2-3 seconds before clicking this occurs less often. 

I tried to zoom more and click precisely in the middle, but it does not change anything:

![image](https://user-images.githubusercontent.com/2164118/139710431-e6a97f7b-95a1-4d62-a897-baef3d57e627.png)

**Comment by awwbees** [comment]
several fixes went in a few weeks ago that should fix this in the next build
