### ISSUE TITLE
Program crashes on start up

### ISSUE THREAD

**Issue by KhanMann** [BespokeSynth/BespokeSynth#529]
I tried to change the audio output from speakers to my bluetooth headphones.  i saved and exited the program and it now crashes when I try to load it
[crash_2021-11-01_17-40.txt](https://github.com/BespokeSynth/BespokeSynth/files/7456425/crash_2021-11-01_17-40.txt)
[crash_2021-11-01_17-42.txt](https://github.com/BespokeSynth/BespokeSynth/files/7456426/crash_2021-11-01_17-42.txt)
[crash_2021-11-01_17-45.txt](https://github.com/BespokeSynth/BespokeSynth/files/7456427/crash_2021-11-01_17-45.txt)
[crash_2021-11-01_17-48.txt](https://github.com/BespokeSynth/BespokeSynth/files/7456428/crash_2021-11-01_17-48.txt)
[crash_2021-11-01_17-39.txt](https://github.com/BespokeSynth/BespokeSynth/files/7456429/crash_2021-11-01_17-39.txt)
.

**Comment by awwbees** [comment]
if you delete `Documents/BespokeSynth/userprefs.json`, that will resolve your crash. I'll take a look to see if I can reproduce it so I can fix this in the future.
