### ISSUE TITLE
Building Bespoke on Mac OS

### ISSUE THREAD

**Issue by bgaster** [BespokeSynth/BespokeSynth#53]
I'm trying to build Bespoke from the git/master on Mac OS with Producer 5.4.7 but it fails to build with undefines:

- sPluginList.createXml()->writeTo
- sPluginList.getTypes();

and no viable overload for:

- mPlugin = VSTLookup::sFormatManager.createPluginInstance(desc, gSampleRate, gBufferSize, errorMessage);

This all seems to be in VSTPlugin.cpp.

I've tried both git/master and the latest source release. 

Any thoughts?

**Comment by awwbees** [comment]
are you sure that you have the correct JUCE source? for example, if I look at https://github.com/juce-framework/JUCE/blob/5.4.7/modules/juce_audio_processors/scanning/juce_KnownPluginList.h, I see that `KnownPluginList::getTypes()` exists. what do you see in your `juce_KnownPluginList.h`?

**Comment by bgaster** [comment]
Thanks, it seems for some reason Producer was not putting the correct header path when generating the xcode file. Of course, I'm now stuck with the fact that I don't have the VST2 SDK and it seems pretty hard to find now! (I still find it a nightmare that they removed it!)

Any idea where I can download it?

**Comment by awwbees** [comment]
it is indeed a nonsensical nightmare that it isn't around anymore. I don't think I currently have a clean local copy, but I believe the last time I had to spelunk to find it, I got it from an archive.org page

________________________________

**Comment by bgaster** [comment]
Indeed, what a pain. I managed to find one. Thanks, building now :-)

**Comment by awwbees** [comment]
excellent!
