### ISSUE TITLE
JUCE embed file dialog is not working.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#537]
In Linux JUCE tries to use kdialog or zenity for file dialogs https://docs.juce.com/master/classFileChooser.html#afd55c3c97c97e23a0b18818156dfb71c
If it can't find them then JUCE's dialog should be invoked, but this doesn't happen.
Maybe some problem with modal loop and give a try to launch it async?

**Comment by asmw** [comment]
This might be an issue with the distribution providing wrappers for unknown commands which tell you how to install them, which leads to bespoke thinking there is e.g. a zenity, when in reality the wrapper is called and does nothing.

**Comment by KottV** [comment]
no,
all other JUCE apps works without kdialog/zenity by using JUCE dialog
if you disable NativeDialog in the Bespoke's code then it doesn't shows any

**Comment by asmw** [comment]
Yeah, I just read the discussion on this. I was misinformed.
