### ISSUE TITLE
data/drums/hits missed in repo

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#54]
Hi,

Drumplayer searches samples in drums/hits now. This dir with samples is absent in source repo (Builds/MacOSX/build/Release/data) while it's present in .zip releases.

**Comment by awwbees** [comment]
ah yes, I forgot that I had added that directory to my .gitignore, all set in 881cb92378294a26830f1d4dc7df0637c9d0f18a now!
