### ISSUE TITLE
I'd like to be able to combine pitch and modulation information.

### ISSUE THREAD

**Issue by TheGuyWhoo** [BespokeSynth/BespokeSynth#550]
For doing stuff like FM'ing Oscillator module. Currently, as far as I'm aware, only phase modulation is available on this module through audiotocv module. Is there a way to modulate actual frequency and still send in pitch data?

**Comment by awwbees** [comment]
you should be able to use the "detune" slider to achieve frequency modulation. you'll probably want to ctrl-click the upper and lower extents of the slider to increase the min and max allowed detune values. here's a picture of an FM setup:
![image](https://user-images.githubusercontent.com/839239/140421554-1ba30a71-3a23-462d-baaf-a027657ae4e0.png)

**Comment by TheGuyWhoo** [comment]
Nice, thank you! This piece of software pretty much changed the way I make music within two days. It has the convenience of a regular daw and all the possibilities of a modular system. Thanks!
