### ISSUE TITLE
First time you add a plugin in carla VST, it closes the window on Linux

### ISSUE THREAD

**Issue by tobiasBora** [BespokeSynth/BespokeSynth#559]
I recently upgraded BespokeSynth to 4a74e80, and since this upgrade when I add a plugin in Carla VST is closes the window the first time (but works when I retry it).

Other people also reported this issue on 1.0 (see discord, #linux-discution) as well while it was working fine for me, so I'm not sure if it's a regression or if it comes from the fact that my 1.0 version (packaged by Nix) was using a different JUCE version (the exact derivation is [here](https://github.com/NixOS/nixpkgs/blob/4269070d9465d9add707bc4e0db4ea0909f4df5f/pkgs/applications/audio/bespokesynth/default.nix) and uses JUCE 5.4.7). The new derivation I'm using is [here](https://github.com/NixOS/nixpkgs/blob/5efe5f57ce415b97653eb3dead81facb6ff8469d/pkgs/applications/audio/bespokesynth/default.nix).

To reproduce:
- Start a fresh BespokeSynth (tested on linux), and make sure Carla is installed (I got two different behaviors using the same Carla's version, so I don't think the issue comes from Carla)
- vst plugins > Carla Rack.so
- Click on "open" on the Carla plugin
- Add plugin. You will see quickly a new window appearing that will be closed quickly. If you start again it works. Note that if you close carla's plugin and start again, the issue is still present.

**Comment by KottV** [comment]
I haven't such issue on my system.
What is the Carla version and it's build flags?
Do you see this bug in other (JUCE or not) hosts?

**Comment by NoxyNixie** [comment]
This may have been resolved with the latest Nightly build.

If this is still happening with the latest nightly build feel free to comment on this issue or create a new one.
