### ISSUE TITLE
VST MIDI

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#57]
Hi Ryan,

What do you think about adding a MIDI feature to VSTs? So we can put some exotic sequencers, arps or whatever in BespokeSynth.

**Comment by KottV** [comment]
After 12 days I realized that using "put" and "in" weren't polite words, maybe. If so - I kindly ask to excuse me:)
BTW I miss feature for using MIDI patterns. Midiplayer (as i can see) is disabled and only way is to route midi-in via virtual port.

**Comment by awwbees** [comment]
ah, no worries, I didn't perceive any impoliteness! this issue just slipped through the cracks.

I should look into adding midi output from VSTs, it likely wouldn't be difficult. can you suggest any VSTs I should test with?

**Comment by KottV** [comment]
Sure!
https://venomode.com/phrasebox (demo)
http://graywolf2004.net/wp/
https://surge-synth-team.org/stochas/

**Comment by baconpaul** [comment]
Heya @KottV we can close this if #334 gets merged I think!

**Comment by KottV** [comment]
cooooooooool
