### ISSUE TITLE
Offer possibilities to devendor used libraries and tooling

### ISSUE THREAD

**Issue by dvzrv** [BespokeSynth/BespokeSynth#590]
When building the package for Arch Linux I currently have to devendor some libraries by patching various CMakeLists.txt files (see relevant patch https://aur.archlinux.org/cgit/aur.git/tree/bespokesynth-1.0.0.r246.gfd389e6-devendoring.patch?h=bespokesynth-git).

Many libraries and tooling (e.g. jsoncpp, JUCE, pybind11) are available on downstream distributions and they usually prefer to build against those, as vendoring is bad (Fedora has an extensive write-up on the topic: [Bundled Libraries](https://fedoraproject.org/wiki/Bundled_Libraries)).

It would be awesome to be able to provide options for the use of system libraries (e.g. `USE_SYSTEM_JSONCPP`), which can be provided during build time to allow downstream distributions to seamlessly build against their system libraries instead of the bundled ones.

**Comment by awwbees** [comment]
I don't really understand any of this (or am particularly interested in doing the research!) but I'm happy to take a pull request

**Comment by dvzrv** [comment]
Cool! I will try to offer this as time permits!

**Comment by NotAFile** [comment]
I would advise introducing some easy way to tell official builds from distro builds so that issues caused by subtle library version mismatches resulting from this can be correctly reported to the distros instead of here.

**Comment by dvzrv** [comment]
Unfortunately there is not really a "one size fits all" solution to that problem.

One way to deal with it in the context of this project is to use [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository), so that people have to report
* what version of the software they are using
* on what operating system (and optionally version) they are using the software
* how they installed the version that they are using

That way it becomes much clearer for the project developers to tell things apart and to e.g. ask for help if there is an issue with a specific distribution package.
It is important to not only look at this in the context of dependency issues, but also in the context of changes to the build system (which may introduce problems as well).

Users of the Arch Linux distribution are expected to follow the distribution's [bug reporting guidelines](https://wiki.archlinux.org/title/Bug_reporting_guidelines). [This section](https://wiki.archlinux.org/title/Bug_reporting_guidelines#Upstream_or_Arch?) in particular is relevant for this discussion. Having guidelines of course does not keep anyone from disregarding them and filing tickets in the wrong place, but there is not much that can be done about that I am afraid.

**Comment by dvzrv** [comment]
I have added issue templates in #647 (for bug reports and enhancement requests).

I also had a look at the [PKGBUILD in OBS](https://build.opensuse.org/package/view_file/home:bespokesynth/bespokesynth/PKGBUILD?expand=1) and not to step on anyone's toes, but I think it could use a few improvements to adhere to the [Arch package guidelines](https://wiki.archlinux.org/index.php/Arch_package_guidelines). If you tell me where, I'd be happy to provide support.

**Comment by KottV** [comment]
@dvzrv 
it's my first and only Arch PKGBUILD, any suggestions are welcome

**Comment by dvzrv** [comment]
> it's my first and only Arch PKGBUILD, any suggestions are welcome

Okay, here are some inline comments! :)
Feel free to also have a look at [bespokesynth-git in the AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bespokesynth-git) for inspiration (it is devendored though!).

```
# remove all occurences of empty variables

# you might consider a pkgname=bespokesynth-official and a provides/conflicts towards bespokesynth (which will be in the repos soonish). the provides/conflicts towards bespokesynth-bin is not required (if a bespokesynth-bin ever exists, it needs to provides/conflicts bespokesynth as well)
pkgname="bespokesynth"
pkgdesc="Software modular DAW."
pkgver=1.1.0
# pkgrel must always start from 1
pkgrel=0
arch=(x86_64)
url="https://github.com/awwbees/BespokeSynth"
license=(GPL3)
depends=('jack' 'curl' 'mesa' 'python')
# gcc does not have to be added specifically because it is in base-devel:
# https://archlinux.org/groups/x86_64/base-devel/
# some dependencies are listed twice
# python3 should not be used, but just python instead
makedepends=('gcc' 'libx11' 'libxinerama' 'freetype2' 'cmake' 'libxcursor' 'mesa' 'libusb' 'libxext' 'libxrandr' 'libxcomposite' 'libusb' 'jack' 'mesa' 'python3')
checkdepends=()
optdepends=()
provides=('bespokesynth' 'bespokesynth-bin')
conflicts=('bespokesynth' 'bespokesynth-bin')
replaces=()
noextract=()
# if possible, provide a real file link (also for the patches below, not sure how they end up in the build environment)
source=("${pkgname}-${pkgver}.tar.gz")
# why skip the checksums?
md5sums=('SKIP')
sha512sums=('SKIP')

prepare() {
  cd ${pkgname}-${pkgver}
  patch -p1 -i /usr/src/packages/SOURCES/bespokesynth-juce-vst2.patch
  cp /usr/src/packages/SOURCES/juce_VSTInterface.h libs/JUCE/modules/juce_audio_processors/format_types/
}

build() {
  cd ${pkgname}-${pkgver}
  # you can also have a look at the official cmake packaging guidelines for this, although you will likely keep CMAKE_BUILD_TYPE=Release here
  # https://wiki.archlinux.org/title/CMake_package_guidelines
  cmake -Bcmake-build \
      -DCMAKE_BUILD_TYPE=Release \
      -DBESPOKE_VST2_SDK_LOCATION=/usr/local/include \
      -DCMAKE_INSTALL_PREFIX=/usr

  cmake --build cmake-build --config Release -j`nproc`
}

package() {
  cd ${pkgname}-${pkgver}
  # it is required to quote instances of ${pkgdir} and ${srcdir} (using "") as they may contain whitespaces
  # I'm personally not used to using cmake to build and install, but usually use the generated Makefiles instead. it seems not correct to use --prefix with $pkgdir here, as in Makefile-land one usually uses DESTDIR="${pkgdir}" (the prefix is set initially using CMAKE_INSTALL_PREFIX already
  cmake --install cmake-build --prefix ${pkgdir}/usr
}
```

In general it is advisable to use [devtools](https://archlinux.org/packages/extra/any/devtools/) to [build things in a clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) and ensure that e.g. [namcap](https://wiki.archlinux.org/title/Namcap) and `checkpkg` are run for package checks.

I can't really comment on how OBS deals with any of this, but the official packages for Arch Linux are all built using devtools (to ensure we provide the correct set of dependencies and do not link to potentially differing runtime environment of the builder).

**Comment by KottV** [comment]
Thanks! I made some updates in https://build.opensuse.org/package/show/home:bespokesynth/bespokesynth-current

**Comment by dvzrv** [comment]
@KottV Cool! I have a few further questions/ notes about the changes:

* What do you use bubblewrap for in makedepends?
* What is the specific use-case for python-jedi in optdepends? If it enables or extends a feature of the program, please specify its use-case after a colon (e.g. `'<name>: <purpose>'`)
* The package should have `bespokesynth` in `provides` and `conflicts`.
* `replaces` and `noextract` are both empty and should be removed

**Comment by KottV** [comment]
>What do you use bubblewrap for in makedepends?

~~something wants webkit2gtk now (i can't see what, my previous PKGBUILD worked fine) and webkit2gtk wants bubblewrap and it ambiguous: `unresolvable: have choice for bubblewrap needed by webkit2gtk: bubblewrap bubblewrap-suid` so i put it for workaround~~
it caused by `zenity`

>What is the specific use-case for python-jedi in optdepends?

code completion in Bespoke

>The package should have `bespokesynth` in `provides` and `conflicts`.

~~it should be a name of the binary or a package? package is named `bespokesynth-current`~~

>replaces and noextract are both empty and should be removed

it's easy :)

**Comment by dvzrv** [comment]
> something wants webkit2gtk now (i can't see what, my previous PKGBUILD worked fine) and webkit2gtk wants bubblewrap and it ambiguous: unresolvable: have choice for bubblewrap needed by webkit2gtk: bubblewrap bubblewrap-suid so i put it for workaround

Hm, that's odd. I can investigate in a bit.

> it should be a name of the binary or a package? package is named bespokesynth-current

As I will provide `bespokesynth` in the official repositories, it should provide/conflict that (as it provides the same files).

On a different note: How does OBS provide the build with the tarball?
I lack the understanding/knowledge for really making any judgement calls there, but maybe it makes more sense to look into the [VCS package guidelines](https://wiki.archlinux.org/title/VCS_package_guidelines), as you seem to want to provide a sort of "nightly"/ "latest".

**Comment by KottV** [comment]
it was `zenity`, OBS checks it's dependency at build prepare stage =/
so i'll try to put it in `optdepends`

>On a different note: How does OBS provide the build with the tarball?

via _service worker: https://build.opensuse.org/package/view_file/home:bespokesynth/bespokesynth-current/_service?expand=1
there is no way to call any VCS at the build process, afaik it's intended for reproducible builds

**Comment by dvzrv** [comment]
> it was `zenity`, OBS checks it's dependency at build prepare stage =/ so i'll try to put it in `optdepends`

Is that a new runtime dependency?

> via _service worker: https://build.opensuse.org/package/view_file/home:bespokesynth/bespokesynth-current/_service?expand=1 there is no way to call any VCS at the build process, afaik it's intended for reproducible builds

Ah, alright. We take care of this within the context of our build tooling. We usually rely on e.g. commit pinning or signed tags (however, not all source forges support irremovable tags) for VCS packages.

At any rate, I will now close this ticket, as all things that I could easily devendor are now devendored. Thanks! :)
