### ISSUE TITLE
Missing license information for the vendored libraries

### ISSUE THREAD

**Issue by dvzrv** [BespokeSynth/BespokeSynth#591]
The vendored libraries in [libs/](https://github.com/BespokeSynth/BespokeSynth/tree/35369170f452c34af877098dd260b4d84b31d6ff/libs) do not declare their license.

While e.g. [exprtk](http://www.partow.net/programming/exprtk/index.html) creates a problem by not even including the required MIT license file (and should be contacted about this), there are other libraries such as 3dxware for which you do not have the permission to redistribute it ("all rights reserved"):
https://github.com/BespokeSynth/BespokeSynth/blob/35369170f452c34af877098dd260b4d84b31d6ff/libs/3dxware/include/3dxware/si.h#L8-L16
It is unclear where these files are actually from. If the LicenseAgreementSDK.txt allows for redistribution of that code, it *must be* included.

With all bundled libraries it seems that the license files have been removed (e.g. https://github.com/memononen/nanovg/blob/master/LICENSE.txt for nanovg). This is rather problematic for packaging purposes also, as it is not unlikely that packaging this software is illegal (there is no easy way of telling as the license files are missing).

**Comment by dvzrv** [comment]
@awwbees can you please have a look at this? This is somewhat a major blocker for packaging and risks this project potentially receiving a DMCA takedown notice (over 3dxware).

**Comment by awwbees** [comment]
yes, I have a plan for this, I'll be implementing it soon

**Comment by ArashPartow** [comment]
The MIT license is mentioned in the header right at the top:

https://www.partow.net/programming/exprtk/code/exprtk.hpp


    Copyright notice:
    Free use of the C++ Mathematical Expression Toolkit Library is
    permitted under the guidelines and in accordance with the most
    current version of the MIT License.
    http://www.opensource.org/licenses/MIT

I do not believe having the complete license in a file is a hard requirement as long as there is a link to or mention of the license.

**Comment by dvzrv** [comment]
> I do not believe having the complete license in a file is a hard requirement as long as there is a link to or mention of the license.

The license itself specifies it:

> The above copyright notice and this permission notice (including the next paragraph) shall be included in all copies or substantial portions of the Software.

@ArashPartow Having the MIT license *in each file* is not a hard requirement, but having at least a separate file stating the entire license is.
Apart from not duplicating the information in all files this enables e.g. downstream distributions to use a file instead of extracting this information from another file. This is e.g. the case for Arch Linux (and also other distributions), if one would want to devendor exprtk (read: use a system-wide installed exprtk version instead of the bundled version) when building bespokesynth (which is a very common thing to do).

> The MIT license is mentioned in the header right at the top:

A link to how to use and format it is mentioned, but the license itself is not correctly stated.
Exprtk does not use the standard MIT license file text in the header but just points to a place that explains how to format and use it (https://opensource.org/licenses/MIT).
Do note also, that the MIT license does not seem to have a standardized license header (to be used in files, see SPDX: https://spdx.org/licenses/MIT.html).

The reason why we have to use an actual (specific) file to ship alongside the code is, that e.g. the MIT license specification has a section that makes it unique (the copyright statement and date lists the author by name/mail and a potentially varying date range for each release) per project.
For a set of other licenses we do not have this requirement (e.g. GPL3, LGPL2.1) as they are (usually) not modified when shipped and do not carry specific identifying pieces of information.

**Comment by awwbees** [comment]
took care of 3dxware in #633 and added missing licenses that hadn't survived some moves in #634. I guess exprtk is still unavoidably in "violation" of the MIT license due to how they include it, but I don't feel that it's worth losing sleep over. thanks for bringing these to my attention! please let me know if I have missed anything.

**Comment by dvzrv** [comment]
@awwbees thanks a lot for looking into this! :)
