### ISSUE TITLE
Vst plugins are not saved from one session to another

### ISSUE THREAD

**Issue by Linteum** [BespokeSynth/BespokeSynth#594]
Each time i quit bespoke and come back all my vst are gone.
I have to rescan all the vsts ( which last 2 min long each time)

By the way this synth is incredible.

**Comment by awwbees** [comment]
this is a bug which seems to only occur for some users in 1.0.0. if you create a folder called `vst` in your `Documents/BespokeSynth/` directory, it should resolve it. this issue is fixed in the latest beta.
