### ISSUE TITLE
Deleting pinned LFO Module makes it impossible to bring back up

### ISSUE THREAD

**Issue by dospunk** [BespokeSynth/BespokeSynth#60]
Steps to reproduce:
1. add LFO to a slider and pin the LFO module. Change the high and/or low values
2. select the LFO module and delete it
3. Right click the slider again

You'll see that no LFO menu comes up when the slider is right clicked again, but the LFO is still active for the slider

Platform: Windows 10

**Comment by awwbees** [comment]
fixed in a12219f7502d8465d5713d8faa0ea1709076f6ba, thanks!
