### ISSUE TITLE
channelfilter in layout file is ignored

### ISSUE THREAD

**Issue by coax75ohm** [BespokeSynth/BespokeSynth#600]
I've created 3 different layout files for an Arturia Keystep Pro: default note based, channel 10 drums, and channel 16 knobs. Everything is working, including modwheelcc and pitchbendrange parameters, except for the channelfilter parameter that seems to be ignored.

[KeyStep Pro MIDI IN.json.txt](https://github.com/BespokeSynth/BespokeSynth/files/7531037/KeyStep.Pro.MIDI.IN.json.txt)
[KeyStep Pro Drum.json.txt](https://github.com/BespokeSynth/BespokeSynth/files/7531039/KeyStep.Pro.Drum.json.txt)
[KeyStep Pro Knobs.json.txt](https://github.com/BespokeSynth/BespokeSynth/files/7531040/KeyStep.Pro.Knobs.json.txt)

**Comment by awwbees** [comment]
hmm, I suspect you may be on a build that doesn't yet support "channelfilter". could you click the `?` icon in the upper left corner, click "copy build info", then paste your build info here?

if you don't have a "copy build info" button, that means you are on 1.0.0, which doesn't yet support "channelfilter" via layout files. bespoke 1.1.0 will support this. the latest beta is currently available [here](https://www.bespokesynth.com/builds/20211107_1_0_999/), and it will be fully released in several days.

**Comment by coax75ohm** [comment]
Good to hear that this is already done.

Please add some variant of the KeyStep Pro files into the releases version, as this is a very common sequencer.

**Comment by awwbees** [comment]
are the files you posted suitable to include in the next release? I don't have a KeyStep Pro to test with

**Comment by coax75ohm** [comment]
I don't know of any changes to the JSON format that would matter. Should be okay.
