### ISSUE TITLE
clicking off objects should unhighlight them

### ISSUE THREAD

**Issue by coax75ohm** [BespokeSynth/BespokeSynth#601]
A minor annoyance, clicking on items within a midicontroller layout will highlight that item. If unconnected, that item will remain highlighted. It would be better UI design if it reverted to standard unselected color.

Also, clicking on a blank area should unselect/unhighlight items.

**Comment by awwbees** [comment]
hmm... they remain highlighted to make it easy to adjust their settings in the panel on the left of the midicontroller. this behavior is intentional, unless I'm misunderstanding the nature of your request.

**Comment by coax75ohm** [comment]
I don't think you're misunderstanding. I'm just suggesting that you should be able to unselect.

**Comment by awwbees** [comment]
gotcha. ok, this is intentional behavior, then!
