### ISSUE TITLE
Preset module doesn't work correctly with drumsequencer

### ISSUE THREAD

**Issue by OleksiySitka** [BespokeSynth/BespokeSynth#604]
Observed this in 1.1.0 beta installed from .deb on Pop Os (ubuntu 21.04 based)

Steps to reproduce:
1. Create preset and drumsequencer modules
2. Connect grey dot from preset to drumsequencer
3. Set some sequence in drumsequencer and save it to first slot of preset (shift+click)
4. Make some changes to the sequence
5. Load the preset from the first slot by clicking it
**6. See that saved sequence is not loadad and all row pitches are set to 0**

Expected behaviour:
Sequence is recalled together with other parameters (as in notesequencer) and row pitches are set to the saved values (or at least not reset to 0)

**Comment by OleksiySitka** [comment]
Oh, I didn't see #337, so it's partly a duplicate. But it doesn't mention reset of row pitches there

**Comment by NoxyNixie** [comment]
I believe this has been resolved in the latest Nightly builds and I'm unable to reproduce it.

![BespokeSynth_20230125_192232](https://user-images.githubusercontent.com/211381/214649777-468562ea-0482-4ff2-96d1-1c69151b41b3.gif)
