### ISSUE TITLE
Prefabs and Savestates not saving with extension 

### ISSUE THREAD

**Issue by spectromas** [BespokeSynth/BespokeSynth#612]
I'm pretty sure this was the way it was for a while and then it was fixed but seems to have regressed. 

Go to Save As, write something, save. 
Go to Load and you cannot see the file as .bsk was not written to it. 

Same thing for prefabs. 

Linux with 1.0.9992

**Comment by KottV** [comment]
what's file dialog, kdialog, zenity, JUCE?

**Comment by spectromas** [comment]
It's kdialog

**Comment by KottV** [comment]
do you see the "automatically set extension" checkbox at the bottom of kdialog?

**Comment by spectromas** [comment]
Ah yes I do and that works as expected. Thanks, I'll close this then.
