### ISSUE TITLE
Crash to desktop. Windows 11 - latest Bespoke Beta

### ISSUE THREAD

**Issue by gl33mer** [BespokeSynth/BespokeSynth#613]
Simple effect chain. 2 effects or so. Curve looper modulating a parameter on one of the effects (I believe it was the right most one). Delete the effect. Crash to desktop.

Have tried to reproduce the crash using the latest save. Haven't managed to crash it yet but there does seem to be some odd behavior. Sometimes. When the owner of the parameter (the effect) is deleted. 

Seems that atm the normal behavior varies between sending the cable end to the top left corner of the canvas and leaving it where it was before the effect was deleted.

**Comment by gl33mer** [comment]
Stumbled on what seems like another phenomenon:
Instantiate 1 effect chain. & 2 curveloopers. Randomize loopers. 
Set 1st looper to modulate the add effect button on the effect rack.
Now either set the 2nd looper to modulate the new parameter that has shown up on the effect rack. It reads "spa" - the first letters from spawn. 
That will crash. 
Pressing on the first parameter manually also seem to trigger that same infinite loop type scenario leading to crash to desktop.

**Comment by NoxyNixie** [comment]
> Simple effect chain. 2 effects or so. Curve looper modulating a parameter on one of the effects (I believe it was the right most one). Delete the effect. Crash to desktop.

I am unable to reproduce any crashes by deleting a module that is being modulated in the `effectchain`.

>Seems that atm the normal behavior varies between sending the cable end to the top left corner of the canvas and leaving it where it was before the effect was deleted.

This PR: #1189 should resolve that (and possibly related crashes).

>Now either set the 2nd looper to modulate the new parameter that has shown up on the effect rack. It reads "spa" - the first letters from spawn.

There is a limit of a 100 effects that you very quickly reach by modulating the spawn button.

I can make the button not targetable by modulation cables but that does take away from a potential use case. Or I could make it so it does not crash, or maybe even remove the limit and leave it up to the user to figure out this isn't a good idea :P

Either way it shouldn't crash so I'll think of a fix.

**Comment by NoxyNixie** [comment]
#1195 "fixes" the crash.
