### ISSUE TITLE
Doc: multitrackrecorder image is not displayed

### ISSUE THREAD

**Issue by ycollet** [BespokeSynth/BespokeSynth#621]
On the documentation webpage (https://www.bespokesynth.com/docs/index.html), the image of multitrackrecorder  is not displayed.
![image](https://user-images.githubusercontent.com/1255536/141807331-0b4335cd-0dc5-4ff7-93d6-eeb3f261f19b.png)

**Comment by NoxyNixie** [comment]
Resolved
