### ISSUE TITLE
VST's being forced to the front causes issues interacting with errors in windows

### ISSUE THREAD

**Issue by Smiggs2112** [BespokeSynth/BespokeSynth#627]
I noticed that when you get an error in a VST, specifically Kontact in my case, there is no way to interact with the error message at all so you just have to kill the program.

Steps to recreate:
Load Kontact as a VST
Load a VST in kontact
Change a setting
Try to drag a vst over the top to force the error in kontact

Attached a recording of my replicating the issue

https://user-images.githubusercontent.com/94576994/142308812-d41e0f22-b4e3-4d5f-bbe2-cebe57048ada.mp4

**Comment by awwbees** [comment]
hmm, this seems like potentially an issue with how JUCE handles "always on top" (or possibly how KONTAKT deals with it?), but I will look into it. if you disable "vst_always_on_top", does that behave better in this case?

**Comment by Smiggs2112** [comment]
Oh I completely forgot I could just turn it off haha. Yes with the setting turned off there is no issue. Cheers
