### ISSUE TITLE
What does the Radio Sequencer do?

### ISSUE THREAD

**Issue by dospunk** [BespokeSynth/BespokeSynth#63]
I can't find any information about it

**Comment by awwbees** [comment]
I don't use that one much, but it's intended to be used along the lines of this:
![image](https://user-images.githubusercontent.com/839239/100570509-eb5e9d00-329e-11eb-862a-4e25f46e037f.png)
you wire it up to a few checkboxes, and you can sequence which checkbox is on over a course of steps. in this example, you'd have the first sequencer run for 2 measures, the second sequencer run for the next measure, and the last two sequencers run for the final measure. it's called "radio sequencer" in reference to "radio buttons": only one is on at a time.

**Comment by dospunk** [comment]
Got it, thank you!
