### ISSUE TITLE
Immediately closes when launching on win 10

### ISSUE THREAD

**Issue by manchaary** [BespokeSynth/BespokeSynth#639]
Bespoke version is 1.1.0
Win 10 Pro build 19043.1348

After installation when I try and launch BespokeSynth I can see window of a BespokeSynth and after it closes immediately. Tried restarting after installation no luck.

I have globally installed
python 3.9.7
node 14.18.0
npm 6.14.15

**Comment by NoxyNixie** [comment]
Can you try with the latest Nightly build?

Also don't forget to reset your settings file in `Documents\BespokeSynth\userprefs.json` before launching so that incorrectly configure audio settings aren't the cause.
