### ISSUE TITLE
Empty window on launch macOS

### ISSUE THREAD

**Issue by bangnoise** [BespokeSynth/BespokeSynth#646]
Bespoke 1.1.0
macOS 12.0.1
M1 Mac mini
On first (and subsequent) launches, Bespoke opens a blank black window, nothing happens.
Quitting using command-Q causes the application to hang and it must be force-quit.

**Comment by awwbees** [comment]
I don't have any other reports of this one. can you test if this happens with the latest nightly build? available here: https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly

**Comment by awwbees** [comment]
seems to have been an issue in monterey with certain I/O configs, I recently got an M1 and was experiencing the same thing. updating JUCE seems to have fixed it.
