### ISSUE TITLE
Only VST (but not VST3) plugins are listed in the pop-up list when pressing a letter

### ISSUE THREAD

**Issue by marcora** [BespokeSynth/BespokeSynth#648]
For example, if I press "p" I see my PolySix (VST) plugin in the list, but not my Pigments (VST3) plugin.

**Comment by awwbees** [comment]
do you see the VST3 version in the "vst plugins" dropdown? or in the plugin manager? maybe it hasn't been scanned by bespoke.

**Comment by werame** [comment]
I cannot quite repro this as they do show up for me (with 1.1.0, which was released Nov 16, so I guess the OP was using that version too)

![image](https://user-images.githubusercontent.com/97036286/151575178-010a908a-c756-4599-b5b6-79877a24366e.png)

But it's a bit disappointing that there's no param info etc. Just "no tooltip found"

**Comment by KottV** [comment]
Not a bug anymore. But showin plugin's info as tooltip would be cool.

**Comment by PowerUser64** [comment]
Seems this is fixed now
