### ISSUE TITLE
Clicking on dropdown opens it, but clicking again does not close it

### ISSUE THREAD

**Issue by marcora** [BespokeSynth/BespokeSynth#649]
I am on macOS Big Sur, Bespoke v1.1 and when I click on a dropdown menu it opens, however when I click on it again it does not close. The only way to close it is to click on empty space, which is not the commonly expected UI behavior for dropdowns generally.

**Comment by ThePython10110** [comment]
Still true now...
**bespoke NIGHTLY 1.1.0 (Sep 13 2022 00:30:04) - Windows 10 - HEAD 0acb8eb**
