### ISSUE TITLE
Couple of little bugs in Eq UI.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#65]
It's me again...

Eq is beautiful!

![изображение](https://user-images.githubusercontent.com/4686351/101346076-c6d47780-38d3-11eb-8d66-251319d069f7.png)

When Eq is resized to not-default values you'll see the filters labels on the background:
![изображение](https://user-images.githubusercontent.com/4686351/101346141-deabfb80-38d3-11eb-9ad1-eb026584869c.png)

Or curve's artifacts:

![изображение](https://user-images.githubusercontent.com/4686351/101346244-01d6ab00-38d4-11eb-9459-200e1c11b5c6.png)

**Comment by awwbees** [comment]
thank you for logging these issues! it's definitely helpful to have somebody catching my blind spots

**Comment by mthierman** [comment]
Window resize breaks if you make EQ too small

![bespokeeq](https://user-images.githubusercontent.com/68129072/143619035-749afbc7-9ae2-4583-a110-10919d3ddac0.gif)

**Comment by KottV** [comment]
Maybe just to set a limits for a minimal and maximal sizes?

**Comment by awwbees** [comment]
fixed by #1086
