### ISSUE TITLE
MacOS Mojave loss of audio when crearting midi controller module

### ISSUE THREAD

**Issue by dadakopf** [BespokeSynth/BespokeSynth#651]
__When I start with a blank page except for the gain-splitter-output default and connect a signalgenerator to the gain module, I get sound. If I use the menu to get a midicontroller, as soon as the module popes up on the screen, there is a click and all audio stops, until I quit the app and start over. I just downloaded an hour ago the latest version of Bespoke and it took awhile to find what is going on. I had no audio at all, and I think its because of this midicontroller thing.

**Comment by awwbees** [comment]
I haven't experienced any issues like this, so additional information might help sort it out. which midi controller are you using?

**Comment by dadakopf** [comment]
Ryan,

Basically I open up the file attached below. Click the keyboard. Notes play. From the instruments drop down I select midicontroller, and place it in the window. I do nothing else with it. Click the keyboard, no sound out, though the outputs register sound coming out in the VU meter box.The sound is dead for any other app running at the same time. If I quit Bespoke, the sound returns. I have to close and restart the app to get sound out again. This happened with other patches when I tried to add midicontroller. I’m running macOS 10.14.6. 

Model Name:	iMac
  Model Identifier:	iMac16,2
  Processor Name:	Intel Core i5
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB
  Boot ROM Version:	427.140.8.0.0

**Comment by dadakopf** [comment]
Ryan,

Oops. I forgot to attache the file. Here it is.

**Comment by NoxyNixie** [comment]
hhmmm the file that was attached is not visible here on github and a lot has changed around the midicontroller so this bug might have been fixed.

If this bug is still happening feel free to comment here or post a new issue.
