### ISSUE TITLE
module "presets" doesn't work on module "dumsequencer"

### ISSUE THREAD

**Issue by rerry1234** [BespokeSynth/BespokeSynth#652]
module "presets" doesn't work on module "dumsequencer".
sequences are not saved in presets.

which does work in "notesequencer".

**Comment by rerry1234** [comment]
also, doesn't save sequences on "controlsequencer"

**Comment by NoxyNixie** [comment]
I believe this has been resolved in the latest Nightly builds and I'm unable to reproduce it.

![BespokeSynth_20230125_192232](https://user-images.githubusercontent.com/211381/214649777-468562ea-0482-4ff2-96d1-1c69151b41b3.gif)
![BespokeSynth_20230126_002336](https://user-images.githubusercontent.com/211381/214715718-9a8cc716-6e0d-4504-a6d4-03b06726c16a.gif)
