### ISSUE TITLE
Midi controller connections are removed when I save, close and re-open a patch

### ISSUE THREAD

**Issue by fenderberg** [BespokeSynth/BespokeSynth#653]
Midi controller connections are removed when is save, close and re-open a patch

When I do this all my MIDI control connections are gone. But when I save it all as a prefab, the connections stay. 

MacBook
Midi controller: Novation circuit tracks 

![image](https://user-images.githubusercontent.com/95136176/143686210-171a250e-ce5b-4f7b-bc84-ba549e82057c.png)

**Comment by mthierman** [comment]
Can you try re-selecting the layout used in the midicontroller and see if the connections come back? I've noticed layouts going wonky when loading a patch or applying the triangle menu
![midipatch](https://user-images.githubusercontent.com/68129072/143688751-59eabe06-a017-4279-b139-3dc6e5f4c6a4.gif)
![apply](https://user-images.githubusercontent.com/68129072/143688754-f2157425-1515-4995-ae1f-d21890f3db35.gif)

**Comment by fenderberg** [comment]
the controller I use (novation circuit tracks) isn't among them. if I open the prefab patch I get this error message:
![image](https://user-images.githubusercontent.com/95136176/143854164-0ff7874d-7fc7-4f46-a344-2231cf12d497.png)

**Comment by fenderberg** [comment]
is there anyway to use the default layout and rename it to novation circuit tracks? I can't find the default.json

**Comment by fenderberg** [comment]
Opened a new issue for this one
