### ISSUE TITLE
input and midioutput not saving/restoring selected value in layout

### ISSUE THREAD

**Issue by semi-co** [BespokeSynth/BespokeSynth#654]
I am trying to create a custom layout for myself using the `saveas` console command . I am able to do so and load the layout successfully with "new patch" but the values in my "input" and "midioutput" modules aren't making it.

![image](https://user-images.githubusercontent.com/90988805/143764880-7fd5e364-797c-46cc-be20-4fe50d575c5e.png)
Creating this prefab in an empty file works as expected with the correct channels in the inputs and the correct devices in midioutput and midioutput2. 

Doing `saveas` and then clicking "new patch" produces this:
![image](https://user-images.githubusercontent.com/90988805/143764916-97cb02f2-5b3f-400a-9733-e405a14a39eb.png)

The inputs all initialize to channel 1 and the midioutputs initialize to -----. The midicontroller modules work as expected. The module positions get a little messed up too but I'm not worried about that as I can fix them in the json. I tried adding the missing properties to the json file for "ch"/"channel" and "controller" but that didn't seem to work.

This was all done on Windows 10 in version 1.1.0 (November 16 build).

Thanks!

**Comment by awwbees** [comment]
the `saveas` command isn't really supported (it's old legacy stuff) so it is expected that things like this will be broken. fully-formed save data exists only within BSK save files, not the json. saving jsons via `saveas` can still be useful for some things, but it's an "as-is" thing, and won't receive any fixes.
