### ISSUE TITLE
Auto-start at windows boot

### ISSUE THREAD

**Issue by Arteneko** [BespokeSynth/BespokeSynth#655]
By the look of it, I don't see a way to set a "default song to open at software start", which makes it painful for me to add it to my windows system startup pipeline.

Is there a way to do so ? (Using Bespoke for a mic clean pipeline)

**Comment by KottV** [comment]
you can load savestate as argument to the BespokeSynth.exe, then add this to Autostart

**Comment by awwbees** [comment]
for example, a shortcut where the target is `"C:\Program Files\BespokeSynth\BespokeSynth.exe" desired_save_file.bsk`
