### ISSUE TITLE
Error on midi controller module when I re-open a patch (couldn't load layout file)

### ISSUE THREAD

**Issue by fenderberg** [BespokeSynth/BespokeSynth#662]
Every time I save a patch and later re-open it, all my  midi controller connections are gone. I get the following error:

![image](https://user-images.githubusercontent.com/95136176/144704433-c827928a-76da-4d61-a32f-e26a2e9114fc.png)

(couldn't load layout file)

However: When I save the same patch as one big prefab file, the midi controllers are saved.

**Comment by NoxyNixie** [comment]
I'm unable to reproduce this in the latest Nightly build so this may have been resolved.

If this bug happens again, feel free to comment here or create a new issue.
