### ISSUE TITLE
Childprocess for youtube-dl not running

### ISSUE THREAD

**Issue by jhurlbut** [BespokeSynth/BespokeSynth#68]
I can't get the youtube downloading working on either windows or macosx. This is with Juce 6.0.5. The process output is blank and the exit code returned is 0 so it seems like the command was executed but the temp folder is empty. When I run the same command in terminal or cmd prompt it runs fine and downloads to the temp folder. Wondering if you have any idea what the issue might be? Maybe I should try using the same version of Juce as the repo? Thank you.

Here is the example command string (I qualified the youtube-dl path but same result either way) :

running export PATH=/opt/local/bin:$PATH; /usr/local/bin/youtube-dl "ytsearch10:breaks" --no-playlist --write-info-json --skip-download -o "/Users/hurlbut/BespokeSynth/Builds/MacOSX/build/Release/data/youtube_temp/%(title)s#%(duration)s#%(id)s.%(ext)s"
31.8849:  process output: 
31.8849:  exit code: 0

**Comment by KottV** [comment]
I thought that this is just Macos specific formatting and why the current code doesn't work on Linux. So I had to fix it to make work on Linux:
```
--- Source/SamplePlayer.cpp.orig        2021-01-03 23:24:01.482237800 +1000
+++ Source/SamplePlayer.cpp     2021-01-03 23:25:13.254240001 +1000
@@ -455,7 +455,7 @@
 #if BESPOKE_WINDOWS
       return "youtube-dl.exe ";
 #else
-      return "export PATH=/opt/local/bin:$PATH; youtube-dl ";
+      return "youtube-dl ";
 #endif
    }
 }
@@ -480,7 +480,7 @@
          file.deleteFile();
    }

-   string command = GetYoutubeDlPrefix() + search + " --extract-audio --audio-format wav --audio-quality 0 --no-progress -o \""+ ofToDataPath(tempDownloadName) +"\" "+ options;
+   string command = GetYoutubeDlPrefix() + search + " --extract-audio --audio-format wav --audio-quality 0 --no-progress -o "+ ofToDataPath(tempDownloadName) +" "+ options;
    ofLog() << "running " << command;
    mRunningProcessType = RunningProcessType::DownloadYoutube;

@@ -517,7 +517,7 @@
    dir.createDirectory();
    mYoutubeSearchResults.clear();

-   string options = "\"ytsearch"+ofToString(kMaxYoutubeSearchResults)+":"+searchTerm+"\" --no-playlist --write-info-json --skip-download -o \""+tempPath+"/%(title)s#%(duration)s#%(id)s.%(ext)s\"";
+   string options = "ytsearch"+ofToString(10)+":\""+searchTerm+"\" --no-playlist --write-info-json --skip-download -o "+tempPath+"/%(title)s#%(duration)s#%(id)s.%(ext)s";
    string command = GetYoutubeDlPrefix() + options;
    ofLog() << "running " << command;
```
I removed some quotes from command line args. With them it downloads into " (quotation mark) directory where you run Bespoke binary.

**Comment by awwbees** [comment]
I can get it to run in Windows if I place youtube-dl.exe and ffmpeg.exe aside my BespokeSynth.exe, but it looks like ChildProcess requires an absolute path otherwise (it appears to ignore your system's PATH). I have a local change, not submitted yet, to allow the path to youtube-dl.exe to be specified in userprefs.json.

This fix also allows things to run in OSX, but I'm hitting a separate issue in OSX with permissions where youtube-dl can't create the files it wants to place in youtube_temp. It worked when I was just running youtube-dl with a popen(), but not as a ChildProcess. So, OSX is currently a work-in-progress while I figure that out.

**Comment by jhurlbut** [comment]
Thanks for the additional info. I am able to get youtube-dl to run with Childprocess on OSX if I wrap the call into a bash script and pass the values as parameters. I can get the json files downloaded correctly but I'm unable to get the second youtube-dl command to export wav files and to rename and copy into the folder specified by -o. I tried using the --exec flag to run a script to copy and rename the file after downloading but that isn't working either. It seems like these are limitations of youtube-dl though. Looking forward to your progress.

**Comment by jhurlbut** [comment]
It's working good for me in windows so I'll close the issue. Thank you
