### ISSUE TITLE
vst-plugin: `show parameter` doesn't respond to `parameter change request`

### ISSUE THREAD

**Issue by dromer** [BespokeSynth/BespokeSynth#682]
## Describe the bug

It is described in the mouse-over help that the `show parameter` option for the vst-plugin host should respond to parameter changes, however when a plugin sends a `parameter change request` it still doesn't show up.

Tested with: latest Cardinal build -> https://github.com/DISTRHO/Cardinal/commit/28d3ca2d689804b6acd7a07667a8ef6174e18407

Here it is simply sending this call, but with the current value. Perhaps BespokeSynth is actually expecting a _change_ in value? This shouldn't be needed though.

In this case the parameter is a pure input and doesn't have any controls so any value change would then have to be simulated.

## Build info

bespoke 1.1.0 (Dec  9 2021 21:41:07) - Linux - main 8c3f5c2

## Steps To Reproduce

Add plugin. Have plugin send `parameter change request` (connect one of the jacks inside). Do not see parameter appear in the list.

## Expected vs. actual behavior

See the parameter appear in the list.

**Comment by falkTX** [comment]
To be clear, the VST2 plugin here is sending:
1. touch/drag start
2. parameter value change (which matches the currently-set one)
3. touch/drag end

I could tweak cardinal so that it sends a dummy +0.1 and then back -0.1 to make step 2 a "real" parameter change, but that seems hacky and unnecessary.

Tested in FLStudio and it works as-is, no hacks necessary for it.

**Comment by awwbees** [comment]
yeah, I think this is just my own ignorance about the existence of "parameter change request". I'll listen for that.

**Comment by falkTX** [comment]
since bespoke uses juce, you likely want to use `AudioProcessorListener`.
https://docs.juce.com/master/classAudioProcessorListener.html#a38075b5e4654a8c50e135eee40c74f2e or alike, so "gestureBegin" (and not just real parameter changes) bring the parameter to the front.

**Comment by awwbees** [comment]
thank you! I will check that out

**Comment by CarloCattano** [comment]
Can confirm this still happens on last build . Cardinal populates other software but Bespoke ignores the params even when reopening etc
<img src="https://user-images.githubusercontent.com/17380530/147343963-b3f4c81b-03fb-4f54-b78d-60e76bd44f77.png" width="500" height="400">

**Comment by falkTX** [comment]
that gui looks from a very old build of cardinal.
the fake parameter set was not present on that version

**Comment by dromer** [comment]
@falkTX it doesn't work currently either, though. :)

**Comment by Sahaathyva** [comment]
Hi and thanks both for Bespoke and Cardinal marvels,

Sadly still not working using Bespoke 1.1.0 nightly build from the 04/24/2022 and Cardinal v 22.05... :(

This combo is so great i expect this feature to be operationnal a day or another :)

**Comment by awwbees** [comment]
hey, finally fixed this one. it also got me to download cardinal, super cool!! I had for some reason incorrectly assumed that cardinal was linux-only

**Comment by dromer** [comment]
> I had for some reason incorrectly assumed that cardinal was linux-only

Now why would you think that? ;)

And cheers! will try this after the weekend!
