### ISSUE TITLE
deleting effects crash Bespoke

### ISSUE THREAD

**Issue by trvnkwil** [BespokeSynth/BespokeSynth#686]
## Describe the bug

when i delete effects, Bespoke crashes.

## Build info

bespoke 1.1.0 (Dec  8 2021 23:44:55) - Linux - main 6f3bbbc
OS = Manjaro GNOME 21.12

## Steps To Reproduce

- load the savestate
- delete effects in this order
- tremolo, pumper, pitchshift, noisify, granulator, gate, gainstage, freeverb, distortion, delay, dcremover, compressor, butterworth, bitcrush, biquad, basiceq.
- it will give a crash, not sure exactly when because i think it's random but it does crash a lot.

## Expected vs. actual behavior

i should be able to delete effects without a problem but it crashes Bespoke.

https://wormhole.app/neoYA#ogj_V9-Lg32zf6lV_IuNng

**Comment by NoxyNixie** [comment]
The savestate is no longer downloadable so I can't verify with your savestate but I can add and delete effect willy nilly on the latest Nightly build without any crashes.

If this problem re-emerges feel free to reply on this issue and it will be re-opened or you can post a new one ;)
