### ISSUE TITLE
presets module is not saving note values for circlesequencer - upon recalling, resets note0 -> note3 values to 0

### ISSUE THREAD

**Issue by Concrete3vidence** [BespokeSynth/BespokeSynth#687]
## Describe the bug

Shift-clicking on presets modules empty grid saves other parameters of the circlesequencer module, but not the note0, note1, note2, note3

## Build info

bespoke 1.1.0 (Nov 16 2021 11:41:32) - Windows 10 - main bd41884b9

## Steps To Reproduce

Create circlesequencer module, create presets module. Connect presets module to circlesequencer. Save preset with a shiftclick. Reload preset by clicking preset.

## Expected vs. actual behavior

I would expect the presets module to store the note values instead of setting them to 0.

**Comment by redpiranha** [comment]
I have the same issue with the drumsequencer.
### Describe the bug

Clicking on saved preset resets all the rowpitch values to 0 and the steps are unchanged.
### Build info

bespoke 1.1.0 (Nov 16 2021 11:41:32) - Windows 10
### Steps To Reproduce

Create drumsequencer module, create presets module. Connect presets module to drumsequencer. Save preset with a shiftclick. Reload preset by clicking preset.
### Expected vs. actual behavior

I would expect the presets module to store the steps and the rowpitch values.

**Comment by awwbees** [comment]
the originally reported bug here is fixed by #729

the comment is an unrelated issue (the presets module is not designed to store the drumsequencer's grid, it only stores UI control values. although maybe it's a valid feature request for the grid state to be stored by presets as well)
