### ISSUE TITLE
When capo enables a note while notesequencer disables the note at the same time, note becomes stuck

### ISSUE THREAD

**Issue by Amolith** [BespokeSynth/BespokeSynth#689]
## Describe the bug

While playing, there's a sustained note in the background that stops and starts again after a bit. After disabling the note sequencer, it becomes apparent that the tone is coming from the oscillator. Re-enabling the note sequencer and disabling the capo fixes the issue.

From Discord,
> **awwbees:** it looks like there's a bug with a stuck note in the fifth step, due to the `capo` note-on-ing the same note that the `notesequencer` is note-off-ing

## Build info

```
bespoke 1.1.0 (Dec 10 2021 14:36:34) - Linux - makepkg bd41884
```

## Steps To Reproduce

De-compress this archive (GitHub doesn't support uploading `.bsk` files directly) and load the save state.
> [2021-12-14_10-39.bsk.gz](https://github.com/BespokeSynth/BespokeSynth/files/7716246/2021-12-14_10-39.bsk.gz)

**Comment by NoxyNixie** [comment]
I am unable to reproduce the stuck notes with the latest Nightly build.

If this bug resurfaces please comment here or post a new issue.
