### ISSUE TITLE
OSX Catalina Notarization

### ISSUE THREAD

**Issue by z-plane** [BespokeSynth/BespokeSynth#69]
Just FYI, it won't run under OSX Catalina due to Apple's notarization process.

**Comment by awwbees** [comment]
it runs on catalina for me, what is the error that you are getting? apple has gotten pretty aggressive lately in their messaging about running "unauthorized apps", but you should still be able to run it if you jump through the correct hoops.

**Comment by z-plane** [comment]
Yea my bad, I think you have to right click and then open the app rather than double click.
