### ISSUE TITLE
Support hot-loading prefab title bar options

### ISSUE THREAD

**Issue by shiehn** [BespokeSynth/BespokeSynth#694]
## Summary

- currently the title bar options for prefabs are loaded at application start time. If a prefab is removed from the file system and the Bespoke user selects the cached prefab the application will crash

- this change will enable a user to add prefabs to the file system during a running Bespoke session and essentially "hot loads" them

## Proposed Solution:

- read the prefabs directory at runtime when the user selects the prefabs title bar drop down (DropdownClicked). I believe this is a lightweight operation and improves both user experience and stability

## PR: 
[PULL REQUEST](https://github.com/BespokeSynth/BespokeSynth/pull/692)

### Motivation

I am interested in being able to share prefabs across systems.  This is almost possible if the user re-starts Bespoke but is a poor user experience.

**Comment by awwbees** [comment]
merged #692
