### ISSUE TITLE
BespokeSynth terminates with »Getötet«

### ISSUE THREAD

**Issue by ShantySuffisance** [BespokeSynth/BespokeSynth#70]
Hey 

i wanted to try BespokeSynth cause i like the concept and look. Great work! 

When i started BespokeSynth (via terminal) it opened a window without content, it froze all HID and terminated with the message: »Getötet« (killed in German)

Any Ideas how i could use this synth? 

Greetings 
Shanty

Operating System: Ubuntu 18.04.5 LTS
Kernel: Linux 5.4.0-63-generic
Architecture: x86-64

**Comment by awwbees** [comment]
not a very descriptive error, unfortunately! are you able to build from source and possibly get more info? when I put out the latest release, I tested in Ubuntu 18 (can't remember the exact version number I run) and it worked

**Comment by awwbees** [comment]
I could try changing my locale settings on my Ubuntu install to German, maybe I have a Linux-only localization bug due to comma/period separators, this has happened before. if you want to try changing your locale settings, that might be a thing to test!

**Comment by ShantySuffisance** [comment]
> I could try changing my locale settings on my Ubuntu install to German, maybe I have a Linux-only localization bug due to comma/period separators, this has happened before. if you want to try changing your locale settings, that might be a thing to test!

thank you for your advise. 

i changed localisation to english and the Synth started successfully! It also started, when i undid the change in localisation… 

Well, the problem is solved for me, even though not really satisfactory… 

Thank you awwbees!
