### ISSUE TITLE
Laks of edit code abilty in Linux.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#71]
Hi,

The code editing in the Linux is reduced in compare of other platforms (I checked win only): it's imposible to do copy-paste, ctrl-z.
I'm not sure of what it depends, nanovg, juce or overall windowing subsystem.

It would be nice if you check this and say something )

**Comment by awwbees** [comment]
ah, it's likely just an issue with the ctrl key not coming through for some reason, I'll investigate next time I'm running linux. it's probably something in GetKeyModifiers() in SynthGlobals.cpp

**Comment by KottV** [comment]
that makes sense
what I found that some keys works: ctrl+[ and ctrl+] for example, but ctrl+letter - not
I changed copy shortcut to ctrl+insert and paste to the shift+insert and the text is definitely copied to the clipboard, but pressing paste shortcut does inserting some "script~code" string only
looking into the code and I don't see getTextFromClipboard () call in paste block

**Comment by KottV** [comment]
I see this is fixed in https://github.com/awwbees/BespokeSynth/commit/a9d4d5d4032f97f653e0b129762d5e9d197ea586

Thank you!
