### ISSUE TITLE
Crashes on 10.11

### ISSUE THREAD

**Issue by jhelangley** [BespokeSynth/BespokeSynth#711]
I'm on El Capitan 10.11.6 and Bespoke crashes as soon as it loads. The crash report shows 
`Dyld Error Message:
  Symbol not found: _clock_gettime`

Can't build it myself on El Cap so I can't get it working at all currently.

**Comment by NoxyNixie** [comment]
I believe we can't truly support El Capitan anymore since none of the developers owns a machine with it.
