### ISSUE TITLE
Other than Envelope what else can output OSC value?

### ISSUE THREAD

**Issue by enzyme69** [BespokeSynth/BespokeSynth#72]
<img width="1680" alt="Screen Shot 2021-02-19 at 9 44 15 pm" src="https://user-images.githubusercontent.com/3952687/108494527-bee57a80-72fb-11eb-9452-bca6ea6afaf8.png">

I am testing OSC signal sending into other app from BespokeSynth, I am curious on what other node can output "value" other than Envelope.

If I generate random notes, how to get the frequency and math etc?

**Comment by awwbees** [comment]
anything in the purple "modulators" dropdown in the top bar will output a value.
![image](https://user-images.githubusercontent.com/839239/108606248-fbaa8380-7386-11eb-8706-6a8fda34c3bd.png)
to get the frequency of a note, use the "notetofreq" module from that list
to perform math functions, use "add", "subtract", "mult", etc from that list
to get audio data, use the "audiotocv" or "leveltocv" modules from that list

**Comment by awwbees** [comment]
additionally, I'm adding functionality that will allow you to send notes directly into an "oscoutput" module and send the note information, which will be in a release coming soon
