### ISSUE TITLE
Cannot launch the Mac version (missing font)

### ISSUE THREAD

**Issue by metaphorz** [BespokeSynth/BespokeSynth#721]
## Describe the bug

Downloaded the latest .dmg for the Mac. 

## Build info

N/A. Used prebuilt dmg

## Steps To Reproduce

Download Mac dmg and launch. A screen with this error is shown: couldn't load font from /Applications/BespokeSynth/resource/frabk.ttf

## Expected vs. actual behavior

Expect no errors. The error occurs because the ttf file is in the wrong place -- under Resources/resource

**Comment by awwbees** [comment]
I can't reproduce this issue. do you get it when running the latest nightly build from here? https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly

**Comment by metaphorz** [comment]
Ryan

 I did the nightly build after removing the old app from Applications/ for the iMac.

Seems to be working!! Thanks. Probably, the coolest data flow example – as I am

always searching for things to use in class.

-p

 

Paul Fishwick, PhD
Distinguished University Chair of Arts, Technology, and Emerging Communication
Professor of Computer Science
Director, Creative Automata Laboratory
The University of Texas at Dallas
Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Home: utdallas.edu/atec/fishwick
Media: ***@***.***
Modeling: digest.sigsim.org
Twitter: @PaulFishwick

ONLINE: Webex,Collaborate, TEAMS, Zoom, Skype, Hangout

 

 

From: Ryan Challinor ***@***.***>
Reply-To: BespokeSynth/BespokeSynth ***@***.***>
Date: Saturday, January 22, 2022 at 3:33 PM
To: BespokeSynth/BespokeSynth ***@***.***>
Cc: Paul Fishwick ***@***.***>, Author ***@***.***>
Subject: Re: [BespokeSynth/BespokeSynth] Cannot launch the Mac version (missing font) (Issue #721)

 

I can't reproduce this issue. do you get it when running the latest nightly build from here? https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly
