### ISSUE TITLE
RPi4 Bullseye support

### ISSUE THREAD

**Issue by ghost** [BespokeSynth/BespokeSynth#722]
## Summary

Current BespokeSynth need libpython3.7, but Bullseye has libpython 3.8 and 3.9. armhf binary on the website can install BespokeSynth but **can't run it**. Expect the same for arm64 Bullseye.

### Motivation

Since last October 30, 2021. Raspberry Pi OS officially changed to Debian version 11 Bullseye. I hope BespokeSynth will support it.

Best health,

**Comment by KottV** [comment]
just added Raspbian 11 for 1.1.0 release, should be available in hour or so
also you already can get bespokesynth-current for Raspbian 11 https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth-current

**Comment by ghost** [comment]
It working. Thanks :)
