### ISSUE TITLE
Input not working on mac osx

### ISSUE THREAD

**Issue by SATURNIN2** [BespokeSynth/BespokeSynth#726]
Input seems to not working on my mac (10.15.7). No signal when i put the input module, and i don't find bespoke in the permissions for microphone in the preferences... I use oversight and it don't seems to recognise bespoke (normally i get a notification every time an application try to use audio input), it's like bespoke don't even request to use the audio input.
I tried many times to uninstall and reinstall it, even with oversight disabled, but still not working...

bespoke 1.1.0 (Nov 16 2021 11:51:26) - Mac OSX 10.15.7 - main bd41884b

**Comment by awwbees** [comment]
this is fixed in the latest nightly build, available on the "Releases" page
