### ISSUE TITLE
wrong lettercase in ScriptModule_PythonInterface.i #include "OscOutput.h"

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#73]
Hi!

This won't work in case-sensitive OS like Linux:
https://github.com/awwbees/BespokeSynth/blob/master/Source/ScriptModule_PythonInterface.i#L22

#include "OscOutput.h"
should be changed to OSCOutput.h (or filename should be renamed)

**Comment by awwbees** [comment]
d'oh! I hate how case-insensitive file systems allow me to get away with typos like that. thanks for the catch. fixed in ae31f3592536c2ca5d025b7f052ec546502e7846
