### ISSUE TITLE
LFO range

### ISSUE THREAD

**Issue by bretikov** [BespokeSynth/BespokeSynth#731]
## Describe the bug

I found a small bug in the integrated LFO directly in the module.  
## Build info

bespoke NIGHTLY 1.1.0 (Jan 21 2022 05:12:56) - Mac OSX 11.5.2 - HEAD 026ca2e

## Steps To Reproduce

Set the low and high range, which will then appear in the module (green range).  Save the project.  I open the project again and when I change the low and high range in the LFO, this change will not take effect.  The green range remains at the same values ​​as when saved...

## Expected vs. actual behavior
<img width="123" alt="Snímek obrazovky 2022-01-23 v 13 50 58" src="https://user-images.githubusercontent.com/98257558/150679358-546be5dc-0811-4fbf-869c-42cde7cc5341.png">

A description of what you expected to happen vs. what happened.

**Comment by NoxyNixie** [comment]
I can't reproduce this in the latest Nightly build.

If this problem still exists please don't hesitate to reply to this issue or post a new one ;)
