### ISSUE TITLE
Samples with upper file name case in extension aren't shown in the load window

### ISSUE THREAD

**Issue by starry-abyss** [BespokeSynth/BespokeSynth#732]
## Describe the bug

I just want to use a sample file e.g. sample.WAV, but it isn't shown, have to rename it first to sample.wav.
(Upper case is happening for me when I copy samples from my PCM recorder to a Linux computer.)

## Build info

1.1

couldn't copy build info, as this feature (copying build info) just hangs the application for me

## Steps To Reproduce

- rename a .wav sample extension to .WAV
- try to load it into a sampler

## Expected vs. actual behavior

Expected: the .WAV sample in the Bespoke-run file manager
Actual: only .wav samples are shown

**Comment by NoxyNixie** [comment]
I can't reproduce this issue but I'm also on windows where capitalization matters less.

Is this on Linux or Mac per chance? And can you also check if this is still the case with the latest Nightly Build?

**Comment by starry-abyss** [comment]
I believe this was on Linux
