### ISSUE TITLE
Main Menu klick through

### ISSUE THREAD

**Issue by GlOwl** [BespokeSynth/BespokeSynth#741]
## Describe the bug
The main menu is displayed on top but when dragging a module underneath so that a button/"drop down menu"... of the main menu is on top of one of the modules buttons the modules button/"drop down menu"/"text field"... is activated.
![bespoke bug](https://user-images.githubusercontent.com/25726955/151363618-af9fa11a-c753-4012-aaf7-988ee9d3f3c7.png)

## Build info

bespoke 1.1.0 (Dec 25 2007 09:50:38) - Linux - unknown-branch deadbeef

freshly downloaded and installed the .deb version from the following link on Ubuntu 20.04.3 LTS today (27th January 2022)
https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth
https://download.opensuse.org/repositories/home:/bespokesynth/xUbuntu_20.04/amd64/bespokesynth_1.1.0-0_amd64.deb

## Steps To Reproduce

- Create module
- drag underneath main menu
- try to press main menu button

## Expected vs. actual behavior

I would expect the top most drawn button to be activated.

**Comment by awwbees** [comment]
this is fixed in #695, not sure when those opensuse builds are built from

**Comment by KottV** [comment]
nightly builds available at https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth-current
