### ISSUE TITLE
Cabbage VST3s don't show any parameters in the dropdown list by default, even when they have less than 20

### ISSUE THREAD

**Issue by werame** [BespokeSynth/BespokeSynth#744]
## Describe the bug

I have a Cabbage VST3 with just 3 parameters.

![image](https://user-images.githubusercontent.com/97036286/151577025-c45ad32a-9b90-492f-bf63-57ea055edeef.png)

But Bespoke seems to think it has more than 20:

![image](https://user-images.githubusercontent.com/97036286/151576579-13d75af9-6278-4ecc-a543-1a40b5f21c24.png)

They do show up (one by one) in that drop-down list if I follow the advice and wiggle them in the VST's own UI, but that's pretty time consuming to do over and over when I add that VST3.

## Build info

bespoke 1.1.0 (Nov 16 2021 11:41:32) - Windows 10 - main bd41884b9

## Steps To Reproduce

Using Cabbage 2.8.0. Cabbage code for the VST3 effect, adapted from the Cabbage-supplied examples. 

```
<Cabbage>
form size(280, 160), caption("Simple Reverb"), pluginId("cfxr")
groupbox bounds(20, 12, 233, 112), text("Reverb")    
rslider bounds(32, 40, 68, 70), channel("size"), range(0, 1, .2, 1, 0.001), text("Size"), colour(2, 132, 0, 255), 
rslider bounds(102, 40, 68, 70), channel("fco"), range(1, 22000, 10000, 1, 0.001), text("Cut-Off"), colour(2, 132, 0, 255), 
rslider bounds(172, 40, 68, 70), channel("gain"), range(0, 1, .5, 1, 0.001), text("Gain"), colour(2, 132, 0, 255), 
</Cabbage>
<CsoundSynthesizer>
<CsOptions>
-n -d -+rtmidi=NULL -M0 -m0d 
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 64
nchnls = 2
0dbfs=1

instr 1
    kFdBack chnget "size"
    kFco chnget "fco"
    kGain chnget "gain"
    aInL inch 1
    aInR inch 2
    aOutL, aOutR reverbsc aInL, aInR, kFdBack, kFco
    outs aOutL*kGain, aOutR*kGain
endin

</CsInstruments>  
<CsScore>
f1 0 1024 10 1
i1 0 z
</CsScore>
</CsoundSynthesizer>
```

## Expected vs. actual behavior

I'd expect Bespoke to "see" the 3 parameters by itself, without wiggling. Maybe there's something wrong on the Cabbage side, but I'm not sure what.

**Comment by NoxyNixie** [comment]
Parameters show up in the latest Nightly build so this is likely resolved.

If this bug comes back feel free to comment here or post a new issue.
