### ISSUE TITLE
No audio input on macOS

### ISSUE THREAD

**Issue by maedoc** [BespokeSynth/BespokeSynth#746]
## Describe the bug

The audio interface shows up but no sound comes through.

Related perhaps, in the Systems Preferences > Privacy > Microphone settings other applications request microphone access but not Bespoke. 

## Build info

bespoke 1.1.0 (Nov 16 2021 11:48:29) - Mac OSX 11.6 - main bd41884b

## Steps To Reproduce

(This is on a MacBook Air m1)

I start Bespoke, configure in settings to use an audio interface I have (Komplete 2), which works on a Windows 10 machine w/ Bespoke, save & restart Bespoke.  I create an input node, with channels 1&2, connect to output gain, hook up my bass and strum.  The blue lights light up on the audio interface but nothing shows up on the wire from the input node to gain/output.  This works well on my other machine with Win10.  

I thought it might be the audio interface, but I ran Zoom and checked audio settings, and the bass strum makes the meter go up in Zoom and Zoom repeats back the sound of the bass to me. 

## Expected vs. actual behavior

I expected sound to come through.

## ps 

thanks for the awesome synth environment

**Comment by awwbees** [comment]
this should be fixed in the latest nightly build: https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly

I should do a 1.1.1 release with this fix! maybe soon.
