### ISSUE TITLE
motion_trails causes UI flickering

### ISSUE THREAD

**Issue by dancesWithBugs** [BespokeSynth/BespokeSynth#747]
When motion_trails is set to > 0 in the graphics section of the settings, the UI begins flickering when moving things around. It looks like a single frame from the beginning of movement is rendered far too late. Note that this cannot be reproduced in the debug build because the offending frame appears to be skipped when FPS are halved in MainComponent.cpp:128.

Version: 1.1.0 (compiled from git main branch)
OS: Linux

Here's a video:

https://user-images.githubusercontent.com/75453205/152116868-62b36d63-d8ca-4688-8a3d-ab0cd4f34483.mp4

**Comment by KottV** [comment]
Version? OS?

**Comment by dancesWithBugs** [comment]
> Version? OS?

added to OP

**Comment by NoxyNixie** [comment]
The graphics pipeline as well as JUCE have all been updated. This has likely been fixed.

If this is still happening in the latest Nightly build please comment here or create a new issue.
