### ISSUE TITLE
Specific .bsk crashes bespoke upon load in Windows, Linux

### ISSUE THREAD

**Issue by ClintonEmsley** [BespokeSynth/BespokeSynth#748]
## Describe the bug

A fairly simple BSK crashed bespoke every time it is loaded. Can reproduce on Windows, and also verified [another user reproduced on Linux](https://discord.com/channels/846834873254805554/890239057878200350/938351602287378472). 

To my recollection, it's a fairly simple setup: a drum sequencer, drum player, effect chain with 3-4 effects and...maybe an oscillator, I can't remember.

## Build info

bespoke NIGHTLY 1.1.0 (Feb  1 2022 00:08:30)) 
(I copied this from the crash log since i don't have access to the computer currently)

## Steps To Reproduce

- Load the attached BSK file

BSK file: [new_drums.bsk.zip](https://github.com/BespokeSynth/BespokeSynth/files/7987441/new_drums.bsk.zip)
Crash log: [crash_2022-02-01_22-08.txt](https://github.com/BespokeSynth/BespokeSynth/files/7987436/crash_2022-02-01_22-08.txt)

## Expected vs. actual behavior

I expect that this would load rather than crash.

**Comment by ThePython10110** [comment]
This still happens for me...
bespoke NIGHTLY 1.1.0 (Sep 13 2022 00:30:04) - Windows 10 - HEAD 0acb8eb'
But that could just be a platform issue. I don't know, and I don't have a Linux device to test.
