### ISSUE TITLE
Improve Contrast And Visual Accessibility Features

### ISSUE THREAD

**Issue by therealfakemoot** [BespokeSynth/BespokeSynth#751]
It can be difficult to visually distinguish what inputs a module accepts: the color for note and pulse are somewhat similar.

Module Inputs:
* The module input indicators could have different or configurable colors
* icons or graphics could be added to the input indicators 
* mousing over the module or the inputs specifically could display tooltip information

There's also some requests for text scaling options, more UI scaling sliders, and so on.

**Comment by ThePython10110** [comment]
I agree that the pulse/MIDI colors are too similar.

**Comment by NoxyNixie** [comment]
* Configurable colors are in the works here: https://github.com/KottV/BespokeSynth/tree/color-editor
* The input indicators have a PR now: #1106.
> There's also some requests for text scaling options, more UI scaling sliders, and so on.

What exactly do you mean here? Where are these "requests"? There is UI scaling setting which does scale the text too?

**Comment by NoxyNixie** [comment]
If you have more info you can post here and I'll reopen the issue.
