### ISSUE TITLE
Inserting FL Studio VSTi crashes Bespoke

### ISSUE THREAD

**Issue by marcora** [BespokeSynth/BespokeSynth#754]
## Describe the bug

Inserting FL Studio VSTi crashes Bespoke

## Build info

bespoke 1.1.0 (Nov 16 2021 11:51:26) - Mac OSX 11.6 - main bd41884b

## Steps To Reproduce

Fresh install of Bespoke on macOS 11.6 using Homebrew. Latest version of FL Studio installed (20.9).

 ## Expected vs. actual behavior

Bespoke should not crash when inserting FL Studio VSTi and allow FL Studio to be used within Bespoke.

Instead Bespoke crashes with this message:

Initialization error 1

**Comment by marcora** [comment]
Forgot to mention that FL Studio VSTi works just fine in multiple DAWs I have also installed (Ableton Live, Bitwig Studio, Reaper, etc).

**Comment by NoxyNixie** [comment]
Many things have changed around plugins in Bespoke and this bug may have been fixed. If this is still happening on the latest Nightly build please respond here and I'll reopen the issue or create a new issue.

**Comment by marcora** [comment]
The FL Studio plugin issue is now solved. Still several plugins that have
no problems with other DAWs are not working with Bespoke.

[image: image.png]

**Comment by NoxyNixie** [comment]
Good to hear thanks!

That may be plugin specific. Could you create a new issue with crashlogs and plugin names/types? Preferably free or demo versions so that we can more easily reproduce.
