### ISSUE TITLE
Pitchbender Device doesn't seem to work

### ISSUE THREAD

**Issue by rxlxnd** [BespokeSynth/BespokeSynth#755]
## Describe the bug

Hooking the Pitchbender device up to a VST or internal Synth, doesn't seem to do anything. I've checked and the VST has Pitchbend set to +24semitones.

## Build info

bespoke 1.1.0 (Nov 16 2021 11:41:32) - Windows 10 - main bd41884b9

## Steps To Reproduce
hook up a Pitchbender to a VST/Hardware Synth/internal Synth

## Expected vs. actual behavior

Pitch is not bended, Pitch should be bended :)

**Comment by r-o-l-a-n-d** [comment]
sorry, this was due to my own stupidity. One has to pass the notes through the Pitchbender for it to work... of course.
