### ISSUE TITLE
When trying to turn on bespoke, it opens for a moment with a white screen and then crashes.

### ISSUE THREAD

**Issue by Raptorj42** [BespokeSynth/BespokeSynth#761]
[crash_2022-02-21_12-39.txt](https://github.com/BespokeSynth/BespokeSynth/files/8108516/crash_2022-02-21_12-39.txt)
Basically I try to open it, it opens for a moment with a white screen and then closes itself. I do have my laptop "connected" to my desktop and did recently use Bespoke on there. Could it be why it is not working proper on my desktop maybe?

**Comment by Raptorj42** [comment]
[crash_2022-02-21_13-17.txt](https://github.com/BespokeSynth/BespokeSynth/files/8108729/crash_2022-02-21_13-17.txt)
happened on nightly too.

**Comment by NoxyNixie** [comment]
![image](https://user-images.githubusercontent.com/211381/155114263-90a8a0ce-8594-47c2-9bcd-3d3fe06891f1.png)
