### ISSUE TITLE
[Wish list] Everything Quantizer to start instruments and more on time.

### ISSUE THREAD

**Issue by xy124** [BespokeSynth/BespokeSynth#766]
## Summary

Other DAWs like Ableton allow to activate things always on time (first beat of a bar e.g.). While I can think of plenty of 'hacky' ways one could achieve this within BespokeSynth (e.g., using the scripting module or making some fancy pulse magic), it would be cool to have such a feature natively. So to say a gate that can block midi signals, pulses or notes (ok for notes there is already the note quantizer) or whatever until  the next bar / beat /.... In the ideal case this was integratable with the midi controller module allowing to blink activated but waiting controller buttons as Ableton live does it on the launch pad.

### Motivation

This would be very useful for live sessions to activate multiple things in parallel and on beat without human mistake.

I think I could get my hands dirty implementing this on my own but I have no idea what would be the best place to add such a feature / what is the ideomatic way of introducing such a component into BespokeSynth. Setting up the build system might also not be in relation to the few lines of code probably necessary for such a component.

**Comment by NoxyNixie** [comment]
The `pulsetrain` module will now activate its first pulse in sync with the transport so perfect starting things on the beat. This is available in the latest nightly build and was made to work better in 61cd74c1.
