### ISSUE TITLE
Looper is distorted non-default tempo.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#77]
I've just found that when temp is set to any different of initial bpm, then the looper distorts the sound, like huge overdrive.
EDIT: It distorts when the capturing (red) is toggled.

**Comment by KottV** [comment]
And it works fine thru the looper recorder.

**Comment by awwbees** [comment]
ah yeah, I mostly used looper with looperrecorder in the past, so I didn't run into this. here's a new solution, probably not the best one, in 774d742e02afc5752c6c0f090c47b6d1da9ab905
