### ISSUE TITLE
modules that create signals intended to output CV to dc coupled audio interfaces

### ISSUE THREAD

**Issue by solipsvs** [BespokeSynth/BespokeSynth#771]
## Summary  i would absolutely love to use bespoke synth to create signals intended to control my physical modular gear through an expert sleepers interface i will be using with my raspberry pi

Brief explanation of the feature.  pitch cv and gate as well as LFO and ENV generators

### Motivation  there is no solution for linux/raspberry pi for this idea yet

What use cases would this feature improve?  control of my euro modules with my euro racked raspberry pi

If you are able to provide a pull request yourself for the feature that you are
proposing, please say so!  unable

**Comment by NoxyNixie** [comment]
I believe this is already a thing you can do with the `dcoffset` module. You can modulate the offset slider and it will be reflected in your audio output.

![BespokeSynth_20230126_213655](https://user-images.githubusercontent.com/211381/214945017-939bec0b-b02f-47a2-a01b-5ce369a9d586.gif)

How that further maps to your rack is likely up to you and the audio hardware itself.

If you think there is something else missing to achieve this then please don't hesitate to reply to this issue or post a new one ;)
