### ISSUE TITLE
cannot load new scripts in example__scripting.bsk

### ISSUE THREAD

**Issue by khimaros** [BespokeSynth/BespokeSynth#778]
## Describe the bug

when i load example__scripting.bsk, i can select other script files from the dropdown, but clicking load does nothing.

## Build info

bespoke NIGHTLY 1.1.0 (Mar  9 2022 02:30:04) - Linux - HEAD a898b39

## Steps To Reproduce

1. open BespokeSynth
2. load the example__scripting.bsk
3. click dropdown on the python scripting box
4. choose another file
5. click load

## Expected vs. actual behavior

the script should be loaded but instead nothing happens

**Comment by KottV** [comment]
this is caused by https://github.com/BespokeSynth/BespokeSynth/commit/0a1ed8214c4ef6860df8f007ab112bd82cfbf2b0
file is not picked by `load` in script module now 

i reverted this commit in bespoke-current OBS builds

**Comment by khimaros** [comment]
@KottV it looks like this is still broken in the nightly tarballs. is that expected?

**Comment by KottV** [comment]
what tarballs, from @awwbees GH ?

as we can see the issue is still open, I haven't time (and Ryan probably too) to fix it
on OBS builds i've just reverted that commit with script sorting, which seems to break loading

**Comment by awwbees** [comment]
oops, didn't see this until now!
