### ISSUE TITLE
Oscillator wanted for VCV rack

### ISSUE THREAD

**Issue by XtremeSounds** [BespokeSynth/BespokeSynth#780]
HI If we cannot get this Bespoke as a vst plugin, I would like the oscillator module as its own VCV rack module.   IT is so good with all the parameters it has.

**Comment by NoxyNixie** [comment]
I believe this is beyond the scope of Bespoke at this time. There is already way too much to do on Bespoke itself to spend additional developer time on this side project.

If someone in the community wants to do this they "easily" can from the source.
