### ISSUE TITLE
Prehistoric nonfunctional settings in the oscillator module.

### ISSUE THREAD

**Issue by NoxyNixie** [BespokeSynth/BespokeSynth#795]
![image](https://user-images.githubusercontent.com/211381/159822467-6406cb6e-8499-43d5-a521-7c78c05a172f.png)

**Comment by ThePython10110** [comment]
Sill there in bespoke NIGHTLY 1.1.0 (Sep 13 2022 00:30:04) - Windows 10 - HEAD 0acb8eb
