### ISSUE TITLE
Notesequencer. Editing note's velocity drops other notes on step.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#813]
## Describe the bug

When you try to adjust the velocity of note (step) and the step marker is moved to the next, all other columns become silent.

## Build info
From HEAD
Nightly-78-8ef8173e

## Steps To Reproduce

Add notesequencer.
Add/generate some notes.
Try to adjust step volume or try to slide the mouse cursor (with holding RMB) along velocity row.
See attached video.

## Expected vs. actual behavior

All step's velocity must remain.

https://user-images.githubusercontent.com/4686351/163400248-6d14a0ef-7724-429f-8a09-e14b9fce37e8.mp4

**Comment by awwbees** [comment]
hmm, I can't reproduce this issue. what am I doing differently? which platform are you on? I can't reproduce on macOS or windows.

https://user-images.githubusercontent.com/839239/163905208-e76aa017-a6cd-40df-a370-5250febfe7bf.mp4

you mention that you're using RMB to do this, is that correct or a typo? RMB shouldn't work here, only LMB should work, which is what I'm using in the above video.

**Comment by KottV** [comment]
Sorry, Linux (forgot to mention it) and yes, it's with LMB.
On Windows I can't reproduce it too. Is there somewhere I can debug it?

**Comment by awwbees** [comment]
does this only happen with notesequencer, or can you reproduce with controlsequencer?

**Comment by KottV** [comment]
just checked - with notesequencer only

**Comment by KottV** [comment]
Trying to catch what happening here. In the debug build it rarely occurs (and this is bad) so I'm thinking how to get the output of some values to the Bespoke's console (or maybe stdout?).

**Comment by NoxyNixie** [comment]
You can use:
```c++
ofLog() << "Debug output: " << yourvariables;
```
You can chain as many pieces of text as well as variables with the << operator.

ofLog() should output to stdout as well in debug mode.

**Comment by KottV** [comment]
> You can use:
> 
> ```c++
> ofLog() << "Debug output: " << yourvariables;
> ```

It crashes Bespoke when I add `ofLog() << mVels[i];` to the https://github.com/BespokeSynth/BespokeSynth/blob/87a9368bf07c036c4e46cad0af6beabf5742e5c5/Source/NoteStepSequencer.cpp#L434

So I simply used `std:cout` And see that `SyncGridToSeq();` calls `mVelocityGrid->Clear();` https://github.com/BespokeSynth/BespokeSynth/blob/87a9368bf07c036c4e46cad0af6beabf5742e5c5/Source/NoteStepSequencer.cpp#L1035
What it's purpose here and why it works on other OS? I commented that line and problem has gone, now I can set velocities and remove them normally  :)

**Comment by NoxyNixie** [comment]
> It crashes Bespoke when I add ofLog() << mVels[i]; to the

That smells like uninitialized values which tends to behave differently on different systems but normally MSVC catches that in debug mode and it works just fine for me as:
```c++
      for (int i = 0; i < mVelocityGrid->GetCols(); ++i)
      {
         mVels[i] = mVelocityGrid->GetVal(i, 0) * 127;
         ofLog() << mVels[i];
      }
```

I'm kind of confused why it would work if you comment out `mVelocityGrid->Clear();` since the SyncGridToSeq() function should rebuild the grids based on the values in `mVel` and `mTones`.
