### ISSUE TITLE
Karplus synth noise.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#82]
Hi,

There is very audible noise in karplus/strong synth. It sounds like loud pop just after attack then fading pops during decay.
PS. This is on Linux. I'll check Windows later soon.

**Comment by awwbees** [comment]
hmm, I don't see this behavior. do you have any way of capturing a video, to illustrate what might be different for you?

https://user-images.githubusercontent.com/839239/113516681-9df28500-9549-11eb-86b1-4c83050e8636.mp4

**Comment by KottV** [comment]
Nothing wrong on windows:(
Yes, I'll try to record a video.

**Comment by KottV** [comment]
this not so related, but I can't use Window Audio devices in Windows, I recompiled Bespoke with ASIO as workaround (and it's unsupported in OBS screen grabber), other JUCE-based apps works fine

![изображение](https://user-images.githubusercontent.com/4686351/113527764-e3728900-9601-11eb-90bf-80fba0b7fd42.png)

The name of device is correct.

**Comment by awwbees** [comment]
interesting... yes, definitely a separate issue.

Windows Audio does work for me, it is what I primarily use. I wonder if Bespoke is handling the Russian device names incorrectly, and their mere presence is screwing something up somehow? I'm not sure how I could attempt to reproduce this on my end, short of buying a device with a Russian name. (I am assuming this is Russian text, let me know if I am mistaken)

**Comment by KottV** [comment]
It worked before. And with Russian card name (I renamed it to "Speakers").
Ok, nevermind. I considering that my windows setup became broken more and more...

**Comment by KottV** [comment]
>short of buying a device with a Russian name

lol, no :)
you can define any name for device:

![изображение](https://user-images.githubusercontent.com/4686351/113539163-728e9980-9620-11eb-9ad2-0d23846cb3bc.png)

**Comment by KottV** [comment]
@awwbees 
video:


https://user-images.githubusercontent.com/4686351/113559801-5b15d780-9645-11eb-8269-89ea5543d4fc.mp4

**Comment by awwbees** [comment]
> you can define any name for device:

Good to know!

> video:

Interesting! And this only happens on Linux? Very strange. Is it possible that the Xkey is spamming a bunch of control messages? The "double-hit" sound is strange. Does this also reproduce if you use the keyboarddisplay device instead of the Xkey?

I can't reproduce this exact issue, but it does look like karplusstrong is introducing a large DC offset for higher pitch notes (you can see that the waveform goes way off-center). I see that in your video here, and also when I try it myself. If I fix that, maybe that will help resolve your issue.

**Comment by KottV** [comment]
I didn't test Xkey+karpusstrong on Windows neither regular input on Linux. Will do.

**Comment by KottV** [comment]
Tested with keyboardisplay only (as in your video) and there is no any noise on Linux. With XKey it looks like weird reaction on aftertouch commands, but there is no such issue in any other instruments, DAWs etc.
I'll test with other keys and in Windows too next time.

Update:
>Is it possible that the Xkey is spamming a bunch of control messages?

Dunno if it's spam or not, but there are some control messages:
![изображение](https://user-images.githubusercontent.com/4686351/113704785-f4b1b780-971f-11eb-8f79-653f9760b758.png)
or:
![изображение](https://user-images.githubusercontent.com/4686351/113704869-0f842c00-9720-11eb-81d7-d46f3d5fe894.png)

**Comment by KottV** [comment]
It's fixed now.
Thanks
