### ISSUE TITLE
Daw parameters not visible for PlugData VST

### ISSUE THREAD

**Issue by nay-seven** [BespokeSynth/BespokeSynth#822]
When using the vst PlugData, the Daw parameters are not visible ( works in other Daw's)

bespoke NIGHTLY 1.1.0 (Apr 18 2022 02:57:06) - Mac OSX 10.14.6 - HEAD 213d9ac

PlugData lets you use/create Pure data patch in a VST
https://github.com/timothyschoen/PlugData

and an example .pd patch to test:
[test simple osc.pd.zip](https://github.com/BespokeSynth/BespokeSynth/files/8546789/test.simple.osc.pd.zip)

**Comment by KottV** [comment]
Fixed with https://github.com/BespokeSynth/BespokeSynth/commit/e2663cf281a6f45000547f44379ff2797b5ee95d

![изображение](https://user-images.githubusercontent.com/4686351/171074639-872a8c47-5a47-4449-9d5e-22ea6ba5b24b.png)
