### ISSUE TITLE
Linux build issue with missing JUCE header

### ISSUE THREAD

**Issue by djdeath** [BespokeSynth/BespokeSynth#823]
## Build issue on Linux

I'm running into this build issue on Linux Ubuntu 21.10 : 
```
$ cmake -Bignore/build -DCMAKE_BUILD_TYPE=Release
...
/home/user/src/BespokeSynth/Source/AbletonLink.cpp:31:10: fatal error: juce_audio_devices/juce_audio_devices.h: No such file or directory
   31 | #include "juce_audio_devices/juce_audio_devices.h"
```

This file is in the JUCE directory though : 
```
$ find . -name juce_audio_devices.h
./libs/JUCE/modules/juce_audio_devices/juce_audio_devices.h
```

Not sure what's up with that, maybe a cmake issue?

## Build info

N/A

## Steps To Reproduce

Just run :  `cmake -Bignore/build -DCMAKE_BUILD_TYPE=Release`

## Expected vs. actual behavior

N/A

**Comment by NoxyNixie** [comment]
Did you do a:?
```git
git submodule update --init --recursive
```
I'm asking because these kinds of missing headers usually point to not having done an update or not completely?

**Comment by djdeath** [comment]
> Did you do a:?
> 
> ```
> git submodule update --init --recursive
> ```
> 
> I'm asking because these kinds of missing headers usually point to not having done an update or not completely?

Thanks that was my issue :)
