### ISSUE TITLE
Sequential composition

### ISSUE THREAD

**Issue by tobiasBora** [BespokeSynth/BespokeSynth#825]
## Summary

Provide a method to play sequentially/in parallel multiple slots of sound.

### Motivation

As far as I can see, bespokesynth is fundamentally doing "parallel" composition: when we add a new item, it plays at the same time as all others already added items. But in many case, it is handy to write separately multiple musics, and compose them in a more complicated way, in particular sequentially (i.e. play music 1, then music 2…). This is possible in others DAWs, for instance in reaper it is possible to compose tracks in a quite complex way, including sequentially or in parallel:

![image](https://user-images.githubusercontent.com/2164118/165340067-e4dbef59-bf5d-433b-914b-4ff4b9963cbb.png)

It would be great to have something like this in Bespoke. For instance, I see no obvious way to compose two `notecanvas` sequentially:

![image](https://user-images.githubusercontent.com/2164118/165341170-da42baf8-4ff9-456c-bd84-58caa1076071.png)

(of course, in this simple example it is certainly possible to write everything in a single canvas, but then it quickly gets too complicated when we want to add notes in the first part, sync with some other tools like sampleplayer…)

**User interface**

I guess the hardest part here would be to properly design the UI. One possibility would be to create a `ComposeTracks` component, where it would be possible to add tracks and clips in this component. Each clip could take inputs from other components like a sampleplayer (a nice functionality would be to hide all components which are not linked to the current clip when selecting another clip). Then, each clip would be played depending on its duration and position in the tracks (there may be also some options to specify if the transport should be reset when a new clip starts playing).

For fun, I designed a very sketchy and ugly UI to illustrate this idea:

![image](https://user-images.githubusercontent.com/2164118/165345509-f37535eb-0d3d-4341-be7f-765fc589356f.png)

**Possible extensions**

Another cool feature would be to provide a way to add some vertical lines in the `ComposeTracks` (also taking inputs), which would play the clips attached on their left until they receive some inputs (e.g. some pulse/midi events), and then they would play the clips on their left. It would be also cool to provide overlaps/easing transitions, to transit smoothly from one clip to another.

**Comment by KottV** [comment]
>For instance, I see no obvious way to compose two notecanvas sequentially:

![изображение](https://user-images.githubusercontent.com/4686351/165406815-6b51fc36-6881-4753-bb89-38a53812e8cc.png)

Though it won't work for variable canvas length

**Comment by tobiasBora** [comment]
Thanks for the trick! But indeed it won't work in more complex setups as you said.

**Comment by KottV** [comment]
> Thanks for the trick! But indeed it won't work in more complex setups as you said.

with `eventcanvas` you can do it freely aven with overlaping:
![изображение](https://user-images.githubusercontent.com/4686351/165500468-a2e9a949-6ee2-4904-9da0-414ccf25184e.png)

**Comment by awwbees** [comment]
it seems like `eventcanvas` solves this, as @KottV points out, correct? the visuals are pretty identical to the originally proposed solution

**Comment by tobiasBora** [comment]
That looks pretty cool, thanks a lot! I still need to test it to see if we can use it to control any kind of sounds (play/pause/restart...). Unfortunately, for now I can't find how to create a long-lasting event, the events are just fired during a few ms:

![image](https://user-images.githubusercontent.com/2164118/168092273-d96c71aa-d6ff-4b38-9b64-9db9837c1f9c.png)

**EDIT**

Actually, I realized I could resize the events (simply by dragging the right/left side) when the event is not plugged on a "click" button. I'll experiment a bit more.
