### ISSUE TITLE
Multitrack Suggestion

### ISSUE THREAD

**Issue by everythingability** [BespokeSynth/BespokeSynth#830]
When I record a multitrack then bounce it ... the filenames are:

multitrack_2022-05-01_12-12_1.wav
multitrack_2022-05-01_12-12_2.wav
multitrack_2022-05-01_12-12_3.wav

Could they instead, either be in a folder that uses the name of the Bespoke file ... or could each file be the name of the Bespoke file... I have over 100 tracks I'd like to make stems for ... and it's already messy and I'm only on my first.

Thanks.

**Comment by awwbees** [comment]
I could prepend the current save file name to the output file names, yeah

**Comment by everythingability** [comment]
Fab!  Similar for mid exports... <filename>_<notesequencer1>.mid perhaps?
