### ISSUE TITLE
Filename suggestion

### ISSUE THREAD

**Issue by everythingability** [BespokeSynth/BespokeSynth#831]
When I "write audio" I get a file that is named like this.

some_kinda_love_2022-03-25_11-17.wav

For my purposes, the date of that recording isn't that useful. I appreciate something needs to be there, (or does it? - what if it was stored in a folder named "2022-03-25_11-17" in the recordings folder?)

More useful to me would to be able to specify a format string with the key it is in, and the BPM, for example...

/recordings/2022-03-25_11-17/some_kinda_love_F#_120.wav

**Comment by awwbees** [comment]
I think the timestamp plus the save file name is probably going to be the most relevant combo of information. if I made an atonal drone recording that didn't use scales and had no tempo, then having the key and tempo noted in the filename wouldn't be very relevant, right?

**Comment by everythingability** [comment]
Mmm? Yeah I guess... yeah...  I think my aim to to easily (at the Finder level) get to the meta data somehow.... so I don't need to open every file, wait for it to load... write it down...

I wonder if a python walk files script might do the same thing? Open all the .bsk files and write to csv or something. Not a job for you, but would that be possible?

**Comment by awwbees** [comment]
the data is stored in a binary format, so it would be quite difficult for a python script to look at a file and figure out the key/tempo

**Comment by everythingability** [comment]
Ah thanks for the heads-up. I just realised I can "invent" my own filename format... <name>-<key>-<tempo>.bsk, later removing regex matched dates from an .wavs generated.

Thanks for listening, and sorry for wasting your time....
