### ISSUE TITLE
GUI frozen

### ISSUE THREAD

**Issue by tobiasBora** [BespokeSynth/BespokeSynth#833]
## Describe the bug

I opened a few days ago BespokeSynth, and did not use it for a few days, and today I'm using it again, and I can see a strange behavior: the GUI is basically frozen in a short loop (so even if I stop the music, the sound wave continues to move… I can even see the tooltips appearing bellow the buttons repeatedly if I hovered my mouse maybe 0.5s before stopping the music), and the GUI only refreshes when I resize or change the window. Note that I can still click on the transport button or move elements, it just won't be visible graphically. To be more precise, the full GUI is not frozen: often there is a rectangular area where the GUI is refreshed (this area is not always at the same position) while the rest is frozen. This can be seen when zooming the whole interface. This can lead to strange looking results:

![image](https://user-images.githubusercontent.com/2164118/166498700-f60f3942-7e7d-432d-8be0-e2a0de3d24f2.png)

## Build info

bespoke 1.1.0 (Jan  1 1980 00:00:00) - Linux - unknown-branch deadbeef

The reason why the time is strange and the branch is unknown is because I use the NixOs packaged version that removes git to ensure purity and maximize the chance of having reproducible builds. The precise file used to build and install Bespoke is https://github.com/NixOS/nixpkgs/blob/ae00b02e5bc940aeed7fd974965442a70ccc47d6/pkgs/applications/audio/bespokesynth/default.nix and is based on the commit pinned by the revision 1.1.0.

## Steps To Reproduce

No idea how to reproduce it. It occurred only once in my system.

**Comment by KottV** [comment]
It looks that rectangle is a dead window of some plugin, Ildaeil?

**Comment by tobiasBora** [comment]
It's what I thought first, but then I closed the plugin and the same thing was happening, but the refreshing part was moving on the screen. However, I experienced this with multiple other tools since my upgrade (Blender, zoom, Bespokesynth), so I guess it's not a bug of bespokesynth. But out of curiosity, which GUI backend is Bespoke using? (like SDL,Qt,QTK...) I'm trying to see if I can see a common root between blender, zoom and bespokesynth. 

I reported a bug directly to my OS https://github.com/NixOS/nixpkgs/issues/171702

**Comment by tobiasBora** [comment]
Actually, it's even stranger: it seems that when bespokesynth has this issue, it can transmit it to some softwares ^^' It's like COVID but for softwares. The windows of bespokesynth becomes the refreshing part of blender. And when I close bespokesynth, the refreshing part changes in blender and seems to be random.

**Comment by awwbees** [comment]
bespoke renders with nanovg (https://github.com/memononen/nanovg)

**Comment by KottV** [comment]
I'm sure it's a Driver/X11/OpenGL/DE/WM issue, not Bespoke.

**Comment by tobiasBora** [comment]
Thanks, I'll close the issue then. Thanks!
