### ISSUE TITLE
Freeverb is mono

### ISSUE THREAD

**Issue by ednolbed** [BespokeSynth/BespokeSynth#836]
## Describe the bug

The Freeverb plug-in seems to be mono. Should be stereo.

## Build info

bespoke 1.1.0 (Nov 16 2021 11:41:32) - Windows 10 - main bd41884b9

**Comment by awwbees** [comment]
if you send stereo audio into `freeverb`, you get stereo audio out

**Comment by ednolbed** [comment]
That's a bit limiting, I find, because quite often mono sources are made
stereo by means of a reverb. Also, in reality, most sound sources are mono
but become stereo through the space (reverb) and mainly because of our
perception...

Personally, I think it would be an improvement if the reverb was stereo
even when receiving a mono signal. Especially since, for example, the
oscillator is mono...



Jürgen De Blonde
Goedendagstraat 5
9000 Gent
+32 (0)485 024 957

kohn.bandcamp.com
allthingssound.be
soundcloud.com/co9
facebook.com/koneun


Op di 10 mei 2022 om 04:20 schreef Ryan Challinor ***@***.***

**Comment by ednolbed** [comment]
Also, you don't get stereo out. The sound of the reverb itself always
sounds mono, no matter what I put through it.

Jürgen De Blonde
Goedendagstraat 5
9000 Gent
+32 (0)485 024 957

kohn.bandcamp.com
allthingssound.be
soundcloud.com/co9
facebook.com/koneun


Op di 10 mei 2022 om 04:20 schreef Ryan Challinor ***@***.***

**Comment by NoxyNixie** [comment]
I've spotted a bug in the freeverb module that limited the "width" parameter of the freeverb module between 0 and 1. It should have been 0 and 100. This meant that even though the module (and algorithm) is fully stereo the width of this stereo was never fully utilized.

I've posted a fix as a PR here: #838.

There is also a workaround for you in the meantime. If you `control`-`click` on the right side of the width slider you can manually set the maximum to 100 so you can fully utilize the width of the freeverb module.

**Comment by ednolbed** [comment]
Thank you!

That workaround works perfectly!

greetings

Jürgen De Blonde
Goedendagstraat 5
9000 Gent
+32 (0)485 024 957

kohn.bandcamp.com
allthingssound.be
soundcloud.com/co9
facebook.com/koneun


Op di 10 mei 2022 om 17:47 schreef Noxy Nixie ***@***.***>:
