### ISSUE TITLE
expect multichannel audio

### ISSUE THREAD

**Issue by ednolbed** [BespokeSynth/BespokeSynth#837]
## Describe the bug

Some plugins generate a 'yellow exclamation mark' warning that says, 'target expects multichannel audio...' and consequently audio plays only on one channel... The only workaround I found so far is to insert an independent output module, set it to channels 1+2 and insert that module there... This shouldn't be, i feel...

The tremolo module being a good example of that.

**Comment by awwbees** [comment]
if you send multichannel audio into a `tremolo`, it will output multichannel, along with all of the effects.

`signalgenerator` is a good example of a single-channel audio source, though. the best way to convert a single-channel audio source to multichannel is to insert a `panner` module after it.

**Comment by ednolbed** [comment]
Hi, thanks for your reply. In this case (see screen grab) the situation
just makes very little sense and feels quite counterintuitive
[image: image.png]


The oscillator sounds on both channels, the signalgenerator only on left.

Kindest regards

Jürgen De Blonde
Goedendagstraat 5
9000 Gent
+32 (0)485 024 957

kohn.bandcamp.com
allthingssound.be
soundcloud.com/co9
facebook.com/koneun


Op di 10 mei 2022 om 04:19 schreef Ryan Challinor ***@***.***

**Comment by NoxyNixie** [comment]
Hi, It looks like your "screengrab" is not received on Github. the following is all we see on Github:

> [image: image.png] 

Could you perhaps upload and clarify your message on Github?

**Comment by ednolbed** [comment]
![bespoke screengrb](https://user-images.githubusercontent.com/105210684/167686214-4e4a7739-1436-40da-be4b-fcb5d4991a5e.png)

**Comment by NoxyNixie** [comment]
I'm not really seeing how this is counterintuitive. The connection of the mono signal into the gain module even gives you a warning about the mono signal.

Maybe it confuses you that the `effectchain` module always outputs as many channels as you feed into it?

Either way as @awwbees mentioned this is easily resolved by explicitly stating that you want a stereo signal through the use of a `panner` module:

![image](https://user-images.githubusercontent.com/211381/167694043-a0c02f47-ca42-4ce9-8da0-60f5cd641252.png)

**Comment by ednolbed** [comment]
Hey,

Thanks for getting back. It's counterintuitive because there's no way you
can tell whether a module is mono or stereo, let alone how the gain or any
module really will interpret it.

I don't think it's a problem that the effectsmodule outputs what you feed
it, it's just strange, imo, that it then is only fed to one channel at the
final stage. Like I said, there's no way of telling. I worked a lot with
audiomulch back in the days, and there you could always see how many ins
and outs a module had OR how many it expected. I guess maybe I sort of
expecting that because of that...

It's great that there a warning, for sure, but I did not find a quick and
intuitive way of solving that problem, so initially it was frustrating.
I've learnt indeed that a panner can solve the problem, but then again, I
am surprised that the panner is not present in the "add effect" dropdown
menu in the "effectchain", which could've hinted in the right direction.

Oh, and by the way, besides being critical, I really dig Bespoke. It's real
fun. The ability to save the last half hour is superb!

Also, may I make a suggestion? It would be great to make the handles in
'sea of grains' and the 'multitap delay' controllable by mouse, by dragging
them... But maybe I should put that in the suggestions on Github. 'Sea of
grains' is insanely great, btw.

kindest regards

Jürgen De Blonde
Goedendagstraat 5
9000 Gent
+32 (0)485 024 957

kohn.bandcamp.com
allthingssound.be
soundcloud.com/co9
facebook.com/koneun


Op di 10 mei 2022 om 20:08 schreef Noxy Nixie ***@***.***>:

**Comment by NoxyNixie** [comment]
> It's counterintuitive because there's no way you can tell whether a module is mono or stereo, let alone how the gain or any module really will interpret it.

Almost all modules that deal with audio are stereo capable. You can fairly easily see if you are dealing with a stereo or mono cable.

> that it then is only fed to one channel at the final stage.

It is feeding to one channel since you connected both a stereo signal and a mono signal to the same module. If you only connected a mono signal the output would have been split to both left and right:

![image](https://user-images.githubusercontent.com/211381/167700767-34818f06-434e-40cc-85d2-99cdba0f0090.png)

> I am surprised that the panner is not present in the "add effect" dropdown menu in the "effectchain"

This is because it isn't an effect and it would also not work since the effectchain does not change the signal type.

> besides being critical, I really dig Bespoke. It's real fun.

Please stay critical, not everything is obvious to everyone and I must admit I've been digging around in the code and even there not everything is obvious. I can't have a "new user experience" since I've already learned so much about bespoke.

> Also, may I make a suggestion? It would be great to make the handles in 'sea of grains' and the 'multitap delay' controllable by mouse, by dragging them... But maybe I should put that in the suggestions on Github.

Since this issue is already closed I'm not sure a new suggestion on this issue will be seen and/or remembered so absolutely make a new issue ;)
