### ISSUE TITLE
Feature. Presets for modules.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#84]
Hi Ryan! Glad to see you back from RSI.

I have an idea. What about saving presets per module? As BespokeSyntsh saves whole state then we can save separate module state. I assume these presets can be keep in data/presets/"modulename"/"presetname"

Kind of mock-up
![saveas](https://user-images.githubusercontent.com/4686351/115108673-1b3fe000-9fb5-11eb-8a68-d5e15d786fcd.png)
:

It will greatly improve the workflow: allow to share sequenser's patterns, effect presets (everything) between projects.
For some modules, such script editor, it can be disabled.

**Comment by awwbees** [comment]
I think if you use the "prefab" module, this will give you the functionality you are looking for. it is like a mini-savestate for a collection of modules. saved prefabs can then be loaded from the prefabs menu on the top bar, or quick-spawned by holding the first letter of a prefab's filename.

**Comment by awwbees** [comment]
but I do see what you're getting at... a per-module version of this would be very convenient, with a UI like the one you're describing

**Comment by KottV** [comment]
I totally forgot about  prefabs.

**Comment by ThePython10110** [comment]
The preset module exists now, so this can probably be closes.

**Comment by awwbees** [comment]
the version that @KottV describes still seems cool and useful, I'd like to implement it someday

**Comment by KottV** [comment]
OMG, so great :)
