### ISSUE TITLE
Notecanvas Lost Notes Randomly When outputting Notes

### ISSUE THREAD

**Issue by Bosegluon** [BespokeSynth/BespokeSynth#844]
## Describe the bug

When I use a notecanvas with a measures of 4 and the number of music bars is more than 40 or so, some random notes are not output when they should be output, and I also don't see the animation of its cable.

## Build info

bespoke NIGHTLY 1.1.0 (May 19 2022 01:30:08) - Windows 10 - HEAD c14bccd
and
bespoke 1.1.0

## Steps To Reproduce

see the zip

[w.zip](https://github.com/BespokeSynth/BespokeSynth/files/8746098/w.zip)

**Comment by ThePython10110** [comment]
This works perfectly for me.
bespoke NIGHTLY 1.1.0 (Sep 13 2022 00:30:04) - Windows 10 - HEAD 0acb8eb

**Comment by KottV** [comment]
@Bosegluon not reproduced on my side too.
You can check the output of `notecanvas` with `notedisplayer`.

**Comment by NoxyNixie** [comment]
I am unable to reproduce this with the provided savestate. It all works perfectly on my end with the latest Nightly build.

If this issue still happens or if it comes back please feel free to comment here or create a new issue.
