### ISSUE TITLE
choppy sound  with sound card

### ISSUE THREAD

**Issue by clairewiwi** [BespokeSynth/BespokeSynth#845]
Hi, i have just installed Bespoke synth on my Ubuntu 18.04.5 but my sound is very choppy. I have tested with 2 different ubuntu compatible soundcards, using ALSA.  I tried the exact same configuration and sound cards with Pure Data where my sound comes out perfectly. 
Input: Presonus audiobox iTwo direct hardware device without any conversions
Output: Presonus audiobox iTwo direct hardware device without any conversions
44100 sample rate
When i use my internal intel sound card sound is good through Bespoke. 
It seems that for both of my sound cards they are  listed as a mixer or speaker on the list proposed

Many thanks for sharing lights ;)

![bespokebug](https://user-images.githubusercontent.com/8216968/169836562-5935cbbd-5eaa-455a-b359-714e7b0836c2.png)

**Comment by KottV** [comment]
Hi,

Is your hardware controlled by PulseAudio? Did you try to disabled it (with pasuspender) ?

**Comment by clairewiwi** [comment]
Thanks KottV
Yes i use  PulseAudio and pasuspender did the trick! Many thanks i can have fun now ;)
$ pasuspender -- alsa --device hw:0

**Comment by KottV** [comment]
Yeah, it's known that JUCE apps and PulseAudio cannot directly access to the soundcard together.
If you need PA for that device you may consider to use Jack with jack-pulsaudio bridge.

**Comment by clairewiwi** [comment]
Ok, many thanks for the advice i will try that and see what is the best option.

**Comment by NoxyNixie** [comment]
I believe this resolves the issue right? If it is a JUCE issue that it can't negotiate with pulseaudio I doubt we can do much on Bespoke's side to resolve it.
