### ISSUE TITLE
Wrong selector connection from loading state.

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#85]
And it's impossible to remove "main" output (it always draw the new one connector), only to delete selector module and add it again.

Initial patch:
![Screenshot_20210418_131634](https://user-images.githubusercontent.com/4686351/115133064-ad44f880-a048-11eb-8956-ce82d7d2c222.png)

Loaded patch:
![Screenshot_20210418_131711](https://user-images.githubusercontent.com/4686351/115133068-b5049d00-a048-11eb-956e-9bf30b22eb2f.png)

**Comment by awwbees** [comment]
fixed in 6ccf017b7813149514ce5ff80102298673f8edda !
