### ISSUE TITLE
Stuck notes with controlled `notegate`

### ISSUE THREAD

**Issue by NoxyNixie** [BespokeSynth/BespokeSynth#855]
## Describe the bug

Stuck notes with controlled `notegate`.

## Build info

bespoke NIGHTLY 1.1.0 (Jun  4 2022 02:32:42) - Windows 10 - HEAD 298e472

## Steps To Reproduce

Notes are getting stuck on in the following scenario:
![image](https://user-images.githubusercontent.com/211381/171991716-fc52d801-854d-4c21-a7f7-041933c975d6.png)

[bug_stuck_notes_2022-06-04_10-36.zip](https://github.com/BespokeSynth/BespokeSynth/files/8837306/bug_stuck_notes_2022-06-04_10-36.zip)

Loading the above savestate seems to not reproduce this issue but when I build the same or similar network, the newly build one will display the incorrect behavior and have stuck notes.

## Expected vs. actual behavior

Notes to not be stuck on.

**Comment by awwbees** [comment]
#904 should fix this
