### ISSUE TITLE
Add a way to sync Bespoke with an external clock

### ISSUE THREAD

**Issue by GiulioCocconi** [BespokeSynth/BespokeSynth#856]
## Summary

Add a way to sync Bespoke with an external clock

### Motivation
It would improve any setup using an external controller connected with hw

I would be able to submit a pull request with a little help

**Comment by KottV** [comment]
`clockin` and `clockout` modules, no? :)

**Comment by NoxyNixie** [comment]
Indeed `clockin` exists in the Nightly builds which can adjust the tempo from incoming midi. Do you mean that or do you want a different form of synchronization?

**Comment by GiulioCocconi** [comment]
Yes,`clockin` works fine but since Nightly features aren't present in the docs I hadn't noticed...sorry
