### ISSUE TITLE
No font showing on Windows build

### ISSUE THREAD

**Issue by angelhandgel** [BespokeSynth/BespokeSynth#86]
There is no text visible.  Is this related to the graphics card?
![image](https://user-images.githubusercontent.com/83003232/115682046-fea4fe80-a34c-11eb-8e51-29f8f4cdaaf1.png)

**Comment by awwbees** [comment]
that's a new one to me! do you see the font file `frabk.ttf` in the `data` directory next to `BespokeSynth.exe`?

I suppose it _could_ be a graphics card issue if you have some bizarre or ancient graphics card that doesn't support some OpenGL features, but that would be surprising.

**Comment by angelhandgel** [comment]
It's an Intel(R) UHD Graphics 630.  The font is there and it is installed.

**Comment by awwbees** [comment]
hmm, yeah, it definitely seems like that graphics card should be fine. I'm a bit at a loss for what the issue could be... I'll have to think about it. later tonight I could make a custom build to try to learn more info from your machine.

for what it's worth, if I delete those fonts from the `data` directory, I get the same results as your screenshot.

**Comment by angelhandgel** [comment]
This is a more powerful machine (work laptop to test it) than I'm used to but when I've ran it on my surface pro 7 there's no issue with the font. However the program crashes on the surface, I think due to the graphics card getting maxed out. Pretty frustrated because I love your program.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by awwbees** [comment]
can you try this build on the machine with the UHD Graphics 630, and post a screenshot of what you see?
[BespokeFontTest.zip](https://github.com/awwbees/BespokeSynth/files/6362397/BespokeFontTest.zip)

**Comment by angelhandgel** [comment]
Sorry but this version doesn't boot up.

**Comment by awwbees** [comment]
since you have now posted a more recent issue, it sounds like this one has resolved
