### ISSUE TITLE
How to import a custom external module inside a script in Besproke?

### ISSUE THREAD

**Issue by MNbrpopo12** [BespokeSynth/BespokeSynth#868]
Hello. I can't figure out how to import a custom module inside a script in Besproke?
I'm trying to create a complex long sequence of notes and plug it in the original sequence module (arpeggiate_input.py).
However, using Python's standard import rules returns an error that my module is not defined.
Are there any special conditions for importing a third party module?

**Comment by NoxyNixie** [comment]
Bespoke's python is in its own folder. On windows this is where you installed Bespoke in the subfolder `python`. You can verify where `python` is looking with the following script:
```python
import sys
me.output(sys.executable)
me.output(sys.version)
me.output(sys.path)
```
When run in Bespoke it should look something like:
![image](https://github.com/user-attachments/assets/babeb297-a35e-4608-9e26-8236efba9d6f)

This should allow you to place your scripts where Bespoke's python can find them.
