### ISSUE TITLE
High GPU usage

### ISSUE THREAD

**Issue by angelhandgel** [BespokeSynth/BespokeSynth#87]
Hi Ryan, 

Now I'm trying it on my Surface Pro 7 and the GPU is at 80%.  If I start adding modules or even try to scroll in and out, the program crashes.  Is this normal for the GPU to be so high?  Does Bespoke need a decent graphic card?

![image](https://user-images.githubusercontent.com/83003232/115777873-bc5fd980-a3ad-11eb-98ee-ea9f5ae9acf2.png)

**Comment by awwbees** [comment]
[edit... reposting below. I just realized I was accidentally recording my screen with OBS when I took the screenshot, which consumes GPU, so the real usage is even lower, as seen below]

**Comment by awwbees** [comment]
it shouldn't... it runs just fine on my 2013 macbook pro, for example. I primarily used bespoke on that laptop for many years. here it is in running in windows with a much more complex patch, on a GTX 1070, which is a fairly old card. I'm sure there are plenty of ways the graphics could be optimized, but in their current state they shouldn't be presenting a bottleneck/roadblock. maybe you've got some graphics driver issues? not sure.
![image](https://user-images.githubusercontent.com/839239/115815822-aeb64e00-a3c5-11eb-84c9-6da287c4541c.png)

**Comment by angelhandgel** [comment]
Looking at the memory usage, maybe my issue is a lack of RAM.  Presumably the memory usage increases with the more complex patches?  Is there a minimum amount of RAM required to run the program?

**Comment by awwbees** [comment]
the primary thing that consumes ram is any modules that have sample data or record sample data, so memory usage will go up when you add modules like that.

but, there is a baseline large amount of memory that gets eaten up due to my recording system: bespoke is always recording the last 30 minutes of audio, to allow the user can save the sounds they just made. this is a pretty significant chunk of memory (about 700mb according to my napkin math), so I should make that record buffer size configurable, to better support devices with less memory. soon I'll make a build like that for you, which you can test

**Comment by awwbees** [comment]
here's a build which cuts that record buffer down to just 1 minute long, for you to test
[BespokeLowMem.zip](https://github.com/awwbees/BespokeSynth/files/6366968/BespokeLowMem.zip)

**Comment by angelhandgel** [comment]
Hi mate, that's sorted it.  Thanks!  It's a great feature but it was obviously what was dragging my pc down.  Is the amount of time it buffers configurable in the user preferences?  Is that what the buffer size in the settings do?  I love the tooltips by the way!

**Comment by awwbees** [comment]
it's not yet configurable, I'll add the ability to configure it soon. in this build, the record buffer is hardcoded to 1 minute long (instead of 30 minutes).

the "buffer size" option in the settings is different, it refers to how the audio processing slices time into chunks.

**Comment by NewNodeGames** [comment]
> Looking at the memory usage, maybe my issue is a lack of RAM. Presumably the memory usage increases with the more complex patches? Is there a minimum amount of RAM required to run the program?

the ram usage is abnormally high, even with an empty project (1.4 gb approx)

**Comment by awwbees** [comment]
this is pretty much entirely due to the 30 minute audio recording buffer. if you go into the settings, you can set it to as low as 1 minute, drastically reducing RAM usage.
