### ISSUE TITLE
pulsesequence

### ISSUE THREAD

**Issue by wolfnotdog** [BespokeSynth/BespokeSynth#877]
## Describe the bug

When changing the maximum length of pulsesequence above 32 to 64 by CTRL + right clicking and moving the slider forces a crash of Bespoke.

## Build info

bespoke 1.1.0 (Nov 16 2021 11:41:32) - Windows 10 - main bd41884b9

## Steps To Reproduce

>place pulsesequence empty on workspace
>CTRL + right mouse on length
>type 64 in right hand box
>hit enter
>drag length slider to the right
>crash

## Expected vs. actual behavior

I expected to be able to change the amount of sequences higher than 32. What I get is crash of Bespoke.

**Comment by KottV** [comment]
>bespoke 1.1.0 (Nov 16 2021 11:41:32) - Windows 10 - main https://github.com/BespokeSynth/BespokeSynth/commit/bd41884b9032b585c6271b6d91f8942d3fac4e2b

It's an old build. Did the nightly build crash?

**Comment by wolfnotdog** [comment]
Good morning
I didn't realize that was an old build. I will try the newest build today.
Sincerely
B.

Just because I lay near the fire does not mean I will not eat you.

------- Original Message -------

**Comment by wolfnotdog** [comment]
Yes it did crash
bespoke NIGHTLY 1.1.0 (Jul 9 2022 04:39:50) - Windows 10 - HEAD 2c959c6

Just because I lay near the fire does not mean I will not eat you.

------- Original Message -------

**Comment by KottV** [comment]
it must not be 64 or any value greater than 32

@awwbees 
looks it goes over `kMaxSteps`, I looked at other modules and adding `mLength = MIN(mLength, kMaxSteps);` in `PulseSequence.cpp` fixes that

```
void PulseSequence::IntSliderUpdated(IntSlider* slider, int oldVal)
{
   if (slider == mLengthSlider)
   {
      mLength = MIN(mLength, kMaxSteps);
      mVelocityGrid->SetGrid(mLength, 1);
      GridUpdated(mVelocityGrid, 0, 0, 0, 0);
   }
}
```

otherwise we got division by zero or `this->mIntervalSelector was nullptr`
