### ISSUE TITLE
midicontroler remap

### ISSUE THREAD

**Issue by wolfnotdog** [BespokeSynth/BespokeSynth#878]
## Describe the bug

I cannot remap specific keys from my Alesis V25 to any of the default notes or controllers

## Build info

bespoke NIGHTLY 1.1.0 (Jul  9 2022 04:39:50) - Windows 10 - HEAD 2c959c6

## Steps To Reproduce

1. Open midicontroler
2. Select V25 from list
3. Open 'Layout'
4. Select 'default' from the 'Layout' drop down menu
5. Select 'bind (hold shift)'
5. Hover pointer over desired note or cc,
6. Hold shift while actuating key or button,
7. Nothing remaps

## Expected vs. actual behavior

I expected the key to be remapped to a new position on the layout.

**Comment by ThePython10110** [comment]
As far as I know, you can't map notes and cc's to other notes and cc's. The mapping is meant so that you can control other modules with MIDI.

**Comment by awwbees** [comment]
yes, this is a misunderstanding of the feature. instead, you should be hovering over a control on a different module for step 6. this will bind the actuated button to the control you were hovering over.
