### ISSUE TITLE
VST Plugins (and other audio objects?) are never removed from the processing loop

### ISSUE THREAD

**Issue by baconpaul** [BespokeSynth/BespokeSynth#881]
When debugging the VST Plugin I noticed that `::Process` gets called even after I delete the VST Plugin. You can see this by putting a print there, creating a VST, deleting it, and watching the print go by.

The reason for this is because

1. `ModularSynth::OnModuleDeleted` starts with a check `if (!module->CanBeDeleted() || module->IsDeleted()) return`
2. BUT `ModularSynth::DeleteModule` calls `module->MarkAsDeleted` before it calls `TheSynth->OnModuleDeleted`
3. So every deleted plugin skips all of `OnModuleDeleted` which is what removes a plugin from `mSources`
4. So the modular synth loop over `mSources` keeps you alive and calls you

Seems wrong. but also seems like fixing it will show up a lot of bugs which will occur when we do *actually* delete things?

**Comment by awwbees** [comment]
I think my PR #542 fixes this, which I've been sitting on for months. I'm waiting for a good time to merge at a safe spot after a big release, since it has the potential to reveal a lot of nasty bugs, as you say.

**Comment by baconpaul** [comment]
Yup that's the fix I was too scared to suggest also :)

I'll close this. But you should merge that!
