### ISSUE TITLE
prefabs shrinking and cables

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#89]
prefabs rises and shrinks on bottom and right sides, but on left and bottom it's rises only, only way is to move all modules into left bottom then
![изображение](https://user-images.githubusercontent.com/4686351/119261572-56b87480-bc1b-11eb-923c-51055dae3b19.png)

if prefabs is minimized - cables are left hanging on canvas or disappeared. Not sure... how it can be fixed. Is it difficult to solve?
![изображение](https://user-images.githubusercontent.com/4686351/119261727-ffff6a80-bc1b-11eb-8dc3-2d50cfa13da6.png)

**Comment by awwbees** [comment]
fixed the issue with cables drawing incorrectly with minimized prefabs in 44b1b0655d71da4d6b3bb06790de81ef87e0a63a

the behavior with the prefab window sizing does have some oddness to it, but the design is behaving as intended. I'll think a bit in the future about a cleaner way to handle it

**Comment by KottV** [comment]
Hi!

Thanks for fix, only the modulation cable has not redrawn:

![изображение](https://user-images.githubusercontent.com/4686351/126137919-1f665a00-18e7-4669-bc7f-fadfcb6328f1.png)

**Comment by awwbees** [comment]
got it! 9265e0c9895f33ddf0f64325ac0c71c0d5c6970f thanks for the report
