### ISSUE TITLE
midicontroller polyphony

### ISSUE THREAD

**Issue by ibz** [BespokeSynth/BespokeSynth#903]
I have this setup: `midicontroller` -> `oscillator` -> `gain` -> `splitter` -> `output`.

The `midicontroller` does not seem to output multiple keys pressed simultaneously on my physical keyboard.

HOWEVER:

If I feed `midicontroller` into a `keyboarddisplay` and *then* into `oscillator` and I press one key on my physical MIDI keyboard and one key on the `keyboarddisplay` using the mouse, both keys can be heard, which makes me think the issue is with `midicontroller` and not with the rest of the setup.

ALSO:

If I open the "layout" of the `midicontroller`, I can see multiple keys being pressed at the same time, which means the correct signal is being sent all the way to the `midicontroller` component.

I am thinking this *should* just work, but of course I might be missing something very obvious. But then, maybe it could be better documented somehow?

Cheers!

**Comment by awwbees** [comment]
the setup that you describe should work fine, and does for me, as demonstrated in the video below. I'm not sure what could be happening on your end. is it possible that you have your keyboard set to some sort of "mono" mode or something?

https://user-images.githubusercontent.com/839239/186802988-d9d735d7-60d8-4b60-9acd-1d2d706c7449.mp4

**Comment by PowerUser64** [comment]
Cannot reproduce
