### ISSUE TITLE
Bespoke won't load FM8 VST

### ISSUE THREAD

**Issue by wrightflyer** [BespokeSynth/BespokeSynth#905]
Perhaps I'm just expecting too much because Bespoke happily scans and finds (and will then load) all the VST3 files under Windows C:\Program Files\Common Files\VST3 but I recently got a copy of FM8 by Native Instruments but this supplies a .DLL rather than .VST3 file in C:\Program Files\Native Instruments\VST Plugins x64\. (note directory name does include "VST" so I assume it really is?). Cakewalk finds and loads the DLL as a VST with no issues and it's just listed in among the VST from VST3 files. But Bespoke won't see it. I naively thought VST3 might just be DLL with a changed extension so, in case Bespoke is only looking for VST* files I made a copy of FM8.dll as FM8.vst3 in a new directory and told Bespoke where to look. After that it found the file but gave a message about "invalid plug in" then listed FM8.vst3

## Build info

Not near laptop now. Will add later but I literally just downloaded Bespoke a few days ago maybe 23/24th August 2022? 

## Steps To Reproduce

Install FM8 from Native Instruments (think their site has a trial version too) then add the directory to Bespoke and Scan

## Expected vs. actual behavior

Expect the VST to be found and listed (like in Cakewalk). In fact it is not found in scan.

Perhaps expecting too much? Perhaps the issue here is Native Instruments should supply .vst3 rather than .dll? But I keep coming back to the fact that Cakewalk seems to be able to handle both and treats them all like VST3?

**Comment by NoxyNixie** [comment]
Did you add the path `C:\Program Files\Native Instruments\VST Plugins x64` to the search list in Bespoke's plugin manager?

**Comment by wrightflyer** [comment]
Yup that was added.

**Comment by NoxyNixie** [comment]
hhmm a quick (not thorough) inspection of the website lists only VST (and not VST3) as supported interfaces. You should never need to change the extension from `.dll` to `.vst3` and if done so will likely not result in anything usable. Are you sure it is a VST3? Have you tried scanning it as a VST instead?

![image](https://user-images.githubusercontent.com/211381/188231795-4e45e3c0-377a-4205-816d-688a23f0dc19.png)

**Comment by wrightflyer** [comment]
A thousand apologies - this was more about my misunderstanding (a) that FM8 is not VST3 (just assumed it would be!) and (b) not entirely understanding Bespoke's VST scan and that it has separate scans for VSt and VST3. So, yeah, it works nicely so there is NO ISSUE here and will close.

But let me take the opportunity to say that Bespoke is a work of utter genius. I love the workflow and find it so much more intuitive than any other DAW.
