### ISSUE TITLE
1.1.0: Build fails due to undeclared member mPluginListWindow

### ISSUE THREAD

**Issue by dvzrv** [BespokeSynth/BespokeSynth#918]
## Describe the bug

When trying to rebuild 1.1.0 for a soname bump in another library on Arch Linux I get a failing build:

```
[ 99%] Building CXX object Source/CMakeFiles/BespokeSynth.dir/__/libs/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.o
cd /build/bespokesynth/src/build/Source && /usr/bin/c++ -DBESPOKE_LINUX=1 -DJUCE_ALLOW_STATIC_NULL_VARIABLES=0 -DJUCE_ALSA=1 -DJUCE_CATCH_UNHANDLED_EXCEPTIONS=0 -DJUCE_COREGRAPHICS_DRAW_ASYNC=1 -DJUCE_DIRECTSOUND=1 -DJUCE_DISPLAY_SPLASH_SCREEN=0 -DJUCE_GLOBAL_MODULE_SETTINGS_INCLUDED=1 -DJUCE_JACK=1 -DJUCE_JACK_CLIENT
_NAME=\"BespokeSynth\" -DJUCE_MODAL_LOOPS_PERMITTED=1 -DJUCE_MODULE_AVAILABLE_juce_audio_basics=1 -DJUCE_MODULE_AVAILABLE_juce_audio_devices=1 -DJUCE_MODULE_AVAILABLE_juce_audio_formats=1 -DJUCE_MODULE_AVAILABLE_juce_audio_processors=1 -DJUCE_MODULE_AVAILABLE_juce_core=1 -DJUCE_MODULE_AVAILABLE_juce_data_structures=1
-DJUCE_MODULE_AVAILABLE_juce_events=1 -DJUCE_MODULE_AVAILABLE_juce_graphics=1 -DJUCE_MODULE_AVAILABLE_juce_gui_basics=1 -DJUCE_MODULE_AVAILABLE_juce_gui_extra=1 -DJUCE_MODULE_AVAILABLE_juce_opengl=1 -DJUCE_MODULE_AVAILABLE_juce_osc=1 -DJUCE_PLUGINHOST_VST3=1 -DJUCE_PLUGINHOST_VST=0 -DJUCE_REPORT_APP_USAGE=0 -DJUCE_STA
NDALONE_APPLICATION=1 -DJUCE_STRICT_REFCOUNTEDPOINTER=1 -DJUCE_USE_CAMERA=disabled -DJUCE_USE_CURL=0 -DJUCE_VST3_CAN_REPLACE_VST2=0 -DJUCE_WASAPI=1 -DJUCE_WEB_BROWSER=0 -DLINUX=1 -DNDEBUG=1 -DPYBIND11_EXPORT="" -D_NDEBUG=1 -I/build/bespokesynth/src/build/Source/BespokeSynth_artefacts/JuceLibraryCode -I/build/bespokesy
nth/src/bespokesynth/Source -I/usr/include/python3.10 -I/build/bespokesynth/src/bespokesynth/libs/exprtk/include -I/build/bespokesynth/src/bespokesynth/libs/freeverb/. -I/build/bespokesynth/src/bespokesynth/libs/leathers/. -I/build/bespokesynth/src/bespokesynth/libs/nanovg/. -I/build/bespokesynth/src/bespokesynth/libs
/psmove/include -I/build/bespokesynth/src/bespokesynth/libs/push2/include -I/build/bespokesynth/src/bespokesynth/libs/xwax/. -I/build/bespokesynth/src/bespokesynth/libs/oddsound-mts/MTS-ESP/Client -I/build/bespokesynth/src/bespokesynth/libs/JUCE/modules -I/build/bespokesynth/src/bespokesynth/libs/JUCE/modules/juce_aud
io_processors/format_types/VST3_SDK -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security
 -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -fPIE -pthread -std=c++17 -MD -MT Source/CMakeFiles/BespokeSynth.dir/__/libs/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.o -MF CMakeFiles/BespokeSynth.dir/__/libs/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.o.d -o CMakeFiles/Bespo
keSynth.dir/__/libs/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp.o -c /build/bespokesynth/src/bespokesynth/libs/JUCE/modules/juce_gui_basics/juce_gui_basics.cpp
/build/bespokesynth/src/bespokesynth/Source/TitleBar.cpp: In member function ‘void TitleBar::ManageVSTs()’:
/build/bespokesynth/src/bespokesynth/Source/TitleBar.cpp:214:8: error: ‘mPluginListWindow’ was not declared in this scope; did you mean ‘PluginListWindow’?
  214 |    if (mPluginListWindow == nullptr)
      |        ^~~~~~~~~~~~~~~~~
      |        PluginListWindow
/build/bespokesynth/src/bespokesynth/Source/TitleBar.cpp:217:4: error: ‘mPluginListWindow’ was not declared in this scope; did you mean ‘PluginListWindow’?
  217 |    mPluginListWindow->toFront(true);
      |    ^~~~~~~~~~~~~~~~~
      |    PluginListWindow
/build/bespokesynth/src/bespokesynth/Source/TitleBar.cpp: In member function ‘virtual void TitleBar::OnWindowClosed()’:
/build/bespokesynth/src/bespokesynth/Source/TitleBar.cpp:222:4: error: ‘mPluginListWindow’ was not declared in this scope; did you mean ‘PluginListWindow’?
  222 |    mPluginListWindow.reset(nullptr);
      |    ^~~~~~~~~~~~~~~~~
      |    PluginListWindow
/build/bespokesynth/src/bespokesynth/Source/TitleBar.cpp: In member function ‘virtual void TitleBar::DrawModuleUnclipped()’:
/build/bespokesynth/src/bespokesynth/Source/TitleBar.cpp:443:8: error: ‘mPluginListWindow’ was not declared in this scope; did you mean ‘PluginListWindow’?
  443 |    if (mPluginListWindow != nullptr)
      |        ^~~~~~~~~~~~~~~~~
      |        PluginListWindow
```

## Build info

n/a

## Steps To Reproduce

```
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=None \
        -Wno-dev \
        -B build \
        -S $pkgname
  make VERBOSE=1 -C build
```

## Expected vs. actual behavior

The build succeeds.
When building current HEAD (0acb8ebff6e59f8b000da240e11f31ccee9cca72) I don't get this issue, but that's likely because juce >= 7.0.0 is supported there.
As [the update to juce >= 7.0.0 is large itself](https://github.com/BespokeSynth/BespokeSynth/commit/3e1d28441aeac4d0a45a329bfde609b0527c3071) and there have been many changes since 1.1.0 it will not apply cleanly on top of 1.1.0.

For downstreams this is problematic, as they can not rebuild this software anymore without going through large patches introducing instabilities or dropping the software.

The C++ ecosystem (and especially also juce) is a moving target due to compiler updates and staying on top of it with regular releases is necessary (see #912).

**Comment by dvzrv** [comment]
FWIW, I have also tried with applying https://github.com/juce-framework/JUCE/commit/ce8aff22c31c4d932a8414bc6f6185381dc970db to the bundled juce (as mentioned in #807), but that leads to the same issue, so it's not really clear when this got fixed in juce (or bespokesynth).

**Comment by KottV** [comment]
1.1.0 is too old. I see no sense to use it at present.

**Comment by dvzrv** [comment]
> 1.1.0 is too old. I see no sense to use it at present.

I would agree, but there is no newer stable release. In distribution packaging we use releases for a reason :)

**Comment by KottV** [comment]
> > 1.1.0 is too old. I see no sense to use it at present.
> 
> I would agree, but there is no newer stable release. In distribution packaging we use releases for a reason :)

I use `tag`+`commit_offset`+`commit_hash` for package versioning.

**Comment by dvzrv** [comment]
> I use `tag`+`commit_offset`+`commit_hash` for package versioning.

I'm aware of how to chain strings for a valid version (we have [entire wiki sections](https://wiki.archlinux.org/title/VCS_package_guidelines#Git) about this). :)
It's nonetheless not a stable release.

**Comment by NoxyNixie** [comment]
1.1.0 is not meant to compile with juce 7. Compile it with juce 6 <https://github.com/juce-framework/JUCE/tree/6.1.6>.

We will likely not make 1.1.0 compile with juce 7 as active work is already being done to finalize a 1.2.0 release (there is no ETA).

**Comment by dvzrv** [comment]
As mentioned above, compiling juce 6.1.x also doesn't work anymore... so yeah.

**Comment by NoxyNixie** [comment]
I did not see you mention that and honestly still don't see where you mentioned that it does not work with Juce 6.

All I see is that you mention that you tried with a specific revision which actually looks to be early juce 7:

> FWIW, I have also tried with applying [juce-framework/JUCE@ce8aff2](https://github.com/juce-framework/JUCE/commit/ce8aff22c31c4d932a8414bc6f6185381dc970db) to the bundled juce

The above looks to be far past the last juce 6 release (which is this one: https://github.com/juce-framework/JUCE/commit/2f980209cc4091a4490bb1bafc5d530f16834e58).

Have you tried it with that one?

**Comment by ghost** [comment]
Bespoke v1.1.0 builds with JUCE 6.1.1
It won't build using GCC 12, 
there have been a number of patches in JUCE since 6.1.1 adressing that, 
applying https://github.com/juce-framework/JUCE/commit/ce8aff22c31c4d932a8414bc6f6185381dc970db won't be enough unfortunately. 
If you can build with GCC 9 (maybe 10) it will work.

**Comment by ghost** [comment]
Or, if you want to patch Bespoke,
you can add `#include <memory>` here: https://github.com/BespokeSynth/BespokeSynth/blob/v1.1.0/Source/TitleBar.h#L29
Then v1.1.0 also builds using GCC 12
(with JUCE 6.1.1 plus https://github.com/juce-framework/JUCE/commit/ce8aff22c31c4d932a8414bc6f6185381dc970db)
