### ISSUE TITLE
circlesequencer of length 1 = no output

### ISSUE THREAD

**Issue by jpnielsen** [BespokeSynth/BespokeSynth#919]
## Describe the bug

circlesequencer of length 1 does not send any notes.

![image](https://user-images.githubusercontent.com/27916597/190845679-87b6f533-4805-4258-953b-f24c2e7a76bd.png)

## Build info

bespoke NIGHTLY 1.1.0 (Sep 13 2022 00:30:04) - Windows 10 - HEAD 0acb8eb

## Expected vs. actual behavior

Expected one note output.

Here is one that works, where the length is set to 2, and only the first note is active.

![image](https://user-images.githubusercontent.com/27916597/190845783-d766177e-dec9-44b0-93ba-c62e4483d9ab.png)

**Comment by jpnielsen** [comment]
I forgot to search, seems it is a duplicate:

https://github.com/BespokeSynth/BespokeSynth/issues/218

**Comment by NoxyNixie** [comment]
Thanks for confirming this is still an issue either way ;)
