### ISSUE TITLE
CPU usage with circlesequencer and fmsynth

### ISSUE THREAD

**Issue by KottV** [BespokeSynth/BespokeSynth#92]
Hi,

I know circlesequencer has abandoned status, anyway some users tries to load it and sees big CPU usage with fmsynth connected.
Add circlesequencer, fmsynth, connect wires, add some dots in sequencer. CPU eating rises.
![Screenshot_20210603_162630](https://user-images.githubusercontent.com/4686351/120597939-04801a80-c489-11eb-933b-162a19428b9f.png)

**Comment by awwbees** [comment]
ah yes! the circlesequencer was originally intended to be used with drums, so it only sends note on messages, not note offs. as a result, in this patch it's just taking FM voices over and over again until the CPU runs out.

but, there's no reason for it to not also send note offs, which will allow you to use it with synths too. I'll add that!

**Comment by awwbees** [comment]
fixed in 1faf6628d3ea6e1e04b825508c1f9a256a0bac3c
