### ISSUE TITLE
 Prefab saving fails silently if BespokeSynth folder is a symlink to another position

### ISSUE THREAD

**Issue by crshrprt** [BespokeSynth/BespokeSynth#926]
## Describe the bug

Prefab saving fails silently if BespokeSynth folder is a symlink to another position (ex. outside "~/Documents")

## Build info

Linux
Debian Sid
Latest Nightly (aa6f2b9)

## Steps To Reproduce

Create a prefab
Click on the Save button
Confirm the "Save as prefab as ..." dialog
Prefab is not saved

NOTE: This bug doesn't affect saving savestates (bsk). Saving savestates in a symlinked folder works as expected.

## Expected vs. actual behavior

Prefab is saved in the chosen folder

**Comment by nedrob** [comment]
I have the same issue on my Mac M1. All other saving in Bespoke works. Just not with prefabs.

**Comment by nedrob** [comment]
The issue for me is that I am using Dropbox to Autosave everything in my Documents folder. If I turn this Dropbox feature off, the prefabs save correctly. 

I can't selectively remove the BespokeSynth or Prefabs sub-directories from the Autosave. As long as Documents is in the Autosave path for Dropbox, saving prefabs doesn't work. 
![Screen Shot 2022-12-27 at 8 52 19 AM](https://user-images.githubusercontent.com/20388271/209699617-8fc5ed21-0247-4ec1-bb31-80f0ac6a5b75.png)
