### ISSUE TITLE
Any chance of supporting LV2 plugins?

### ISSUE THREAD

**Issue by Kirtai** [BespokeSynth/BespokeSynth#93]
As the title says, could LV2 plugins be supported in addition to VST?

**Comment by awwbees** [comment]
it appears that JUCE, the framework that bespoke is built upon, does not yet support LV2 (https://github.com/juce-framework/JUCE/issues/123). so, I will probably wait until JUCE properly supports LV2.

if there is significant demand, I could look into using one of the JUCE forks with LV2 support, but that runs the risk of introducing headaches

**Comment by Kirtai** [comment]
Oh well, that's disappointing. Let's hope they add support soon then :)

**Comment by awwbees** [comment]
(oops, fat-fingered the close button). agreed on LV2, I'll keep an eye on that JUCE issue

**Comment by dromer** [comment]
Have a look at https://github.com/lv2-porting-project/JUCE and https://jatinchowdhury18.medium.com/building-lv2-plugins-with-juce-and-cmake-d1f8937dbac3

**Comment by KottV** [comment]
> Have a look at https://github.com/lv2-porting-project/JUCE and https://jatinchowdhury18.medium.com/building-lv2-plugins-with-juce-and-cmake-d1f8937dbac3

This is for plugins, not the hosts.

**Comment by dromer** [comment]
@KottV yes, derp. for a moment I thought that BespokeSynth was itself a plugin -_-

LV2 hosting inside of JUCE is still on the wishlist.

**Comment by KottV** [comment]
https://github.com/lvtk/jlv2/tree/master
It works, but will take some work to integrate

**Comment by awwbees** [comment]
yeah... I will probably still just wait for JUCE to tackle LV2 support "officially", rather than doing a bunch of work that will later become obsolete. so if you want LV2 support, communicate your desire to JUCE! that would definitely be the best option to achieve widespread LV2 support

**Comment by hellocatfood** [comment]
Juce is finally going to support lv2! https://github.com/juce-framework/JUCE/issues/123#issuecomment-914228048

**Comment by awwbees** [comment]
awesome. I will definitely keep an ear out for when that goes in.

**Comment by unfa** [comment]
Yay! https://github.com/falkTX Could probably help with it :)

**Comment by dromer** [comment]
@unfa no, we're waiting on JUCE team to officially support LV2 (and they want to sort out the preliminary work out of the public eye so they can better focus on it ;) )
Once they have a preview available we can help with bug-hunting and adding their branches to projects.

**Comment by unfa** [comment]
I see. I am going to await it impatiently, since LV2 is my preffered plug-in format (beecause of maximum freedom and no Steinberg involved).

I am going to chechout Bespoke Synth and probably mkae a video/livestream about it. It seems mighty impressive!
Thank you for making it open-source and supporting Linux OOTB!

**Comment by dromer** [comment]
@unfa yeah lets hope for the best!

Until then Bespoke is 100% usable without thinking about using plugins at all ;)
(and you could always load Carla vst and have your LV2 plugins run in that :thinking: )

**Comment by mxmilkiib** [comment]
JUCE 7 preview supports LV2 plugins and hosting.

**Comment by mxmilkiib** [comment]
I see @KottV is on it;

![](https://linuxmusicians.com/download/file.php?id=3183)

**Comment by awwbees** [comment]
@KottV did it!! plugin hosting has now been updated to be much more flexible, and supports LV2 (and also audiounit on macos). I haven't tested LV2 hands-on with linux yet, holler if you find issues!

**Comment by dromer** [comment]
@awwbees you can run LV2 on other OSes too ;)

**Comment by Kirtai** [comment]
Yay :D
