### ISSUE TITLE
Notelooper write, del/mute buttons not working properly when 'lookahead (exp)' is on

### ISSUE THREAD

**Issue by AndrewClaes** [BespokeSynth/BespokeSynth#930]
When using scripts, the lookahead function switches on. While on, the notelooper writeand del/mute functions don't work as expected anymore. 
Normally when write and del/mute are pressed, the notelooper will record like a buffer, and will overwrite when it loops  (it will delete old notes and then write the new ones). When lookahead is enabled, it will write the new notes but instantly delete them...
attached is a patch showcasing the problem
[notesequencer_lookahead_problem.bsk.zip](https://github.com/BespokeSynth/BespokeSynth/files/9690820/notesequencer_lookahead_problem.bsk.zip)

**Comment by NoxyNixie** [comment]
There is a triangle setting that makes the notelooper work correctly with lookahead enabled. I've changed the default value of this to enabled so that it appears to behave correctly in most cases.

See: #1710.
