### ISSUE TITLE
macroslider does not work with inputs larger the output's inferred max

### ISSUE THREAD

**Issue by JustAPerson** [BespokeSynth/BespokeSynth#937]
## Describe the bug

Here's a video demonstrating where adding a macroslider breaks a working modulator setup

https://user-images.githubusercontent.com/789308/194771655-7c6d3e75-c1c0-4b9e-8d81-f6e653f3b19a.mp4

In the beginning, there is an expression module whose output peaks at 8192. This is able to drive the `freq` param of a signalgenerator even though that has a default max of 4khz. Once I add a macroslider on the output of the expression module, things break and the signalgenerator is no longer being modulated.

## Build info

`bespoke 1.1.0 (Oct  8 2022 14:30:30) - Mac OSX 12.3.1 - main 616ad67c`

## Steps To Reproduce

- Create an `lfo`, `expression`, and `signalgenerator` modules
- Set the lfo to sweep from 0 to 1 and feed it into the input of the expression module
- Set the expression module to evaluate `2^(7+6*x)` and feed the input into the `freq` param of the signalgenerator
- Shift-left click the output of the expression module to add a macroslider
- Observe that the signalgenerator is no longer being modulated

## Expected vs. actual behavior

Honestly I just wish shift clicking a modulator did the exact same as every other type of node. I want to literally duplicate the output of the modulator. I do not want the extra functionality of the `macroslider` whatsoever.

**Comment by awwbees** [comment]
I've got a PR at https://github.com/BespokeSynth/BespokeSynth/pull/944 which allows you to duplicate the output of a modulator as desired. I need to test it more before merging it, but if you're able to build code, you can help me test it by grabbing that branch

**Comment by KottV** [comment]
@awwbees @JustAPerson Can we closed it as fixed with https://github.com/BespokeSynth/BespokeSynth/pull/944 ?

**Comment by NoxyNixie** [comment]
I tested the originally presented issue with the latest Nightly build and can confirm that this has been resolved:

![BespokeSynth_20221029_131636](https://user-images.githubusercontent.com/211381/198828502-30018f03-a989-4c43-9174-5d4071510f2c.gif)
