### ISSUE TITLE
midicontroller modules in prefabs don't remember mapping destinations.

### ISSUE THREAD

**Issue by ThePython10110** [BespokeSynth/BespokeSynth#946]
For some reason, midicontrollers in prefabs completely forget what controls they should be modulating when the patch is loaded. Either this information isn't saved correctly or it isn't being loaded correctly.
Before saving/loading:
![image](https://user-images.githubusercontent.com/87204246/197244456-f31416b3-7d0d-40af-82bc-8cd98742fb3a.png)
After saving/loading:
![image](https://user-images.githubusercontent.com/87204246/197244574-58839f87-7742-4547-8031-ed26b9694988.png)

**Comment by awwbees** [comment]
prefabs can only save connections to modules within their own scope, they can't refer to modules outside of it. if you place all the gains inside your prefab, then the connection will be maintained when you reload it.
