### ISSUE TITLE
UI parameters of a VST don't display his parameter name, only a generic one

### ISSUE THREAD

**Issue by nay-seven** [BespokeSynth/BespokeSynth#949]
(bespoke NIGHTLY 1.1.0 (Oct 25 2022 23:31:16) - Mac OSX 10.14.6 - HEAD 72f5662)

Hello, 
The UI parameters of a VST (when connected to a MIDI controller)  display a generic name ( vstplugin- paramid  XXX), no more the vst parameter name ...normal ?

Best

**Comment by awwbees** [comment]
yes, this is a semi-unfortunate side effect of #936. in #950, however, I updated the midi activity popup to show the name that the VST reports, to make this better:
<img width="831" alt="Screen Shot 2022-11-01 at 10 05 01 PM" src="https://user-images.githubusercontent.com/839239/199382547-76444263-4e52-4fce-a388-d8dd511242f8.png">
