### ISSUE TITLE
Add support for 32-bit plugins

### ISSUE THREAD

**Issue by ThePython10110** [BespokeSynth/BespokeSynth#952]
## Summary

A built-in bit bridge. I have _no idea_ how hard this would be (probably very difficult...) but it would be great.

### Motivation

Some VST plugins don't have a 64-bit version.

**Comment by NoxyNixie** [comment]
If you compile Bespoke in 32-bit mode you can actually load 32-bit VST's (but not 64-bit).

Making 32-bit and 64-bit VST's work at the same time requires Bespoke to have a form of VST sandboxing or virtualization which will have a noticeable performance impact (You can see this in DAW's that allow non sandboxed and sandboxed VST's).

Unfortunately the amount of effort to make this work correctly is likely not worth it. Even compiling as 32-bit application isn't really supported and usually not tested.

**Comment by NoxyNixie** [comment]
Unfortunately this will likely not be implemented any time soon or at all. There are currently no plans to make this possible.

You might be better off investing (or investigating) some time in setting up a bridge like these:
- https://github.com/falkTX/Carla
- https://jstuff.wordpress.com/jbridge/
- https://totomusic.github.io/TBridge/indexEn.html
