### ISSUE TITLE
Input text (paths) LV2 plugin parameters not shown or configurable.

### ISSUE THREAD

**Issue by joseluisquiroga** [BespokeSynth/BespokeSynth#954]
## Describe the bug

When using LV2 plugins like Calf Fluidsynth or Fluida that need a path (textual input) to the SF2 soundfont file in order to work, there is no way to set it up. 

There is no way for me to use all my SF2 soundfonts in BespokeSynth if this does not work.

## Build info

Tested with this builds in EndeavourOS (Arch) with KDE Plasma.

bespoke 1.1.0 (Sep 15 2022 20:52:56) - Linux - makepkg 0acb8ebf
bespoke 1.1.0 (Nov 11 2022 10:48:21) - Linux - main 4c00c8b1

## Steps To Reproduce

1) sudo pacman -S calf
2) yay fluida
3) BespokeSynth
4) C -> Calf Fluidsyth
5) F -> Fluida
6) Click "open" in either module.

Note: When running BespokeSynth from command line and adding the Fluida LV2 plugin the console output is the following:

fluidsynth: error: fluid_sfloader_load(): Failed to open '': File does not exist.
fluidsynth: error: Unable to open file ''
fluidsynth: error: ipatch_file_open() failed with error: 'No such file or directory'
fluidsynth: error: Failed to load SoundFont ""

So I looked for a configuration option in a saved session file but it gets easy to break BespokeSynth.

## Expected vs. actual behavior

I expect to be able to set the path of the SF2 file that I want the LV2 plugin to use.
But BespokeSynth does not let me do that. There is no field to do that in the interface.
And when I open (click "open" in the plugin) the plugin interface it does not show me the proper plugin interface (like in Carla or Ardour) but an interface proper to BespokeSynth that does not have a text input field that allows me to set the path.

**Comment by KottV** [comment]
There is no way to set string parameter via JUCE plugin generic-GUI host part.
And there is no GUI for any Gtk-based LV2 plugin, like Calf.

By the way `Fluida` works fine here (be sure you have latest version https://github.com/brummer10/Fluida.lv2/commit/76449f1de577b581d4f24925db2612857b855a87) also `juicysfplugin` is good for SF2 play.

![изображение](https://user-images.githubusercontent.com/4686351/201448993-04e36aba-8614-4ac2-91c7-60c189998c05.png)

**Comment by joseluisquiroga** [comment]
Thanks for your prompt answer.

I tried  two different builds of BeSpoke. One is the latest "main" in github built with my system and the other is community/bespokesynth of the arch repositories.

These are my screenshots of the plugins using BeSpoke vs using Carla

![ScreenShot_BeSpoke_01](https://user-images.githubusercontent.com/8698378/201497662-3eca05e5-eb94-4fd4-b6de-d12f2a5f12ac.png)
![Screenshot_Carla_1](https://user-images.githubusercontent.com/8698378/201497676-046cfe92-e312-45b3-b224-a2127d284a91.png)

In Carla they show fine in BeSpoke they do not.

juicysfplugin is not in the main arch repositories  (aur, community, extra) and I could not build it without warnings and errors. So I could not try it.

I did see a gtk message while building BeSpoke that looked out of place since my sys uses kde.
These are some lines found with 'grep -i gtk CMakeCache.txt' in my build dir.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_gtk-3:FILEPATH=/usr/lib/libgtk-3.so
pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_javascriptcoregtk-4.0:FILEPATH=/usr/lib/libjavascriptcoregtk-4.0.so
pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_webkit2gtk-4.0:FILEPATH=/usr/lib/libwebkit2gtk-4.0.so
....
JUCE_BROWSER_LINUX_DEPS_gtk+-x11-3.0_INCLUDEDIR:INTERNAL=/usr/include
JUCE_BROWSER_LINUX_DEPS_gtk+-x11-3.0_LIBDIR:INTERNAL=/usr/lib
JUCE_BROWSER_LINUX_DEPS_gtk+-x11-3.0_MODULE_NAME:INTERNAL=gtk+-x11-3.0
JUCE_BROWSER_LINUX_DEPS_gtk+-x11-3.0_PREFIX:INTERNAL=/usr
JUCE_BROWSER_LINUX_DEPS_gtk+-x11-3.0_VERSION:INTERNAL=3.24.34
JUCE_BROWSER_LINUX_DEPS_webkit2gtk-4.0_INCLUDEDIR:INTERNAL=/usr/include
JUCE_BROWSER_LINUX_DEPS_webkit2gtk-4.0_LIBDIR:INTERNAL=/usr/lib
JUCE_BROWSER_LINUX_DEPS_webkit2gtk-4.0_MODULE_NAME:INTERNAL=webkit2gtk-4.0
JUCE_BROWSER_LINUX_DEPS_webkit2gtk-4.0_PREFIX:INTERNAL=/usr
JUCE_BROWSER_LINUX_DEPS_webkit2gtk-4.0_VERSION:INTERNAL=2.38.2
__pkg_config_arguments_JUCE_BROWSER_LINUX_DEPS:INTERNAL=webkit2gtk-4.0;gtk+-x11-3.0
//ADVANCED property for variable: pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_gtk-3
pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_gtk-3-ADVANCED:INTERNAL=1
//ADVANCED property for variable: pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_javascriptcoregtk-4.0
pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_javascriptcoregtk-4.0-ADVANCED:INTERNAL=1
//ADVANCED property for variable: pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_webkit2gtk-4.0
pkgcfg_lib_JUCE_BROWSER_LINUX_DEPS_webkit2gtk-4.0-ADVANCED:INTERNAL=1
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Maybe a build option ?

Thanks again.

**Comment by joseluisquiroga** [comment]
I am not an expert but it seems to me that in order for the custom gui of lv2 plugins to work on any linux toolkit (x11, Qt4, gtk):

Ardour uses a library called Suil
https://drobilla.net/software/suil.html
https://archlinux.org/packages/community/x86_64/suil/

And Carla uses its own library called lv2-host
https://archlinux.org/packages/community/x86_64/carla/

Just saying ...

**Comment by KottV** [comment]
BespokeSynth uses JUCE framework for dealing with plugins, where the non-X11 GUI for plugins is not supported https://github.com/juce-framework/JUCE/issues/1123#issuecomment-1280723787 and text parameters also https://forum.juce.com/t/lv2-issues/52412/24

You can use [Ildaeil](https://github.com/DISTRHO/Ildaeil) for bridging Calf plugins here.
For Fluida.lv2 you have to compile it with the latest commit or ping Arch maintainer to update it, I provided link for that commit in the previous answer. If you're unable to compile juicysfplugin - fill the issue in it's GH page.

**Comment by joseluisquiroga** [comment]
As a workaround  [Ildaeil](https://github.com/DISTRHO/Ildaeil) did the trick. Thanks !

![BeSpoke_sf2](https://user-images.githubusercontent.com/8698378/201550940-644268aa-924c-4f2e-af9c-4ea17e97c4c0.png)

Maybe BeSpoke should have a built-in fluidsynth module?
Or call Suil for LV2 plugin UI (after all it does support X11)?
Just saying ...

**Comment by KottV** [comment]
>Maybe BeSpoke should have a built-in fluidsynth module?

Perhaps it's possible.

>Or call Suil for LV2 plugin UI (after all it does support X11)?
 
No. Have you read that Bespoke uses JUCE for plugins?

**Comment by NoxyNixie** [comment]
Due to this not being an issue with bespoke but instead JUCE I'm closing this for now.

Current accepted resolution is to use [Ildaeil](https://github.com/DISTRHO/Ildaeil) or perhaps other plugin bridging software.
