### ISSUE TITLE
I would like to have some control over this 30 minute buffer.

### ISSUE THREAD

**Issue by TheGuyWhoo** [BespokeSynth/BespokeSynth#961]
It's a cool and convenient feature, but not terribly practical on shit computers and not something that is strictly necessary. It would be nice to be able to turn it off, especially since I'm mostly doing the recording manually anyways.

**Comment by TheGuyWhoo** [comment]
Just wanted to add, thank you for this great software! I have been enjoying it quite a lot!

**Comment by KottV** [comment]
![изображение](https://user-images.githubusercontent.com/4686351/202582629-ee03b13d-5319-4e39-8ef2-29a6eb5be285.png)

**Comment by TheGuyWhoo** [comment]
Ah sweet, I didn't realize it was the same thing. Thank you.

**Comment by TheGuyWhoo** [comment]
Ah sweet, I didn't realize it was the same thing. Thank you.

**Comment by TheGuyWhoo** [comment]
Hi! sorry for going off topic, but I thought I'd ask here so I don't unnecessarily open an issue. What is the simplest way to go about mixing rhythm divisions? Say I want to do trap Hi hats, and I want to do 16th, 32nd as well as triplet notes all on the same line. How can I accomplish this?

**Comment by NoxyNixie** [comment]
> Hi! sorry for going off topic, but I thought I'd ask here so I don't unnecessarily open an issue. What is the simplest way to go about mixing rhythm divisions? Say I want to do trap Hi hats, and I want to do 16th, 32nd as well as triplet notes all on the same line. How can I accomplish this?

This is more a question for the [Discord](https://discord.gg/jtxTKvU6Rb). But you can mix and match sequencers as much as you want including having different sequencers at different timing intervals.
