### ISSUE TITLE
Preset module zooms notecanvas in to max values when you change preset.

### ISSUE THREAD

**Issue by TheGuyWhoo** [BespokeSynth/BespokeSynth#966]
linux mint 20, bespoke 1.1.0

When you save presets of notecanvas module using preset module, switching between presets causes the notecanvas to zoom in to max value(inside the notecanvas itself, in other words a single note cell takes up the entire ui of the note canvas.)

**Comment by ghost** [comment]
for me in Fedora preset module + notecanvas  creates unpredictable nearly random results.

preset + notesequencer works as I expect.

but notecanvas STB

**Comment by v64** [comment]
can confirm the unpredictable behavior of preset + notecanvas on macos with the latest nightly as well

in my experience, when adding new presets, it seems to overwrite the already set values of previous presets with notes from the current preset you're setting. Will try to capture a video of it next time I see it

**Comment by NoxyNixie** [comment]
This seems to have been resolved. I'm unable to reproduce this in the latest Nightly build.

If this bug still happens please feel free to comment on this issue or create a new one.
