### ISSUE TITLE
It would be nice to have more control over playhead.

### ISSUE THREAD

**Issue by TheGuyWhoo** [BespokeSynth/BespokeSynth#969]
Whether that is adding shortcuts for shifting the playhead backwards or forwards or a slider that you can drag to a precise position, either would be an improvement over only having the option of clicking the little arrows.

**Comment by awwbees** [comment]
the new `timelinecontrol` module (#976) should take care of this!

**Comment by TheGuyWhoo** [comment]
This and the song builder are great additions! However it is kind of frustrating that it is no longer possible to go to negative values on the transport. It is now impossible for me to trigger a loop from the beginning, it never starts at the start. linux mint 20 64 bit, latest nightly as of December 7.

**Comment by NoxyNixie** [comment]
Are you sure? Triggering things from the start should have been resolved with the songbuilder addition. If not then this is likely a new bug and I'd love to see a new bug report with details on how to reproduce your issues.

**Comment by TheGuyWhoo** [comment]
In the mean time I've solved it by starting things on the second bar and using the looping function of the timelinecontrol. If I get time tomorrow I will post a screen recording, but my computer is quite shit so it's quite possible that's the issue. A negative transport time is no longer necessary though since we now have more control over the transport, so I do apologize for whinging about that.

**Comment by TheGuyWhoo** [comment]
I have determined that it is a matter of blocksize. With blocksize higher than 512 it will not trigger correctly. Should I make an issue regarding this or is it expected behavior?

**Comment by NoxyNixie** [comment]
Make an issue, thanks.
