### ISSUE TITLE
Changing the phase of certain VST synths changes the sound

### ISSUE THREAD

**Issue by ThePython10110** [BespokeSynth/BespokeSynth#971]
## Describe the bug
Changing the phase of certain VST synths changes the sound, but only in new versions of Bespoke.
The patch I used was simply a midicontroller module connected to [Vital Synth](https://vital.audio) with the default preset. I noticed that Vital's phase randomization (which sets a random phase for every note) was actually changing the sound in the latest version.
This happens with both the VST2 and VST3 versions of Vital and [Surge XT](https://surge-synthesizer.github.io), but not [MOscillator](https://www.meldaproduction.com/MOscillator) or the built-in oscillator or signalgenerator.
I then tried going through older versions, and I can confirm that this didn't happen until _after_ the release of 1.10 (it only happens in the nightly builds). I didn't go back to find out exactly when this changed, so it could have been anytime in the last year...

## Build info
bespoke NIGHTLY 1.1.0 (Nov 17 2022 05:19:51) - Windows 10 - HEAD 6234e19

## Steps To Reproduce
* Open the latest version of Bespoke
* Add a midicontroller and [Vital Synth](https://vital.audio)
* Play one note multiple times and notice the different sound.
* Close Bespoke.
* Open any version of Bespoke up to and including v1.10
* Add a midicontroller and [Vital Synth](https://vital.audio)
* Play one note multiple times and notice that they all sound exactly the same.

## Expected vs. actual behavior
I expected that the sound of a single saw wave would not be affected by the phase.
But it was.

**Comment by NoxyNixie** [comment]
I believe this is related to #1545 and is likely resolved by the mentioned PR.

**Comment by NoxyNixie** [comment]
Fixed in: 2aceb5a.
