### ISSUE TITLE
deb dependency check not working/invalid?

### ISSUE THREAD

**Issue by LOGUNIVPM** [BespokeSynth/BespokeSynth#987]
I read #108  which is partly related, but I want to add my usecase which will be common, as many people will quickly discover that they can't run bespoke on their pc and get frustrated. 

The site provides deb packages for several versions of ubuntu and debian. On my system (Linux Mint) the deb package manager says that all dependencies are satisfied, but when running Bespoke I get an error like:
`BespokeSynth: error while loading shared libraries: libpythonx.y.so.1.0: cannot open shared object file: No such file or directory`
where you can replace x.y with the required version of libpyton (it depends on the version for which the deb is targeted). After installing the required version from apt I see two further erros:
BespokeSynth: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by BespokeSynth)
BespokeSynth: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by BespokeSynth)
At that point I stop since I believe that many other libraries will be not aligned to the required version.

Overall, I believe that the deb does not correctly manage dependencies, otherwise the package manager would know before installing that the correct versions of these dependencies are missing. I also want to add that being so specific about the python and glibc version seems strange to me. Why is that and why can't any later version be loaded?

Yes, I know that I am NOT on a vanilla ubuntu, so the problem is probably not severe. I'm on Linux Mint, which is Ubuntu-based, and generally works flawlessly with debs targeted for ubuntu. One easy solution would be to add a link with instructions to compile just below the buttons to download the deb packages. It took me a few minutes to find the right repo and instructions on the site (after spending several minutes trying to install several debs from the site). This will stray people away from bespoke. Anyway I believe the deb packaging could be improved.

Environment:
Linux5.4.0-109-generic #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 19.3 Cinnamon 64-bit
The problem can be reproduced with any of the currently available downloads for Debian and ubuntu.

**Comment by KottV** [comment]
What Mint version?

**Comment by LOGUNIVPM** [comment]
As above 19.3, Cinnamon 64-bit

**Comment by KottV** [comment]
According Wiki it's Ubuntu 18.04 based. Have you tried the 18.04 package from https://software.opensuse.org//download.html?project=home%3Abespokesynth&package=bespokesynth-current ?

**Comment by LOGUNIVPM** [comment]
Well, I surely did, but now I tried downloading again the deb and I see that we have:
bespokesynth-current_1.1.0+git.160.4f00ab8-0_amd64.deb
instead of the 1.1.0-0 I downloaded last week.
This new deb works!

**Comment by KottV** [comment]
Yes, it was an old release-based build, topical package in OBS is the `bespoke-current`
