### ISSUE TITLE
Keyboard Input Module - Module to trigger mappings or actions based on Key Commands 

### ISSUE THREAD

**Issue by ShamanicArts** [BespokeSynth/BespokeSynth#988]
A computer keyboard in module to expand custom mappings and allow creation of custom shortcuts within a project 

such a module is found in other modular live coding and network building environments, would greatly expand the sorts of shortcuts and controls a user can build in and or help with testing features ( key to pulse for example )

**Comment by dongmingchao** [comment]
agree; important

**Comment by NoxyNixie** [comment]
The `keyboarddisplay` module was expanded upon and is now capable of taking up this role. As well as a `keyboard` type in the `midicontroller` were added.
