### ISSUE TITLE
License component lacking

### ISSUE THREAD

**Issue by MetalMaxMX** [BespokeSynth/BespokeSynth#99]
Hi! Big fan and rather curious onlooker of Bespoke synth! I was so excited at watching your demos of the synth that I decided to share them with a few other people so they can learn and be inspired by it. One of the people there however told me that the license that you chose (GPLv3) needed a few modifications so to speak. I'll link to a reputable source in order to highlight the issue: https://opensource.org/licenses/GPL-3.0

If you go to "How to Apply These Terms to Your New Programs" you'll notice that a short notice, the copyright and more, etc. needs to be applied to the start of each source file. Though for practicality, a short header is applied to every source file (once again, described on the site) or some people just do the minimal thing with: Copyright, further contact, license name and where to get the full license. 

This must be on every file though, regardless of the approach you take. And hopefully my explanation makes sense! 

I _really_ hope I'm not bothering you with this. I just wanted to get it out of my system precisely because this software is really cool and to get this done before the full release would make it look nice and dandy.

Thanks for reading my issue! 

Cheers!
MetalMaxMX

**Comment by awwbees** [comment]
thank you! I am dumb at this stuff, so it is very helpful to be pointed in the right direction at how to be license-compliant. I will get right on this.

**Comment by awwbees** [comment]
I am now compliant (hopefully!) as of 824bf874720be38e8def59d5228dda374f679d63

thanks!
