### ISSUE TITLE
Hide cables not currently involved in signal chain 

### ISSUE THREAD

**Issue by ShamanicArts** [BespokeSynth/BespokeSynth#998]
## Summary
Current implementation of cabless is not sustainable. I understand Awwbees has stated before that he would not hide cables as he does not agree that signal chains should be obscured, which I do in principle agree with , however current implementation of showing every cable regardless of wether that cables is active or not  makes complex projects in bespoke unoptimized. 

We all love spaghetti and this isnt a request to hide spaghetti, Just a request to  allow for hiding of spaghetti that is not on my plate. 
My frames have dropped by half, and routing modules is becoming increasingly difficult, simply because of the amount of cables in my template, a template that has only existed for 24 hours, and needs to scale by 20x this amount to make it practical for my use case.

 a simple settings option to hide cables which are not currently in use, would restore frames, make visualising the actual signal chain much easier (current implementation actually hinders good visualisation of signal path due to clutter and visual noise ) and generally help Bespoke be a more scaleable system for building complex live performance environments. 
 
 also the feature technically already exists when minimizing modules, however, this actually does go against Awwbees philosophy as with my audio routers minimized, I can not see what target my modules are sending too. if hiding cables is okay when a module is minimized, even though this goes against design philosophy, then having the option to hide unused cables to better show actual signal chain and allow for visual decluttering should absolutely be ok. 

attached is a picture of a dynamic modular FX routing system illustrating how difficult current implementation is to work with 

![Screenshot 2022-12-18 at 13 57 10](https://user-images.githubusercontent.com/90007349/208303153-cb42f6d9-79ba-4517-8ac1-e579ba717595.png)

**Comment by ShamanicArts** [comment]
for comparison here are the frames when all these cables are hidden 
![Screenshot 2022-12-18 at 14 33 28](https://user-images.githubusercontent.com/90007349/208304230-62e0e2c1-020b-468d-a5ec-0477ae833760.png)

**Comment by awwbees** [comment]
`audiorouter`s and `noterouter`s now have a new option in their triangle menu, "only_show_active_cable", which only shows the cable for the active output
